<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>А-банк</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&amp;subset=cyrillic" rel="stylesheet">
<link rel="shortcut icon" href="/favicon.ico"></head>
<body><div id="app"></div><script type="text/javascript" src="/js/vendor.547a60e9072e6fcfcba0.js"></script><script type="text/javascript" src="/js/common.40fc43bab0f01f876593.js"></script><script type="text/javascript" src="/js/appCommon.92e77d526650efa8f93e.js"></script><script type="text/javascript" src="/js/app.4c855c9a541502163092.js"></script></body>
</html>