<!doctype html>
<!--[if lt IE 7]><html class="no-js ie6 oldie" lang="en"><![endif]-->
<!--[if IE 7]><html class="no-js ie7 oldie" lang="en"><![endif]-->
<!--[if IE 8]><html class="no-js ie8 oldie" lang="en"><![endif]-->
<!--[if gt IE 8]><!--><html class="no-js" lang="en"><!--<![endif]-->
<head>
  <meta name="google-site-verification" content="wn8cFZf84zMWSGRQjEktDQEBuPVHsywRwlzRLcNLQls" />
  <link rel="apple-touch-icon" sizes="180x180" href="//cdn.shopify.com/s/files/1/0661/9019/t/105/assets/apple-touch-icon.png?518293478356493345?v=KmbRwOyv9P">
  <link rel="icon" type="image/png" href="//cdn.shopify.com/s/files/1/0661/9019/t/105/assets/favicon-32x32.png?518293478356493345?v=KmbRwOyv9P" sizes="32x32">
  <link rel="apple-touch-icon" sizes="180x180" href="//cdn.shopify.com/s/files/1/0661/9019/t/105/assets/apple-touch-icon.png?518293478356493345?v=KmbRwOyv9P">
<link rel="icon" type="image/png" href="//cdn.shopify.com/s/files/1/0661/9019/t/105/assets/favicon-32x32.png?518293478356493345?v=KmbRwOyv9P" sizes="32x32">
<link rel="icon" type="image/png" href="//cdn.shopify.com/s/files/1/0661/9019/t/105/assets/android-chrome-192x192.png?518293478356493345?v=KmbRwOyv9P" sizes="192x192">
<link rel="icon" type="image/png" href="//cdn.shopify.com/s/files/1/0661/9019/t/105/assets/favicon-16x16.png?518293478356493345?v=KmbRwOyv9P" sizes="16x16">
<link rel="manifest" href="//cdn.shopify.com/s/files/1/0661/9019/t/105/assets/manifest.json?518293478356493345?v=KmbRwOyv9P">
<link rel="mask-icon" href="//cdn.shopify.com/s/files/1/0661/9019/t/105/assets/safari-pinned-tab.svg?518293478356493345?v=KmbRwOyv9P" color="#5bbad5">
<link rel="shortcut icon" href="//cdn.shopify.com/s/files/1/0661/9019/t/105/assets/favicon.ico?518293478356493345?v=KmbRwOyv9P">
<meta name="apple-mobile-web-app-title" content="Alisa.ua">
<meta name="application-name" content="Alisa.ua">
<meta name="theme-color" content="#ffffff">
  <meta charset="utf-8">
  <!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->

    
     <title>
    Интернет-магазин нижнего белья Алиса, Одесса &ndash; Купить женское и мужское белье в Киеве и Украине</title>
  

  
  
  <meta name="description" content="1&amp;#818;0&amp;#818;0&amp;#818;%&amp;#818; &amp;#818;г&amp;#818;а&amp;#818;р&amp;#818;а&amp;#818;н&amp;#818;т&amp;#818;и&amp;#818;я &amp;#9654; профессиональный подбор белья &amp;#58146; &amp;#9654; бесплатный возврат &#9654; доставка курьером &#57613; по Киеву и Украине" />
   
  

  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  
  <link rel="canonical" href="https://alisa.ua/" /> 

  


  <meta property="og:type" content="website" />
  <meta property="og:title" content="Интернет-магазин нижнего белья Алиса, Одесса" />
  
   <!-- <meta property="og:image" content="http://cdn.shopify.com/s/files/1/0661/9019/t/105/assets/logo.png?518293478356493345" />
    <meta property="og:image:secure_url" content="https://cdn.shopify.com/s/files/1/0661/9019/t/105/assets/logo.png?518293478356493345" />
    -->
    <meta property="og:image" content="https://cdn.shopify.com/s/files/1/0661/9019/files/alisa-round-logo.png?1114719313463203002" />
  



<meta property="og:description" content="1&amp;#818;0&amp;#818;0&amp;#818;%&amp;#818; &amp;#818;г&amp;#818;а&amp;#818;р&amp;#818;а&amp;#818;н&amp;#818;т&amp;#818;и&amp;#818;я &amp;#9654; профессиональный подбор белья &amp;#58146; &amp;#9654; бесплатный возврат" />

<meta property="og:url" content="https://alisa.ua/" />
<meta property="og:site_name" content="Alisa.ua" />
  
 


  <link href="//cdn.shopify.com/s/files/1/0661/9019/t/105/assets/styles.scss.css?518293478356493345" rel="stylesheet" type="text/css" media="all" />
  <link href="//cdn.shopify.com/s/global/social/social-icons.css" rel="stylesheet" type="text/css" media="all" />
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet" type="text/css" media="all" />
  
  <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans:300,400,700&subset=cyrillic,cyrillic-ext,latin">
  
  
  <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans:300,400,700&subset=cyrillic,cyrillic-ext,latin">
  
  <script src="//cdn.shopify.com/s/files/1/0661/9019/t/105/assets/html5shiv.js?518293478356493345" type="text/javascript"></script>

  <meta id="shopify-digital-wallet" name="shopify-digital-wallet" content="/6619019/digital_wallets/dialog">
<script>var Shopify = Shopify || {};
Shopify.shop = "alisa-ua-2.myshopify.com";
Shopify.theme = {"name":"Minimal Production","id":90401606,"theme_store_id":null,"role":"main"};
Shopify.theme.handle = "null";
Shopify.theme.style = {"id":null,"handle":null};
</script>
<script>(function() {
  function asyncLoad() {
    var urls = ["https:\/\/s3.amazonaws.com\/maxeffi\/persistent-cart\/alisa-ua-2.myshopify.com\/app.js?shop=alisa-ua-2.myshopify.com","https:\/\/error404.atomseo.com\/scripts\/shopify-404-real-time-monitoring.js?shop=alisa-ua-2.myshopify.com","https:\/\/shopify.retargetapp.com\/pixel.js?key=YWxpc2EtdWEtMi5teXNob3BpZnkuY29t\u0026shop=alisa-ua-2.myshopify.com","https:\/\/d8sfokcjiy6.cloudfront.net\/cdn\/automatic-discount\/wallsh_dp.min.js?shop=alisa-ua-2.myshopify.com","\/\/storage.googleapis.com\/pixelperfect\/pixel-perfect.js?shop=alisa-ua-2.myshopify.com","https:\/\/instafeed.n3f.me\/cdn\/d85379cf3cb3cbd05f69ca83d5489303.js?shop=alisa-ua-2.myshopify.com","https:\/\/cdn.shopifycloud.com\/messenger_commerce\/assets\/new_message_us?version=1517350892\u0026page_id=\u0026color=\u0026size=\u0026position_horizontal=\u0026position_vertical=\u0026messenger_app_id=1163199097047119\u0026shop=alisa-ua-2.myshopify.com"];
    for (var i = 0; i < urls.length; i++) {
      var s = document.createElement('script');
      s.type = 'text/javascript';
      s.async = true;
      s.src = urls[i];
      var x = document.getElementsByTagName('script')[0];
      x.parentNode.insertBefore(s, x);
    }
  };
  if(window.attachEvent) {
    window.attachEvent('onload', asyncLoad);
  } else {
    window.addEventListener('load', asyncLoad, false);
  }
})();
</script>
<script id="__st">var __st={"a":6619019,"offset":7200,"reqid":"a76de02f-75e9-40c4-8aa6-3bf5d6eabc27","pageurl":"alisa.ua\/","u":"f62e904504d2","p":"home"};</script>
<script>window.ShopifyPaypalV4VisibilityTracking = true;</script>
<script>window.Shopify = window.Shopify || {};
window.Shopify.Checkout = window.Shopify.Checkout || {};
window.Shopify.Checkout.apiHost = "alisa-ua-2.myshopify.com";
window.Shopify.Checkout.requestHost = "alisa.ua"
window.Shopify.Checkout.rememberMeHost = "pay.shopify.com";
window.Shopify.Checkout.rememberMeAccessToken = "UDEzV25hUkQyYytnaTlLdEIra1ZoTnZ4bWRsc2NrOTB6R0RBcGRyKzl3WT0tLTR2bGRQVTZPUm9QNHB4Q09EOHdKQlE9PQ==--76c3af25744936ef853797572b76d62831996236";
window.Shopify.Checkout.sheetStyleSheetUrl = "\/\/cdn.shopify.com\/s\/assets\/shared\/sheet\/main-c150bd783aa9b2c6b0c41ded3880c45a0848a9914354d4222628be6c924200a3.css";
window.ShopifyPay = window.ShopifyPay || {};
window.ShopifyPay.acceleratedFlowIncontext = false;
</script>
<script>
      window.ShopifyAnalytics = window.ShopifyAnalytics || {};
      window.ShopifyAnalytics.meta = window.ShopifyAnalytics.meta || {};
      window.ShopifyAnalytics.meta.currency = 'UAH';
      var meta = {"page":{"pageType":"home"}};
      for (var attr in meta) {
        window.ShopifyAnalytics.meta[attr] = meta[attr];
      }
    </script>
<script>window.ShopifyAnalytics.merchantGoogleAnalytics = function() {
  
};
</script>
<script class="analytics">(window.gaDevIds=window.gaDevIds||[]).push('BwiEti');


(function () {
  var customDocumentWrite = function(content) {
    var jquery = null;

    if (window.jQuery) {
      jquery = window.jQuery;
    } else if (window.Checkout && window.Checkout.$) {
      jquery = window.Checkout.$;
    }

    if (jquery) {
      jquery('body').append(content);
    }
  };

  var trekkie = window.ShopifyAnalytics.lib = window.trekkie = window.trekkie || [];
  if (trekkie.integrations) {
    return;
  }
  trekkie.methods = [
    'identify',
    'page',
    'ready',
    'track',
    'trackForm',
    'trackLink'
  ];
  trekkie.factory = function(method) {
    return function() {
      var args = Array.prototype.slice.call(arguments);
      args.unshift(method);
      trekkie.push(args);
      return trekkie;
    };
  };
  for (var i = 0; i < trekkie.methods.length; i++) {
    var key = trekkie.methods[i];
    trekkie[key] = trekkie.factory(key);
  }
  trekkie.load = function(config) {
    trekkie.config = config;
    var script = document.createElement('script');
    script.type = 'text/javascript';
    script.onerror = function(e) {
      (new Image()).src = '//v.shopify.com/internal_errors/track?error=trekkie_load';
    };
    script.async = true;
    script.src = 'https://cdn.shopify.com/s/javascripts/tricorder/trekkie.storefront.min.js?v=2017.09.05.1';
    var first = document.getElementsByTagName('script')[0];
    first.parentNode.insertBefore(script, first);
  };
  trekkie.load(
    {"Trekkie":{"appName":"storefront","development":false,"defaultAttributes":{"shopId":6619019,"isMerchantRequest":null,"themeId":90401606,"themeCityHash":12084954425169799795}},"Performance":{"navigationTimingApiMeasurementsEnabled":true,"navigationTimingApiMeasurementsSampleRate":1.0},"Google Analytics":{"trackingId":"UA-4704423-1","domain":"auto","siteSpeedSampleRate":"10","enhancedEcommerce":true,"doubleClick":true,"includeSearch":true},"Facebook Pixel":{"pixelIds":["814141062055437"],"agent":"plshopify1.2"},"Session Attribution":{}}
  );

  var loaded = false;
  trekkie.ready(function() {
    if (loaded) return;
    loaded = true;

    window.ShopifyAnalytics.lib = window.trekkie;
    
      ga('require', 'linker');
      function addListener(element, type, callback) {
        if (element.addEventListener) {
          element.addEventListener(type, callback);
        }
        else if (element.attachEvent) {
          element.attachEvent('on' + type, callback);
        }
      }
      function decorate(event) {
        event = event || window.event;
        var target = event.target || event.srcElement;
        if (target && (target.getAttribute('action') || target.getAttribute('href'))) {
          ga(function (tracker) {
            var linkerParam = tracker.get('linkerParam');
            document.cookie = '_shopify_ga=' + linkerParam + '; ' + 'path=/';
          });
        }
      }
      addListener(window, 'load', function(){
        for (var i=0; i < document.forms.length; i++) {
          var action = document.forms[i].getAttribute('action');
          if(action && action.indexOf('/cart') >= 0) {
            addListener(document.forms[i], 'submit', decorate);
          }
        }
        for (var i=0; i < document.links.length; i++) {
          var href = document.links[i].getAttribute('href');
          if(href && href.indexOf('/checkout') >= 0) {
            addListener(document.links[i], 'click', decorate);
          }
        }
      });
    

    var originalDocumentWrite = document.write;
    document.write = customDocumentWrite;
    try { window.ShopifyAnalytics.merchantGoogleAnalytics.call(this); } catch(error) {};
    document.write = originalDocumentWrite;

    
        window.ShopifyAnalytics.lib.page(
          null,
          {"pageType":"home"}
        );
      
    
  });

  
      var eventsListenerScript = document.createElement('script');
      eventsListenerScript.async = true;
      eventsListenerScript.src = "//cdn.shopify.com/s/assets/shop_events_listener-f2c5800305098f0ebebdfa7d980c9abf56514c46d5305e97a7c476f7c9116163.js";
      document.getElementsByTagName('head')[0].appendChild(eventsListenerScript);
    
})();
</script>
<script defer="defer" integrity="sha256-3igvyAQspxPXvvCO4dejA0hpfvfOL7D6yRYWGvByptM=" crossorigin="anonymous" src="//cdn.shopify.com/s/assets/storefront/express_buttons-de282fc8042ca713d7bef08ee1d7a30348697ef7ce2fb0fac916161af072a6d3.js"></script>
<script defer="defer" src="//cdn.shopify.com/s/assets/themes_support/ga_urchin_forms-68ca1924c495cfc55dac65f4853e0c9a395387ffedc8fe58e0f2e677f95d7f23.js"></script>

  
  <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.min.js"></script>
  
  <script src="//cdn.shopify.com/s/assets/themes_support/option_selection-ea4f4a242e299f2227b2b8038152223f741e90780c0c766883939e8902542bda.js" type="text/javascript"></script>
  <script src="//cdn.shopify.com/s/assets/themes_support/api.jquery-0ea851da22ae87c0290f4eeb24bc8b513ca182f3eb721d147c009ae0f5ce14f9.js" type="text/javascript"></script>

  
  
  <meta name="yandex-verification" content="73b01b198e67d727" />
  <meta name="p:domain_verify" content="85ce6a62ca5f2e2c95715afc68922a9c"/>
  
  <script>
    function calculateShippingTime(spr, wh){
      wh = wh.split(',');
      var alisa_working_days = [0, 1, 1, 1, 1, 1, 0];
	
      var value = 0;
      var start_date = new Date();
	 
	  
      if ( wh.indexOf('36') != -1){ // "Афина"
          value = +start_date; // сегодня
          if (start_date.getDay() == 0 || start_date.getHours() >= 15){ // завтра
              start_date.setHours(0);
              value = +start_date.setDate(start_date.getDate() + 1);
          }
          if (start_date.getDay() == 6 && start_date.getHours() >= 15){ // послезавтра
              value = +start_date.setDate(start_date.getDate() + 2);
          }
		  check_date=start_date;
		  while(alisa_working_days[start_date.getDay()]==0){
		  value = +start_date.setDate(check_date.getDate()+1);
		  }
      } else{ // "Афины" нет, перебираем склады, выбираем самый большой срок
          value = [];
          for (var i = 0; i < wh.length; i++){
              if (spr[wh[i]]) { // в справочнике есть такой склад
                  var w = spr[wh[i]];

                  if (w.special_date != '' && +new Date(w.special_date) > +start_date){ // установлена специальная дата, считаем от неё
                      start_date = new Date(w.special_date);
                  }

                  // start_date - нерабочий день поставщика?
                  while (!w.working_days[start_date.getDay()]){
                      start_date.setDate(start_date.getDate() + 1);
                      start_date.setHours(0); // сбрасываем часы перед проверкой deadline
                  }

                  // проверка deadline
                  var deadline = w.deadline.split(':');
                  if (start_date.getHours() > deadline[0] || (start_date.getHours() == deadline[0] && start_date.getMinutes() > deadline[1])){
                      // рабочий день поставщика, но время - после deadline
                      // добавляем 1 день и ищем следующий рабочий день поставщика
                      start_date.setDate(start_date.getDate() + 1);
                      while (!w.working_days[start_date.getDay()]){
                          start_date.setDate(start_date.getDate() + 1);
                      }
                  }
                  while (w.shipping_days){
                      start_date.setDate(start_date.getDate() + 1);
                      if (alisa_working_days[start_date.getDay()]) w.shipping_days--;
                  }

                  value.push(+start_date);
              }
          }
          if (value.length){
              value = Math.max.apply(null, value);
          } else {
              value = 0;
          }
      }

      return value;
  }
  </script>
</head>

<body>
  <!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-5DGB9H"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-5DGB9H');</script>
<!-- End Google Tag Manager -->
      
  
  <!-- Begin toolbar -->
  <div class="toolbar-wrapper">
    <div class="toolbar clearfix">
        <ul class="unstyled">
          <li class="search-field fr">
            <form class="search" action="/search">
              <button type="submit" alt="Go" class="go"><i class="fa fa-search"></i></button>
              <input type="text" name="q" class="search_box" placeholder="Поиск" value="" />
            </form>
          </li>
          
              <li class="fr"><a href="/cart" class="cart" title="Корзина"><i class="fa fa-shopping-cart"></i> Корзина пока пуста</a></li>
        
          
          
  
    <li class="customer-links">
      <a href="/account/login" id="customer_login_link">Войти</a>
      
     <!-- 99 Rabbits 
      <span class="or">|</span>
      <a href="/account/register" id="customer_register_link">Зарегистрироваться</a>
     99 Rabbits -->
      
    </li>

  


          
        </ul>
        <div id="menu-button" class="menu-icon"><i class="fa fa-bars"></i>Меню</div>
    </div>
  </div>
  <!-- End toolbar -->
  
  <!-- Begin Mobile Nav -->
  <div class="row mobile-wrapper">    
    <nav class="mobile clearfix">
      <div class="flyout">
<ul class="clearfix">
  <!-- 99Rabbits Catalog Menu-->
  
  <li>
   <!-- <a href="/collections/all" class=" navlink"><span>Каталог</span></a>    -->
    <span class="account-links">Каталог</span>
    <span class="more"><i class="fa fa-plus"></i></span>
    <ul class="sub-menu">
       
      <li> <a href="/collections/zhenskoe-belyo" class=" navlink"><span>Женское белье</span></a></li>
      
      <li> <a href="/collections/eroticheskoe-belyo" class=" navlink"><span>Эротическое белье</span></a></li>
      
      <li> <a href="/collections/chulki-kolgotki" class=" navlink"><span>Чулки и колготки</span></a></li>
      
      <li> <a href="/collections/dlya-doma-i-sna" class=" navlink"><span>Домашняя одежда</span></a></li>
      
      <li> <a href="/collections/zhenskaya-odezhda" class=" navlink"><span>Женская одежда</span></a></li>
      
      <li> <a href="/collections/kupalniki-i-plyazhnaya-odezhda" class=" navlink"><span>Купальники</span></a></li>
      
      <li> <a href="/collections/muzhskoe-beliyo" class=" navlink"><span>Мужское</span></a></li>
      
      <li> <a href="/collections/dizainery" class=" navlink"><span>Дизайнеры</span></a></li>
      
      <li> <a href="/collections/sale" class=" navlink"><span>Sale</span></a></li>
      
      <li> <a href="/collections/new" class=" navlink"><span>Новинки</span></a></li>
      
      <li> <a href="/collections/podarki-dlya-nee" class=" navlink"><span>❤ Подарки для нее</span></a></li>
      
      <li> <a href="/collections/podarki-dlya-nego" class=" navlink"><span>♣ Подарки для него</span></a></li>
      
    </ul>
  </li> 
  <!-- 99Rabbits Catalog Menu End-->
  
  
  
  <li>
    <a href="/pages/dostavka" class=" navlink"><span>Доставка и оплата</span></a>
  </li>
  
  
  
  <li>
    <a href="/pages/kontakty" class=" navlink"><span>Контакты</span></a>
  </li>
  
  
  
  <li>
    <a href="/pages/uznat_razmer_po_brendam" class=" navlink"><span>Сервис</span></a>
  </li>
  
  
  
  <li>
    <a href="/pages/obmen-i-vozvrat" class=" navlink"><span>Условия обмена</span></a>
  </li>
  
  



  <li><span class="account-links">Личный кабинет</span>
    <span class="more"><i class="fa fa-user"></i></span>
    <ul class="sub-menu">
    
      <li class="customer-links"><a href="/account/login" id="customer_login_link">Войти</a></li>
      
      <li class="customer-links"><a href="/account/register" id="customer_register_link">Зарегистрироваться</a></li>
      
    
    </ul>
  </li>

  
  <li><span class="account-links">Позвоните нам</span>
    <span class="more"><i class="fa fa-phone"></i></span>
    <ul class="sub-menu">
      <li class="customer-links"><a><i class="fa fa-caret-down"></i> кликните, чтобы позвонить/написать <i class="fa fa-caret-down"></i></i></a></li>
    	  <li class="customer-links"><a href="tel:+380674834842">(067) 48 348 42</a></li>
          <li class="customer-links"><a href="tel:+380997139433">(099) 71 39 433</a></li>
          <li class="customer-links"><a href="tel:+380636969340">(063) 69 69 340</a></li>
          <li class="customer-links"><a href="tel:+380487003077">(048) 700 30 77</a></li>
          <li class="customer-links"><a href="mailto:contact@alisa.in.ua">contact@alisa.in.ua</a></li>
    </ul>
  </li>
    <li class="search-field">
    <form class="search" action="/search">
      <button type="submit" alt="Go" class="go"><i class="fa fa-search"></i></button>
      <input type="text" name="q" class="search_box" placeholder="Поиск" value="" />
    </form>
  </li>
</ul>
</div>
    </nav>  
  </div>
  <!-- End Mobile Nav -->

  <!-- Begin wrapper -->
  <div id="transparency" class="wrapper">
    <div class="row">      
      <!-- Begin right navigation -->
      
      <div class="row" id="header" style="margin:0 0 5px 0px !important;">
        <div class="span12 border-bottom">
          <div class="span4 inner-left logo-wrapper">
            <div class="logo">
              
              <a href="/"><img src="//cdn.shopify.com/s/files/1/0661/9019/t/105/assets/logo.png?518293478356493345" alt="Alisa.ua" /></a>
             <!-- <h1 class="tagline">интернет-магазин нижнего белья</h1> -->
              
              <h1 style="display:none"><a href="/">Alisa.ua</a></h1>
              
              
            </div> 
          </div> 
      
          
          <section id="nav">
            <div class="span8 inner-right">
              <nav class="main">
                <ul class="horizontal unstyled clearfix fr">
  
  
  
  
  


  <li class="">
    <a href="/pages/dostavka" >
      Доставка и оплата
      
    </a> 
    
  </li>
  
  
  
  
  


  <li class=" dropdown">
    <a href="/pages/kontakty" >
      Контакты
       <i class="fa fa-angle-down"></i>
    </a> 
    
    <ul class="dropdown">
      
        
        <li>
          <a href="/pages/about-us" >О нас</a>
        </li>
        
      
    </ul>
    
  </li>
  
  
  
  
  


  <li class=" dropdown">
    <a href="/pages/uznat_razmer_po_brendam" >
      Сервис
       <i class="fa fa-angle-down"></i>
    </a> 
    
    <ul class="dropdown">
      
        
        <li>
          <a href="/pages/uznat_razmer_po_brendam" >Как выбрать размер</a>
        </li>
        
        <li>
          <a href="/pages/kak-kupit" >Как купить</a>
        </li>
        
        <li>
          <a href="/pages/faq" >Вопросы и ответы (FAQ)</a>
        </li>
        
        <li>
          <a href="/pages/tkani-materialy" >Справочник по тканям и материалам</a>
        </li>
        
        <li>
          <a href="/pages/vozvrat" >Заявка на возврат</a>
        </li>
        
      
    </ul>
    
  </li>
  
  
  
  
  


  <li class="">
    <a href="/pages/obmen-i-vozvrat" >
      Условия обмена
      
    </a> 
    
  </li>
  
</ul>
              </nav> 
            </div> 
          </section> 
 <div class="span8 inner-right">
   <p class="promo-line">
   Бесплатная доставка по Киеву &#9679; Бесплатный Возврат &#9679; 35к покупателей с 2003 &#9679; Говоримо Українською
   </p>
          </div>
        </div> 
      </div> 
      
      <!-- End right navigation -->
      
        <!-- Begin below navigation -->
 
      <section id="nav" class="row" style="padding-bottom:15px; margin:0 0 5px 0px !important;">
        <div class="span12">
          <nav class="catalog">
            <ul class="horizontal unstyled clearfix catalog">
  
  
  
  
  


  <li class=" dropdown">
    <a href="/collections/zhenskoe-belyo" >
      
       Женское белье
      
       <i class="fa fa-angle-down"></i>
    </a> 
    
    <ul class="dropdown">
      
        
        <li>
          <a href="/collections/bustgaltery" >Бюстгальтеры</a>
        </li>
        
        <li>
          <a href="/collections/trusiki" >Трусики</a>
        </li>
        
        <li>
          <a href="/collections/poyasa-dlya-chulok" >Пояса</a>
        </li>
        
        <li>
          <a href="/collections/mayki" >Майки</a>
        </li>
        
        <li>
          <a href="/collections/body" >Боди</a>
        </li>
        
        <li>
          <a href="/collections/zhenskoe-belyo/big-size" >Большие размеры</a>
        </li>
        
        <li>
          <a href="/collections/termo-woman" >Термобелье</a>
        </li>
        
        <li>
          <a href="/collections/utiagivaiushchee-belyo" >Утягивающее</a>
        </li>
        
        <li>
          <a href="/collections/besshovnoe" >Бесшовное</a>
        </li>
        
        <li>
          <a href="/collections/sport" >Спортивное</a>
        </li>
        
        <li>
          <a href="/collections/mamam" >Для мам</a>
        </li>
        
        <li>
          <a href="/collections/aksessuary" >Аксессуары</a>
        </li>
        
      
    </ul>
    
  </li>
  
  
  
  
  


  <li class=" dropdown">
    <a href="/collections/eroticheskoe-belyo" >
      
       Эротическое белье
      
       <i class="fa fa-angle-down"></i>
    </a> 
    
    <ul class="dropdown">
      
        
        <li>
          <a href="/collections/seksualnye-komplekty" >Сексуальные комплекты</a>
        </li>
        
        <li>
          <a href="/collections/sorochki-i-babydolly" >Сорочки и бебидоллы</a>
        </li>
        
        <li>
          <a href="/collections/eroticheskie-trusiki" >Эротические трусики</a>
        </li>
        
        <li>
          <a href="/collections/pikantnye-body" >Пикантные боди</a>
        </li>
        
        <li>
          <a href="/collections/bodystocking" >Бодистокинги</a>
        </li>
        
        <li>
          <a href="/collections/igrovye-kostyumy" >Игровые костюмы</a>
        </li>
        
        <li>
          <a href="/collections/korsety" >Корсеты</a>
        </li>
        
        <li>
          <a href="/collections/chulki-i-poyasa" >Чулки и пояса</a>
        </li>
        
        <li>
          <a href="/collections/klubnye-platya" >Клубные платья</a>
        </li>
        
        <li>
          <a href="/collections/eroticheskie-aksessuaryi" >Эротические аксессуары</a>
        </li>
        
      
    </ul>
    
  </li>
  
  
  
  
  


  <li class=" dropdown">
    <a href="/collections/chulki-kolgotki" >
      
       Чулки и колготки
      
       <i class="fa fa-angle-down"></i>
    </a> 
    
    <ul class="dropdown">
      
        
        <li>
          <a href="/collections/chulki" >Чулки</a>
        </li>
        
        <li>
          <a href="/collections/kolgotki" >Колготки</a>
        </li>
        
        <li>
          <a href="/collections/legginsy" >Леггинсы</a>
        </li>
        
        <li>
          <a href="/collections/nosky" >Носочки/следки</a>
        </li>
        
        <li>
          <a href="/collections/golfy" >Гольфы/ботфорты</a>
        </li>
        
        <li>
          <a href="/collections/getri" >Гетры</a>
        </li>
        
      
    </ul>
    
  </li>
  
  
  
  
  


  <li class=" dropdown">
    <a href="/collections/dlya-doma-i-sna" >
      
       Домашняя одежда
      
       <i class="fa fa-angle-down"></i>
    </a> 
    
    <ul class="dropdown">
      
        
        <li>
          <a href="/collections/pizhamki" >Пижамы</a>
        </li>
        
        <li>
          <a href="/collections/sorochki-dlya-sna" >Ночные сорочки</a>
        </li>
        
        <li>
          <a href="/collections/halaty" >Халаты</a>
        </li>
        
        <li>
          <a href="/collections/smart-collection" >Платья</a>
        </li>
        
        <li>
          <a href="/collections/odezhda-dlya-doma" >Домашняя одежда</a>
        </li>
        
        <li>
          <a href="/collections/domashnya-obuv" >Домашняя обувь</a>
        </li>
        
      
    </ul>
    
  </li>
  
  
  
  
  


  <li class=" dropdown">
    <a href="/collections/zhenskaya-odezhda" >
      
       Женская одежда
      
       <i class="fa fa-angle-down"></i>
    </a> 
    
    <ul class="dropdown">
      
        
        <li>
          <a href="/collections/platie" >Платья</a>
        </li>
        
        <li>
          <a href="/collections/bluza" >Блузы, рубашки, топы</a>
        </li>
        
        <li>
          <a href="/collections/golf" >Водолазки</a>
        </li>
        
        <li>
          <a href="/collections/kofta" >Джемперы, свитшоты</a>
        </li>
        
        <li>
          <a href="/collections/yubca" >Юбки</a>
        </li>
        
        <li>
          <a href="/collections/bryuki" >Брюки</a>
        </li>
        
        <li>
          <a href="https://alisa.ua/collections/shorti" >Шорты</a>
        </li>
        
        <li>
          <a href="/collections/kombinezon" >Комбинезоны</a>
        </li>
        
        <li>
          <a href="/collections/pidzhaki-kardigany" >Пиджаки, жилеты</a>
        </li>
        
      
    </ul>
    
  </li>
  
  
  
  
  


  <li class="">
    <a href="/collections/kupalniki-i-plyazhnaya-odezhda" >
      
       Купальники
      
      
    </a> 
    
  </li>
  
  
  
  
  


  <li class=" dropdown">
    <a href="/collections/muzhskoe-beliyo" >
      
       Мужское
      
       <i class="fa fa-angle-down"></i>
    </a> 
    
    <ul class="dropdown">
      
        
        <li>
          <a href="/collections/muzhskie-trusy" >Трусы</a>
        </li>
        
        <li>
          <a href="/collections/noski-muzhskie" >Носки</a>
        </li>
        
        <li>
          <a href="https://alisa.ua/collections/muzhskaya-odezhda-dlya-sna" >Пижамы</a>
        </li>
        
        <li>
          <a href="https://alisa.ua/collections/muzhskaya-odezhda-dlya-doma" >Одежда для дома</a>
        </li>
        
        <li>
          <a href="/collections/mayki-futbolki-muzhskie" >Майки и футболки</a>
        </li>
        
        <li>
          <a href="/collections/termo-men" >Термобелье</a>
        </li>
        
        <li>
          <a href="https://alisa.ua/collections/plyazhnoe-men" >Плавки и пляжные шорты</a>
        </li>
        
        <li>
          <a href="/collections/myuzhskoe-eroticheskoe" >Эротическое</a>
        </li>
        
        <li>
          <a href="/collections/sport-men" >Спортивное</a>
        </li>
        
      
    </ul>
    
  </li>
  
  
  
  
  


  <li class="">
    <a href="/collections/dizainery" >
      
       Дизайнеры
      
      
    </a> 
    
  </li>
  
  
  
  
  


  <li class="">
    <a href="/collections/sale" >
      
      <span style="color:#e74c3c; font-weight:bold;">
      Sale
      </span>
      
      
    </a> 
    
  </li>
  
  
  
  
  


  <li class="">
    <a href="/collections/new" >
      
       Новинки
      
      
    </a> 
    
  </li>
  
  
  
  
  


  <li class="">
    <a href="/collections/podarki-dlya-nee" >
      
       ❤ Подарки для нее
      
      
    </a> 
    
  </li>
  
  
  
  
  


  <li class="">
    <a href="/collections/podarki-dlya-nego" >
      
       ♣ Подарки для него
      
      
    </a> 
    
  </li>
  
</ul>
          </nav> <!-- /.main -->
          <nav class="mobile clearfix">
            <div class="flyout">
<ul class="clearfix">
  <!-- 99Rabbits Catalog Menu-->
  
  <li>
   <!-- <a href="/collections/all" class=" navlink"><span>Каталог</span></a>    -->
    <span class="account-links">Каталог</span>
    <span class="more"><i class="fa fa-plus"></i></span>
    <ul class="sub-menu">
       
      <li> <a href="/collections/zhenskoe-belyo" class=" navlink"><span>Женское белье</span></a></li>
      
      <li> <a href="/collections/eroticheskoe-belyo" class=" navlink"><span>Эротическое белье</span></a></li>
      
      <li> <a href="/collections/chulki-kolgotki" class=" navlink"><span>Чулки и колготки</span></a></li>
      
      <li> <a href="/collections/dlya-doma-i-sna" class=" navlink"><span>Домашняя одежда</span></a></li>
      
      <li> <a href="/collections/zhenskaya-odezhda" class=" navlink"><span>Женская одежда</span></a></li>
      
      <li> <a href="/collections/kupalniki-i-plyazhnaya-odezhda" class=" navlink"><span>Купальники</span></a></li>
      
      <li> <a href="/collections/muzhskoe-beliyo" class=" navlink"><span>Мужское</span></a></li>
      
      <li> <a href="/collections/dizainery" class=" navlink"><span>Дизайнеры</span></a></li>
      
      <li> <a href="/collections/sale" class=" navlink"><span>Sale</span></a></li>
      
      <li> <a href="/collections/new" class=" navlink"><span>Новинки</span></a></li>
      
      <li> <a href="/collections/podarki-dlya-nee" class=" navlink"><span>❤ Подарки для нее</span></a></li>
      
      <li> <a href="/collections/podarki-dlya-nego" class=" navlink"><span>♣ Подарки для него</span></a></li>
      
    </ul>
  </li> 
  <!-- 99Rabbits Catalog Menu End-->
  
  
  
  <li>
    <a href="/pages/dostavka" class=" navlink"><span>Доставка и оплата</span></a>
  </li>
  
  
  
  <li>
    <a href="/pages/kontakty" class=" navlink"><span>Контакты</span></a>
  </li>
  
  
  
  <li>
    <a href="/pages/uznat_razmer_po_brendam" class=" navlink"><span>Сервис</span></a>
  </li>
  
  
  
  <li>
    <a href="/pages/obmen-i-vozvrat" class=" navlink"><span>Условия обмена</span></a>
  </li>
  
  



  <li><span class="account-links">Личный кабинет</span>
    <span class="more"><i class="fa fa-user"></i></span>
    <ul class="sub-menu">
    
      <li class="customer-links"><a href="/account/login" id="customer_login_link">Войти</a></li>
      
      <li class="customer-links"><a href="/account/register" id="customer_register_link">Зарегистрироваться</a></li>
      
    
    </ul>
  </li>

  
  <li><span class="account-links">Позвоните нам</span>
    <span class="more"><i class="fa fa-phone"></i></span>
    <ul class="sub-menu">
      <li class="customer-links"><a><i class="fa fa-caret-down"></i> кликните, чтобы позвонить/написать <i class="fa fa-caret-down"></i></i></a></li>
    	  <li class="customer-links"><a href="tel:+380674834842">(067) 48 348 42</a></li>
          <li class="customer-links"><a href="tel:+380997139433">(099) 71 39 433</a></li>
          <li class="customer-links"><a href="tel:+380636969340">(063) 69 69 340</a></li>
          <li class="customer-links"><a href="tel:+380487003077">(048) 700 30 77</a></li>
          <li class="customer-links"><a href="mailto:contact@alisa.in.ua">contact@alisa.in.ua</a></li>
    </ul>
  </li>
    <li class="search-field">
    <form class="search" action="/search">
      <button type="submit" alt="Go" class="go"><i class="fa fa-search"></i></button>
      <input type="text" name="q" class="search_box" placeholder="Поиск" value="" />
    </form>
  </li>
</ul>
</div>
          </nav> <!-- /.mobile --> 
        </div> 
                </section> 
      <!-- End below navigation -->
      
<!-- Begin news-row -->
<!-- ОБЪЯВА НА ГЛАВНОЙ -->
<!-- <div class="span12 attention-block yellow">-15% на ВСЁ при покупке от 1000 грн. Даже на товары из <a href="https://alisa.ua/collections/sale">распродажи</a>. Используй купон <strong>ACM15</strong>. Только сегодня.</div>
</div> -->

<!-- End news-row -->

   
      <!-- Begin content -->
      <section id="content" class="clearfix">
        <!-- ОБЪЯВА НА ГЛАВНОЙ -->
<!--  <div class="span12 attention-block green"> C Новым Годом, друзья! Мы уже работаем в обычном графике если что. 
 </div> -->
<!-- End news-row -->

<!-- Begin slider -->
<div class="span12">
  <div class="flexslider-container">
    <div class="flexslider">
      <ul class="slides">
        
          
          
          
          
          
        
          
          
          
          
          
          <li>
            <a href="/collections/polskoe-belyo/sale">
              <img src="//cdn.shopify.com/s/files/1/0661/9019/t/105/assets/slideshow_2.jpg?518293478356493345" alt="-20% на польское белье" />
            </a>
          </li>
          
        
          
          
          
          
          
        
          
          
          
          
          
        
          
          
          
          
          
        
          
          
          
          
          
        
          
          
          
          
          
        
          
          
          
          
          
        
          
          
          
          
          
        
          
          
          
          
          
        
      </ul>
      <div class="flex-controls"></div>
    </div>
  </div>
</div>
<!-- End slider -->


<!-- Begin promo images -->
<div class="row" id="fp-images" style="margin-bottom:25px">
  
  
  
  
  <div class="span4">
    <a href="/collections/keosme">
      <img src="//cdn.shopify.com/s/files/1/0661/9019/t/105/assets/fp_image_1.jpg?518293478356493345" alt="Базовое белье" />
    </a>
  </div>
  
  
  
  
  <div class="span4">
    <a href="/collections/podarki-dlya-nee">
      <img src="//cdn.shopify.com/s/files/1/0661/9019/t/105/assets/fp_image_2.jpg?518293478356493345" alt="Чулки и Колготки" />
    </a>
  </div>
  
  
  
  
  <div class="span4">
    <a href="/collections/sale">
      <img src="//cdn.shopify.com/s/files/1/0661/9019/t/105/assets/fp_image_3.jpg?518293478356493345" alt="Распродажа белья" />
    </a>
  </div>
  
</div>
<!-- End promo images -->

      
<div class="products">
  <div id="glowna_bestsellery_naglowek">
    <div id="glowna_bestsellery_naglowek_linia" class="span12"></div>
    <div id="glowna_bestsellery_tekst_up">
      <div id="glowna_bestsellery_tekst">Новинки недели</div>
    </div>
    <div class="clearfix"></div>
  </div>
  
  

<div class="product span3 ">
  
  
  
  
  
    
  
   
    <span class="circle badge-new">New</span>
  
  
  
   
  <div class="image">
    <a href="/collections/novinki-nedeli/products/byustgalter-jasmine-1301-12-kory-powder">
      <div class="reveal"> 
      <img src="//cdn.shopify.com/s/files/1/0661/9019/products/jasmine-kory-pudra-alisa.ua_d8828fc6-4659-4ad2-863c-31a988e99627_large.JPG?v=1520961485" alt="Бюстгальтер с полудублированными чашками 1301/12 Kory powder" />
        
        <img class="hidden" src="//cdn.shopify.com/s/files/1/0661/9019/products/jasmine-kory-nanet-pudra-alisa.ua_f727880c-3ef3-4a6a-87ef-062d1d3df7af_large.jpg?v=1520961485" alt="Бюстгальтер с полудублированными чашками 1301/12 Kory powder" />   
        
      </div>
    </a>
  </div>
     
  
  <div class="details">
    <a href="/collections/novinki-nedeli/products/byustgalter-jasmine-1301-12-kory-powder" class="clearfix">
      <h4 class="title">Бюстгальтер с полудублированными чашками 1301/12 Kory powder</h4>
      
      <span class="vendor">Jasmine lingerie</span>
      
      
      <span class="price">
      
        
        
    		449 грн.
        
      
      </span>
      
    </a>
  </div>
  
</div>




  
  

<div class="product span3 ">
  
  
  
  
  
    
  
   
    <span class="circle badge-new">New</span>
  
  
  
   
  <div class="image">
    <a href="/collections/novinki-nedeli/products/sorochka-jasmine-8106-12-camelia-powder">
      <div class="reveal"> 
      <img src="//cdn.shopify.com/s/files/1/0661/9019/products/jasmine-camelia-pudra-alisa.ua_42ae0176-e7a5-40a3-b951-d1e696c65711_large.jpg?v=1520961987" alt="Ночная сорочка с принтом 8106/12 Camelia powder" />
        
      </div>
    </a>
  </div>
     
  
  <div class="details">
    <a href="/collections/novinki-nedeli/products/sorochka-jasmine-8106-12-camelia-powder" class="clearfix">
      <h4 class="title">Ночная сорочка с принтом 8106/12 Camelia powder</h4>
      
      <span class="vendor">Jasmine lingerie</span>
      
      
      <span class="price">
      
        
        
    		799 грн.
        
      
      </span>
      
    </a>
  </div>
  
</div>




  
  

<div class="product span3 ">
  
  
  
  
  
    
  
   
    <span class="circle badge-new">New</span>
  
  
  
   
  <div class="image">
    <a href="/collections/novinki-nedeli/products/byustgalter-jasmine-1610-12-glam-powder">
      <div class="reveal"> 
      <img src="//cdn.shopify.com/s/files/1/0661/9019/products/jasmine-glam-pudra-alisa.ua_209c56fd-220c-40d1-8a0b-1cc80e32e00d_large.JPG?v=1520961330" alt="Бралет без косточек с принтом 1610/12 Glam powder" />
        
        <img class="hidden" src="//cdn.shopify.com/s/files/1/0661/9019/products/jasmine-glam-sindy-pudra-alisa.ua_1e95a34b-2585-4079-ac84-067297715317_large.jpg?v=1520961330" alt="Бралет без косточек с принтом 1610/12 Glam powder" />   
        
      </div>
    </a>
  </div>
     
  
  <div class="details">
    <a href="/collections/novinki-nedeli/products/byustgalter-jasmine-1610-12-glam-powder" class="clearfix">
      <h4 class="title">Бралет без косточек с принтом 1610/12 Glam powder</h4>
      
      <span class="vendor">Jasmine lingerie</span>
      
      
      <span class="price">
      
        
        
    		369 грн.
        
      
      </span>
      
    </a>
  </div>
  
</div>




  
  

<div class="product span3 ">
  
  
  
  
  
    
  
   
    <span class="circle badge-new">New</span>
  
  
  
   
  <div class="image">
    <a href="/collections/novinki-nedeli/products/byustgalter-jasmine-1404-12-aris-powder">
      <div class="reveal"> 
      <img src="//cdn.shopify.com/s/files/1/0661/9019/products/jasmine-aris-pudra-alisa.ua_834d5546-5bd0-4c76-ad61-db2cfbd8187a_large.JPG?v=1520961550" alt="Кружевной бюстгальтер с мягкими чашками 1404/12 Aris powder" />
        
        <img class="hidden" src="//cdn.shopify.com/s/files/1/0661/9019/products/jasmine-aris-nanet-pudra-alisa.ua_18e11330-9f8c-44ba-a55e-97f61ec5ce43_large.jpg?v=1520961550" alt="Кружевной бюстгальтер с мягкими чашками 1404/12 Aris powder" />   
        
      </div>
    </a>
  </div>
     
  
  <div class="details">
    <a href="/collections/novinki-nedeli/products/byustgalter-jasmine-1404-12-aris-powder" class="clearfix">
      <h4 class="title">Кружевной бюстгальтер с мягкими чашками 1404/12 Aris powder</h4>
      
      <span class="vendor">Jasmine lingerie</span>
      
      
      <span class="price">
      
        
        
    		429 грн.
        
      
      </span>
      
    </a>
  </div>
  
</div>


<div style="clear:both;"></div>

  
  

<div class="product span3 ">
  
  
  
  
  
    
  
   
    <span class="circle badge-new">New</span>
  
  
  
   
  <div class="image">
    <a href="/collections/novinki-nedeli/products/byustgalter-jasmine-1132-12-juli-powder">
      <div class="reveal"> 
      <img src="//cdn.shopify.com/s/files/1/0661/9019/products/jasmine-juli-pudra-alisa.ua_e7dae35f-bb89-4ec7-9b5e-f01ef0af124d_large.JPG?v=1520961598" alt="Поролоновый бюстгальтер full-cup с принтом 1132/12 Juli powder" />
        
        <img class="hidden" src="//cdn.shopify.com/s/files/1/0661/9019/products/jasmine-juli-nanet-pudra-alisa.ua_847183df-fa0b-491a-98d6-daf62495352a_large.jpg?v=1520961598" alt="Поролоновый бюстгальтер full-cup с принтом 1132/12 Juli powder" />   
        
      </div>
    </a>
  </div>
     
  
  <div class="details">
    <a href="/collections/novinki-nedeli/products/byustgalter-jasmine-1132-12-juli-powder" class="clearfix">
      <h4 class="title">Поролоновый бюстгальтер full-cup с принтом 1132/12 Juli powder</h4>
      
      <span class="vendor">Jasmine lingerie</span>
      
      
      <span class="price">
      
        
        
    		479 грн.
        
      
      </span>
      
    </a>
  </div>
  
</div>




  
  

<div class="product span3 ">
  
  
  
  
  
    
  
   
    <span class="circle badge-new">New</span>
  
  
  
   
  <div class="image">
    <a href="/collections/novinki-nedeli/products/trusy-jasmine-2227-12-sindy-powder">
      <div class="reveal"> 
      <img src="//cdn.shopify.com/s/files/1/0661/9019/products/jasmine-sindy-pudra-alisa.ua_aaa7ca50-3637-4a54-81ce-02b22688f501_large.JPG?v=1520961655" alt="Трусики бразилиана с принтом 2227/12 Sindy powder" />
        
        <img class="hidden" src="//cdn.shopify.com/s/files/1/0661/9019/products/jasmine-glam-sindy-pudra-alisa.ua_large.jpg?v=1520961655" alt="Трусики бразилиана с принтом 2227/12 Sindy powder" />   
        
      </div>
    </a>
  </div>
     
  
  <div class="details">
    <a href="/collections/novinki-nedeli/products/trusy-jasmine-2227-12-sindy-powder" class="clearfix">
      <h4 class="title">Трусики бразилиана с принтом 2227/12 Sindy powder</h4>
      
      <span class="vendor">Jasmine lingerie</span>
      
      
      <span class="price">
      
        
        
    		239 грн.
        
      
      </span>
      
    </a>
  </div>
  
</div>




  
  

<div class="product span3 ">
  
  
  
  
  
    
  
   
    <span class="circle badge-new">New</span>
  
  
  
   
  <div class="image">
    <a href="/collections/novinki-nedeli/products/byustgalter-jasmine-1152-12-neli-powder">
      <div class="reveal"> 
      <img src="//cdn.shopify.com/s/files/1/0661/9019/products/jasmine-neli-pudra-alisa.ua_0f3bb157-da0a-4be4-9716-eba2497f57a9_large.JPG?v=1520961409" alt="Бюстгальтер push-up с принтом 1152/12 Neli powder" />
        
        <img class="hidden" src="//cdn.shopify.com/s/files/1/0661/9019/products/jasmine-neli-elvira-pudra-alisa.ua_5086b420-64eb-4991-93e0-1f3c66fd14a2_large.jpg?v=1520961409" alt="Бюстгальтер push-up с принтом 1152/12 Neli powder" />   
        
      </div>
    </a>
  </div>
     
  
  <div class="details">
    <a href="/collections/novinki-nedeli/products/byustgalter-jasmine-1152-12-neli-powder" class="clearfix">
      <h4 class="title">Бюстгальтер push-up с принтом 1152/12 Neli powder</h4>
      
      <span class="vendor">Jasmine lingerie</span>
      
      
      <span class="price">
      
        
        
    		399 грн.
        
      
      </span>
      
    </a>
  </div>
  
</div>




  
  

<div class="product span3 ">
  
  
  
  
  
    
  
   
    <span class="circle badge-new">New</span>
  
  
  
   
  <div class="image">
    <a href="/collections/novinki-nedeli/products/trusy-jasmine-2222-12-selena-powder">
      <div class="reveal"> 
      <img src="//cdn.shopify.com/s/files/1/0661/9019/products/jasmine-selena-pudra-alisa.ua_286cf48e-72f0-4174-b101-ec04baacd1a6_large.JPG?v=1520961847" alt="Трусики бразилиана с принтом 2222/12 Selena powder" />
        
        <img class="hidden" src="//cdn.shopify.com/s/files/1/0661/9019/products/jasmine-mona-selena-pudra-alisa.ua_752457ad-ef1d-4971-b555-7bd9feeea1c0_large.jpg?v=1520961847" alt="Трусики бразилиана с принтом 2222/12 Selena powder" />   
        
      </div>
    </a>
  </div>
     
  
  <div class="details">
    <a href="/collections/novinki-nedeli/products/trusy-jasmine-2222-12-selena-powder" class="clearfix">
      <h4 class="title">Трусики бразилиана с принтом 2222/12 Selena powder</h4>
      
      <span class="vendor">Jasmine lingerie</span>
      
      
      <span class="price">
      
        
        
    		189 грн.
        
      
      </span>
      
    </a>
  </div>
  
</div>


<div style="clear:both;"></div>

  
</div>


<!-- INSTA FEED START 
<div class="span12 p20" style="padding: 1.5em 0;">
  <div class="intro clearfix">
  	  <div id="glowna_bestsellery_naglowek">
    <div id="glowna_bestsellery_naglowek_linia" class="span12"></div>
    <div id="glowna_bestsellery_tekst_up">
      <div id="glowna_bestsellery_tekst" style="line-height: 25px;">Добавляйтесь в инстаграме</div>
    </div>
    <div class="clearfix"></div>
  </div>
  	
   <div id="insta-feed" style="padding: 1.5em 0;"></div>
  </div>
</div>
<!-- INSTA FEED END -->
<div class="span12 p20">
  <div class="intro clearfix">
      <div class="row">
  <h3 class="collection-title">Отзывы от наших покупателей</h3>
<div class="span6 inner-left">
  <p class="qoutetitle">Лидия (г. Полтава)<span class="qouteorder"> <i class="fa fa-check-square-o"></i> отзыв с сайта <a href="http://www.otzyvua.net/internet-magazina-alisa.html">otzyvua.net</a>
    </span></p>
  
<p><i class="fa fa-quote-left quoteleft"></i> Хочется поделиться первым впечатлением о посещении Вашего магазина, и особенно общением с менеджером по заботе о клиентах интернет- магазина "Алиса" Настей. 
  Особенная доброжелательность. Желание заинтересовать клиента. Я получила грамотные и исчерпывающие ответы на свои вопросы, что очень приятно. 
  Захотелось сразу же подписаться на рассылку новостей и, конечно же, быть клиентом Вашего интернет - магазина. Желаю процветания Вашему интернет-магазину. 
  <i class="fa fa-quote-right quoteright"></i></p>
  </div>
  <p class="qoutetitle">Вячеслав (г. Винница) <span class="qouteorder"> <i class="fa fa-check-square-o"></i> отзыв подтвержден сервисом проверки отзывов <a href="https://shoppilot.ru/companies/alisa/reviews">shoppilot.ru</a></span></p>
  <p><i class="fa fa-quote-left quoteleft"></i> <strong>Отличный товар, отличное обслуживание</strong> <br>Связались через 2 часа после заказа, уточнили все подробности (размеры, способ оплаты и пересылки), о получении денег и отправке уведомили через СМС, на следующий день посылка была уже в моем отделении Новой Почты. 
    Может показаться, что много эмоций в отзыве, но обслуживание и товар действительно безукоризненные. <i class="fa fa-quote-right quoteright"></i>
    <br>
    <span class="qouteorder">Заказ №134ХХХХ</span></p>
   
 
  </div>
<div class="span4 inner-left">
  <p class="qoutetitle">Виктория (Украина)<span class="qouteorder"> <i class="fa fa-check-square-o"></i> отзыв подтвержден сервисом проверки отзывов <a href="https://shoppilot.ru/companies/alisa/reviews">shoppilot.ru</a></span></p>
  <p class="qoute16"><i class="fa fa-quote-left quoteleft"></i>очень приятные в общении менеджеры по продажам, дают корректные и содержательные советы, чувствуется забота о покупателе и репутации магазина. СПАСИБО
      <i class="fa fa-quote-right quoteright"></i><br><span class="qouteorder">Заказ №135ХХХХ</span></p>
  
</div>
<div class="span4 inner-left">
  <p class="qoutetitle">Анна (Украина) <span class="qouteorder"> <i class="fa fa-check-square-o"></i> отзыв подтвержден сервисом проверки отзывов <a href="https://shoppilot.ru/companies/alisa/reviews">shoppilot.ru</a></span></p>
  <p><i class="fa fa-quote-left quoteleft"></i> <strong>Определенно приятно удивлена!</strong> Несколько раз была разочарована интернет-магазинами. На этот раз заказ собрали быстро, консультант позаботилась о правильности выбора размера. 
    Надеюсь, мой позитивный опыт повторится с другими покупательницами
      <i class="fa fa-quote-right quoteright"></i>
  
  
</div>
<div class="span4 inner-left">
 
  <p class="qoutetitle">Маша Грузина <span class="qouteorder"><i class="fa fa-check-square-o"></i> отзыв с сайта <a href="http://hotline.ua/yp/15347/reviews/">hotline.ua</a></span></p>
  
<p class="qoute16"><i class="fa fa-quote-left quoteleft"></i> Весь товар просто супер!!! Особое и огромное спасибо Юленьке, благодаря ей заказ был очень быстрым и приятным))) ...
  <i class="fa fa-quote-right quoteright"></i></p>
  
</div>
  </div>
</div>


<!-- Begin intro -->
<div class="span12 p20">
  <div class="intro clearfix">
   
    <h2>Помогаем женщинам покупать нижнее белье по интернету</h2>
    <div><div class="span8 inner-left">
<p><a href="https://alisa.ua/" title="интернет-магазин нижнего белья Alisa.ua">Alisa.ua</a> — украинский интернет-магазин нижнего белья родом из Одессы. В 2017 году мы открыли склад в Киеве, чтобы ускорить доставку, а клиент-центр теперь работает до 12 ночи.</p>
<p><strong>Мы помогаем женщинам покупать нижнее белье по интернету.</strong> Знаем, как это трудно сделать в обычном магазине и тем более, когда нет возможности примерить бюстгальтер перед покупкой. Поэтому даем невозможную гарантию — безусловный возврат в течение 10 лет. Наши клиентки могут примерить белье и вернуть его, если не подошло.</p>
<p>Списываем бюстгальтер или трусики, если на них остались следы примерки. Прочтите <a href="https://alisa.ua/pages/obmen-i-vozvrat" title="Условия возврата и обмена белья">подробные условия обмена</a>, если вас смущает этот момент.</p>
<h3>Наша миссия — сделать так, чтобы женщины носили правильно подобранное белье.</h3>
<p>Наши менеджеры проходят обязательное обучение бра-фиттингу и сдают экзамен, чтобы мы были уверены, что они могут помочь клиенту правильно подобрать размер и фасон. Даже по телефону. Они спросят <a href="https://alisa.ua/pages/uznat_razmer_po_brendam" title="Как подобрать размер белья">ваши мерки</a> и предпочтения и порекомендуют что выбрать.</p>
<p>Мы просим клиентов оставлять отзывы на сторонних сайтах, где мы не сможем удалить негативный отзыв: на <a href="http://www.otzyvua.net/internet-magazina-alisa.html">ОтзывУА</a>, <a href="http://hotline.ua/yp/15347/reviews/">Хотлайн</a> и в <a href="https://www.facebook.com/pg/alisa.ukraine/reviews/">Фэйсбуке</a>. Так что вы видите там реальную картинку, а не хвалебные оды написанные контент-менеджерами интернет-магазина.</p>
</div>
<div class="span4 inner-left">
<p>Все марки белья в нашем ассортименте от проверенных производителей. Мы стремимся продавать товары с хорошим соотношением цены и качества. Не берем бренды с красивой картинкой и плохой посадкой. Не берем дизайнеров, которые не могут обеспечить одинаковое качество всех своих изделий. Работаем с фабриками напрямую, чтобы в цену товара не включалась наценка оптовых посредников. Используем продвинутые технологии для учета заказов, чтобы ваш заказ не потерялся, о вас не забыли и не тратили ваше время лишними звонками.</p>
</div></div>
  </div>
</div>
<!-- End intro -->



      </section>
      <!-- End content -->
      
    </div>
  </div>
  <!-- End wrapper -->
  
  <!-- Begin footer -->
  <div class="footer-wrapper">
    <footer>
      <div class="row">

        <div class="span12 full-border"></div>
        
        
        
        <!-- Begin latest blog post -->
        
        <!-- End latest blog post -->
        
        <!-- Begin footer navigation -->
        <div class="span2 footer-menu">
          <h4>Сервис</h4>
          <ul class="unstyled">
            
              <li><a href="/pages/dostavka" title="Доставка и оплата">Доставка и оплата</a></li>
            
              <li><a href="/pages/uznat_razmer_po_brendam" title="Как подобрать размер">Как подобрать размер</a></li>
            
              <li><a href="/pages/kak-kupit" title="Как заказать">Как заказать</a></li>
            
              <li><a href="/pages/obmen-i-vozvrat" title="Условия обмена">Условия обмена</a></li>
            
              <li><a href="/pages/vozvrat" title="Заявка на возврат">Заявка на возврат</a></li>
            
              <li><a href="/pages/cooperation" title="Сотрудничество">Сотрудничество</a></li>
            
              <li><a href="/pages/vakansii" title="Вакансии">Вакансии</a></li>
            
          </ul>
        </div>
        <!-- End footer navigation -->
        
        <!-- Begin newsletter/social -->
        <div class="span4">
          
          
          <div class="p30">
            <h4>Подпишитесь на рассылку</h4>
            <form action="//alisa.us1.list-manage.com/subscribe/post?u=d60be08c4cce917ca314e07cd&amp;id=244033a541" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" target="_blank">
              <input type="email" value="" placeholder="Email" name="EMAIL" id="mail" /><input type="submit" class="btn newsletter" value="Вперед!" name="subscribe" id="subscribe" />
            </form>
          </div>
          
          
          
       
               <!-- End newsletter/social -->
        
        
        <div>          
          <div class="clearfix">
          
            <h4>Давайте дружить</h4>
            <span class="social-links">
<a href="https://www.facebook.com/alisa.ukraine" title="Follow us on Facebook"><span class="shopify-social-icon-facebook-circle"></span></a>

<a href="http://www.pinterest.com/alisaua/" title="Follow us on Pinterest"><span class="shopify-social-icon-pinterest-circle"></span></a>
<a href="https://plus.google.com/108328024253348877977" title="Follow us on Google+"><span class="shopify-social-icon-googleplus-circle"></span></a>
<a href="http://instagram.com/alisa_ua/" title="Follow us on Instagram"><span class="shopify-social-icon-instagram-circle"></span></a>




</span>
          
          </div>
          
        </div>
        
          
        </div>
        <div class="span6 footer-menu footer-contacts">
          <div class="col1">
           
            <h4><a href="/pages/kontakty">Контакты</a></h4>
        <ul class="unstyled">
          <li><a href="tel:+380674834842">(067) 48 348 42</a></li>
          <li><a href="tel:+380997139433">(099) 71 39 433</a></li>
          <li><a href="tel:+380636969340">(063) 69 69 340</a></li>
          <li><a href="tel:+380487003077">(048) 700 30 77</a></li>
          <li><a href="mailto:contact@alisa.in.ua">contact@alisa.in.ua</a></li>
         
             </ul>
            
          </div>
            <div class="col2">
          <h4>График работы клиент-центра </h4>
              <p> Пн-Вс: 10:00-19:00 </p>
          <h4>Наш шоурум </h4>
              <p> г. Одесса, ТЦ Афина, 3 этаж, "Аліса" <br>
              (ассортимент отличается от сайта)
               <p>(в Киеве — <a href="/pages/dostavka#kiev">курьерская доставка</a> с примеркой)</p>
          </div>
        </div>
   
        
        <!-- Begin copyright -->
        <div class="span12 tc copyright">
          <p>Copyright &copy; 2003-2018 Alisa.ua | Сделано с любовью в Одессе. Работает на <a href="http://www.shopify.com/?ref=99rabbits">Shopify</a>. </p>
            
            <ul class="credit-cards clearfix">
            
            <li><img src="//cdn.shopify.com/s/files/1/0661/9019/t/105/assets/powered_by_corezoid_bw_40.png?518293478356493345" alt="Corezoid logo" /> </li> 
          
          </ul>
        </div>
        <!-- End copyright -->

      </div> 
    </footer>
  </div>
  <!-- End footer -->
    
  
    <script src="//cdn.shopify.com/s/files/1/0661/9019/t/105/assets/jquery.flexslider-min.js?518293478356493345" type="text/javascript"></script>
  
  
    <script src="//cdn.shopify.com/s/files/1/0661/9019/t/105/assets/jquery.zoom.js?518293478356493345" type="text/javascript"></script>
  
  <script src="//cdn.shopify.com/s/files/1/0661/9019/t/105/assets/jquery.fancybox.js?518293478356493345" type="text/javascript"></script>
  <script src="//cdn.shopify.com/s/files/1/0661/9019/t/105/assets/scripts.js?518293478356493345" type="text/javascript"></script>
  
  

  
<!-- Power Tools view count code -->


<!-- SALES DOUBLER TRACKING -->
<script>
function getCookie(name) {
  var matches = document.cookie.match(new RegExp(
    "(?:^|; )" + name.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g, '\\$1') + "=([^;]*)"
  ));
  return matches ? decodeURIComponent(matches[1]) : undefined;
}

function setCookie(name, value, options) {
  options = options || {};

  var expires = options.expires;

  if (typeof expires == "number" && expires) {
    var d = new Date();
    d.setTime(d.getTime() + expires * 1000);
    expires = options.expires = d;
  }
  if (expires && expires.toUTCString) {
    options.expires = expires.toUTCString();
  }

  value = encodeURIComponent(value);

  var updatedCookie = name + "=" + value;

  for (var propName in options) {
    updatedCookie += "; " + propName;
    var propValue = options[propName];
    if (propValue !== true) {
      updatedCookie += "=" + propValue;
    }
  }

  document.cookie = updatedCookie;
}

function getQueryStringValue (key) {  
  return decodeURIComponent(window.location.search.replace(new RegExp("^(?:.*[&\\?]" + encodeURIComponent(key).replace(/[\.\+\*]/g, "\\$&") + "(?:\\=([^&]*))?)?.*$", "i"), "$1"));  
}  

const utm_mediums = [
	'retargeting',
	'cpc',
	'email',
	'referral',
	'smm',
	'remarketing',
	'cpm'
	];
const utm_sources = [
	'google',
	'facebook',
	'Рассылка%20от%20Алисы',
	'fb',
	'm.facebook.com',
	'l.facebook.com',
	'l.instagram.com',
	'secureurl.fwdcdn.com',
	'facebook.com',
	'instagram',
	'lm.facebook.com',
	'picodi.com',
	'Рассылка+от+Алисы',
	'pokupon',
	'instagram.com',
	'us1.campaign-archive2.com',
	'us1.campaign-archive.com',
	'us1.campaign-archive1.com'
	];
var click_id = getQueryStringValue('aff_sub');
var aff_id = getQueryStringValue('aff_id');
var utm_medium = getQueryStringValue('utm_medium');
var utm_source = getQueryStringValue('utm_source');
var ifCookie = getCookie('sd_visitor');

if (ifCookie != undefined && utm_mediums.includes(utm_medium) && utm_sources.includes(utm_source)){
	setCookie('sd_visitor', "", {expires: 2592000, path: "/"});
} else if(click_id) {
	setCookie('sd_visitor', click_id, {expires: 2592000, path: "/"});
}
if (getQueryStringValue('gclid').length > 0){
	setCookie('sd_visitor', "", {expires: 2592000, path: "/"});
}
</script>
<!-- END OF SALES DOUBLER TRACKING -->

<!-- Power Tools view count code -->

<input type="hidden" name="_pc_params" value="alisa-ua-2.myshopify.com:" />
<script>
jQuery(function(){jQuery("body").on("click",'[name="checkout"], [name="goto_pp"], [name="goto_gc"]',function(){var e=!0,r="Please fill this out and you will be able to check out.";return jQuery('[name^="attributes"], [name="note"]').filter('.required, [required]').each(function(){jQuery(this).removeClass("error"),e&&""==jQuery(this).val()&&(e=!1,r=jQuery(this).attr("data-error")||r,jQuery(this).addClass("error"))}),e?void jQuery(this).submit():(alert(r),!1)})}),jQuery(window).unload(function(){var e=jQuery('form[action="/cart"]');if(e.size()){var r={type:"POST",url:"/cart/update.js",data:e.serialize(),dataType:"json",async:!1};jQuery.ajax(r)}});
</script>
</body>
</html>