<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-5372335809225866",
    enable_page_level_ads: true
  });
</script>
<title>Броне-сайт Чобитка Василия :: бронетанковая библиотека - танки и другие боевые машины</title>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1251" />
<meta NAME="Author" CONTENT="Василий Чобиток / Vasiliy Chobitok" />
<meta NAME="Description" CONTENT="Бронетанковая Интернет-библиотека. Обо всем что связано с танками, бронетанковой техникой, ее историей, развитием и текущим состоянием дел в бронетанковой отрасли" />
<meta NAME="Keywords" CONTENT="танк броня бронетехника БТВТ БМП БТР вооружение оружие Чобиток tank armor armour APC armament weapon gun Chobitok" />
<meta name="verify-v1" content="JqFXytbDICBmyv6FYlY0ZqnZE7TE8VWT9bVxZGsGfK4=" />
<meta name='yandex-verification' content='73ad2697c7a8030d' />
<link rel="search" type="application/opensearchdescription+xml" href="/search.xml" title="Поиск по Броне-сайту" />
<link rel="alternate" type="application/rss+xml" href="site_rss.php" title="RSS канал обновлений Броне-сайта" />
<link rel="alternate" type="application/rss+xml" href="rss.php" title="RSS канал бронетанковых новостей" />
<link href="styles.css" rel="stylesheet" type="text/css" />
<link href="common.css" rel="stylesheet" type="text/css" />
<link rel="openid2.provider" href="https://www.google.com/accounts/o8/ud?source=profiles" /> 
<link rel="openid2.local_id" href="https://profiles.google.com/107836225500495979443" />
<script type="text/javascript" src="jquery-1.9.1.min.js"></script>
<script type="text/javascript" src="script.js"></script>
<script type="text/javascript" src="common.js"></script>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-1689111-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</head>
<body topmargin=0 leftmargin=0 marginheight=0 marginwidth=0 BGCOLOR=#D6D6C0 TEXT=#000000 LINK=#000000 VLINK=#363807 ALINK="#FF0000">
<!--[if IE]>
<style type="text/css">
.header0 { filter : dropShadow(color=#000000, offX=1, offY=1, positive=1); }
</style>
<![endif]-->
<center>
<table width=779 border=0 cellpadding=0 cellspacing=0>
  <tr> 
      <td colspan=3 nowrap><img src="i01.jpg" width=148 height=41><img src="nLogo4.gif" alt="Броне-сайт. Танки, БМП, БТР, бронетехника" width="193" height="41"><img src="nLogo5.gif" width="28" height="41"><a href="Tanks/WWI/"><img src="menu1.gif" alt="Танки Первой мировой" title="Танки Первой мировой" width="64" height="39" vspace="1" border="0"></a><a href="Tanks/BeforeWWII/"><img src="menu2.gif" alt="Танки межвоенного периода" title="Танки межвоенного периода" width="117" height="39" vspace="1" border="0"></a><a href="Tanks/WWII/"><img src="menu3.gif" alt="Танки Второй мировой" title="Танки Второй мировой" width="115" height="39" vspace="1" border="0"></a><a href="Tanks/Modern/"><img src="menu4.gif" alt="Современные танки" title="Современные танки" width="114" height="39" vspace="1" border="0"></a></td>
  </tr>
  <tr> 
      <td width=135 bgcolor=#000000><img src="i02.jpg" width=120 height=16></td>
	  <td colspan=2 align=center bordercolor="#1973DC" bgcolor=#000000><div class="topmenu"><a href="Tanks/">танки</a> 
          | <a href="Battle/">танк в бою</a> | <a href="/wiki/index.php?title=%D0%97%D0%B0%D0%B3%D0%BB%D0%B0%D0%B2%D0%BD%D0%B0%D1%8F_%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B0">изнутри</a> 
          | <a href="/wiki/index.php?title=%CA%E0%F2%E5%E3%EE%F0%E8%FF:%C1%E8%E1%EB%E8%EE%F2%E5%EA%E0">библиотека</a> | <a href="humor/">юмор</a> 
          | <a href="Tanks/wallpapers/">обои</a> | <a href="links/">ссылки</a> 
          | <a href="autors.php">авторы</a>
<noindex>
          <!--TopList COUNTER-->
          <script language="JavaScript"><!--
d=document;js=10;a='&r='+escape(d.referrer)
//--></script><script language="JavaScript1.1"><!--
js=11;a+='&j='+navigator.javaEnabled()
//--></script><script language="JavaScript1.2"><!--
js=12;s=screen;a+='&s='+s.width+'*'+s.height
a+='&d='+(s.colorDepth?s.colorDepth:s.pixelDepth)
//--></script><script language="JavaScript1.3"><!--
js=13//--></script><script language="JavaScript"><!--
d.write('<img src="http://top.list.ru/counter'+
'?id=18461&js='+js+a+'" alt="" height=1 width=1>')
if(js>11)d.write('<'+'!-- ')//--></script><noscript><img src="http://top.list.ru/counter?js=na&amp;id=18461" height="1" width="1" alt></noscript><script language="JavaScript"><!--
if(js>11)d.write('--'+'>')
//--></script> <!--begin of Top100--> <a href="http://top100.rambler.ru/top100/" rel="nofollow"><img src="http://counter.rambler.ru/top100.cnt?102390" alt="Rambler's Top100" width="1" height="1" border="0"></a><!--end of Top100 code--></noindex></div></td>
  </tr>
  <tr> 
    <td width=135 rowspan=2><img src="i03.jpg" width=135 height=74></td>
    <td colspan=2 width=644><img src="images/empty.gif" width=1 height=1></td>
  </tr>
  <tr> 
      <td width=154 height=66><img src="i04.jpg" width="154" height="73"></td>
    <td width=490 bgcolor=#93945C valign=middle align=right>
   <div style="height: 60px;">
    <center>
	<!-- Mestkom code BEGIN -->
  <script type="text/javascript" src="http://dynamic.exaccess.ru/asp/dynamic_script.asp?id_d=1287400"></script>
  <!-- Mestkom code END -->
    </center>
   </div>
	</td>
  </tr>
</table>
<table width=779 border=0 cellspacing=0 cellpadding=0>
  <tr> 
    <td width=153 valign=top bgcolor=#93945C><table width="100%" border=0 cellspacing=0 cellpadding=0>
		<tr>
          <td bgcolor=#000000><div class=div>		  
		  <p><a href="Tanks/" class=header1 title="БТВТ, БКМ, САУ и пр.">Танки - справочник</a></p>
            <p><a href="Battle/" class=header1 title="Войны и конфликты с участием бронетехники">Танк в бою</a></p>
			<p><a href="Tank/" class=header1 title="Статьи, аналитика, факты">Танк изнутри</a></p>
            <p><a href="/wiki/index.php?title=%D0%97%D0%B0%D0%B3%D0%BB%D0%B0%D0%B2%D0%BD%D0%B0%D1%8F_%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B0" class=header1 title="wiki раздел">Энциклопедия</a></p>
            <p><a href="Tanks/BTVT/" class=header1 title="История развития БТВТ в СССР и за рубежом. Краткое учебное пособие">История БТВТ</a></p>
            <p><a href="/wiki/index.php?title=%CA%E0%F2%E5%E3%EE%F0%E8%FF:%C1%E8%E1%EB%E8%EE%F2%E5%EA%E0" class=header1>Библиотека</a></p>
            <p><a href="humor/" class=header1>Юмор</a></p>
            <p><a href="Tanks/wallpapers/" class=header1 title="Бронетанковые обои для рабочего стола">Обои</a></p>
            <p><a href="links/" class=header1>Каталог ссылок</a></p>   	
            <p><a href="Tanks/indeximg.php" class=header1>Графический указатель</a></p>			
            <p><a href="articles.php" class=header1>Перечень статей</a></p>			
            <p><a href="map.php" class=header1>Карта сайта</a></p>			
			</div></td>
        </tr>
        <tr> 
          <td bgcolor=#636502><div class=header0>поиск</div></td>
        </tr>
        <tr> 
          <td bgcolor=#000000><img src="images/empty.gif" width=1 height=1></td>
        </tr>
		<tr><td><div class=div align=center><br><form NAME="web" METHOD="get" ACTION="http://www.yandex.ru/yandsearch" target=_blank>
<input type="text" name="text" size=8 value="Поиск по сайту" maxlength=160 title="Введи ключевые слова и жми Enter" class=input onFocus="if (this.value=='Поиск по сайту') this.value='';">
<input type="hidden" name="site" value="armor.kiev.ua"> 
</form></div></td>

		</tr>
        <tr> 
          <td bgcolor=#636502><div class=header0>сайты портала</div></td>
        </tr>
        <tr> 
          <td bgcolor=#000000><img src="images/empty.gif" width=1 height=1></td>
        </tr>
        <tr> 
          <td><div class=div>
            <p><noindex><a href="http://army.armor.kiev.ua/" class=header2 title="Анатомия Армии. Сайт Ю.Веремеева">Анатомия армии</a></noindex></p>            
            <p><noindex><a href="http://fofanov.armor.kiev.ua" class=header2 title="Современные российские танки (англ.)">Фофанов на Б-С</a></noindex></p>
            <p><a href="ring/" class=header2 title="РОМБ. Русские бронетанковые ресурсы">РОМБ</a></p>
            <p><noindex><a href="http://award.armor.kiev.ua" class=header2>Награды России</a></noindex></p>
          </div></td>
        </tr>
        <tr> 
          <td bgcolor="#636502"><div class=header0>обратная связь</div></td>
        </tr>
        <tr> 
          <td bgcolor=#000000><img src="images/empty.gif" width=1 height=1></td>
        </tr>
        <tr> 
          <td><div class=div><p><noindex><a href="http://www.guestbook.ru/book.cgi?user=vchobitok&action=show" class=header2 rel="nofollow">Гостевая 
              книга</a></noindex></p>
            <p><a href="awards.php" class=header2>Награды сайта</a></p>
            <p class=header2><a href="autors.php" class=header2>Авторы</a></p></div></td>
        </tr>
      <tr> 
          <td bgcolor=#636502><div class=header0>&nbsp;</div></td>
        </tr>
        <tr> 
          <td bgcolor=#000000><img src="images/empty.gif" width=1 height=1></td>
        </tr>
        <tr>
          <td><div class=div align=center><noindex><br>
		<!--begin of Top100 logo--><a href="http://top100.rambler.ru/top100/" rel="nofollow"><img src="http://images.rambler.ru/top100/banner-88x31-rambler-gray2.gif" alt="Rambler's Top100" width="88" height="31" border="0"></a><!--end of Top100 logo --><br>
		  <img src="images/empty.gif" width=1 height=5><br>
		  <!--TopList LOGO--><a target="_top" href="http://top.list.ru/jump?from=18461" rel="nofollow"><img src="http://top.list.ru/counter?id=18461&amp;t=51&amp;l=1" border="0" height="31" width="88" alt="TopList" hspace=2></a><!--TopList LOGO--><br>
		  <img src="images/empty.gif" width=1 height=5><br>
<!-- bigmir)net TOP 100 --><a href="http://www.bigmir.net/" rel="nofollow" target=_blank onClick='img = new Image();img.src="http://www.bigmir.net/?cl=13776";' ><script language="javascript"><!--
bmQ='<img src=http://c.bigmir.net/?s13776&t8'
bmD=document
bmD.cookie="b=b"
if(bmD.cookie)bmQ+='&c1'
//--></script><script language="javascript1.2"><!-- 
bmS=screen;bmQ+='&d'+(bmS.colorDepth?bmS.colorDepth:bmS.pixelDepth)+"&r"+bmS.width;
//--></script><script language="javascript"><!--
bmF = bmD.referrer.slice(7);
((bmI=bmF.indexOf('/'))!=-1)?(bmF=bmF.substring(0,bmI)):(bmI=bmF.length);
if(bmF!=window.location.href.substring(7,7+bmI))bmQ+='&f'+escape(bmD.referrer);
bmD.write(bmQ+" border=0 width=88 height=31 alt='bigmir TOP100'>");
//--></script></a><br><img src="images/empty.gif" width=1 height=5></noindex><br>
<br><img src="images/leechologo.gif" alt="Разработка вебстудии &quot;ЛеЧо&quot;" title="Разработка вебстудии &quot;ЛеЧо&quot;" width=88 height=31 border=0></div></td>
        </tr>
        <tr> 
          <td bgcolor="#636502"><div class=header0>реклама</div></td>
        </tr>
        <tr> 
          <td bgcolor=#000000><img src="images/empty.gif" width=1 height=1></td>
        </tr>
		<tr><td><div class=div>
<p class="rm">
<script type="text/javascript">
<!--
var _acic={dataProvider:10};(function(){var e=document.createElement("script");e.type="text/javascript";e.async=true;e.src="//www.acint.net/aci.js";var t=document.getElementsByTagName("script")[0];t.parentNode.insertBefore(e,t)})()
//-->
</script> <a href="http://1f-light.ru/7-svetilniki-sadovo-parkovye" target="_blank">Садовые светильники</a>  Публикуют <a href="http://Военное.РФ/" target="_blank">военные новости</a> со всей России</p>
		</div></td></tr>
		
      </table></td>
    <td width=3><img src="images/empty.gif" width=3 height=1></td>
    <td width=467 valign=top bgcolor=#BCBC9A><table width="100%" border=0 cellpadding=0 cellspacing=0>
          <tr> 
            <td bgcolor=#D6D6C0><img src="images/empty.gif" width=1 height=3></td>
          </tr>
          <tr> 
            <td bgcolor=#000000 align=right><div class=header0>новости портала, 
                обновления &nbsp;</div></td>
          </tr>
          <tr> 
            <td><div class=div1>
            <p class=news><b><time datetime="2018-03-10">10.03.2018</time> <u>Броне-сайт</u><br> Немецкие пехотные противотанковые средства борьбы</b><br>
Одна из первых публикаций в советской печати о немецких фаустпатронах. Статья из Вестника танковой промышленности № 5—6 за 1944 год.</p>
<p style="text-align:right"><a href="/Tanks/WWII/faustpatrone/" class=news>Перейти &raquo;</a></p><p class=news><img src="http://armor.kiev.ua/Tanks/WWI/rusRover/romadin.jpg" width="100" hspace="4" border="1" align="left"><b><time datetime="2018-03-05">05.03.2018</time> <u>Броне-сайт</u><br> Сергей Ромадин</b><br>
Вслед за ушедшим в прошлом году постоянным сотрудником Броне-сайта Сергеем Зыковым ушел из жизни его друг, известный автор посвященных бронетанковой технике исторических работ, большой любитель бронепоздов <b>Сергей Ромадин</b>.<br />
<br />
Завтра прощание с этим замечательным человеком. Светлая память!</p>
<p class=news><img src="/news/d30_.jpg" width="100" hspace="4" border="1" align="left"><b><time datetime="2018-02-26">26.02.2018</time> <u>Броне-сайт</u><br> Гаубица Д-30</b><br>
Вышла в свет новая книга нашего автора Анатолия Сорокина, посвященная советской гаубице Д-30. Спешите приобрести в магазинах вашего города и интернете своей страны!</p>
<p style="text-align:right"><a href="https://www.ozon.ru/context/detail/id/144284365/?partner=armor_kiev" class=news>Перейти &raquo;</a><br clear="both" /></p><p class=news><img src="/news/23feb1.jpg" width="100" hspace="4" border="1" align="left"><b><time datetime="2018-02-23">23.02.2018</time> <u>Броне-сайт</u><br> С Праздником!</b><br>
С Днем Советской Армии и ВМФ! Со 100-летием.</p>
<p class=news><img src="/news/i223.jpg" width="100" hspace="4" border="1" align="left"><b><time datetime="2017-11-19">19.11.2017</time> <u>БТ-энциклопедия</u><br> Белый слон отечественной артиллерии</b><br>
Ко Дню Ракетных Войск и Артиллерии новая статья от Анатолия Сорокина</p>
<p style="text-align:right"><a href="http://armor.kiev.ua/wiki/index.php?title=%D0%91%D0%B5%D0%BB%D1%8B%D0%B9_%D1%81%D0%BB%D0%BE%D0%BD_%D0%BE%D1%82%D0%B5%D1%87%D0%B5%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D0%BE%D0%B9_%D0%B0%D1%80%D1%82%D0%B8%D0%BB%D0%BB%D0%B5%D1%80%D0%B8%D0%B8" class=news>Перейти &raquo;</a><br clear="both" /></p>			<p style="clear: both;">[<a href="newsarchive.php?type=site" class="news">Архив новостей</a>]</p></div></td>
          </tr>
          <tr> 
            <td bgcolor=#D6D6C0><img src="images/empty.gif" width="1" height="3"></td>
          </tr>
          <tr> 
            <td bgcolor="#000000" align="right"><div class="header0">бронетанковые новости, события &nbsp;</div></td>
          </tr>
          <tr> 
            <td><div class="div1">
			<p class=news><img class="resizebleImg"src="http://vestnik-rm.ru/userfiles/images/0001/aaaaa/shilka.jpg" width="100" hspace="4" border="1" align="left"><b><time datetime="2018-03-15">15.03.2018</time>  В Сирии самоходки "Шилка" научили бить ракетами от "Катюш"?</b><br>
Зенитная самоходная установка ЗСУ-23-4 принимала участие в большом количестве военных конфликтов. На Ближнем Востоке из нее сбивали "Фантомы" и "Скайхоки". Активно применяли их во время Ирано-иракской войны, в Эфиопии и Анголе...</p>
<p style="text-align:right"><noindex><a href="http://vestnik-rm.ru/news-4-23364.htm" class=news rel="nofollow">Перейти &raquo;</a></noindex><br clear="both" /></p><p class=news><img class="resizebleImg"src="http://vestnik-rm.ru/userfiles/images/0001/aaaaa/tos_1a.jpg" width="100" hspace="4" border="1" align="left"><b><time datetime="2018-03-15">15.03.2018</time>  ТОС-1А "Солнцепек" усилили мощь 2-й армии ЦВО   </b><br>
Подразделение войск радиационной, химической и биологической (РХБ) защиты, дислоцированное в Алтайском крае, получило ротный комплект из трех пусковых установок "Солнцепек"...</p>
<p style="text-align:right"><noindex><a href="http://vestnik-rm.ru/news-4-23352.htm" class=news rel="nofollow">Перейти &raquo;</a></noindex><br clear="both" /></p><p class=news><img class="resizebleImg"src="http://vestnik-rm.ru/userfiles/images/0001/aaaaa/bgbgoqocwb4.jpg" width="100" hspace="4" border="1" align="left"><b><time datetime="2018-03-15">15.03.2018</time>  В Сирии пригодились бы "Колесницы огненной смерти"- БМО-Т</b><br>
Российская армия опробовала в Сирии большое количество образцов военной техники. Обкатку войной прошли, в том числе, некоторые образцы для сухопутных войск, такие как танки Т-90А, БМПТ "Терминатор", бронеавтомобили различных моделей...<br />
<br />
 </p>
<p style="text-align:right"><noindex><a href="http://vestnik-rm.ru/news-4-23349.htm" class=news rel="nofollow">Перейти &raquo;</a></noindex><br clear="both" /></p><p class=news><img class="resizebleImg"src="http://vestnik-rm.ru/userfiles/images/0001/aaaaa/t_72.jpg" width="100" hspace="4" border="1" align="left"><b><time datetime="2018-03-13">13.03.2018</time>  Сирийские танки в опасности: дефицит "реактивной брони"</b><br>
Развернувшиеся в САР активные боевые действия продемонстрировали, что сирийские военные испытывают дефицит в динамической защите или, как ее еще называют, "реактивной броне". Ее попросту не хватает на всех...</p>
<p style="text-align:right"><noindex><a href="http://vestnik-rm.ru/news-4-23336.htm" class=news rel="nofollow">Перейти &raquo;</a></noindex><br clear="both" /></p><p class=news><img class="resizebleImg"src="http://vestnik-rm.ru/userfiles/images/0001/aaaaa/boevaya_bochka_po_prezhnemu_na_puti_voyny_v_vostochnoy_gute.jpg" width="100" hspace="4" border="1" align="left"><b><time datetime="2018-03-12">12.03.2018</time>  http://vestnik-rm.ru/news-4-23317.htm</b><br>
Для ликвидации террористов в Восточной Гуте правительственные войска стянули разнообразную технику. Всевозможные реактивные системы залпового огня, гаубицы и самоходки. Различные танки, в том числе Т-90А.</p>
<p style="text-align:right"><noindex><a href="http://vestnik-rm.ru/news-4-23317.htm" class=news rel="nofollow">Перейти &raquo;</a></noindex><br clear="both" /></p> 			
			<p style="clear: both;">[<a href="newsarchive.php?type=lenta" class="news">Архив новостей</a>]</p></div></td>
          </tr>
        </table>
      </td>
    <td width=3><img src="images/empty.gif" width=3 height=1></td>
    <td width=153 valign=top bgcolor=#93945C><table width="100%" border=0 cellspacing=0 cellpadding=0>
         <tr> 
            <td bgcolor=#636502><div class=header0>&nbsp;</div></td>
          </tr>
          <tr> 
            <td bgcolor=#000000><img src="images/empty.gif" width=1 height=1></td>
          </tr>

          <tr> 
            <td><div align=center> 
<p>
<a href="/t64/"><img src="/t64/logo145.jpg" alt="Основной боевой танк Т-64. 50 лет в строю" width="145" height="174" vspace="3" border="0"></a><br>
[<a href="http://www.labirint.ru/books/526270/?p=17340" target="_blank">Купить</a>]
</p>                			

              </div></td>
          </tr>          
          <tr> 
            <td bgcolor=#636502><div class=header0>новости почтой</div></td>
          </tr>
          <tr> 
            <td bgcolor=#000000><img src="images/empty.gif" width=1 height=1></td>
          </tr>
          <tr> 
			<td>
<div align=center class=div><br>
<form  name=mailform method=post action="/php/mail.php" target=submit onSubmit = "submitMail(document.mailform);">
<input name=email type=text id=email class=input onfocus="if (this.value=='Ваш E-mail') this.value='';" value="Ваш E-mail" size=8 title="Введи E-mail и жми Enter"></form></div></td>
          </tr>
          <tr> 
            <td bgcolor=#636502><div class=header0>лучшие сайты</div></td>
          </tr>
          <tr> 
            <td bgcolor=#000000><img src="images/empty.gif" width=1 height=1></td>
          </tr>
          <tr> 
            <td><div align=center class=div><br><noindex><a href=/links/go.php?id=10 target=_blank rel="nofollow"><img src='http://www.airforce.ru/images/airforce_bt.jpg' alt='ВВС России: люди и самолеты' border=0 vspace=2 width=88 height=31></a></noindex><br>
<noindex><a href=/links/go.php?id=11 target=_blank rel="nofollow"><img src='http://rkka.ru/rkka.gif' alt='Рабоче-Крестьянская Красная Армия' border=0 vspace=2 width=88 height=31></a></noindex><br>
<noindex><a href=/links/go.php?id=12 target=_blank rel="nofollow"><img src='http://www.alexfiles99.narod.ru/oforml/panzer-marsch-3.gif' alt='Двигатели и трансмиссии БТВТ' border=0 vspace=2 width=88 height=31></a></noindex><br>
<noindex><a href=/links/go.php?id=18 target=_blank rel="nofollow"><img src='http://world.guns.ru/banners/88x31a1.gif' alt='Современное стрелковое оружие' border=0 vspace=2 width=88 height=31></a></noindex><br>
			<a href="javascript:BestOpen('bestsites.php')" class=header2 rel="nofollow">показать все</a></div></td>
          </tr>
          <tr> 
            <td bgcolor=#636502><div class=header0>&nbsp;РОМБ: БТ-сайты</div></td>
          </tr>
          <tr> 
            <td bgcolor=#000000><img src="images/empty.gif" width=1 height=1></td>
          </tr>		  
          <tr>
            <td><div align=center class=div><br>
                <a href="ring/"><img src="ring/member1.gif" alt="РОМБ - Русские бронетанковые ресурсы" width="88" height="66" border="0"></a> 
                <a href="ring/?do=prev&id=1" class="header2" rel="nofollow"><br>
                предыдущий</a><br>
                <a href="ring/?do=next&id=1" class="header2" rel="nofollow">следующий</a><br>
                <a href="ring/?do=random&id=1" class="header2" rel="nofollow">случайный</a><br>
                <a href="ring/?do=list&id=1" class="header2" rel="nofollow">все 
                сайты</a><br>
                 </div></td>
          </tr>
		<tr> 
          <td bgcolor="#636502"><div class=header0>реклама</div></td>
        </tr>
        <tr> 
          <td bgcolor=#000000><img src="images/empty.gif" width=1 height=1></td>
        </tr>
		<tr><td><div class=div>
<p class=rm>
 </p>
		</div></td></tr>		  
        </table></td>
  </tr>
  <tr> 
    <td colspan=5><img src="images/empty.gif" width=1 height=3></td>
  </tr>
  <tr>
    <td colspan=5 bgcolor=#000000><div class=topmenu align=right>Сайт открыт 22.07.99 
          &copy; 1999-2009 <a href="mailto:vchobitok@mail.ru" class="topmenu" rel="nofollow">V.Chobitok</a>, design 
          by <a href="mailto:work_leetwin@yahoo.com" class="topmenu" rel="nofollow">Alex Lee</a> 
          &nbsp;<img src="images/empty.gif" width=1 height=14 align="middle"></div></td>
  </tr>
</table>
<p>&nbsp;</p>
</center>
<div id="barlogo" style="position: absolute; left: 100%; margin-left: -214px; top: 0px; width: 200px; display: none;">
<img src="design/armorbarcode.png" alt="ссылка-баркод" title="Броне-сайт: ссылка-баркод" height="198" width="200">
</div>
<div style="position: absolute; left: 100%; margin-left: -14px; top: 0px; width: 14px;">
<img alt="QR code" src="design/barlogo.png" onmouseout="getElement('barlogo').style.display='none'" onmouseover="getElement('barlogo').style.display='block'" height="14" width="14">
</div>
</body>
</html>