<!DOCTYPE html>
<html>
<head>
<link rel='icon' href='data:;base64,iVBORw0KGgo='>
<meta name='viewport' content='width=device-width, initial-scale=1'>
<title>byuu.org</title>
<style>
* {
  box-sizing: border-box;
  -moz-box-sizing: border-box;
  -webkit-box-sizing: border-box;
  margin: 0em;
  outline: none;
  padding: 0em;
}

*.right {
  text-align: right;
}

html {
  overflow-y: scroll;
}

body {
  background: #ffe;
  color: #000;
  font-family: "Verdana", sans;
  font-size: 9pt;
}

a {
  color: #229;
  font-weight: bold;
  text-decoration: none;
}

a:hover {
  color: #77f;
}

input[type="text"], input[type="password"] {
  padding: 0.2em;
}

ul {
  list-style: none;
}

ul > ul {
  margin-left: 1.5em;
}

li:before {
  content: "• ";
}

code, pre {
  font-family: "Consolas", "Menlo", "Lucida Console", "DejaVu Sans Mono", monospace;
  font-size: 9pt;
}

body > nav {
  line-height: 1em;
}

body > nav ul {
  border: 1px solid #000;
  list-style: none;
  z-index: 2;
}

body > nav li {
  background: #555;
  cursor: default;
}

body > nav li:before {
  content: none;
}

body > nav li:hover {
  background: #888;
}

body > nav a {
  color: #fff;
  display: block;
  padding: 0.75em 1.25em;
}

body > nav a:hover {
  color: #fff;
}

body > nav > ul {
  background: #555;
  border: 0px;
  border-bottom: 1px solid #000;
  display: block;
  position: relative;
}

body > nav > ul > li {
  display: inline-block;
  transition: all 0.25s;
}

body > nav > ul ul {
  box-shadow: 0.2em 0.2em 0.2em #888;
}

body > nav > ul > li > ul {
  opacity: 0;
  position: absolute;
  transition: opacity 0.25s;
  visibility: hidden;
  width: 18em;
}

body > nav > ul > li:hover > ul {
  display: block;
  opacity: 1;
  visibility: visible;
}

body > nav > ul > li > ul > li {
  display: block;
  position: relative;
}

body > nav > ul > li > ul > li > ul {
  display: inline-block;
  left: 100%;
  opacity: 0;
  position: absolute;
  top: -1px;
  transition: opacity 0.25s;
  visibility: hidden;
  width: 18em;
}

body > nav > ul > li > ul > li:hover > ul {
  display: block;
  opacity: 1;
  visibility: visible;
}

body > nav > ul > li > ul > li > ul > li {
  display: block;
  position: relative;
}

body {
  padding: 0.5em;
}

body > nav {
  margin: -0.5em;
  margin-bottom: 0.5em;
}

body > header, body > h1 {
  font-size: 20pt;
  font-weight: bold;
  margin-bottom: 0.2em;
}

body > footer {
  font-size: 0.8em;
  opacity: 0.5;
}

section {
  background: #fff;
  border: 1px solid #bbb;
  margin-bottom: 1em;
}

section > form {
  padding: 0.5em;
}

section > header {
  background: #fdd;
  border-bottom: 1px solid #bbb;
  font-weight: bold;
  padding: 0.5em;
}

section > header > span {
  float: right;
  font-family: "Georgia", sans;
}

section > h1 {
  background: #fee;
  border-bottom: 1px solid #bbb;
  border-top: 1px solid #bbb;
  font-size: 1em;
  padding: 0.2em 0.5em;
}

section > h2 {
  background: #fee;
  border: 1px solid #bbb;
  font-size: 1em;
  margin: 0.5em;
  padding: 0.2em 0.5em;
}

section > h3 {
  font-size: 1em;
  padding: 0em 0.5em;
  text-decoration: underline;
}

section > nav {
  padding: 0.5em;
}

section > p {
  max-width: 80em;
}

section > p, section > ul {
  padding: 0.5em;
}

section > pre {
  background: #eef;
  border: 1px solid #bbb;
  margin: 0.5em;
  padding: 0.5em;
}

section > table {
  border-collapse: collapse;
  margin: 0.5em;
}

section > table th {
  background: #eef;
  border-bottom: 1px solid #bbb;
  text-align: left;
}

section > table th, table td {
  padding: 0.25em;
  vertical-align: baseline;
  white-space: nowrap;
}

section > table.grid th, table.grid td {
  padding: 0.5em;
}

section > table.grid tr:nth-child(even) {
  background: #eee;
}

section > table.grid tr:nth-child(odd) {
  background: #fff;
}

section > table.grid {
  border: 1px solid #bbb;
}

section > table.info td:first-child {
  font-weight: bold;
}
</style>
</head>
<body>
<nav>
<ul>
  <li style='float: right;'>
    <a href='//board.byuu.org/'>Board</a>
  </li><li>
    <a href='/'>Home</a>
  </li><li>
    <a href='#'>Emulation</a>
    <ul>
      <li><a href='/emulation/higan/'>higan</a></li>
      <li><a href='/emulation/preservation/'>Preservation</a></li>
    </ul>
  </li><li>
    <a href='#'>Tools</a>
    <ul>
      <li><a href='/tool/bass/'>bass</a></li>
      <li><a href='/tool/beat/'>beat</a></li>
      <li><a href='/tool/trance/'>trance</a></li>
    </ul>
  </li><li>
    <a href='#'>Libraries</a>
    <ul>
      <li><a href='/library/libco/'>libco</a></li>
      <li><a href='#' style='color: #aaa;'>nall</a></li>
      <li><a href='#' style='color: #aaa;'>ruby</a></li>
      <li><a href='#' style='color: #aaa;'>hiro</a></li>
    </ul>
  </li><li>
    <a href='#'>Other</a>
    <ul>
      <li><a href='/articles/'>Articles</a></li>
      <li><a href='/other/social-media/'>Social Media Accounts</a></li>
      <li><a href='/other/about/'>About</a></li>
    </ul>
  </li>
</ul>
</nav>
<section><header id="3821817034">New article: What Is Emulation?<span>2018-02-06</span></header>
<p>I want to have an honest discussion on the technical merits of FPGA devices, and
I believe I missed the mark on that yesterday. So if you'll indulge me, I'd like
to take another shot at that. This time, free of money, motives, etc.</p>
<p><a href="/articles/what-is-emulation/">Article - What Is Emulation?</a></p>
</section><section><header id="4197853728">New article: FPGAs Aren't Magic<span>2018-02-05</span></header>
<p>Regrettably, I've seen a continued reluctance by the press to challenge the
marketing spin by the Analogue CEO regarding their new Super Nt product. So,
since journalists won't do their jobs, I'll do it for them.</p>
<p><a href="/articles/fpgas-arent-magic/">Article - FPGAs Aren't Magic</a></p>
</section><section><header id="1768428399">New article: Experiment!<span>2018-01-20</span></header>
<p>Figured I'd start off 2018 with something truly out of character: an article
with a positive tone to it! First time for everything, right?</p>
<p><a href="/articles/experiment/">You can read the article here, if you like.</a></p>
</section><section><header id="4039491934">higan v106 released<span>2017-11-19</span></header>
<p>This release adds auto-saving RAM support and a new tool to save per-game text
notes. It also adds 64 new SNES PAL game verifications to the icarus database,
courtesy of DoNotWant and Smarthuman.</p>
<p><a href="//byuu.org/emulation/higan/">( Download )</a>
<a href="//board.byuu.org/viewtopic.php?f=4&amp;t=1868">( Discuss )</a></p>
</section><section><header id="3707713396">higan v105tr1 released<span>2017-10-25</span></header>
<p>This release supersedes higan v105, and is released to fix a critical issue that
was affecting the newly completed English translation of Tengai Makyou Zero. It
also has fixes for two other games.</p>
<p>Many special thanks to Cydrak for putting this release together during my
vacation! =^-^=</p>
<p>Changelog:</p>
<ul>
<li>Super Famicom: fixed real-time clock functionality in Tengai Makyou Zero [Cydrak]</li>
<li>Super Famicom: fixed real-time clock functionality in Dai Kaijuu Monogatari II [Cydrak]</li>
<li>Super Famicom: fixed SMP regression that broke Majuu Ou in previous releases [Jonas Quinn]</li>
</ul>
<p><a href="//byuu.org/emulation/higan/">( Download )</a>
<a href="//board.byuu.org/viewtopic.php?f=4&amp;t=1849">( Discuss )</a></p>
</section><section><header id="1167409679">bass v15 released<span>2017-10-08</span></header>
<p>After two years, a new version of bass has been released, which contains many
substantial changes: expressions, multi-argument defines, inline macros, and
much more.</p>
<p>Unfortunately, code written for bass v14 is unlikely to be compatible with v15,
and code changes will be necessary.</p>
<p>However, the goal going forward is for bass to stabilize. I wanted to offer a
guarantee that all code compiled with v15 will be forward-compatible, but given
the large number of changes, this seems a bad idea. Instead, I'd like to run
with v15 for a decent length of time, and if no serious issues arise, then we
can consider this for the next release.</p>
<p>Do note that unlike previous releases, backward-incompatible changes won't occur
to v15 unless they are of significant, quantifiable benefit.</p>
<p><a href="//byuu.org/tool/bass/">( Download )</a>
<a href="//board.byuu.org/viewtopic.php?f=20&amp;t=1830">( Discuss )</a></p>
</section><section><header id="3971690557">higan v105 released<span>2017-10-07</span></header>
<p>This release provides several major improvements to Mega Drive emulation which
enhances compatibility a good deal. It also includes important Super Famicom
mosaic emulation improvements, plus a much-needed SuperFX save state issue fix.</p>
<p>This will be the last release for a while: I have an upcoming vacation, and
following that, I'll be shifting my focus back to the SNES preservation project
until my backlog of 125 PAL games is cleared.</p>
<p>Changelog:</p>
<ul>
<li>higan: many improvements to Emulator::Interface to support forks/frontends</li>
<li>higan: refreshed program icon</li>
<li>icarus: new program icon</li>
<li>Game Boy Advance: slight emulation speedup over v104</li>
<li>Game Boy Advance: synchronize APU FIFO updates better</li>
<li>Mega Drive: added automatic region detection [hex_usr]</li>
<li>Mega Drive: support 8-bit SRAM</li>
<li>Game Boy Advance: fixed bug when changing to THUMB mode via MSR [MerryMage]</li>
<li>Master System: fix bug in backdrop color and background 0 priority [hex_usr]</li>
<li>Mega Drive: backgrounds always update output priority bit [Cydrak]</li>
<li>Mega Drive: emulated interlaced video output</li>
<li>Mega Drive: emulated shadow/highlight mode [Cydrak]</li>
<li>Super Famicom: auto joypad polling clears the shift register when starting</li>
<li>Super Famicom: added new low-entropy RAM initialization mode to more closely match hardware</li>
<li>Game Boy Advance: rumble will now time out after being left on for 500ms</li>
<li>ruby: improved rumble support in udev input driver [ma_rysia]</li>
<li>M68K: move.b (a7)[+/-] adjust a7 by two</li>
<li>M68K: illegal/lineA/lineF opcodes do not modify the stack register</li>
<li>Mega Drive: emulate VIP status bit</li>
<li>uPD7725: improved emulation of OV1/S1 flags [byuu, AWJ, Lord Nightmare]</li>
<li>uPD7725: improved handling of DP, RP updates [Jonas Quinn]</li>
<li>Super Famicom: improved emulation of mosaic effects in hires, interlace, and offset-per-tile modes [byuu, Cydrak]</li>
<li>ruby: improved Direct3D exclusive mode monitor selection [Cydrak]</li>
<li>Super Famicom: fixed save state bug affecting SuperFX games [Cydrak]</li>
<li>Mega Drive: added workaround for Clang compiler bug; allowing this core to work on macOS [Cydrak, Sintendo]</li>
<li>higan: hotkeys now also trigger when the main window lacks focus yet higan is set to allow input on focus loss</li>
<li>higan: fixed an edge case where int16_t &lt;&gt; double audio conversion could possibly result in overflows</li>
<li>higan: fixed a crash on macOS when choosing quit from the application menu [ncbncb]</li>
</ul>
<p><a href="//byuu.org/emulation/higan/">( Download )</a>
<a href="//board.byuu.org/viewtopic.php?f=4&amp;t=1827">( Discuss )</a></p>
</section><section><header id="3903889180">higan v104 released<span>2017-08-12</span></header>
<p>There are lots of improvements in this new release, both to core emulation and
to the user interface. However, some of these changes are quite substantial, so
regressions are a possibility. Please report any regressions from v103 on the
forums if found.</p>
<p>Note that Mega Drive save RAM files will not be compatible with v103, but will
now be compatible with save RAM files from all other Mega Drive emulators, and
the format will be stable going forward.</p>
<p>Also!! Thanks to the tireless work of Screwtape, the Help-&gt;Documentation link in
higan now takes you to a very comprehensive user guide. Please be sure to
consult this if you have any questions about using higan.</p>
<p>Lastly, I've added a link to my Patreon page
(<a href="https://patreon.com/byuu/">https://patreon.com/byuu/</a>) to the higan
downloads page. The money will go exclusively toward purchasing SNES games for
preservation, hardware and flash carts for reverse engineering, equipment such
as backup drives, etc. Donating is entirely optional and comes with no rewards,
but would of course be greatly appreciated! ^^;</p>
<p>Changelog:</p>
<ul>
<li>nall/dsp: improved first-order IIR filtering</li>
<li>Famicom: improved audio filtering (90hz lowpass + 440hz lowpass + 14khz highpass)</li>
<li>Game Boy Advance: corrected bug in PSG wave channel emulation [Cydrak]</li>
<li>Mega Drive: added first-order 2.84KHz low-pass filter to match VA6 model hardware</li>
<li>Mega Drive: lowered PSG volume relative to YM2612 to match VA6 model hardware</li>
<li>Mega Drive: Hblank flag is not always set during Vblank</li>
<li>Mega Drive: fix PAL mode reporting from control port reads</li>
<li>Famicom: improved phase duty cycle emulation (mode 3 is 25% phase inverted; counter decrements)</li>
<li>Mega Drive: reset does not cancel 68K bus requests</li>
<li>Mega Drive: 68K is not granted bus access on Z80 reset</li>
<li>Mega Drive: CTRL port is now read-write, maintains value across controller changes</li>
<li>Z80: IX, IY override mode can now be serialized in save states</li>
<li>68K: fixed calculations for ABCD, NBCD, SBCD [hex_usr, SuperMikeMan]</li>
<li>SPC700: improved all cycle timings to match results observed by Overload with a logic anaylzer</li>
<li>Super Famicom: SMP uses a separate 4x8-bit buffer for $f4-f7; not APU RAM [hex_usr]</li>
<li>Super Famicom: SMP TEST register is now finally 100% fully emulated [byuu, AWJ]</li>
<li>Game Boy Advance: DMA can run between CPU instruction cycles</li>
<li>Game Boy Advance: added 2-cycle delay between DMA activation and transfers</li>
<li>higan: improved aspect ratio correction accuracy at higher video scaling sizes</li>
<li>higan: overscan masking will now actually crop the underlying video instead of just blanking it</li>
<li>Mega Drive: center video when overscan is disabled</li>
<li>higan: added increment/decrement quick save slot hotkeys</li>
<li>Game Boy Advance: fixed wave RAM nibble ordering (fixes audio in Castlevania, Pocket NES)</li>
<li>higan: added new adaptive windowed mode: resizes the window to the current emulated system's size</li>
<li>higan: added new integral scaling mode: resizes the window to fill as much of the screen as possible</li>
<li>higan: main window is now resizable and will automatically scale contents based on user settings</li>
<li>higan: fixed one-time blinking of the main window on startup caused by focus stealing bug</li>
<li>ruby: fixed major memory leak in Direct3D driver</li>
<li>ruby: added fullscreen exclusive mode to Direct3D driver</li>
<li>Super Famicom: corrected latching behavior of BGnHOFS PPU registers</li>
<li>higan: all windows sans the main viewport can be dismissed with the escape key now</li>
<li>ruby: complete API rewrite; many audio drivers now support device selection</li>
<li>higan: output frequency can now be modified</li>
<li>higan: configuration settings split to individual menu options for faster access to individual pages</li>
<li>ruby: improved WASAPI driver to event-driven model; more compatible in exclusive mode now</li>
<li>libco: fix compilation of sjlj and fiber targets [Screwtape]</li>
<li>ruby: added YV12 and I420 support to X-Video driver</li>
<li>Game Boy: added TAMA emulation (RTC emulation is not working yet) [thanks to endrift for notes]</li>
<li>Game Boy: correct data ordering of MMM01 ROMs (MMM01 ROMs will need to be re-imported into higan)</li>
<li>Game Boy: store MBC2 save RAM as 256-bytes instead of 512-bytes (RAM is 4-bit; not 8-bit with padding)</li>
<li>Game Boy: fixed a bug with RAM serialization in games without a battery</li>
<li>Mega Drive: fix CRAM reads (fixes Sonic Spinball) [hex_usr]</li>
<li>Game Boy: added rumble support to MBC5 games such as Pokemon Pinball</li>
<li>Game Boy: added MBC7 emulation (accelerometer X-axis, EEPROM not working yet) [thanks to endrift for notes]</li>
<li>hiro: macOS compilation fixes and UI improvements [MerryMage, ncbncb]</li>
<li>Game Boy: added MBC6 emulation (no phone link or flash support; timing bugs in game still)</li>
<li>Game Boy: HDMA syncs to other components after each byte transfer now</li>
<li>Game Boy: disabling the LCD completely halts the PPU (fixes onscreen graphical corruption in some games)</li>
<li>Mega Drive: added 6-button Fighting Pad emulation [hex_usr]</li>
<li>68K: TAS sets d7 when EA mode is a direct register (fixes Asterix graphical corruption)</li>
<li>Game Boy: STAT mode is forced to zero when LCD is disabled (fixes Pokemon Pinball)</li>
<li>LR35902: complete rewrite</li>
<li>icarus: high-DPI is not supported on Windows yet; remove setting for consistency with higan window sizes</li>
<li>hiro: added full support for high-DPI displays on macOS [ncbncb]</li>
<li>ARM7TDMI: complete rewrite</li>
<li>Super Famicom: disabled channels during HDMA initialization appear to set DoTransfer flag</li>
<li>V30MZ: code cleanup</li>
<li>Mega Drive: added optional TMSS emulation; disabled by default [hex_usr]</li>
<li>ARM7TDMI: pipeline decode stage caches CPSR.T [MerryMage]</li>
<li>ARM7TDMI: fixed timing of THUMB stack multiple instruction [Cydrak]</li>
<li>higan: detect when ruby drivers crash; disable drivers on next startup to prevent crash loop</li>
<li>Mega Drive: added automatic region detection (favors NTSC-J &gt; NTSC-U &gt; PAL) [hex_usr]</li>
<li>Mega Drive: support 8-bit SRAM</li>
<li>ARM7TDMI: PC should be incremented by 2 when setting CPSR.T via MSR instruction [MerryMage]</li>
<li>ruby: add Windows ASIO driver support (does not work on some systems due to buggy vendor drivers)</li>
<li>higan: default to safe drivers on a new install; due to instability with some optimal drivers</li>
</ul>
<p><a href="//byuu.org/emulation/higan/">( Download )</a>
<a href="//board.byuu.org/viewtopic.php?f=4&amp;t=1734">( Discuss )</a></p>
</section><section><header id="3836087803">higan v103 released<span>2017-06-21</span></header>
<p>With this release, PC Engine, Master System, Game Gear, Mega Drive and the newly
added SuperGrafx support are now quite usable! They're far from the best
emulators for these systems, but with many bugfixes, full sound emulation, and
save state support ... many games are now fully playable with decent accuracy.</p>
<p>The Game Boy Advance emulation is also now substantially improved with vastly
improved sound quality and a new dot-based PPU renderer. With that change, every
single component in higan is now cycle-based. Regrettably, these changes do
carry a ~20% performance penalty compared to GBA emulation in v102.</p>
<p>Changelog:</p>
<ul>
<li>added SuperGrafx emulation</li>
<li>improved audio band-pass filtering for all emulated systems</li>
<li>screen rotation is now a hotkey; automatically rotates control bindings</li>
<li>screen rotation now supported on the Game Boy Advance as well (used by a small number of games)</li>
<li>massive improvements to Mega Drive emulation</li>
<li>massive code cleanups and rewrites to many CPU emulation cores (MOS6502, WDC65816, SPC700, etc)</li>
<li>Famicom, Master System, Mega Drive: added PAL emulation support</li>
<li>PC Engine, SuperGrafx, Master System, Game Gear, Mega Drive: added save state support</li>
<li>PC Engine, SuperGrafx: added PSG sound emulation</li>
<li>Master System, Game Gear: added PSG sound emulation</li>
<li>Mega Drive: added Z80 APU emulation [with help from Cydrak]</li>
<li>Mega Drive: added PSG sound emulation</li>
<li>Mega Drive: added YM2612 sound emulation [Cydrak]</li>
<li>Super Famicom: fixed Super Game Boy emulation</li>
<li>PC Engine: added save RAM support (using per-game PCE-CD backup RAM)</li>
<li>Game Boy Advance: substantial improvements to audio emulation quality</li>
<li>Game Boy Advance: convert scanline-based PPU renderer to a dot-based renderer</li>
<li>Game Boy Advance: properly initialize CPU state (fixes Classic NES Series games)</li>
<li>Game Boy Advance: MUL timing corrected [Jonas Quinn]</li>
<li>Mega Drive: emulate special mappers for Phantasy Star IV, Super Street Fighter II, etc.</li>
<li>Super Famicom: use darker luma for INIDISP=0 (large improvement to Final Fantasy III opening)</li>
<li>Super Famicom: fixed bugs in SMP OR1,AND1 instructions</li>
<li>cheat code database regrettably removed from official releases; will be made available separately</li>
</ul>
<p>This changelog is a summary of major changes. For a detailed list of all
changes, which spans several pages, please see the higan Gitlab repository.</p>
<p><a href="//byuu.org/emulation/higan/">( Download )</a>
<a href="//board.byuu.org/viewtopic.php?f=4&amp;t=1656">( Discuss )</a></p>
</section><section><header id="3768286426">higan v102 released<span>2017-01-19</span></header>
<p>This release adds very preliminary emulation of the Sega Master System
(Mark III), Sega Game Gear, Sega Mega Drive (Genesis), and NEC PC Engine
(Turbografx-16). These cores do not yet offer sound emulation, save states or
cheat codes.</p>
<p>I'm always very hesitant to release a new emulation core in its alpha stages, as
in the past this has resulted in lasting bad impressions of cores that have
since improved greatly. For instance, the Game Boy Advance emulation offered
today is easily the second most accurate around, yet it is still widely judged
by its much older alpha implementation.</p>
<p>However, it's always been tradition with higan to not hold onto code in secret.
Rather than delay future releases for another year or two, I'll put my faith in
you all to understand that the emulation of these systems <em>will</em> improve over
time.</p>
<p>I hope that by releasing things as they are now, I might be able to receive some
much needed assistance in improving these cores, as the documentation for these
new systems is very much less than ideal.</p>
<p>Also, please note that starting with this release, I am omitting the
<code>settings.bml</code> file. This means that you will have to manually configure your
gamepad input assignments, and select the appropriate devices from the system
menu after loading games. You may also want to select a more conservative driver
profile than the default (OpenGL, WASAPI.) If they cause you any troubles, a
safer bet would be (Direct3D, DirectSound.)</p>
<p>The good news in omitting this file is that you'll only have to configure inputs
once, and you won't lose any customizations by upgrading to future releases.</p>
<p><a href="//byuu.org/emulation/higan/">( Download )</a>
<a href="//board.byuu.org/viewtopic.php?f=4&amp;t=1493">( Discuss )</a></p>
</section><section><header id="862953638">New articles<span>2016-11-12, 2016-12-01</span></header>
<p>I've posted some new articles around the politics as of late. I needed a space
to reflect on things. Take of them what you will.</p>
<ul>
<li><a href="/articles/common-ground/">Common Ground</a></li>
<li><a href="/articles/futility-of-hope/">The Futility of Hope</a></li>
</ul>
</section><section><header id="2806039332">New article on SSL/HTTPS<span>2016-09-18</span></header>
<p>I've posted a new article concerning SSL/HTTPS on the web; the push for all
sites to move to HTTPS; and the failure of free certificate authorities.</p>
<p><a href="/articles/ssl/">Transport Layer Security (SSL/HTTPS)</a></p>
<p>For those who don't want to read an entire article; I'd just like to publicly
call out the blatant hypocisy of Let's Encrypt here:</p>
<p>They deny their users the ability to request wildcard certificates; yet enjoy
using wildcards on their parent site, eff.org</p>
<p>They deny their users the ability to request certificates that last longer than
three months, yet their very own letsencrypt.org website uses a certificate with
a <em>three year</em> validity length!</p>
<p>If they want to tell all their users how to run their sites, then they should
lead by example and give up these luxuries themselves.</p>
</section><section><header id="3348317890">New servers; SSL/HTTPS support; IPv6 support<span>2016-09-17</span></header>
<p>The old byuu.org has been replaced with two new servers. The forum now runs on
its own separate server. In order for the SSL certificate to work across both;
I had to use A/AAAA records to point board.byuu.org at the secondary server.</p>
<p>With the server move from New Jersey to Chicago, IPv6 support has begun working
once again.</p>
<p>For anyone who has been following my progress for the past two weeks; I have
been trying my best to find a solution to avoid paying for an SSL certificate:
not because I couldn't afford it, but because security should not cost money.</p>
<p>Unfortunately, there are only two free options: StartSSL, which won't cover
subdomains at all (a complete non-starter); and Let's Encrypt, a hypocritical
joke of a service.</p>
<p>I'll write more on this topic at a later date, but for now — and against my
strongest moral objections — I gave in and paid for an SSL certificate. Since it
is recognized by all browsers, I went ahead and made HTTP automatically redirect
to the HTTPS version of the site.</p>
</section><section><header id="1033552294">Sega Mega Drive (Sega Genesis) emulation<span>2016-08-21</span></header>
<p>On July 8th, I started on a Sega Mega Drive emulation core.</p>
<p>As of today, it's finally able to run its first game with no visible issues
other than a lack of audio emulation. Yay!</p>
<p>Still, it's going to be a long haul to get this core to be of high quality: the
Mega Drive is roughly on par with the SNES in terms of technical complexity when
it comes to aiming for extreme accuracy.</p>
<p>I'm not sure when it will appear in official releases.</p>
</section>
<footer>&copy;2018 byuu &mdash; accessed from 54.166.146.211</footer>
</body>
</html>