<!DOCTYPE HTML>
<!--[if lt IE 7]> <html lang="el" class="no-js ie ie6"> <![endif]-->
<!--[if IE 7]> <html lang="el" class="no-js ie ie7"> <![endif]-->
<!--[if IE 8]> <html lang="el" class="no-js ie ie8"> <![endif]-->
<!--[if IE 9 ]> <html class="no-js ie ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!-->
<html lang="el" class="no-js">
<!--<![endif]-->
<head>
<base href="http://www.cnn.gr/" />
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta http-equiv="refresh" content="400" />
	<meta name="keywords" content="CNN Greece,CNN Ελλάδα, cnn.gr, cnngreece, ειδησεις,ειδησεισ,eidhseis,ειδήσεις τώρα,ειδησεις τωρα,eidhseis twra,ειδήσεις ελλάδα,eidhseis ellada,ειδησεις ελλαδα, ειδήσεις σήμερα,eidhseis shmera,eidhseis live,ειδήσεις live,ειδήσεις ,τελευταίες ειδήσεις,τελευταιες ειδησεις,teleytaies eidhseis,news,news now,νέα,νεα,nea, Νέα Δημοκρατία, ΠΑΣΟΚ, Σύριζα, ΣΥΡΙΖΑ, ΚΚΕ, ΧΡΥΣΗ ΑΥΓΗ, Χρυσή Αυγή, ΑΝ.ΕΛ., Ανεξάρτητοι Έλληνες, Οικολόγοι, Πρωθυπουργός, Πρόεδρος, Δημοκρατία, Πρόεδρος της Δημοκρατίας, Αντιπρόεδρος, Βουλευτής, Βουλή, Χρήματα, Tax, Φόροι, Τρόικα,Panagopoulos, παναγοπουλος, Καρχιλάκη, karchilaki, τσοχος, news google,ειδήσεις google,ειδησεις google,eidhseis google, Συρία,Syria,startups,τεχνολογία, mobile, app, mobile app, εφαρμογή" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<meta name="google-site-verification" content="ZmBfgOk6gl73HSTVSlNlk0GnBCD-WPDYBQJk0FzEA9k" />
	<meta name="description" content="Αληθινές ειδήσεις με το κύρος του CNN.gr Όλη η έκτακτη επικαιρότητα, οι εξελίξεις και τα τελευταία νέα από την Ελλάδα και τον Κόσμο για Πολιτική, Οικονομία, Σπορ, Πολιτισμό, Αυτοκίνητο, Τεχνολογία" />
	<meta name="generator" content="Joomla! - Open Source Content Management" />
	<title>Έκτακτη επικαιρότητα, Ειδήσεις, Ελλάδα, Κόσμος, Πολιτική, Οικονομία, Σπορ - CNN.gr</title>
	<link href="https://www.google.com/+cnngreece" rel="publisher" />
	<link href="http://cdn.cnngreece.gr/templates/kgt_cnn/images/touch-icon-iphone.jpg" rel="apple-touch-icon" />
	<link href="http://cdn.cnngreece.gr/templates/kgt_cnn/images/touch-icon-ipad.jpg" rel="apple-touch-icon" sizes="76x76" />
	<link href="http://cdn.cnngreece.gr/templates/kgt_cnn/images/touch-icon-iphone-retina.jpg" rel="apple-touch-icon" sizes="120x120" />
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic&amp;subset=greek,latin" rel="stylesheet" />
	<link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,700,300,100&amp;subset=greek-ext" rel="stylesheet" />
	<link href="http://cdn.cnngreece.gr/stylesheets/0.6.20/kgt_cnn/css/style.min.css" rel="stylesheet" />
	<link href="/templates/kgt_cnn/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon" />
	<script type="text/javascript">

	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
	
	ga('create', 'UA-69029409-2', 'auto');
	ga('require', 'displayfeatures');
	
	ga('send', 'pageview');

	</script>
	<meta property="og:image" content="http://cdn.cnngreece.gr/templates/kgt_cnn/images/cnn_shared.jpg"/>
	<meta property="og:url" content="http://www.cnn.gr"/>
	<meta property="og:type" content="website"/>
	<meta property="fb:pages" content="134135906635470, 1462467174050685, 106193836872, 102549033154905, 143977845643534, 158325784220099, 483909011688295, 443713705655615, 144055192272531, 148059922321456, 605703926111961, 317229385034604, 187844828286947" />



<script type='text/javascript'>
var googletag = googletag || {};
googletag.cmd = googletag.cmd || [];
(function() {
var gads = document.createElement('script');
gads.async = true;
gads.type = 'text/javascript';
var useSSL = 'https:' == document.location.protocol;
gads.src = (useSSL ? 'https:' : 'http:') + 
'//www.googletagservices.com/tag/js/gpt.js';
var node = document.getElementsByTagName('script')[0];
node.parentNode.insertBefore(gads, node);
})();
</script>
	
	<script type="text/javascript" id="ean-native-embed-tag" src="https://cdn.elasticad.net/native/serve/js/nativeEmbed.gz.js"></script>
	
	
	<script type="text/javascript">
	function setUpAgknTag(tag) {
			tag.setBpId("dpggreece");
	}
	</script>
	<script src="//js.agkn.com/prod/v0/tag.js" async></script>

	<!--Agora Plugin-->
	
	<!-- Criteo Publisher Tag -->
	<script async='async' type="text/javascript" src="https://static.criteo.net/js/ld/publishertag.js"></script>

		<script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async=""></script>
		<script>
			var OneSignal = window.OneSignal || [];
			OneSignal.push(function() {
				OneSignal.init({
					appId: "eab72852-eac6-4b87-af07-896259402b26",
				});
			});
		</script>
</head>
<body id="com_news" class="site wide-960 respond homepage-view itemid-101 section-101 site-main home-page view-layout-default el-gr-site">
<div id="fb-root"></div>

<div class="hidden">
<div id="app-banner-prestitial" class="ad-unit"></div>

</div>

<h1 class="homepage-title">Ειδήσεις, Νέα και Βίντεο από την Ελλάδα και τον Κόσμο</h1>


	
<div id="app-page-header">
	
	
	
	
	<div class="fixed-zone">
	
		
		
		
		<div class="breaking">
		
			<div class="breaking-news-label">
				<div class="screen p0-10">
					BREAKING NEWS
					<div class="message-hide close-btn icon icon-close"></div>
				</div>
			</div>
			<div class="breaking-news">
				<div class="screen p0-10">
					<span class="message">
</span>
				</div>
			</div>
		</div>
		
	
		<div class="header-zone">
	    	<div class="screen">
		    
	        	<a class="logo" href="http://www.cnn.gr">CNN Greece</a>
	        
	        
	        
	        
		        <div class="navigation">
			        
			        			        
			        			        <div class="nav">
												
												<ul class="menu" id="app-page-main-menu">

	
	<li class="item-101 active  parent">
		<a href="/">Ειδήσεις</a>

		<ul class="nav-child submenu">
			<li class="item-122"><a href="/news/ellada">Ελλάδα</a></li>
			<li class="item-187"><a href="/news/politiki">Πολιτική</a></li>
			<li class="item-189"><a href="/news/kosmos">Κόσμος</a></li>
			<li class="item-190"><a href="/news/sports">Σπορ</a></li>
			<li class="item-199"><a href="/news/prosopa">Πρόσωπα</a></li>
			<li class="item-427"><a href="/news/perivallon">Περιβάλλον</a></li>
			<li class="item-404"><a href="/news/viral">Viral</a></li>
			<li class="item-229"><a href="/efimerides">Εφημερίδες</a></li>


		</ul>
	</li>

	<li class="item-188 parent">
		<a href="/videos">Video</a>

		<ul class="nav-child submenu">
			<li class="item-191"><a href="/videos/synenteyxeis">Συνεντεύξεις</a></li>
			<li class="item-192"><a href="/videos/reportaz">Ρεπορτάζ</a></li>
			<li class="item-193"><a href="/videos/ereynes">Έρευνες</a></li>
			<li class="item-194"><a href="/videos/viral">Viral</a></li>
		</ul>
	</li>

	<li class="item-209 parent">
		<a class="focus-link" href="/focus">Focus</a>
				<ul class="nav-child submenu">
			<li class="item-231"><a href="/focus/editorial">Editorial</a></li>
			<li class="item-230"><a href="/focus/apopseis">Απόψεις</a></li>
			<li class="item-403"><a href="/focus/explainers">Explainers</a></li>
		</ul>
	</li>

	<li class="item-195 parent">
		<a href="/oikonomia">Οικονομία</a>

		<ul class="nav-child submenu">
			<li class="item-196"><a href="/oikonomia/agores">Αγορές</a></li>
			<li class="item-197"><a href="/oikonomia/epixeiriseis">Επιχειρήσεις</a></li>
			<li class="item-371"><a href="/oikonomia/insights">Insights</a></li>
			<li class="item-432"><a href="/oikonomia/business">Business Stories</a></li>
		</ul>
	</li>


	<li class="item-198 parent">
		<a href="/tech">Tech</a>

		<ul class="nav-child submenu"><li><span class="placeholder">&nbsp;</span></li></ul>
	</li>


	<li class="item-202 parent">
		<a href="/style">Style</a>

		<ul class="nav-child submenu">
			<li class="item-200"><a href="/style/psyxagogia">Ψυχαγωγία</a></li>
			<li class="item-203"><a href="/style/politismos">Πολιτισμός</a></li>
			<li class="item-201"><a href="/style/moda">Μόδα</a></li>
			<li class="item-204"><a href="/style/aytokinito">Αυτοκίνητο</a></li>
			
					</ul>
	</li>

	<li class="item-205 parent">
		<a href="/taksidi/featured">Ταξίδι</a>

		<ul class="nav-child submenu">
			<li class="item-206"><a href="/taksidi/ellada">Ελλάδα</a></li>
			<li class="item-207"><a href="/taksidi/kosmos">Κόσμος</a></li>
			<li class="item-208"><a href="/taksidi/protaseis">Προτάσεις</a></li>
		</ul>
	</li>

	
	

	<li class="item-211 parent">
		<a href="/more/cnn-mobile">More</a>

		<ul class="nav-child submenu">
			<li class="item-212"><a href="/more/cnn-mobile">CNN Mobile</a></li>
			<li class="item-350"><a href="/more/widgets">Widgets</a></li>
			<li class="item-213"><a href="/more/who-we-are">Who we are</a></li>
		</ul>
	</li>
</ul>
						
			        </div>
								        
		        </div>
		        
		        <div class="burger"><span></span></div>
		        
		        
		        
		        <div class="search-area">
			    
			        <form method="get" action="/search">
				        
				        <div class="search-box">
			        		<input class="search-input" name="q" type="text" placeholder="Αναζήτηση" required>
				        </div>
				        <div class="search-button">
			        		<button type="submit"><span>Search</span></button>
				        </div>
				        <div class="search-toggle"><span></span></div>
				        
			        </form>
		        </div>
		        
		        		        <div class="header-share">
					<span class="share-block">
					    <a href="https://www.facebook.com/cnn.greece" class="share-trigger share-facebook" target="_blank">
					        <span class="icon icon-facebook"></span>
					    </a>
					</span>
					
				    <span class="share-block">
				    	<a href="https://twitter.com/CNNgreece" class="share-trigger share-twitter" target="_blank">
				        	<span class="icon icon-twitter"></span>
				    	</a>
				    </span>
					
					<span class="share-block">
						<a href="https://www.youtube.com/channel/UCA449AY-qrJsvE7HX8MZVog" class="share-trigger share-youtube" target="_blank">
						    <span class="icon icon-youtube"></span>
						</a>
					</span>
					
					<span class="share-block">
				    	<a href="https://instagram.com/cnngreece/" class="share-trigger share-instagram" target="_blank">
				        	<span class="icon icon-instagram"></span>
				    	</a>
				    </span>
					<span class="share-block">
				    	<a href="http://chats.viber.com/cnngreece" class="share-trigger share-viber" target="_blank">
					    	<span class="icon icon-viber"></span>
				    	</a>
				    </span>
				</div>
		        	        
	        </div>
	        
	        
	    </div>
	</div>
</div>





<div class="dfp-skin-zone" style="max-width:1140px; margin:auto;">
	<div class="dfp-skin-box"></div>
</div>

<div id="dfp-skin-place"></div>
<div id="app-dfp-skin" class="dfp-skin"></div>


	
	
	

	
	
			
	

	


		
	
		
	

		


	
		

<div class="zone ad-zone" id="adzone">
	<div class="screen">
		<div id="app-banner-wide-1-0" class="ad-unit"></div>
	</div>
</div>



<div class="zone content-zone theme-bright">

	<div id="content" class="screen">
		
		<div class="row section">
	        	
        	<div class="main-pack md10 theme-bright">
	        	
	        	<div class="main md10 lg-right">
		        	
		        			        	
			        						
		<div class="module p10">
			
						
				<div class="module-content">
				
<div class="news-stories">



	<div class="items-block">
	 
	
		<div class="item-block media-block cd-xl odd-block">
			
						
								<div class="item-media">
					<a class="story-image-link" href="/news/politiki/story/122275/synantisi-tsipra-kammenoy-i-apantisi-sta-senaria-peri-rixis">
						<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/topic/2018/03/20/2657/main/4013196.jpg" alt="Συνάντηση Τσίπρα – Καμμένου η απάντηση στα σενάρια περί ρήξης" />
					</a>
				</div>
								
				<div class="item-contents">

								
								
								
				
								<h2 class="item-title">
					<a href="/news/politiki/story/122275/synantisi-tsipra-kammenoy-i-apantisi-sta-senaria-peri-rixis">
					Συνάντηση Τσίπρα – Καμμένου η απάντηση στα σενάρια περί ρήξης					</a>
				</h2>
								
								
				
								
				
								
								
				
								
				
							
			
			
			
			</div>
						
		</div>
		
	
		</div>
</div>
				</div>
			
		</div>
	
										
						        	</div>
	        	
	        	<div class="side md10">
		        	
		        	<div class="sm10 md5 lg10">
			        						
		<div class="module lst p10 on-title track-latestnews">
			
						
				<div class="module-content">
				
<!-- List-Image-First -->





	<div class="module-head">
			
						<h3 class="module-title module-link">
				
								
				<a href="/eidhseis">
					Ροή ειδήσεων				</a>
				
							</h3>
				
				</div>
	


<div class="news-items" id="m-103">

	<div class="items-block">
	 
	
		<div class="item-block  on-pic w10">
		
						
			
						<div class="item-media">
				<a class="item-image-link" href="/news/perivallon/story/122196/aeiforia-i-nea-tasi-sto-lifestyle-mas-klirodotei-ena-viosimo-mellon">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/19/122196/snapshot/kizi-studio1.jpg" alt="Αειφορία: η νέα τάση στο lifestyle μας κληροδοτεί ένα βιώσιμο μέλλον" />
					
																				</a>
			</div>
						
						
							
								<div class="item-timestamp">
					<span class=red>5'</span>				</div>
							
						
						<h3 class="item-title">
				<a href="/news/perivallon/story/122196/aeiforia-i-nea-tasi-sto-lifestyle-mas-klirodotei-ena-viosimo-mellon">
				Αειφορία: η νέα τάση στο lifestyle μας κληροδοτεί ένα βιώσιμο μέλλον								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
	 
	
		<div class="item-block  on-title w10">
		
						
			
						
						
							
								<div class="item-timestamp">
					<span class=red>14'</span>				</div>
							
						
						<h3 class="item-title">
				<a href="/oikonomia/story/122278/tsakalotos-kai-stoyrnaras-vlepoyn-mayra-synnefa-stin-eyrozoni">
				Τσακαλώτος και Στουρνάρας βλέπουν «μαύρα σύννεφα» στην ευρωζώνη 								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
	 
	
		<div class="item-block  on-title w10">
		
						
			
						
						
							
								<div class="item-timestamp">
					<span class=red>24'</span>				</div>
							
						
						<h3 class="item-title">
				<a href="/news/ellada/story/122293/zoyn-kai-vasileyoyn-oi-speires-poy-xtypoyn-atm">
				Ζουν και βασιλεύουν οι σπείρες που χτυπούν ΑΤΜ								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
	 
	
		<div class="item-block  on-title w10">
		
						
			
						
						
							
								<div class="item-timestamp">
					<span class=red>35'</span>				</div>
							
						
						<h3 class="item-title">
				<a href="/news/politiki/story/122275/synantisi-tsipra-kammenoy-i-apantisi-sta-senaria-peri-rixis">
				Συνάντηση Τσίπρα – Καμμένου η απάντηση στα σενάρια περί ρήξης								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
	 
	
		<div class="item-block  on-title w10">
		
						
			
						
						
							
								<div class="item-timestamp">
					<span class=red>45'</span>				</div>
							
						
						<h3 class="item-title">
				<a href="/news/ellada/story/122292/ta-protoselida-ton-efimeridon-20-martioy">
				Τα πρωτοσέλιδα των εφημερίδων (20 Μαρτίου)								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
	 
	
		<div class="item-block  on-title w10">
		
						
			
						
						
							
								<div class="item-timestamp">
					<span class=red>53'</span>				</div>
							
						
						<h3 class="item-title">
				<a href="/news/ellada/story/122257/kairos-analytika-i-prognosi-gia-simera">
				Καιρός: Αναλυτικά η πρόγνωση για σήμερα 								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
	 
	
		<div class="item-block  on-title w10">
		
						
			
						
						
							
							
						
						<h3 class="item-title">
				<a href="/news/ellada/story/122249/poies-ores-tha-einai-kleistos-o-stathmos-toy-metro-panepistimio">
				Ποιες ώρες θα είναι κλειστός ο σταθμός του μετρό «Πανεπιστήμιο» 								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
	 
	
		<div class="item-block  on-title w10">
		
						
			
						
						
							
							
						
						<h3 class="item-title">
				<a href="/news/ellada/story/122290/seismos-anastatose-ta-ximeromata-ti-zakyntho">
				Σεισμός αναστάτωσε τα ξημερώματα τη Ζάκυνθο								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
		</div>

</div>

				</div>
			
		</div>
	
							        	</div>
		        	
		        	<div class="sm10 md5 lg10">
						<div id="app-banner-rectangle-1-0" class="ad-unit"></div>
		        	</div>
		        	
	        	</div>
	        	
	        	<div class="main-pack-rtl md10">
		        	
		        	<div class="main sm10 md5">
		        	
			        							
		<div class="module lst p10 on-title">
			
						
				<div class="module-content">
				
<!-- List-Image-First -->





	<div class="module-head">
			
						<h3 class="module-title module-link">
				
								
				<a href="/eidhseis">
					Top επικαιρότητα				</a>
				
							</h3>
				
				</div>
	


<div class="news-items" id="m-104">

	<div class="items-block">
	 
	
		<div class="item-block cd-lg">
			
						
						<div class="item-media">
				<a class="item-image-link" href="/oikonomia/story/122278/tsakalotos-kai-stoyrnaras-vlepoyn-mayra-synnefa-stin-eyrozoni">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/19/122278/snapshot/4409346.jpg" alt="Τσακαλώτος και Στουρνάρας βλέπουν «μαύρα σύννεφα» στην ευρωζώνη " />
					
					
										
				</a>
			</div>
						
						<div class="item-contents">
				
																		
						
						
						
						
						<h3 class="item-title">
				<a href="/oikonomia/story/122278/tsakalotos-kai-stoyrnaras-vlepoyn-mayra-synnefa-stin-eyrozoni">
				Τσακαλώτος και Στουρνάρας βλέπουν «μαύρα σύννεφα» στην ευρωζώνη 								
				</a>
			</h3>
						
						
						
						
						
						
						
						</div>
					</div>
	
	
	 
	
		<div class="item-block cd-thumb">
			
						
						
						
						<div class="item-media">
				<a class="item-image-link" href="/news/ellada/story/122293/zoyn-kai-vasileyoyn-oi-speires-poy-xtypoyn-atm">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/20/122293/thumb/IMG_0263.jpg" alt="Ζουν και βασιλεύουν οι σπείρες που χτυπούν ΑΤΜ" />
									</a>
			</div>
						
						
						
						<h3 class="item-title">
				<a href="/news/ellada/story/122293/zoyn-kai-vasileyoyn-oi-speires-poy-xtypoyn-atm">
				Ζουν και βασιλεύουν οι σπείρες που χτυπούν ΑΤΜ								
				</a>
			</h3>
						
						
						
						
						
						
						
					</div>
	
	
	 
	
		<div class="item-block cd-thumb">
			
						
						
						
						<div class="item-media">
				<a class="item-image-link" href="/news/politiki/story/122259/kotzias-h-merkel-exei-paremvei-ston-erntogan-gia-to-thema-ton-dyo-ellinon-stratiotikon">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/19/122259/thumb/4267134.jpg" alt="Κοτζιάς: Η Μέρκελ έχει παρέμβει στον Ερντογάν για το θέμα των δύο Ελλήνων στρατιωτικών " />
									</a>
			</div>
						
						
						
						<h3 class="item-title">
				<a href="/news/politiki/story/122259/kotzias-h-merkel-exei-paremvei-ston-erntogan-gia-to-thema-ton-dyo-ellinon-stratiotikon">
				Κοτζιάς: Η Μέρκελ έχει παρέμβει στον Ερντογάν για το θέμα των δύο Ελλήνων στρατιωτικών 								
				</a>
			</h3>
						
						
						
						
						
						
						
					</div>
	
	
	 
	
		<div class="item-block cd-thumb">
			
						
						
						
						<div class="item-media">
				<a class="item-image-link" href="/news/politiki/story/122269/kataggelia-voytsi-gia-apeiles-kata-voyleyton-ean-psifisoyn-yper-synthetis-onomasias-tis-pgdm">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/19/122269/thumb/4409206.jpg" alt="Καταγγελία Βούτση για απειλές κατά βουλευτών εάν ψηφίσουν υπέρ σύνθετης ονομασίας της πΓΔΜ" />
									</a>
			</div>
						
						
						
						<h3 class="item-title">
				<a href="/news/politiki/story/122269/kataggelia-voytsi-gia-apeiles-kata-voyleyton-ean-psifisoyn-yper-synthetis-onomasias-tis-pgdm">
				Καταγγελία Βούτση για απειλές κατά βουλευτών εάν ψηφίσουν υπέρ σύνθετης ονομασίας της πΓΔΜ								
				</a>
			</h3>
						
						
						
						
						
						
						
					</div>
	
	
	 
	
		<div class="item-block cd-thumb">
			
						
						
						
						<div class="item-media">
				<a class="item-image-link" href="/news/ellada/story/122139/dolofonia-19xronoy-sto-maroysi-stis-epafes-toy-kinitoy-toy-thymatos-anazitoyn-ton-drasti">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/19/122139/thumb/4361649.jpg" alt="Δολοφονία 19χρονου στο Μαρούσι: Στις επαφές του κινητού του θύματος αναζητούν τον δράστη" />
									</a>
			</div>
						
						
						
						<h3 class="item-title">
				<a href="/news/ellada/story/122139/dolofonia-19xronoy-sto-maroysi-stis-epafes-toy-kinitoy-toy-thymatos-anazitoyn-ton-drasti">
				Δολοφονία 19χρονου στο Μαρούσι: Στις επαφές του κινητού του θύματος αναζητούν τον δράστη								
				</a>
			</h3>
						
						
						
						
						
						
						
					</div>
	
	
		</div>

</div>

				</div>
			
		</div>
	
											
		        	</div>
		        	
		        	<div class="side md5">
			        	
												
		<div class="module p10 on-title">
			
						
				<div class="module-content">
				
<!-- List-Image-First -->





	<div class="module-head">
			
						<h3 class="module-title module-link">
				
								
				<a href="/news/kosmos">
					Κόσμος				</a>
				
							</h3>
				
				</div>
	


<div class="news-items" id="m-95">

	<div class="items-block">
	 
	
		<div class="item-block  cd-md w10">
		
						
			
						<div class="item-media">
				<a class="item-image-link" href="/news/kosmos/story/122287/fovoi-gia-epistrofi-toy-isis-logo-tis-toyrkikis-epixeirisis-stin-afrin">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/19/122287/snapshot/2018-03-18T204705Z_1343541313_RC1922C026C0_RTRMADP_3_MIDEAST-CRISIS-SYRIA-AFRIN.JPG" alt="Φόβοι για «επιστροφή» του ISIS λόγω της τουρκικής παρουσίας στην Αφρίν" />
					
																				</a>
			</div>
						
			
						
						
						
						<h3 class="item-title">
				<a href="/news/kosmos/story/122287/fovoi-gia-epistrofi-toy-isis-logo-tis-toyrkikis-epixeirisis-stin-afrin">
				Φόβοι για «επιστροφή» του ISIS λόγω της τουρκικής παρουσίας στην Αφρίν								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
	 
	
		<div class="item-block  cd-pic w10">
		
						
			
						
			
						<div class="item-media">
				<a class="item-image-link" href="/news/kosmos/story/122222/brexit-symfonia-vretanias-e-e-gia-ti-metavatiki-periodo">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/19/122222/pic/2018-03-19T131559Z_2021471343_RC1A65E366B0_RTRMADP_3_BRITAIN-EU-DEAL.JPG" alt="Brexit: Συμφωνία Βρετανίας-Ε.Ε. για τη μεταβατική περίοδο " />
									</a>
			</div>
						
						
						
						<h3 class="item-title">
				<a href="/news/kosmos/story/122222/brexit-symfonia-vretanias-e-e-gia-ti-metavatiki-periodo">
				Brexit: Συμφωνία Βρετανίας-Ε.Ε. για τη μεταβατική περίοδο 								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
	 
	
		<div class="item-block  cd-pic w10">
		
						
			
						
			
						<div class="item-media">
				<a class="item-image-link" href="/news/kosmos/story/122250/o-erntogan-tha-zitisei-apo-tin-e-e-ta-ypoloipa-3-dis-eyro-tis-voitheias-gia-toys-prosfyges">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/19/122250/pic/erdogan.jpg" alt="Ο Ερντογάν θα ζητήσει από την Ε.Ε. τα «υπόλοιπα 3 δισ. ευρώ» της βοήθειας για τους πρόσφυγες" />
									</a>
			</div>
						
						
						
						<h3 class="item-title">
				<a href="/news/kosmos/story/122250/o-erntogan-tha-zitisei-apo-tin-e-e-ta-ypoloipa-3-dis-eyro-tis-voitheias-gia-toys-prosfyges">
				Ο Ερντογάν θα ζητήσει από την Ε.Ε. τα «υπόλοιπα 3 δισ. ευρώ» της βοήθειας για τους πρόσφυγες								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
	 
	
		<div class="item-block  cd-pic w10">
		
						
			
						
			
						<div class="item-media">
				<a class="item-image-link" href="/news/kosmos/story/122258/dw-paratasi-stoys-elegxoys-ptiseon-apo-ellada-skeftetai-to-verolino">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/19/122258/pic/2494927.jpg" alt="DW: Παράταση στους ελέγχους πτήσεων από Ελλάδα σκέφτεται το Βερολίνο " />
									</a>
			</div>
						
						
						
						<h3 class="item-title">
				<a href="/news/kosmos/story/122258/dw-paratasi-stoys-elegxoys-ptiseon-apo-ellada-skeftetai-to-verolino">
				DW: Παράταση στους ελέγχους πτήσεων από Ελλάδα σκέφτεται το Βερολίνο 								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
	 
	
		<div class="item-block  cd-pic w10">
		
						
			
						
			
						<div class="item-media">
				<a class="item-image-link" href="/news/kosmos/story/122276/yvristikes-ekfraseis-toy-maxmoynt-ampas-gia-ton-amerikano-presvi-sto-israil">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/19/122276/pic/2018-03-01T170826Z_1019066425_RC12BC79AF90_RTRMADP_3_ISRAEL-PALESTINIANS-ABBAS.JPG" alt="Υβριστικές εκφράσεις του Μαχμούντ Αμπάς για τον Αμερικανό πρέσβη στο Ισραήλ" />
									</a>
			</div>
						
						
						
						<h3 class="item-title">
				<a href="/news/kosmos/story/122276/yvristikes-ekfraseis-toy-maxmoynt-ampas-gia-ton-amerikano-presvi-sto-israil">
				Υβριστικές εκφράσεις του Μαχμούντ Αμπάς για τον Αμερικανό πρέσβη στο Ισραήλ								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
	 
	
		<div class="item-block  cd-pic w10">
		
						
			
						
			
						<div class="item-media">
				<a class="item-image-link" href="/news/kosmos/story/122277/aytonomo-aytokinito-xoris-odigo-tis-uber-skotose-pezi">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/19/122277/pic/17083274.jpg" alt="Αυτόνομο αυτοκίνητο χωρίς οδηγό της Uber σκότωσε πεζή " />
									</a>
			</div>
						
						
						
						<h3 class="item-title">
				<a href="/news/kosmos/story/122277/aytonomo-aytokinito-xoris-odigo-tis-uber-skotose-pezi">
				Αυτόνομο αυτοκίνητο χωρίς οδηγό της Uber σκότωσε πεζή 								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
		</div>

</div>

				</div>
			
		</div>
	
									        	
		        	</div>
	        	</div>
	        	
        	</div>
        	
        </div>
        
	</div>
	
	
			
		
	
		
	
</div>


	

<div class="zone theme-dark featured-zone">
	<div class="screen">
		<div class="row section">		
			<div class="section-header p10">
				<h2 class="section-title lines"><a href="/focus">Focus</a></h2>
			</div>
		
			<div class="main-pack">
				<div class="main">
				
									
				
		<div class="module lst p10 on-title">
			
						
				<div class="module-content">
				
<!-- List-Image-First -->








<div class="news-items" id="m-969">

	<div class="items-block">
	 
	
		<div class="item-block cd-lg">
			
						
						<div class="item-media">
				<a class="item-image-link" href="http://www.cnn.gr/to-nero-zei-mazi-mas">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/16/121810/main/29342471_608426096176279_2474846909999611904_n.jpg" alt=" Το νερό ζει μαζί μας: Μας καλλιεργεί" />
					
					
										
				</a>
			</div>
						
						<div class="item-contents">
				
																		
						
						
						
						
						<h3 class="item-title">
				<a href="http://www.cnn.gr/to-nero-zei-mazi-mas">
				 Το νερό ζει μαζί μας: Μας καλλιεργεί								
				</a>
			</h3>
						
						
						
						
						
						
						
						</div>
					</div>
	
	
		</div>

</div>

				</div>
			
		</div>
	
		<div class="module p10 on-title cd-md">
			
						
				<div class="module-content">
				
<!-- List-Image-First -->








<div class="news-items" id="m-972">

	<div class="items-block grid">
	 
	
		<div class="item-block p10 md5 odd-block w5">
			
							
						<div class="item-media">
				<a class="item-image-link" href="/focus/story/122157/vlantimir-poytin-enas-isovios-igetis">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/19/122157/snapshot/vladimir-putin.JPG" alt="Βλαντιμίρ Πούτιν: Ένας ισόβιος ηγέτης;" />
									</a>
			</div>
						
			<div class="item-badged">
				
								<span class="badge red-badge">
				της ΜΑΡΙΑΣ ΚΑΡΧΙΛΑΚΗ				</span>
									
			
								
								<h3 class="item-title">
					<a href="/focus/story/122157/vlantimir-poytin-enas-isovios-igetis">
					Βλαντιμίρ Πούτιν: Ένας ισόβιος ηγέτης;										</a>
				</h3>
								
								
								
								
								
								
							
			</div>
			
			
		</div>
	
		
	 
	
		<div class="item-block p10 md5 even-block w5">
			
							
						<div class="item-media">
				<a class="item-image-link" href="/focus/story/122040/axel-troost-oi-anagkes-epivaloyn-synergasia-aristeras-sosialdimokratias">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/18/122040/snapshot/ZE8A2804.JPG" alt="Άξελ Τρόοστ: Οι ανάγκες επιβάλουν συνεργασία Αριστεράς - Σοσιαλδημοκρατίας" />
									</a>
			</div>
						
			<div class="item-badged">
				
								<span class="badge red-badge">
				του ΚΩΣΤΑ ΠΛΙΑΚΟΥ				</span>
									
			
								
								<h3 class="item-title">
					<a href="/focus/story/122040/axel-troost-oi-anagkes-epivaloyn-synergasia-aristeras-sosialdimokratias">
					Άξελ Τρόοστ: Οι ανάγκες επιβάλουν συνεργασία Αριστεράς - Σοσιαλδημοκρατίας										</a>
				</h3>
								
								
								
								
								
								
							
			</div>
			
			
		</div>
	
	<div class="clr"></div>	
		</div>

</div>

				</div>
			
		</div>
	
					
					
								
				</div>
				<div class="side md10">
					
		<div class="module p10 on-title lg10 sm5">
			
						
				<div class="module-content">
				
<!-- List-Image-First -->





	<div class="module-head">
			
						<h3 class="module-title module-link">
				
								
				<a href="/focus/apopseis">
					Editorial - Απόψεις				</a>
				
							</h3>
				
				</div>
	


<div class="news-items" id="m-970">

	<div class="items-block">
	 
	
		<div class="item-block  cd-md w10">
		
						
			
						<div class="item-media">
				<a class="item-image-link" href="/focus/editorial/story/121326/ferte-piso-tin-paidiki-mas-ilikia">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/13/121326/snapshot/balla.jpg" alt="Φέρτε πίσω την παιδική μας ηλικία" />
					
										<span class="badge red-badge">
					του ΑΔΑΜΟΥ ΖΑΧΑΡΙΑΔΗ					</span>
									</a>
			</div>
						
			
						
						
						
						<h3 class="item-title">
				<a href="/focus/editorial/story/121326/ferte-piso-tin-paidiki-mas-ilikia">
				Φέρτε πίσω την παιδική μας ηλικία								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
	 
	
		<div class="item-block  cd-pic w10">
		
						
			
						
			
						<div class="item-media">
				<a class="item-image-link" href="/focus/apopseis/story/120235/italikes-ekloges-avevaiotita-anodos-tis-akrodexias-kai-mia-mikri-elpida">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/05/120235/pic/2018-03-04T165914Z_2114447417_RC18D295EBB0_RTRMADP_3_ITALY-ELECTION-1.JPG" alt="Ιταλικές εκλογές: Αβεβαιότητα, άνοδος της ακροδεξιάς, και μια μικρή ελπίδα" />
									</a>
			</div>
						
						
						
						<h3 class="item-title">
				<a href="/focus/apopseis/story/120235/italikes-ekloges-avevaiotita-anodos-tis-akrodexias-kai-mia-mikri-elpida">
				Ιταλικές εκλογές: Αβεβαιότητα, άνοδος της ακροδεξιάς, και μια μικρή ελπίδα								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
	 
	
		<div class="item-block  cd-pic w10">
		
						
			
						
			
						<div class="item-media">
				<a class="item-image-link" href="/focus/editorial/story/119711/exi-symperasmata-apo-ton-anasximatismo">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/01/119711/pic/1111.jpg" alt="Έξι συμπεράσματα από τον ανασχηματισμό" />
									</a>
			</div>
						
						
						
						<h3 class="item-title">
				<a href="/focus/editorial/story/119711/exi-symperasmata-apo-ton-anasximatismo">
				Έξι συμπεράσματα από τον ανασχηματισμό								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
		</div>

</div>

				</div>
			
		</div>
	
					
		<div class="module p10 on-title lg10 sm5">
			
						
				<div class="module-content">
				
<!-- List-Image-First -->





	<div class="module-head">
			
						<h3 class="module-title module-link">
				
								
				<a href="/focus/explainers">
					Explainers				</a>
				
							</h3>
				
				</div>
	


<div class="news-items" id="m-971">

	<div class="items-block">
	 
	
		<div class="item-block  cd-md w10">
		
						
			
						<div class="item-media">
				<a class="item-image-link" href="/news/kosmos/story/122016/vretania-rosia-oi-ypotheseis-kataskopeias-oi-apelaseis-kai-ta-antipoina">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/17/122016/snapshot/2018-03-17T134835Z_334028014_RC16A8DFAE70_RTRMADP_3_SOCCER-ENGLAND-BOU-WBA.JPG" alt="Βρετανία-Ρωσία: Οι υποθέσεις κατασκοπείας, οι απελάσεις και τα αντίποινα  " />
					
																				</a>
			</div>
						
			
						
						
						
						<h3 class="item-title">
				<a href="/news/kosmos/story/122016/vretania-rosia-oi-ypotheseis-kataskopeias-oi-apelaseis-kai-ta-antipoina">
				Βρετανία-Ρωσία: Οι υποθέσεις κατασκοπείας, οι απελάσεις και τα αντίποινα  								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
		</div>

</div>

				</div>
			
		</div>
	
				</div>
			</div>
		</div>
	</div>
</div>



<div class="zone content-zone theme-bright">
	
	<div id="more-content" class="screen">
        
        <div class="row section">
        	<div class="main-pack-duplex">
	        	
	        	<div class="side md5">
		        	<div class="sm10">
			        							
		<div class="module lst p10 on-title">
			
						
				<div class="module-content">
				
<!-- List-Image-First -->





	<div class="module-head">
			
						<h3 class="module-title">
				Επιλογές			</h3>
				</div>
	


<div class="news-items" id="m-122">

	<div class="items-block">
	 
	
		<div class="item-block  cd-md w10">
		
						
			
						<div class="item-media">
				<a class="item-image-link" href="/news/ellada/story/122172/poso-asfali-einai-ta-toyrkika-trofima-poy-eisagontai-se-ellada-kai-ee">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/19/122172/snapshot/13047361-n97.jpg" alt="Πόσο ασφαλή είναι τα τουρκικά τρόφιμα που εισάγονται σε Ελλάδα και ΕΕ " />
					
										<span class="badge red-badge">
					ΡΕΠΟΡΤΑΖ CNN GREECE 					</span>
									</a>
			</div>
						
			
						
						
						
						<h3 class="item-title">
				<a href="/news/ellada/story/122172/poso-asfali-einai-ta-toyrkika-trofima-poy-eisagontai-se-ellada-kai-ee">
				Πόσο ασφαλή είναι τα τουρκικά τρόφιμα που εισάγονται σε Ελλάδα και ΕΕ 								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
	 
	
		<div class="item-block  cd-pic w10">
		
						
			
						
			
						<div class="item-media">
				<a class="item-image-link" href="/style/politismos/story/122184/sampania-rekor-poliseon-4-9-disek-eyro-gia-tis-fysalides-tis-polyteleias">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/19/122184/pic/two-glasses-of-champagne.jpg" alt="Σαμπάνια: ρεκόρ πωλήσεων 4,9 δισεκ. ευρώ για τις φυσαλίδες της πολυτέλειας " />
									</a>
			</div>
						
						
						
						<h3 class="item-title">
				<a href="/style/politismos/story/122184/sampania-rekor-poliseon-4-9-disek-eyro-gia-tis-fysalides-tis-polyteleias">
				Σαμπάνια: ρεκόρ πωλήσεων 4,9 δισεκ. ευρώ για τις φυσαλίδες της πολυτέλειας 								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
	 
	
		<div class="item-block  cd-pic w10">
		
						
			
						
			
						<div class="item-media">
				<a class="item-image-link" href="/news/kosmos/story/122142/mia-teleytaia-simantiki-theoria-afise-parakatathiki-o-stiven-xokingk">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/19/122142/pic/19245028.jpg" alt="Μία τελευταία σημαντική θεωρία άφησε παρακαταθήκη ο Στίβεν Χόκινγκ" />
									</a>
			</div>
						
						
						
						<h3 class="item-title">
				<a href="/news/kosmos/story/122142/mia-teleytaia-simantiki-theoria-afise-parakatathiki-o-stiven-xokingk">
				Μία τελευταία σημαντική θεωρία άφησε παρακαταθήκη ο Στίβεν Χόκινγκ								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
		</div>

</div>

				</div>
			
		</div>
	
								        	</div>
	        	</div>
	        	
	        	<div class="side-two md5">
		        	<div class="sm10">
			        							
		<div class="module lst p10">
			
						
				<div class="module-content">
				
<!-- List-Image-First -->





	<div class="module-head">
			
						<h3 class="module-title module-link">
				
								
				<a href="http://www.cnn.gr/style">
					Style				</a>
							</h3>
				
				</div>
	


<div class="news-items" id="m-124">

	<div class="items-block">
	 
	
		<div class="item-block on-pic cd-md w10">
		
						
			
						<div class="item-media">
				<a class="item-image-link" href="/style/moda/story/122217/fashion-fax-telos-epoxis-ston-dior-homme-poios-o-diadoxos-toy-kris-van-assche">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/19/122217/thumb/dior-homme-kris-van-assche-06.jpg" alt="Fashion fax: τέλος εποχής στον Dior Homme - ποιος ο διάδοχος του Kris Van Assche" />
					
																				</a>
			</div>
						
			
						
						
						
						<h3 class="item-title">
				<a href="/style/moda/story/122217/fashion-fax-telos-epoxis-ston-dior-homme-poios-o-diadoxos-toy-kris-van-assche">
				Fashion fax: τέλος εποχής στον Dior Homme - ποιος ο διάδοχος του Kris Van Assche								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
	 
	
		<div class="item-block on-pic cd-pic w10">
		
						
			
						
			
						<div class="item-media">
				<a class="item-image-link" href="/style/psyxagogia/story/122274/h-miranta-toy-sex-and-the-city-diekdikei-ti-thesi-toy-kyverniti-tis-neas-yorkis">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/19/122274/pic/2018-03-19T184940Z_777356439_RC17704D9030_RTRMADP_3_NEW-YORK-GOVERNOR-CYNTHIANIXON.JPG" alt="Η Μιράντα του «Sex and the City» διεκδικεί τη θέση του κυβερνήτη της Νέας Υόρκης" />
									</a>
			</div>
						
						
						
						<h3 class="item-title">
				<a href="/style/psyxagogia/story/122274/h-miranta-toy-sex-and-the-city-diekdikei-ti-thesi-toy-kyverniti-tis-neas-yorkis">
				Η Μιράντα του «Sex and the City» διεκδικεί τη θέση του κυβερνήτη της Νέας Υόρκης								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
	 
	
		<div class="item-block on-pic cd-pic w10">
		
						
			
						
			
						<div class="item-media">
				<a class="item-image-link" href="/style/moda/story/122231/antzelina-tzoli-agapo-ta-girateia-moy-thymizoyn-oti-eimai-zontani">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/19/122231/pic/jol.PNG" alt="Aντζελίνα Τζολί: Αγαπώ τα γηρατειά, μου θυμίζουν ότι είμαι ζωντανή" />
									</a>
			</div>
						
						
						
						<h3 class="item-title">
				<a href="/style/moda/story/122231/antzelina-tzoli-agapo-ta-girateia-moy-thymizoyn-oti-eimai-zontani">
				Aντζελίνα Τζολί: Αγαπώ τα γηρατειά, μου θυμίζουν ότι είμαι ζωντανή								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
		</div>

</div>

				</div>
			
		</div>
	
								        	</div>
	        	</div>
	        	
	        	<div class="main md10">
		        	<div class="sm10">
			        							
		<div class="module lst p10 on-pic ">
			
						
				<div class="module-content">
				
<!-- List-Image-First -->





	<div class="module-head">
			
						<h3 class="module-title module-link">
				
								
				<a href="/videos">
					Video stories				</a>
				
							</h3>
				
				</div>
	


<div class="news-items" id="m-123">

	<div class="items-block grid">
	 
	
		<div class="item-block p10 md5 odd-block w5">
			
							
						<div class="item-media">
				<a class="item-image-link" href="/reportaz/video/9631/o-mpasar-al-asant-panigyrizei-gyros-toy-thriamvoy-stin-isopedomeni-gkoyta">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/19/122242/thumb/2018-03-18T212128Z_166140129_RC188D48B2D0_RTRMADP_3_MIDEAST-CRISIS-SYRIA-GHOUTA.JPG" alt="Ο Μπασάρ αλ-Άσαντ πανηγυρίζει: «Γύρος του θριάμβου» στην ισοπεδωμένη Γκούτα" />
					<span class="icon icon-media-video"><i data-text="01:39"></i></span>				</a>
			</div>
						
			<div class="item-badged">
				
									<span class="icon icon-media-video"><i data-text="01:39"></i></span>									
			
								
								<h3 class="item-title">
					<a href="/reportaz/video/9631/o-mpasar-al-asant-panigyrizei-gyros-toy-thriamvoy-stin-isopedomeni-gkoyta">
					Ο Μπασάρ αλ-Άσαντ πανηγυρίζει: «Γύρος του θριάμβου» στην ισοπεδωμένη Γκούτα					<span class="icon icon-media-video"><i data-text="01:39"></i></span>					</a>
				</h3>
								
								
								
								
								
								
							
			</div>
			
			
		</div>
	
		
	 
	
		<div class="item-block p10 md5 even-block w5">
			
							
						<div class="item-media">
				<a class="item-image-link" href="/synenteyxeis/video/9630/o-podosfairistis-me-to-prosthetiko-xeri-to-troxaio-poy-toy-allaxe-ti-zoi-kai-i-epimoni-sto-oneiro">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/19/122218/thumb/180309181600-cosmin-lambru-tease-video-exlarge-169.jpg" alt="Ο ποδοσφαιριστής με το προσθετικό χέρι: Το τροχαίο που του άλλαξε τη ζωή και η επιμονή στο όνειρο" />
					<span class="icon icon-media-video"><i data-text="02:47"></i></span>				</a>
			</div>
						
			<div class="item-badged">
				
									<span class="icon icon-media-video"><i data-text="02:47"></i></span>									
			
								
								<h3 class="item-title">
					<a href="/synenteyxeis/video/9630/o-podosfairistis-me-to-prosthetiko-xeri-to-troxaio-poy-toy-allaxe-ti-zoi-kai-i-epimoni-sto-oneiro">
					Ο ποδοσφαιριστής με το προσθετικό χέρι: Το τροχαίο που του άλλαξε τη ζωή και η επιμονή στο όνειρο					<span class="icon icon-media-video"><i data-text="02:47"></i></span>					</a>
				</h3>
								
								
								
								
								
								
							
			</div>
			
			
		</div>
	
	<div class="clr"></div>	
	 
	
		<div class="item-block p10 md5 odd-block w5">
			
							
						<div class="item-media">
				<a class="item-image-link" href="/reportaz/video/9629/frikto-atyxima-thanasimi-ptosi-akrovati-toy-cirque-du-soleil-kata-ti-diarkeia-parastasis">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/19/122175/thumb/Arnaud-3.PNG" alt="Φρικτό ατύχημα: Θανάσιμη πτώση ακροβάτη του Cirque du Soleil κατά τη διάρκεια παράστασης " />
					<span class="icon icon-media-video"><i data-text="01:28"></i></span>				</a>
			</div>
						
			<div class="item-badged">
				
									<span class="icon icon-media-video"><i data-text="01:28"></i></span>									
			
								
								<h3 class="item-title">
					<a href="/reportaz/video/9629/frikto-atyxima-thanasimi-ptosi-akrovati-toy-cirque-du-soleil-kata-ti-diarkeia-parastasis">
					Φρικτό ατύχημα: Θανάσιμη πτώση ακροβάτη του Cirque du Soleil κατά τη διάρκεια παράστασης 					<span class="icon icon-media-video"><i data-text="01:28"></i></span>					</a>
				</h3>
								
								
								
								
								
								
							
			</div>
			
			
		</div>
	
		
	 
	
		<div class="item-block p10 md5 even-block w5">
			
							
						<div class="item-media">
				<a class="item-image-link" href="/reportaz/video/9628/to-proi-trapezikos-ependytis-to-vrady-dj-aytos-einai-o-epomenos-proedros-tis-goldman-sachs">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/18/122102/thumb/Solomon.PNG" alt="Το πρωί τραπεζικός επενδυτής, το βράδυ DJ: Αυτός είναι ο επόμενος πρόεδρος της Goldman Sachs" />
					<span class="icon icon-media-video"><i data-text="00:49"></i></span>				</a>
			</div>
						
			<div class="item-badged">
				
									<span class="icon icon-media-video"><i data-text="00:49"></i></span>									
			
								
								<h3 class="item-title">
					<a href="/reportaz/video/9628/to-proi-trapezikos-ependytis-to-vrady-dj-aytos-einai-o-epomenos-proedros-tis-goldman-sachs">
					Το πρωί τραπεζικός επενδυτής, το βράδυ DJ: Αυτός είναι ο επόμενος πρόεδρος της Goldman Sachs					<span class="icon icon-media-video"><i data-text="00:49"></i></span>					</a>
				</h3>
								
								
								
								
								
								
							
			</div>
			
			
		</div>
	
	<div class="clr"></div>	
		</div>

</div>

				</div>
			
		</div>
	
								        	</div>
	        	</div>
	        	
	        	
        	</div>
        	
        	<div class="clr"></div>
        	
        </div>
        
	</div>
</div>













	




 
<div class="zone content-zone theme-bright">

	<div id="even-more-content" class="screen">
        
        <div class="row section">
	        
	        <div class="section-header p10">
		        
				<h2 class="section-title lines">Featured Sections</h2>
			</div>
	        	
        	<div class="sm10 md5 lg33">
	        					
		<div class="module lst p10">
			
						
				<div class="module-content">
				
<!-- List-Image-First -->





	<div class="module-head">
			
						<h3 class="module-title module-link">
				
								
				<a href="/news/ellada">
					Ελλάδα				</a>
				
							</h3>
				
				</div>
	


<div class="news-items" id="m-125">

	<div class="items-block">
	 
	
		<div class="item-block on-title cd-md on-pic w10">
		
						
			
						<div class="item-media">
				<a class="item-image-link" href="/news/ellada/story/122234/ypothesi-marioy-papageorgioy-diekopi-i-diki-epeidi-katerreyse-i-mitera-toy">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/19/122234/thumb/4070246.jpg" alt="Υπόθεση Μάριου Παπαγεωργίου: Διεκόπη η δίκη επειδή κατέρρευσε η μητέρα του" />
					
																				</a>
			</div>
						
						
						
						<h3 class="item-title">
				<a href="/news/ellada/story/122234/ypothesi-marioy-papageorgioy-diekopi-i-diki-epeidi-katerreyse-i-mitera-toy">
				Υπόθεση Μάριου Παπαγεωργίου: Διεκόπη η δίκη επειδή κατέρρευσε η μητέρα του								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
	 
	
		<div class="item-block on-title on-title w10">
		
						
			
						
						
						
						<h3 class="item-title">
				<a href="/news/ellada/story/122260/kriti-nekros-syntaxioyxos-astynomikos-poy-parasyrthike-apo-aytokinito">
				Κρήτη: Νεκρός συνταξιούχος αστυνομικός που παρασύρθηκε από αυτοκίνητο								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
	 
	
		<div class="item-block on-title on-title w10">
		
						
			
						
						
						
						<h3 class="item-title">
				<a href="/news/ellada/story/122235/mega-sto-ste-kata-tis-apofasis-toy-esr-prosefygan-pospert-kai-ergazomenoi">
				Μega: Στο ΣτΕ κατά της απόφασης του ΕΣΡ προσέφυγαν ΠΟΣΠΕΡΤ και εργαζόμενοι								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
		</div>

</div>

				</div>
			
		</div>
	
				        	</div>
    	
        	<div class="sm10 md5 lg33">
	        					
		<div class="module lst p10">
			
						
				<div class="module-content">
				
<!-- List-Image-First -->





	<div class="module-head">
			
						<h3 class="module-title module-link">
				
								
				<a href="/news/politiki">
					Πολιτική				</a>
				
							</h3>
				
				</div>
	


<div class="news-items" id="m-126">

	<div class="items-block">
	 
	
		<div class="item-block on-title cd-md on-pic w10">
		
						
			
						<div class="item-media">
				<a class="item-image-link" href="/news/sports/story/122284/vasileiadis-se-exi-mines-den-mporoyn-na-diorthothoyn-oi-pathogeneies-40-xronon">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/19/122284/thumb/4403781.jpg" alt="Βασιλειάδης: Σε έξι μήνες δεν μπορούν να διορθωθούν οι παθογένειες 40 χρόνων" />
					
																				</a>
			</div>
						
						
						
						<h3 class="item-title">
				<a href="/news/sports/story/122284/vasileiadis-se-exi-mines-den-mporoyn-na-diorthothoyn-oi-pathogeneies-40-xronon">
				Βασιλειάδης: Σε έξι μήνες δεν μπορούν να διορθωθούν οι παθογένειες 40 χρόνων								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
	 
	
		<div class="item-block on-title on-title w10">
		
						
			
						
						
						
						<h3 class="item-title">
				<a href="/news/politiki/story/122256/poines-stoys-xrysaygites-gia-ton-dixastiko-toys-logo">
				Ποινές στους χρυσαυγίτες για τον διχαστικό τους λόγο								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
	 
	
		<div class="item-block on-title on-title w10">
		
						
			
						
						
						
						<h3 class="item-title">
				<a href="/news/politiki/story/122220/h-sygkyvernisi-tha-ftasei-mexri-to-telos-dilonei-o-panos-kammenos">
				Π.Καμμένος: Η συγκυβέρνηση θα φτάσει μέχρι το τέλος								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
		</div>

</div>

				</div>
			
		</div>
	
				        	</div>
			
			<span class="clr-md"></span>
			
        	<div class="sm10 md5 lg33">
	        					
		<div class="module lst p10">
			
						
				<div class="module-content">
				
<!-- List-Image-First -->





	<div class="module-head">
			
						<h3 class="module-title module-link">
				
								
				<a href="/oikonomia">
					Οικονομία				</a>
				
							</h3>
				
				</div>
	


<div class="news-items" id="m-127">

	<div class="items-block">
	 
	
		<div class="item-block on-title cd-md on-pic w10">
		
						
			
						<div class="item-media">
				<a class="item-image-link" href="/oikonomia/story/122268/desmeysi-xoyliaraki-gia-apopliromi-ton-fesion-toy-dimosioy-eos-ton-aygoysto">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/19/122268/thumb/4409337.jpg" alt="Δέσμευση Χουλιαράκη για αποπληρωμή των φεσιών του Δημοσίου έως τον Αύγουστο " />
					
																				</a>
			</div>
						
						
						
						<h3 class="item-title">
				<a href="/oikonomia/story/122268/desmeysi-xoyliaraki-gia-apopliromi-ton-fesion-toy-dimosioy-eos-ton-aygoysto">
				Δέσμευση Χουλιαράκη για αποπληρωμή των φεσιών του Δημοσίου έως τον Αύγουστο 								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
	 
	
		<div class="item-block on-title on-title w10">
		
						
			
						
						
						
						<h3 class="item-title">
				<a href="/oikonomia/story/122232/goldman-sachs-pistoliptiki-anavathmisi-tis-ellados-ean-efarmostoyn-oi-metarrythmiseis">
				Goldman Sachs: Πιστοληπτική αναβάθμιση της Ελλάδος εάν εφαρμοστούν οι μεταρρυθμίσεις 								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
	 
	
		<div class="item-block on-title on-title w10">
		
						
			
						
						
						
						<h3 class="item-title">
				<a href="/oikonomia/story/122127/anatropes-se-times-kai-foroys-apo-tis-nees-antikeimenikes">
				Ανατροπές σε τιμές και φόρους από τις νέες αντικειμενικές 								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
		</div>

</div>

				</div>
			
		</div>
	
				        	</div>
        	
        	<span class="clr-lg clr-w"></span>
        	
        	<div class="sm10 md5 lg33">
	        					
		<div class="module lst p10">
			
						
				<div class="module-content">
				
<!-- List-Image-First -->





	<div class="module-head">
			
						<h3 class="module-title module-link">
				
								
				<a href="/tech">
					Tech				</a>
				
							</h3>
				
				</div>
	


<div class="news-items" id="m-157">

	<div class="items-block">
	 
	
		<div class="item-block on-title cd-md on-pic w10">
		
						
			
						<div class="item-media">
				<a class="item-image-link" href="/tech/story/122134/to-facebook-zita-sygnomi-poy-mplokare-diasimo-pinaka-toy-ntelakroya">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/19/122134/thumb/2018-01-12T025128Z_1230377957_RC1EF7BEF380_RTRMADP_3_FACEBOOK-NEWSFEED.JPG" alt="Το Facebook ζητά συγνώμη που μπλόκαρε διάσημο πίνακα του Ντελακρουά " />
					
																				</a>
			</div>
						
						
						
						<h3 class="item-title">
				<a href="/tech/story/122134/to-facebook-zita-sygnomi-poy-mplokare-diasimo-pinaka-toy-ntelakroya">
				Το Facebook ζητά συγνώμη που μπλόκαρε διάσημο πίνακα του Ντελακρουά 								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
	 
	
		<div class="item-block on-title on-title w10">
		
						
			
						
						
						
						<h3 class="item-title">
				<a href="/news/kosmos/story/122140/thema-evdomadon-i-ptosi-toy-tiangkongk-1-sti-gi-h-ellada-sti-zoni-ptosis-toy">
				Η Ελλάδα ανάμεσα στις περιοχές που ενδέχεται να πέσει ο κινεζικός διαστημικός σταθμός								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
	 
	
		<div class="item-block on-title on-title w10">
		
						
			
						
						
						
						<h3 class="item-title">
				<a href="/tech/story/122115/me-drones-tha-parakoloythoyn-tis-sodeies-toys-oi-agrotes-tis-karditsas">
				Με… drones θα παρακολουθούν τις σοδειές τους οι αγρότες της Καρδίτσας 								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
		</div>

</div>

				</div>
			
		</div>
	
				        	</div>
        	
			<span class="clr-md"></span>
        	
        	<div class="sm10 md5 lg33">
	        					
		<div class="module lst p10 on-pic">
			
						
				<div class="module-content">
				
<!-- List-Image-First -->





	<div class="module-head">
			
						<h3 class="module-title module-link">
				
								
				<a href="http://www.cnn.gr/news/viral">
					Viral				</a>
							</h3>
				
				</div>
	


<div class="news-items" id="m-158">

	<div class="items-block">
	 
	
		<div class="item-block on-title cd-md on-pic w10">
		
						
			
						<div class="item-media">
				<a class="item-image-link" href="/news/kosmos/story/122045/treno-fantasma-ekane-stasi-se-stathmo-tis-kinas">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/18/122045/thumb/train-3168728_1920.jpg" alt="Τρένο… φάντασμα έκανε «στάση» σε σταθμό της Κίνας" />
					
																				</a>
			</div>
						
						
						
						<h3 class="item-title">
				<a href="/news/kosmos/story/122045/treno-fantasma-ekane-stasi-se-stathmo-tis-kinas">
				Τρένο… φάντασμα έκανε «στάση» σε σταθμό της Κίνας (vid)								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
	 
	
		<div class="item-block on-title on-title w10">
		
						
			
						
						
						
						<h3 class="item-title">
				<a href="/news/kosmos/story/122030/o-mparak-ompama-mesa-apo-ta-matia-toy-fotografoy-toy">
				Ο Μπαράκ Ομπάμα μέσα από τα... μάτια του φωτογράφου του								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
	 
	
		<div class="item-block on-title on-title w10">
		
						
			
						
						
						
						<h3 class="item-title">
				<a href="/news/kosmos/story/122083/h-peripeteia-toy-homer-simpson-me-tin-astynomia-sti-vretania">
				Η περιπέτεια του «Ηomer Simpson» με την αστυνομία στη Βρετανία (pic) 								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
		</div>

</div>

				</div>
			
		</div>
	
				        	</div>
        	
        	<div class="sm10 md5 lg33">
	        	<div id="app-banner-rectangle-2-0" class="ad-unit"></div>
        	</div>
        	
			<span class="clr-md"></span>
        	<span class="clr-lg clr-w"></span>
        	
        	<div class="sm10 md5 lg33">
	        					
		<div class="module lst p10">
			
						
				<div class="module-content">
				
<!-- List-Image-First -->





	<div class="module-head">
			
						<h3 class="module-title module-link">
				
								
				<a href="/news/sports">
					Sport				</a>
				
							</h3>
				
				</div>
	


<div class="news-items" id="m-223">

	<div class="items-block">
	 
	
		<div class="item-block on-title cd-md on-pic w10">
		
						
			
						<div class="item-media">
				<a class="item-image-link" href="/news/sports/story/122230/poini-afairesis-vathmon-ston-panathinaiko">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/19/122230/thumb/4177534.jpg" alt="Ποινή αφαίρεσης βαθμών στον Παναθηναϊκό" />
					
																				</a>
			</div>
						
						
						
						<h3 class="item-title">
				<a href="/news/sports/story/122230/poini-afairesis-vathmon-ston-panathinaiko">
				Ποινή αφαίρεσης βαθμών στον Παναθηναϊκό								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
	 
	
		<div class="item-block on-title on-title w10">
		
						
			
						
						
						
						<h3 class="item-title">
				<a href="/news/sports/story/122264/moyntial-2018-h-vrazilia-tha-kanei-proetoimasia-sto-londino">
				Μουντιάλ 2018: Η Βραζιλία θα κάνει προετοιμασία στο Λονδίνο								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
	 
	
		<div class="item-block on-title on-title w10">
		
						
			
						
						
						
						<h3 class="item-title">
				<a href="/news/sports/story/122137/hmimarathonios-athinas-entyposiase-i-12xroni-athlitria-glykeria-skagkoy">
				Γλυκερία Σκάγκου, η 12χρονη που «έκλεψε» τις εντυπώσεις στον Ημιμαραθώνιο της Αθήνας								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
		</div>

</div>

				</div>
			
		</div>
	
				        	</div>
        	
    	
        	<div class="sm10 md5 lg33">
	        					
		<div class="module lst p10">
			
						
				<div class="module-content">
				
<!-- List-Image-First -->





	<div class="module-head">
			
						<h3 class="module-title module-link">
				
								
				<a href="/style/aytokinito">
					Αυτοκίνητο				</a>
				
							</h3>
				
				</div>
	


<div class="news-items" id="m-228">

	<div class="items-block">
	 
	
		<div class="item-block on-title cd-md on-pic w10">
		
						
			
						<div class="item-media">
				<a class="item-image-link" href="/style/aytokinito/story/122136/to-kainoyrgio-ford-fiesta-st-exei-200-ippoys-apo-1-500-kyvika">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/19/122136/thumb/FORD_2018_FIESTA_ST__08.jpg" alt="Το καινούργιο Ford Fiesta ST έχει 200 ίππους από 1.500 κυβικά" />
					
																				</a>
			</div>
						
						
						
						<h3 class="item-title">
				<a href="/style/aytokinito/story/122136/to-kainoyrgio-ford-fiesta-st-exei-200-ippoys-apo-1-500-kyvika">
				Το καινούργιο Ford Fiesta ST έχει 200 ίππους από 1.500 κυβικά								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
	 
	
		<div class="item-block on-title on-title w10">
		
						
			
						
						
						
						<h3 class="item-title">
				<a href="/style/aytokinito/story/122056/to-e-tron-quattro-to-proto-ilektriko-suv-tis-audi-tha-poleitai-apo-to-fthinoporo">
				To Ε-Tron quattro, το πρώτο ηλεκτρικό SUV της Audi, θα πωλείται από το φθινόπωρο								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
	 
	
		<div class="item-block on-title on-title w10">
		
						
			
						
						
						
						<h3 class="item-title">
				<a href="/style/aytokinito/story/121950/h-maybach-s-650-pullman-ton-6-50-metron-einai-i-pio-polytelis-mercedes">
				H Maybach S 650 Pullman των 6,50 μέτρων είναι η πιο πολυτελής διαθέσιμη Mercedes 								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
		</div>

</div>

				</div>
			
		</div>
	
				        	</div>
        	
			<span class="clr-md"></span>
			
        	<div class="sm10 md5 lg33">
	        					
		<div class="module lst p10">
			
						
				<div class="module-content">
				
<!-- List-Image-First -->





	<div class="module-head">
			
						<h3 class="module-title module-link">
				
								
				<a href="http://www.cnn.gr/taksidi/featured">
					Ταξίδι				</a>
							</h3>
				
				</div>
	


<div class="news-items" id="m-230">

	<div class="items-block">
	 
	
		<div class="item-block on-title cd-md on-pic w10">
		
						
			
						<div class="item-media">
				<a class="item-image-link" href="/taksidi/protaseis/story/122166/oi-kalyteres-apodraseis-gia-giogka-kai-dialogismo-stin-ellada">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/19/122166/thumb/1.jpg" alt="Οι καλύτερες αποδράσεις για γιόγκα και διαλογισμό στην Ελλάδα" />
					
																				</a>
			</div>
						
						
						
						<h3 class="item-title">
				<a href="/taksidi/protaseis/story/122166/oi-kalyteres-apodraseis-gia-giogka-kai-dialogismo-stin-ellada">
				Οι καλύτερες αποδράσεις για γιόγκα και διαλογισμό στην Ελλάδα								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
	 
	
		<div class="item-block on-title on-title w10">
		
						
			
						
						
						
						<h3 class="item-title">
				<a href="/taksidi/protaseis/story/121935/taxideyoyme-gia-savvatokyriako-stin-florentia">
				Ταξιδεύουμε για Σαββατοκύριακο στην Φλωρεντία								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
	 
	
		<div class="item-block on-title on-title w10">
		
						
			
						
						
						
						<h3 class="item-title">
				<a href="/taksidi/protaseis/story/121639/volta-stis-ypaithries-agores-ton-vryxellon">
				Βόλτα στις υπαίθριες αγορές των Βρυξελλών								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
		</div>

</div>

				</div>
			
		</div>
	
				        	</div>
        	
        	<span class="clr-lg clr-w"></span>
        	
        	<div class="sm10 md5 lg33">
	        					
		<div class="module lst p10">
			
						
				<div class="module-content">
				
<!-- List-Image-First -->





	<div class="module-head">
			
						<h3 class="module-title">
				Περιβάλλον			</h3>
				</div>
	


<div class="news-items" id="m-953">

	<div class="items-block">
	 
	
		<div class="item-block on-title cd-md on-pic w10">
		
						
			
						<div class="item-media">
				<a class="item-image-link" href="/news/kosmos/story/122179/aystraloi-pithanon-na-anagkastoyn-na-pinoyn-anakyklomeno-nero">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/19/122179/thumb/water-2586392_1920.jpg" alt="Αυστραλοί πιθανόν να αναγκαστούν να πίνουν ανακυκλωμένο νερό" />
					
																				</a>
			</div>
						
						
						
						<h3 class="item-title">
				<a href="/news/kosmos/story/122179/aystraloi-pithanon-na-anagkastoyn-na-pinoyn-anakyklomeno-nero">
				Αυστραλοί πιθανόν να αναγκαστούν να πίνουν ανακυκλωμένο νερό								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
		</div>

</div>

				</div>
			
		</div>
	
				        	</div>
        	
        	<span class="clr-md"></span>
        	
    	
        	<div class="sm10 md5 lg33">
	        					
		<div class="module lst p10">
			
						
				<div class="module-content">
				
<!-- List-Image-First -->





	<div class="module-head">
			
						<h3 class="module-title">
				Sponsored			</h3>
				</div>
	


<div class="news-items" id="m-954">

	<div class="items-block">
	 
	
		<div class="item-block on-title cd-md on-pic w10">
		
						
			
						<div class="item-media">
				<a class="item-image-link" href="/oikonomia/epixeiriseis/story/121628/agt-taxytata-anaptyssomeni-kai-ektos-synoron">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/15/121628/thumb/BULDING.jpg" alt="AGT: «Ταχύτατα αναπτυσσόμενη και εκτός συνόρων»" />
					
																				</a>
			</div>
						
						
						
						<h3 class="item-title">
				<a href="/oikonomia/epixeiriseis/story/121628/agt-taxytata-anaptyssomeni-kai-ektos-synoron">
				AGT: «Ταχύτατα αναπτυσσόμενη και εκτός συνόρων»								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
		</div>

</div>

				</div>
			
		</div>
	
				        	</div>
        	
			
        	<div class="sm10 md5 lg33">
	        					
		<div class="module lst p10">
			
						
				<div class="module-content">
				
<!-- List-Image-First -->





	<div class="module-head">
			
						<h3 class="module-title">
				Sponsored 			</h3>
				</div>
	


<div class="news-items" id="m-955">

	<div class="items-block">
	 
	
		<div class="item-block on-title cd-md on-pic w10">
		
						
			
						<div class="item-media">
				<a class="item-image-link" href="/news/ellada/story/122226/altion-h-nea-seira-sympliromaton-diatrofis-apo-ti-vianex-vian">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/19/122226/thumb/altion-proionta.png" alt="Altion: Η νέα σειρά συμπληρωμάτων διατροφής από τη ΒΙΑΝΕΞ/ΒΙΑΝ" />
					
																				</a>
			</div>
						
						
						
						<h3 class="item-title">
				<a href="/news/ellada/story/122226/altion-h-nea-seira-sympliromaton-diatrofis-apo-ti-vianex-vian">
				Altion: Η νέα σειρά συμπληρωμάτων διατροφής από τη ΒΙΑΝΕΞ/ΒΙΑΝ								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>	
		</div>

</div>

				</div>
			
		</div>
	
				        	</div>
        	
        	
        	<span class="clr"></span>
        	
        </div>
        
	</div>
	
</div>






<div class="zone content-zone theme-bright">


	<div class="screen">       
        
        <div class="row section">
	        
	        
	        <div class="section-header p10">
				<h2 class="section-title lines">Δείτε</h2>
			</div>
			
			
		<div class="module grid p10 on-pic">
			
						
				<div class="module-content">
				
<!-- List-Image-First -->





	<div class="module-head">
			
						<h3 class="module-title module-link">
				
								
				<a href="/videos">
					Videos				</a>
				
							</h3>
				
				</div>
	


<div class="news-items" id="m-136">

	<div class="items-block grid">
	 
	
		<div class="item-block p10 md5 odd-block w25">
			
							
						<div class="item-media">
				<a class="item-image-link" href="/viral/video/9627/star-wars-galaxy-s-edge-enaeria-xenagisi-sto-neo-parko-tis-ntisneilant">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/18/122095/thumb/Disney.PNG" alt="Star Wars – Galaxy’s Edge: Εναέρια ξενάγηση στο νέο πάρκο της Ντίσνεϊλαντ " />
					<span class="icon icon-media-video"><i data-text="00:57"></i></span>				</a>
			</div>
						
						
						<h3 class="item-title">
				<a href="/viral/video/9627/star-wars-galaxy-s-edge-enaeria-xenagisi-sto-neo-parko-tis-ntisneilant">
				Star Wars – Galaxy’s Edge: Εναέρια ξενάγηση στο νέο πάρκο της Ντίσνεϊλαντ 				<span class="icon icon-media-video"><i data-text="00:57"></i></span>				</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	
		
	 
	
		<div class="item-block p10 md5 even-block w25">
			
							
						<div class="item-media">
				<a class="item-image-link" href="/viral/video/9626/monaxo-giati-serfer-ap-olo-ton-kosmo-syrreoyn-stin-kardia-tis-eyropis">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/18/122073/thumb/surfen-eisbach-02.jpg" alt="Μόναχο: Γιατί σέρφερ απ&#039; όλο τον κόσμο συρρέουν στην «καρδιά» της Ευρώπης; " />
					<span class="icon icon-media-video"><i data-text="01:13"></i></span>				</a>
			</div>
						
						
						<h3 class="item-title">
				<a href="/viral/video/9626/monaxo-giati-serfer-ap-olo-ton-kosmo-syrreoyn-stin-kardia-tis-eyropis">
				Μόναχο: Γιατί σέρφερ απ' όλο τον κόσμο συρρέουν στην «καρδιά» της Ευρώπης; 				<span class="icon icon-media-video"><i data-text="01:13"></i></span>				</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	
	<div class="clr-lg clr-md"></div>	
	 
	
		<div class="item-block p10 md5 odd-block w25">
			
							
						<div class="item-media">
				<a class="item-image-link" href="/viral/video/9625/enas-lykos-prostatis-ton-agroton">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/18/122053/thumb/Wolf.PNG" alt="Ένας λύκος «προστάτης» των αγροτών " />
					<span class="icon icon-media-video"><i data-text="01:24"></i></span>				</a>
			</div>
						
						
						<h3 class="item-title">
				<a href="/viral/video/9625/enas-lykos-prostatis-ton-agroton">
				Ένας λύκος «προστάτης» των αγροτών 				<span class="icon icon-media-video"><i data-text="01:24"></i></span>				</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	
		
	 
	
		<div class="item-block p10 md5 even-block w25">
			
							
						<div class="item-media">
				<a class="item-image-link" href="/reportaz/video/9621/xenia-somptsak-h-paris-xilton-tis-rosias-ta-vazei-me-ton-vlantimir-poytin">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/17/121996/thumb/2018-03-05T102856Z_2088038529_UP1EE350T480E_RTRMADP_3_RUSSIA-ELECTION.JPG" alt="Ξένια Σομπτσάκ: Η «Πάρις Χίλτον» της Ρωσίας τα βάζει με τον Βλαντιμίρ Πούτιν " />
					<span class="icon icon-media-video"><i data-text="01:19"></i></span>				</a>
			</div>
						
						
						<h3 class="item-title">
				<a href="/reportaz/video/9621/xenia-somptsak-h-paris-xilton-tis-rosias-ta-vazei-me-ton-vlantimir-poytin">
				Ξένια Σομπτσάκ: Η «Πάρις Χίλτον» της Ρωσίας τα βάζει με τον Βλαντιμίρ Πούτιν 				<span class="icon icon-media-video"><i data-text="01:19"></i></span>				</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>
		
	 
	
		<div class="item-block p10 md5 odd-block w25">
			
							
						<div class="item-media">
				<a class="item-image-link" href="/viral/video/9620/polytaxidemenos-kata-lathos-apo-to-oregkon-sto-kansas-meso-tokio">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/17/121960/thumb/dog.PNG" alt="Πολυταξιδεμένος κατά λάθος: Από το Όρεγκον στο Κάνσας μέσω… Τόκιο" />
					<span class="icon icon-media-video"><i data-text="01:19"></i></span>				</a>
			</div>
						
						
						<h3 class="item-title">
				<a href="/viral/video/9620/polytaxidemenos-kata-lathos-apo-to-oregkon-sto-kansas-meso-tokio">
				Πολυταξιδεμένος κατά λάθος: Από το Όρεγκον στο Κάνσας μέσω… Τόκιο				<span class="icon icon-media-video"><i data-text="01:19"></i></span>				</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	
		
	 
	
		<div class="item-block p10 md5 even-block w25">
			
							
						<div class="item-media">
				<a class="item-image-link" href="/reportaz/video/9619/xaos-se-xionodromiko-kentro-skier-ektoxeyontai-ston-aera-meta-apo-vlavi-se-lift">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/17/121947/thumb/2018-03-16T135712Z_325926198_RC164A8AA770_RTRMADP_3_GEORGIA-ACCIDENT-SKI-LIFT.JPG" alt="Χάος σε χιονοδρομικό κέντρο: Σκιέρ εκτοξεύονται στον αέρα μετά από βλάβη σε λιφτ " />
					<span class="icon icon-media-video"><i data-text="01:27"></i></span>				</a>
			</div>
						
						
						<h3 class="item-title">
				<a href="/reportaz/video/9619/xaos-se-xionodromiko-kentro-skier-ektoxeyontai-ston-aera-meta-apo-vlavi-se-lift">
				Χάος σε χιονοδρομικό κέντρο: Σκιέρ εκτοξεύονται στον αέρα μετά από βλάβη σε λιφτ 				<span class="icon icon-media-video"><i data-text="01:27"></i></span>				</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	
	<div class="clr-lg clr-md"></div>	
	 
	
		<div class="item-block p10 md5 odd-block w25">
			
							
						<div class="item-media">
				<a class="item-image-link" href="/reportaz/video/9616/the-crown-misthologiko-xasma-sto-palati">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/16/121864/thumb/18920071.jpg" alt="The Crown: Μισθολογικό χάσμα στο «Παλάτι»" />
					<span class="icon icon-media-video"><i data-text="01:03"></i></span>				</a>
			</div>
						
						
						<h3 class="item-title">
				<a href="/reportaz/video/9616/the-crown-misthologiko-xasma-sto-palati">
				The Crown: Μισθολογικό χάσμα στο «Παλάτι»				<span class="icon icon-media-video"><i data-text="01:03"></i></span>				</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	
		
	 
	
		<div class="item-block p10 md5 even-block w25">
			
							
						<div class="item-media">
				<a class="item-image-link" href="/reportaz/video/9617/katarreysi-pezogefyras-exi-meres-meta-tin-kataskeyi-tis">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/16/121840/thumb/2018-03-15T223829Z_1358992825_RC14422201E0_RTRMADP_3_FLORIDA-BRIDGE.JPG" alt="Κατάρρευση πεζογέφυρας στο Μαϊάμι, έξι μέρες μετά την κατασκευή της" />
					<span class="icon icon-media-video"><i data-text="01:52"></i></span>				</a>
			</div>
						
						
						<h3 class="item-title">
				<a href="/reportaz/video/9617/katarreysi-pezogefyras-exi-meres-meta-tin-kataskeyi-tis">
				Κατάρρευση πεζογέφυρας στο Μαϊάμι, έξι μέρες μετά την κατασκευή της				<span class="icon icon-media-video"><i data-text="01:52"></i></span>				</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
	
	<div class="clr"></div>
		
		</div>

</div>

				</div>
			
		</div>
	
			
        	<div class="main-pack">
	        	
	        	<div class="main">
			        						
		<div class="module lst p10 on-pic">
			
						
				<div class="module-content">
				
<!-- List-Image-First -->





	<div class="module-head">
			
						<h3 class="module-title">
				Εικόνες			</h3>
				</div>
	


<div class="news-items" id="m-137">

	<div class="items-block grid">
	 
	
		<div class="item-block p10 sm33 odd-block w33">
			
							
						<div class="item-media">
				<a class="item-image-link" href="/style/moda/gallery/6822/faroyk-tis-aigyptoy-xiliades-dolaria-gia-to-syllektiko-roloi-toy-vasilia">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/19/122198/thumb/2018-03-19T114210Z_1977678260_RC12985EB7E0_RTRMADP_3_DUBAI-AUCTION-PATEK.JPG" alt="Φαρούκ της Αιγύπτου: χιλιάδες δολάρια για το συλλεκτικό ρολόι του βασιλιά" />
					<span class="icon icon-media-gallery"></span>				</a>
			</div>
						
			<div class="item-badged">
				
									<span class="icon icon-media-gallery"></span>									
			
								
								<h3 class="item-title">
					<a href="/style/moda/gallery/6822/faroyk-tis-aigyptoy-xiliades-dolaria-gia-to-syllektiko-roloi-toy-vasilia">
					Φαρούκ της Αιγύπτου: χιλιάδες δολάρια για το συλλεκτικό ρολόι του βασιλιά					<span class="icon icon-media-gallery"></span>					</a>
				</h3>
								
								
								
								
								
								
							
			</div>
			
			
		</div>
	
		
	 
	
		<div class="item-block p10 sm33 even-block w33">
			
							
						<div class="item-media">
				<a class="item-image-link" href="/news/kosmos/gallery/6812/uss-iwo-jima-sti-lemeso-to-megalytero-amfivio-polemiko-ploio-ston-kosmo">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/19/122146/thumb/87570841.jpg" alt="USS Iwo Jima: Στη Λεμεσό το μεγαλύτερο αμφίβιο πολεμικό πλοίο στον κόσμο" />
					<span class="icon icon-media-gallery"></span>				</a>
			</div>
						
			<div class="item-badged">
				
									<span class="icon icon-media-gallery"></span>									
			
								
								<h3 class="item-title">
					<a href="/news/kosmos/gallery/6812/uss-iwo-jima-sti-lemeso-to-megalytero-amfivio-polemiko-ploio-ston-kosmo">
					USS Iwo Jima: Στη Λεμεσό το μεγαλύτερο αμφίβιο πολεμικό πλοίο στον κόσμο					<span class="icon icon-media-gallery"></span>					</a>
				</h3>
								
								
								
								
								
								
							
			</div>
			
			
		</div>
	
		
	 
	
		<div class="item-block p10 sm33 odd-block w33">
			
							
						<div class="item-media">
				<a class="item-image-link" href="/style/politismos/gallery/6766/moyseio-mpenaki-i-athina-toy-tote-prosgeionetai-sto-eleytherios-venizelos">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/16/121835/thumb/3813.jpg" alt="Μουσείο Μπενάκη: η Αθήνα του τότε προσγειώνεται στο Ελευθέριος Βενιζέλος" />
					<span class="icon icon-media-gallery"></span>				</a>
			</div>
						
			<div class="item-badged">
				
									<span class="icon icon-media-gallery"></span>									
			
								
								<h3 class="item-title">
					<a href="/style/politismos/gallery/6766/moyseio-mpenaki-i-athina-toy-tote-prosgeionetai-sto-eleytherios-venizelos">
					Μουσείο Μπενάκη: η Αθήνα του τότε προσγειώνεται στο Ελευθέριος Βενιζέλος					<span class="icon icon-media-gallery"></span>					</a>
				</h3>
								
								
								
								
								
								
							
			</div>
			
			
		</div>
	
	<div class="clr"></div>	
	 
	
		<div class="item-block p10 sm33 even-block w33">
			
							
						<div class="item-media">
				<a class="item-image-link" href="/news/kosmos/gallery/6748/eikosi-efeyreseis-poy-allaxan-ton-kosmo-apo-anthropoys-kato-ton-20">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/15/121745/thumb/type.jpg" alt="Είκοσι εφευρέσεις που άλλαξαν τον κόσμο από ανθρώπους κάτω των 20 " />
					<span class="icon icon-media-gallery"></span>				</a>
			</div>
						
			<div class="item-badged">
				
									<span class="icon icon-media-gallery"></span>									
			
								
								<h3 class="item-title">
					<a href="/news/kosmos/gallery/6748/eikosi-efeyreseis-poy-allaxan-ton-kosmo-apo-anthropoys-kato-ton-20">
					Είκοσι εφευρέσεις που άλλαξαν τον κόσμο από ανθρώπους κάτω των 20 					<span class="icon icon-media-gallery"></span>					</a>
				</h3>
								
								
								
								
								
								
							
			</div>
			
			
		</div>
	
		
	 
	
		<div class="item-block p10 sm33 odd-block w33">
			
							
						<div class="item-media">
				<a class="item-image-link" href="/style/moda/gallery/6730/kim-karntasian-i-nea-synetairos-tis-mantona-anadyetai-sto-elle">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/14/121543/thumb/kim3.jpg" alt="Κιμ Καρντάσιαν: η νέα συνέταιρος της Μαντόνα αναδύεται στο ELLE" />
					<span class="icon icon-media-gallery"></span>				</a>
			</div>
						
			<div class="item-badged">
				
									<span class="icon icon-media-gallery"></span>									
			
								
								<h3 class="item-title">
					<a href="/style/moda/gallery/6730/kim-karntasian-i-nea-synetairos-tis-mantona-anadyetai-sto-elle">
					Κιμ Καρντάσιαν: η νέα συνέταιρος της Μαντόνα αναδύεται στο ELLE					<span class="icon icon-media-gallery"></span>					</a>
				</h3>
								
								
								
								
								
								
							
			</div>
			
			
		</div>
	
		
	 
	
		<div class="item-block p10 sm33 even-block w33">
			
							
						<div class="item-media">
				<a class="item-image-link" href="/style/moda/gallery/6709/ekthesi-kosmimaton-empneysmeni-apo-ta-synora-hpa-mexikoy-oxyronei-ti-nea-yorki">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/13/121368/thumb/front1.jpg" alt="Έκθεση κοσμημάτων εμπνευσμένη από τα σύνορα ΗΠΑ-Μεξικού «οχυρώνει» τη Νέα Υόρκη" />
					<span class="icon icon-media-gallery"></span>				</a>
			</div>
						
			<div class="item-badged">
				
									<span class="icon icon-media-gallery"></span>									
			
								
								<h3 class="item-title">
					<a href="/style/moda/gallery/6709/ekthesi-kosmimaton-empneysmeni-apo-ta-synora-hpa-mexikoy-oxyronei-ti-nea-yorki">
					Έκθεση κοσμημάτων εμπνευσμένη από τα σύνορα ΗΠΑ-Μεξικού «οχυρώνει» τη Νέα Υόρκη					<span class="icon icon-media-gallery"></span>					</a>
				</h3>
								
								
								
								
								
								
							
			</div>
			
			
		</div>
	
	<div class="clr"></div>	
		</div>

</div>

				</div>
			
		</div>
	
						        	</div>
	        	
	        	<div class="side">
		        	
		        	<div class="sm10 md10 lg10">
			        	
					<div id="app-banner-rectangle-3-0" class="ad-unit"></div>
		        	</div>
		        	
	        	</div>
        	
        	</div>
        	<div class="clr"></div>
        </div>
	</div>
	
</div>





<div class="zone content-zone theme-bright">
	<div class="screen">        
        
        <div class="row section section-space">
	        
	        <div class="section-header p10">
				<h2 class="section-title lines">Δίκτυο</h2>
			</div>
	        	
        	<div class="sm10 md33">
	        					
		<div class="module lst p10">
			
						
				<div class="module-content">
				
<!-- List-Image-First -->






	<div class="module-head">
			
		<h3 class="module-title module-link">
			
			<a href="http://www.newsbomb.gr/ellada/ethnika/story/869899/entyposiakes-eikones-apo-tin-ptisi-maxitikon-aeroskafon-pano-apo-tin-athina" target="_blank">
				Εντυπωσιακές εικόνες από την πτήση μαχητικών αεροσκαφών πάνω από την Αθήνα			</a>
		</h3>
	</div>




<div class="news-items" id="m-106">

	<div class="items-block">
		
			
		
			
		<div class="item-block  even-block w10">
		
			
						
						<h3 class="item-title">
				<a href="http://www.newsbomb.gr/ellada/news/story/869883/h-sygkinitiki-kinisi-ton-gonion-toy-loxia-poy-krateitai-stin-adrianoypoli-pics" target="_blank">
				Η συγκινητική κίνηση των γονιών του λοχία που κρατείται στην Αδριανούπολη (pics)								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
			
		
			
		<div class="item-block  odd-block w10">
		
			
						
						<h3 class="item-title">
				<a href="http://www.newsbomb.gr/ellada/news/story/869782/poy-vrisketai-o-tafos-toy-megaloy-alexandroy-ereynitis-dilonei-oti-gnorizei-100" target="_blank">
				Πού βρίσκεται ο τάφος του Μεγάλου Αλεξάνδρου - Ερευνητής δηλώνει ότι γνωρίζει «100%»								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
			
		
			
		<div class="item-block  even-block w10">
		
			
						
						<h3 class="item-title">
				<a href="http://www.newsbomb.gr/ellada/news/story/869868/mploko-antiexoysiaston-sto-gkise-tis-turkish-airlines-sto-makedonia-vid" target="_blank">
				Μπλόκο αντιεξουσιαστών στο γκισέ της Turkish Airlines στο «Μακεδονία» (vid)								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
			
		
			
		<div class="item-block  odd-block w10">
		
			
						
						<h3 class="item-title">
				<a href="http://www.newsbomb.gr/kypros/story/869811/stin-kypro-to-iwo-jima-toy-6oy-stoloy-ton-hpa" target="_blank">
				Στην Κύπρο το «Iwo Jima» του 6ου στόλου των ΗΠΑ								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
			
		</div>

</div>

				</div>
			
		</div>
	
				        	</div>
    	
        	<div class="sm10 md33">
	        					
		<div class="module lst p10">
			
						
				<div class="module-content">
				
<!-- List-Image-First -->






	<div class="module-head">
			
		<h3 class="module-title module-link">
			
			<a href="http://www.queen.gr/juicy/juicy-news/story/154808/h-nea-kinisi-toy-prigkipa-harry-ligo-prin-to-gamo-tha-syzitithei-sigoyra" target="_blank">
				Η νέα κίνηση του πρίγκιπα Harry λίγο πριν το γάμο, θα συζητηθεί σίγουρα			</a>
		</h3>
	</div>




<div class="news-items" id="m-130">

	<div class="items-block">
		
			
		
			
		<div class="item-block  even-block w10">
		
			
						
						<h3 class="item-title">
				<a href="http://www.queen.gr/moda/symvoules-modas/story/154641/pente-pragmata-poy-den-ixeres-gia-to-plysimo-ton-jeans-soy" target="_blank">
				Πέντε πράγματα που δεν ήξερες για το πλύσιμο των jeans σου								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
			
		
			
		<div class="item-block  odd-block w10">
		
			
						
						<h3 class="item-title">
				<a href="http://www.gossip-tv.gr/media-tv/story/531021/power-of-love-aytos-einai-o-neos-paiktis-pos-antedrasan-oi-gynaikes" target="_blank">
				Power of love: Αυτός είναι ο νέος παίκτης – Πώς αντέδρασαν οι γυναίκες;								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
			
		
			
		<div class="item-block  even-block w10">
		
			
						
						<h3 class="item-title">
				<a href="http://www.gossip-tv.gr/media-tv/story/531016/survivor-2-h-apisteyti-anatropi-deite-ti-nea-anakoinosi-toy-tanimanidi-stoys-paiktes" target="_blank">
				Survivor 2: Η απίστευτη ανατροπή - Δείτε τη νέα ανακοίνωση του Τανιμανίδη στους παίκτες								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
			
		
			
		<div class="item-block  odd-block w10">
		
			
						
						<h3 class="item-title">
				<a href="https://www.mothersblog.gr/paidi/psyxologia/story/55421/mporoyme-na-voithisoyme-ta-paidia-mas-na-epilexoyn-sostoys-filoys" target="_blank">
				Μπορούμε να βοηθήσουμε τα παιδιά μας να επιλέξουν «σωστούς» φίλους;								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
			
		</div>

</div>

				</div>
			
		</div>
	
				        	</div>
    	
        	<div class="sm10 md33">
	        					
		<div class="module lst p10">
			
						
				<div class="module-content">
				
<!-- List-Image-First -->






	<div class="module-head">
			
		<h3 class="module-title module-link">
			
			<a href="https://www.onsports.gr/podosfairo/story/592122/tromero-pateras-erixe-mpoynies-se-proponiti-se-paidiko-protathlima-video" target="_blank">
				Τρομερό! Πατέρας έριξε μπουνιές σε προπονητή σε παιδικό πρωτάθλημα! (video)			</a>
		</h3>
	</div>




<div class="news-items" id="m-131">

	<div class="items-block">
		
			
		
			
		<div class="item-block  even-block w10">
		
			
						
						<h3 class="item-title">
				<a href="https://www.onsports.gr/podosfairo/superleague/story/592123/xespasma-prigiovits-gia-to-paok-aek-aytos-ftaiei-photo" target="_blank">
				Ξέσπασμα Πρίγιοβιτς για το ΠΑΟΚ-ΑΕΚ: «Αυτός φταίει»! (photo)								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
			
		
			
		<div class="item-block  odd-block w10">
		
			
						
						<h3 class="item-title">
				<a href="https://www.onmed.gr/ygeia/story/365098/karkinos-sto-pagkreas-7-agnosta-symptomata-toy-pio-thanatiforoy-karkinoy" target="_blank">
				Καρκίνος στο πάγκρεας: 7 άγνωστα συμπτώματα του πιο θανατηφόρου καρκίνου (φωτο)								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
			
		
			
		<div class="item-block  even-block w10">
		
			
						
						<h3 class="item-title">
				<a href="https://www.onmed.gr/ygeia/story/365102/giati-oi-andres-prepei-na-apofeygoyn-ta-aitheria-elaia" target="_blank">
				Γιατί οι άνδρες πρέπει να αποφεύγουν τα αιθέρια έλαια								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
			
		
			
		<div class="item-block  odd-block w10">
		
			
						
						<h3 class="item-title">
				<a href="http://www.astrology.gr/zodia/enallaktiki-gonia/story/105037/ti-apokalyptei-to-sxima-ton-nyxion-soy-gia-to-xaraktira-soy" target="_blank">
				Τι αποκαλύπτει το σχήμα των νυχιών σου για το χαρακτήρα σου;								</a>
			</h3>
						
						
						
						
						
						
						
			
		</div>
			
		</div>

</div>

				</div>
			
		</div>
	
				        	</div>
        	
        	
        </div>
        
        
	</div>
</div>


<div class="zone content-zone theme-dark">
	<div class="screen">
		<div class="row section section-space">
	        
	        <div class="section-header p10">
				<h2 class="section-title lines">Αξίζουν</h2>
			</div>
	        	
        	<div class="sm10">
	        					
		<div class="module grid on-title">
			
						
				<div class="module-content">
				
<!-- List-Image-First -->




<div class="lg6 p10">
	<div class="module-head">
			
						<h3 class="module-title">
				Μην το χάσετε			</h3>
				</div>
		
	
	
		
		<div class="item-block cd-lg">
		
					
			
						<div class="item-media">
				<a class="item-image-link" href="/focus/story/121818/analytis-ntanforth-o-tropos-poy-epidiokei-rolo-i-toyrkia-kanei-to-endexomeno-atyximatos-tromaktiko">
					<img class="item-image" src="http://cdn.cnngreece.gr/media/com_news/story/2018/03/16/121818/main/turkey-crowd.jpeg" alt="Αναλυτής Ντάνφορθ: Ο τρόπος που επιδιώκει ρόλο η Τουρκία κάνει το ενδεχόμενο ατυχήματος τρομακτικό" />
									</a>
			</div>
						
			
			<div class="item-contents">
			
								
								<h3 class="item-title">
					<a href="/focus/story/121818/analytis-ntanforth-o-tropos-poy-epidiokei-rolo-i-toyrkia-kanei-to-endexomeno-atyximatos-tromaktiko">
					Αναλυτής Ντάνφορθ: Ο τρόπος που επιδιώκει ρόλο η Τουρκία κάνει το ενδεχόμενο ατυχήματος τρομακτικό										
					</a>
				</h3>
								
								
								
							
			
			
			</div>
			
	
	</div>
		
</div>



<div class="news-items" id="m-129">

	<div class="items-block lg4 p10">
		
		
			
		
				
		<div class="item-block cd-xs">
			
						
			
						
						
								
								<h3 class="item-title">
					<a href="/news/kosmos/story/121757/syria-epta-xronia-polemoy-kai-to-anthropino-drama-synexizetai">
					Συρία: Επτά χρόνια πολέμου και το ανθρώπινο δράμα συνεχίζεται 										
					</a>
				</h3>
								
								
								
							
			
			
						
			
			
			
		</div>
		
			
		
				
		<div class="item-block cd-xs">
			
						
			
						
						
								
								<h3 class="item-title">
					<a href="/focus/story/121608/engkin-mpas-h-kratisi-ton-ellinon-stratiotikon-stin-toyrkia-sxetizetai-me-tin-ypothesi-ton-oxto">
					Ενγκίν Μπας: Η κράτηση των Ελλήνων στρατιωτικών στην Τουρκία σχετίζεται με την υπόθεση «των οχτώ»										
					</a>
				</h3>
								
								
								
							
			
			
						
			
			
			
		</div>
		
			
		
				
		<div class="item-block cd-xs">
			
						
			
						
						
								
								<h3 class="item-title">
					<a href="/focus/story/121338/ta-kryfa-minymata-piso-apo-deka-pasignosta-logotypa-etairion">
					Τα κρυφά μηνύματα πίσω από δέκα πασίγνωστα λογότυπα εταιριών!										
					</a>
				</h3>
								
								
								
							
			
			
						
			
			
			
		</div>
		
			
		
				
		<div class="item-block cd-xs">
			
						
			
						
						
								
								<h3 class="item-title">
					<a href="/news/prosopa/story/71974/moyaoyigia-siasnex-o-efivos-poy-pyrodotise-ton-emfylio-sti-syria-thymatai-pos-xekinisan-ola">
					Μουαουίγια Σιασνέχ: Ο έφηβος που «πυροδότησε» τον εμφύλιο στη Συρία, θυμάται πώς ξεκίνησαν όλα										
					</a>
				</h3>
								
								
								
							
			
			
						
			
			
			
		</div>
		
			
		
				
		<div class="item-block cd-xs">
			
						
			
						
						
								
								<h3 class="item-title">
					<a href="/focus/story/121139/anatoliki-gkoyta-kai-afrin-proskinio-kai-paraskinio-ton-parallilon-polemon-tis-syrias-pics">
					Ανατολική Γκούτα και Αφρίν: προσκήνιο και παρασκήνιο των παράλληλων πολέμων της Συρίας (pics)										
					</a>
				</h3>
								
								
								
							
			
			
						
			
			
			
		</div>
		
			
		
				
		<div class="item-block cd-xs">
			
						
			
						
						
								
								<h3 class="item-title">
					<a href="/news/kosmos/story/121191/lythike-o-grifos-me-tin-pyli-tis-kolaseos-stin-toyrkia">
					Λύθηκε ο γρίφος με την «Πύλη της Κολάσεως» στην Τουρκία										
					</a>
				</h3>
								
								
								
							
			
			
						
			
			
			
		</div>
		
			
		
				
		<div class="item-block cd-xs">
			
						
			
						
						
								
								<h3 class="item-title">
					<a href="/focus/story/120871/o-anthropos-piso-apo-tis-afises-toy-athinaion">
					Ο άνθρωπος πίσω από τις αφίσες του Αθήναιον										
					</a>
				</h3>
								
								
								
							
			
			
						
			
			
			
		</div>
		
			
		
				
		<div class="item-block cd-xs">
			
						
			
						
						
								
								<h3 class="item-title">
					<a href="/focus/story/120665/to-nakgkorno-karampax-ta-lompi-kai-ena-diethnes-entalma-syllipsis-me-elliniko-xroma">
					To Ναγκόρνο Καραμπάχ, τα λόμπι και ένα διεθνές ένταλμα σύλληψης με ελληνικό χρώμα										
					</a>
				</h3>
								
								
								
							
			
			
						
			
			
			
		</div>
		
			
		</div>

</div>

				</div>
			
		</div>
	
				        	</div>
        	
        </div>
	</div>
</div>

<div class="zone content-zone theme-dark">
	<div class="screen">
		<div class="row section section-space">
			<div id="app-banner-wide-2-0" class="ad-unit"></div>
        </div>
	</div>
</div>

		

		
	
	


	


	


	

	




<div class="footer-zone">
	<div class="footer screen">

		<div class="md5 p10">
			<div class="select-edition">
				<a class="icon icon-logo" href="http://www.cnn.gr/"></a>
		        <ul id="app-page-network-bottom" class="select-list">
			        <li class="toggler select-title">Greek Edition</li>
			        <li>
				        <ul>
					        <li class="select-option"><a href="http://edition.cnn.com/" target="_parent">International</a></li>
					        <li class="select-option"><a href="http://us.cnn.com/" target="_parent">US Edition</a></li>
					        <li class="select-option"><a href="http://arabic.cnn.com/" target="_parent">Arabic</a></li>
				        </ul>
			        </li>
		        </ul>
		    </div>
		</div>

	    <div class="md5 p10">

		     <div class="footer-newsletter">
		    	
<div class="newsletter-form" id="app-module-980-form">
	
	
	
		
	<form action="http://www.cnn.gr/">
		
			<span class="pre-text">
		Όσα συμβαίνουν στην Ελλάδα και τον κόσμο στο email σας.
		Με την εγγραφή σας, συμφωνείτε με τους  <a href="http://www.cnn.gr/terms" target="_blank">Όρους Χρήσης</a>
	</span>
		
			<div id="formFields" class="form-fields">
				
				<div class="input-field">
					<input type="email" name="email" id="jcm-mail" required="required" placeholder="Το email σας" />
				</div>
				
				<button class="button jcm-submit" name="submit" id="start">ΕΓΓΡΑΦΗ</button>
				
			</div>
			
			<div class="clr"></div>
			<div id="form-message" data-messages='{
	"success" : "MOD_MAILCHIMP_SUCCESS",
	"error" : "MOD_MAILCHIMP_MAIL_ENTER_EMAIL"
}' class="response"></div>
			
		
	  
	  <input type="hidden" name="option" value="com_ajax" />
	  <input type="hidden" name="module" value="moosend" />
	  <input type="hidden" name="method" value="subscribe" />
	  <input type="hidden" name="format" value="raw" />
	  <input type="hidden" name="id" value="980" />
	  <input type="hidden" name="Itemid" value="101" />
	  
	</form>
</div>


		    </div>
		    	    </div>

		<div class="p10">
			<div class="lines"></div>
		</div>

		<div class="row">
						<div class="md33">
			
	<div class="xs5">
		<ul class="menu">
			<li class="item-101 parent">
	        	<a href="/">ΕΙΔΗΣΕΙΣ</a>
	        	
	        	<ul class="submenu">
					<li class="item-122"><a href="/news/ellada">ΕΛΛΑΔΑ</a></li>
					<li class="item-187"><a href="/news/politiki">ΠΟΛΙΤΙΚΗ</a></li>
					<li class="item-189"><a href="/news/kosmos">ΚΟΣΜΟΣ</a></li>
					<li class="item-190"><a href="/news/sports">ΣΠΟΡ</a></li>
		         <li class="item-199"><a href="/news/prosopa">ΠΡΟΣΩΠΑ</a></li>
					<li class="item-199"><a href="/news/perivallon">ΠΕΡΙΒΑΛΛΟΝ</a></li>
					<li class="item-404"><a href="/news/viral">VIRAL</a></li>
					<li class="item-229"><a href="/efimerides">ΕΦΗΜΕΡΙΔΕΣ</a></li>
	        	</ul>
	        </li>
		</ul>
	</div>
	
	<div class="xs5">
		<ul class="menu">
		    <li class="item-188 parent">
		        <a href="/videos">VIDEO</a>
	        	
	        	<ul class="submenu">
					<li class="item-191"><a href="/videos/synenteyxeis">ΣΥΝΕΝΤΕΥΞΕΙΣ</a></li>
		            <li class="item-192"><a href="/videos/reportaz">ΡΕΠΟΡΤΑΖ</a></li>
		            		            <li class="item-194"><a href="/videos/viral">VIRAL</a></li>
	        	</ul>
	        </li>
		</ul>
	</div>
	
</div>
<div class="md33">

	<div class="xs5">
		
		<ul class="menu">
		    <li class="item-209 parent"><a href="/focus">FOCUS</a>
		    	<ul class="submenu">
	   				<li class="item-230"><a href="/focus/editorial">EDITORIAL</a></li>
	   				<li class="item-231"><a href="/focus/apopseis">ΑΠΟΨΕΙΣ</a></li>
	   				<li class="item-403"><a href="/focus/explainers">EXPLAINERS</a></li>
		        </ul>
		    </li>

		</ul>
	</div>

	<div class="xs5">
		<ul class="menu">
		    <li class="item-202 parent">
		        <a href="/style">STYLE</a>
	        	
	        	<ul class="submenu">
		            <li class="item-200"><a href="/style/psyxagogia">ΨΥΧΑΓΩΓΙΑ</a></li>
		            <li class="item-203"><a href="/style/politismos">ΠΟΛΙΤΙΣΜΟΣ</a></li>
		            <li class="item-201"><a href="/style/moda">ΜΟΔΑ</a></li>
		            <li class="item-204"><a href="/style/aytokinito">ΑΥΤΟΚΙΝΗΤΟ</a></li>
	        	</ul>
	        </li>
		</ul>
	</div>
	
</div>

<div class="md33">
	<div class="xs5">
		<ul class="menu">
		    <li class="item-205 parent">
		        <a href="/taksidi/featured">ΤΑΞΙΔΙ</a>
						        	
				<ul class="submenu">
		            <li class="item-206"><a href="/taksidi/ellada">ΕΛΛΑΔΑ</a></li>
		            <li class="item-207"><a href="/taksidi/kosmos">ΚΟΣΜΟΣ</a></li>
		            <li class="item-208"><a href="/taksidi/protaseis">ΠΡΟΤΑΣΕΙΣ</a></li>
	        	</ul>
	        </li>
		</ul>
	</div>
	
	<div class="xs5">
		<ul class="menu">
		    <li class="item-195 parent">
		        <a href="/oikonomia">ΟΙΚΟΝΟΜΙΑ</a>
	        	
	        	<ul class="submenu">
		            <li class="item-196"><a href="/oikonomia/agores">ΑΓΟΡΕΣ</a></li>
		            <li class="item-197"><a href="/oikonomia/epixeiriseis">ΕΠΙΧΕΙΡΗΣΕΙΣ</a></li>
		            <li class="item-371"><a href="/oikonomia/insights">INSIGHTS</a></li>
						<li class="item-432"><a href="/oikonomia/business">BUSINESS STORIES</a></li>
	        	</ul>
	        </li>
	        <li class="item-205 parent">
		        <a href="/tech">TECH</a>
	        </li>
		</ul>
	</div>
</div>
			
		</div>


	</div>

	<div class="footer-context screen">



		<div class="lg3 p10 lg-right">
			<div class="site-social rem ">

				<div class="page-share">
					<span class="share-block">
					    <a href="https://www.facebook.com/cnn.greece" class="share-trigger share-facebook" target="_blank">
					        <span class="icon icon-facebook"></span>
					    </a>
					</span>

				    <span class="share-block">
				    	<a href="https://twitter.com/CNNgreece" class="share-trigger share-twitter" target="_blank">
				        	<span class="icon icon-twitter"></span>
				    	</a>
				    </span>

					<span class="share-block">
						<a href="https://www.youtube.com/channel/UCA449AY-qrJsvE7HX8MZVog" class="share-trigger share-youtube" target="_blank">
						    <span class="icon icon-youtube"></span>
						</a>
					</span>

					<span class="share-block">
				    	<a href="https://www.google.com/+cnngreece" class="share-trigger share-instagram" target="_blank">
				        	<span class="icon icon-googleplus"></span>
				    	</a>
				    </span>

					<span class="share-block">
				    	<a href="https://www.linkedin.com/company/cnn-greece" class="share-trigger share-linkedin" target="_blank">
				        	<span class="icon icon-linkedin"></span>
				    	</a>
				    </span>

				</div>
			</div>

		</div>

		<div class="lg7 p10">
			<div class="copyrights">
				&copy; 2015 - 2018 D.G. Newsagency S.A. CNN name, logo and all associated elements ® and &copy; 2015 Cable News Network, Inc. All rights reserved. CNN and the CNN logo are registered marks of Cable News Network, Inc., displayed with permission
			</div>

			<div class="footer-static-menu ">
				
		<div class="module">
			
						
				<div class="module-content">
				<ul class="menu" id="footer-menu">
<li class="item-220"><a href="/terms" >Όροι χρήσης</a></li><li class="item-219"><a href="/anti-corruption-policy" >Πολιτική κατά της Διαφθοράς</a></li><li class="item-222"><a href="/feedback" >Επικοινωνία</a></li></ul>
				</div>
			
		</div>
	
			</div>



			<div class="ened-logo" >
				<a href="http://www.ened.gr/" target="_blank">
					<img src="http://cdn.cnngreece.gr/images/ened/26x26_logo_ened_white.png" style="">
					<span style="" >ΜΕΛΟΣ ΕΝΕΔ</span>
				</a>
			</div>



		</div>


	</div>

	<div class="clr"></div>
</div>


<div class="track-pixel">

</div>



<div id="app-page-subscriber-teaser" options='{"cookie":{"name": subscriber-teaser}}' class="teaser-newsletter">
	<span class="icon icon-close teaser-hide"></span>

	<div class="row">

		<div class="teaser-newsletter-contents">
		<div class="teaser-text">
			<span class="newletter-logo"></span>
			<span class="newletter-moto"><strong>News</strong>letter</span>
			<i>ΓΙΑ ΝΑ ΜΗΝ ΧΑΝΕΙΣ ΕΙΔΗΣΗ</i>
		</div>

		<div class="teaser-form">
			<div class="pre-text">Όσα συμβαίνουν στην Ελλάδα και τον Κόσμο στο email σας. Με την εγγραφή σας, συμφωνείτε με τους  <a class="teaser-not-read" href="http://www.cnn.gr/terms" target="_blank">Όρους Χρήσης</a></div>
			
<div class="newsletter-form" id="app-module-981-form">
	
	
	
		
	<form action="http://www.cnn.gr/">
		
			
			<div id="formFields" class="form-fields">
				
				<div class="input-field">
					<input type="email" name="email" id="jcm-mail" required="required" placeholder="Το email σας" />
				</div>
				
				<button class="button jcm-submit" name="submit" id="start">ΕΓΓΡΑΦΗ</button>
				
			</div>
			
			<div class="clr"></div>
			<div id="form-message" data-messages='{
	"success" : "MOD_MAILCHIMP_SUCCESS",
	"error" : "MOD_MAILCHIMP_MAIL_ENTER_EMAIL"
}' class="response"></div>
			
		
	  
	  <input type="hidden" name="option" value="com_ajax" />
	  <input type="hidden" name="module" value="moosend" />
	  <input type="hidden" name="method" value="subscribe" />
	  <input type="hidden" name="format" value="raw" />
	  <input type="hidden" name="id" value="981" />
	  <input type="hidden" name="Itemid" value="101" />
	  
	</form>
</div>


		</div>
		</div>

	</div>
</div>

<div class="page-message" id="app-page-site-cookies">
	<div class="message-title">
		<span class="icon icon-close message-hide"></span>
		Αυτός ο ιστότοπος χρησιμοποιεί cookies
	</div>
	<div class="message-content">
		Με τη χρήση αυτού του ιστότοπου, αποδέχεστε τους <a class="message-read" href="http://www.cnn.gr/terms">Όρους Χρήσης</a>
	</div>
</div>



<div id="app-page-track"></div>

<div id="app-page-external-scripts"></div>


<script>
window.criteo_config = {
	
		"enable": false,
		"placements": [
      {
          "slotid": "app-banner-wide-1-0",
          "zoneid": 805583,
          "start": 320,
          "end": 500
      },
      {
          "slotid": "app-banner-wide-1-0",
          "zoneid": 805584,
          "start": 750,
          "end": 3000
      },
      {
          "slotid": "app-banner-wide-1-0",
          "zoneid": 805585,
          "start": 980,
          "end": 3000
      },
      {
          "slotid": "app-banner-rectangle-1-0",
          "zoneid": 805581,
          "start": 320,
          "end": 3000
      },
      {
          "slotid": "app-banner-rectangle-1-0",
          "zoneid": 805582,
          "start": 320,
          "end": 3000
      }
   ]
};
</script>

<script type="json/pageinfo" class="component-config">
{
	"modules" : [

		{
		"position":"banner-wide-1-0",
		"ajaxPosition":"app-module-banner-wide-1",
		"name":"ads",
		"options" : {
			"ad_id":"app-module-0-ad",
			"adslot":"CNN_Leaderboard_Ros_1",
			"size":[728, 90],
			"override" : 970,
			"sizes":[[728, 90], [970, 250]],
			"ajaxCall": "true",
			"ajaxCallId": "app-module-banner-wide-1",
			"checkResize": true
		}
	},
		{
		"position":"banner-wide-2-0",
		"ajaxPosition":"app-module-banner-wide-2",
		"name":"ads",
		"options":{
			"ad_id":"app-module-0-ad",
			"adslot":"CNN_Leaderboard_Ros_2",
			"size":[728, 90],
			"override" : 970,
			"sizes":[[728, 90], [970, 250]],
			"ajaxCall": "true",
			"ajaxCallId": "app-module-banner-wide-2",
			"checkResize": true
		}
	},
	{
		"position" : "banner-rectangle-1-0",
		"ajaxPosition" : "app-module-banner-rectangle-1",
		"name" : "ads",
		"options" : {
			"ad_id":"app-module-0-ad",
			"adslot":"CNN_Rectangle_Ros_1",
			"size":[300, 250],
			"sizes":[[300, 250], [300, 600]],
			"ajaxCall": "true",
			"ajaxCallId": "app-module-banner-rectangle-1",
			"checkResize": true
		}
	},
	{
		"position":"banner-rectangle-2-0",
		"ajaxPosition":"app-module-banner-rectangle-2",
		"name":"ads",
		"options":{
			"ad_id":"app-module-0-ad",
			"adslot":"CNN_Rectangle_Ros_2",
			"size":[300, 250],
			"sizes":[[300, 250], [300, 600]],
			"ajaxCall": "true",
			"ajaxCallId": "app-module-banner-rectangle-2",
			"checkResize": true
		}
	},
	{
		"position":"banner-rectangle-3-0",
		"ajaxPosition":"app-module-banner-rectangle-3",
		"name":"ads",
		"options":{
			"ad_id":"app-module-0-ad",
			"adslot":"CNN_Rectangle_Ros_3",
			"size":[300, 250],
			"sizes":[[300, 250], [300, 600]],
			"ajaxCall": "true",
			"ajaxCallId": "app-module-banner-rectangle-3",
			"checkResize": true
		}
	}
	]
}
</script>

<script type="json/pageinfo" class="config">
	{
		"modules" : [
		{"position":"module-892-slider","name":"slider","options":{}},
		{"position":"module-979-slider","name":"slider","options":{}},
		{"position":"page-main-menu","name" : "menu","options" : {"ajax": false}},
		{"position":"page-network-bottom","name" : "toggle","options" : {"ajax": false}},
		{"position":"page-header","name" : "header","options" : {"ajax": false}},
		{"position":"page-elevator","name" : "elevator","options" : {"ajax": false}},
		{"position":"page-site-cookies","name" : "message","options" : {"inline":true,"ajax": false, "cookie": {"name": "cnn-terms-v1","path": "/","expire": 365}}},
		{"position":"page-mobile-slider","name" : "slider","options" : {}},
		{"position":"page-widget-editor","name" : "widget","options" : {"ajax": false}},
		{"position":"page-subscriber-teaser","name" : "teaser","options" : {"cookie": {"name": "cnn-teaser-subscriber","path": "/","expire": 365}}},
		{"position":"module-980-form","name":"form","options":{
			"token": false
		}},
		{"position":"module-981-form","name":"form","options":{
			"token": false
		}},
		{
			"position":"dfp-skin",
			"ajaxPosition":"app-module-banner-skin",
			"name":"ads",
			"options":{
				"ad_id":"app-module-0-ad",
				"adslot":"Cnn_Skin_1x1",
				"size":[1, 1],
				"override" : 970,
				"sizes":[[970, 250]],
				"ajaxCall": "false",
				"ajaxCallId": "app-module-banner-skin",
				"checkResize": false
			}
		},
		{
			"position":"page-external-scripts",
			"name" : "scripts",
			"options" : {
			}
		}
		
		
				,{
			"position":"banner-rectangle-slider",
			"ajaxPosition":"app-module-banner-rectangle-slider",
			"name":"ads",
			"options":{
				"ad_id":"app-module-0-ad",
				"adslot":"CNN_Rectangle_Homepage",
				"size":[300, 250],
				"sizes":[[300, 250], [300, 600]],
				"ajaxCall": "true",
				"ajaxCallId": "app-module-banner-rectangle-slider",
				"checkResize": true
			}
		}
		,{
			"position":"page-track",
			"name":"track",
			"options":{}
		}
				,{
			"position":"banner-prestitial",
			"ajaxPosition":"app-module-prestitial",
			"name":"ads",
			"options":{
				"ad_id":"app-module-ad",
				"adslot":"CNN_Prestitial_1x1_Ros",
				"size":[1, 1],
				"override" : 970,
				"sizes":[[970, 250]],
				"ajaxCall": "false",
				"ajaxCallId": "app-module-prestitial",
				"checkResize": false
			}
		}]
	}
</script>

<script>
window.site_config = {
	"ROOT": "http://www.cnn.gr/",
	"TRACK": {
				"ANALYTICSID": "UA-69029409-2"
		},
		"DFP": {
				"ACCOUNTID": "111750332",
				"ACCOUNTNAME": "cnn",
				"TARGET":{
	        	        "noads": false,
	        	        "pagetype": "homepage",
	        	        "section": "home",
	        	        	        "category": "home",
	        	                }
		},
};
</script>



<script>
window.twttr = (function(d, s, id) {
	var js, fjs = d.getElementsByTagName(s)[0],
		t = window.twttr || {};
	if (d.getElementById(id)) return t;
	js = d.createElement(s);
	js.id = id;
	js.src = "https://platform.twitter.com/widgets.js";
	fjs.parentNode.insertBefore(js, fjs);

	t._e = [];
	t.ready = function(f) {
		t._e.push(f);
	};

	return t;
}(document, "script", "twitter-wjs"));
</script>

<script async defer src="//platform.instagram.com/en_US/embeds.js"></script>

<script type="text/javascript" src="http://cdn.cnngreece.gr/static-js/0.2.07/version/js/main.min.js"></script>



<script>(function(d, s, id) {
	var js, fjs = d.getElementsByTagName(s)[0];
	if (d.getElementById(id)) return;
	js = d.createElement(s); js.id = id;
	js.src = "//connect.facebook.net/el_GR/sdk.js#xfbml=1&version=v2.5";
	fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<script data-cfasync="false">
	(function(r,e,E,m,b){E[r]=E[r]||{};E[r][b]=E[r][b]||function(){
	(E[r].q=E[r].q||[]).push(arguments)};b=m.getElementsByTagName(e)[0];m=m.createElement(e);
	m.async=1;m.src=("file:"==location.protocol?"https:":"")+"//s.reembed.com/G-np5551.js";
	b.parentNode.insertBefore(m,b)})("reEmbed","script",window,document,"api");
</script>

<!-- Facebook Pixel Code -->
<script>
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
document,'script','//connect.facebook.net/en_US/fbevents.js');

fbq('init', '1467948313481577');
fbq('track', "PageView");</script>
<noscript><img height="1" width="1" style="display:none" alt="fb-tr"
src="https://www.facebook.com/tr?id=1467948313481577&amp;ev=PageView&amp;noscript=1"
/></noscript>
<!-- End Facebook Pixel Code -->


<div id="analyzer">
<script type="text/javascript">

xtnv = document;
xtsd=(('https:'==document.location.protocol)?'https://logs1312':'http://logw312');
xtdmc = ".cnn.gr";
xtsite = "568879";
xtn2 = "";
xt_xtcpath = "cdn.cnngreece.gr/services/js/xtcore.js";

</script>
<script type="text/javascript">

(function(){
	var at=document.createElement('script');
	at.type='text/javascript';
	at.async=true;
	at.src= (('https:' == document.location.protocol) ? 'https://': 'http://')+xt_xtcpath;
(document.getElementsByTagName('head')[0]||document.getElementsByTagName('body')[0]||document.getElementsByTagName('script')[0].parentNode).insertBefore(at,null);
})();
// AT_hit.sendTag("F")
</script>
</div>














<!-- nugg.ad Tag cnn.gr -->
<script>
  var nuggprof = '';
  var nuggtg = encodeURIComponent('__CONTENT_TAG__');
  var nuggrid = encodeURIComponent(top.location.href);
  var nuggscr = document.createElement('script');
  nuggscr.type = 'text/javascript';
  nuggscr.src ='//:ADWEB:.nuggad.net/rc?nuggn=1230610253&nuggsid=263992112&nuggtg='+nuggtg+'&nuggrid='+nuggrid+'';
  var n = document.getElementsByTagName('script')[0];
  n.parentNode.insertBefore(nuggscr, n);
</script>








<script data-schema="Organization" type="application/ld+json">
{
	"@context": "https://schema.org",
	"@type": "Organization",
	"@id": "http://www.cnn.gr/#organization",
	"url": "http://www.cnn.gr",
	"name": "CNN Greece",
	"logo": "http://www.cnn.gr/media/shared/cnngreece-logo.jpg",
	"sameAs":[
		"https://www.facebook.com/cnn.greece",
		"https://twitter.com/CNNgreece"
	]
}
</script>
<script type="application/ld+json">
{
	"@context": "http://schema.org",
	"@id": "http://www.cnn.gr/#webpage",
	"@type": "WebPage",
	"url": "http://www.cnn.gr",
	"name": "CNN Greece"
}
</script>
<script type="application/ld+json">
{
	"@context": "http://schema.org",
	"@id": "http://www.cnn.gr/#website",
	"@type": "WebSite",
	"url": "http://www.cnn.gr",
	"name": "CNN Greece",
	"potentialAction": {
		"@type": "SearchAction",
		"target": "http://www.cnn.gr/search?q={search_term_string}?src=rc_google",
		"query-input": "required name=search_term_string"
	}
}
</script>





</body>
</html>