                <!DOCTYPE html>
<html lang="" class="no-js">
  <!-- Document Head-->
  <head>
  <!-- Google Tag Manager -->
  <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
  new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
  j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
  'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
  })(window,document,'script','dataLayer','GTM-N3LVP5D');</script>
  <!-- End Google Tag Manager -->

    <script src="https://cdn.optimizely.com/js/6066242011.js"></script>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Cretalive.gr | η Κρήτη στον κόσμο :: Αρχική σελίδα // ειδήσεις on line, live ενημέρωση από Κρήτη, Ελλάδα, Κόσμο, άρθρα, media | Cretalive.gr</title>
    <meta name="robots" content="NOODP">
    <meta name="description" content="Ολη η επικαιρότητα και ειδήσεις live από Κρήτη, Ελλάδα, κόσμο. Το Cretalive παρέχει live πληροφόρηση, επίκαιρα άρθρα, video, ψηφιακή τηλεόραση, νέα για αθλητισμό, τεχνολογία, lifestyle, πολιτισμό">
    <meta name="keywords" content="media, νέα on line, άρθρα, ειδήσεις, πληροφόρηση, ενημέρωση, κόσμος, οικονομία, αθλητισμός, Κρήτη, web tv, video, on line, ψηφιακή τηλεόραση, επικαιρότητα, Ελλάδα, απόψεις, απόδημοι, Κρήτες, δημοσκοπήσεις">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="/favicon.ico">
    <link rel="apple-touch-icon" href="/img/apple-touch-icon.png">
          <link rel="stylesheet" href="/css/all.css">
        <script>
    // Picture element HTML5 shiv
    document.createElement( "picture" );
    </script>
    <script src="/js/min/head-min.js"></script>
            <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-4693790121526316",
    enable_page_level_ads: true
  });
</script>

<script type='text/javascript'>
var googletag = googletag || {};
googletag.cmd = googletag.cmd || [];
(function() {
    var gads = document.createElement('script');
    gads.async = true;
    gads.type = 'text/javascript';
    var useSSL = 'https:' == document.location.protocol;
    gads.src = (useSSL ? 'https:' : 'http:') +
        '//www.googletagservices.com/tag/js/gpt.js';
    var node = document.getElementsByTagName('script')[0];
    node.parentNode.insertBefore(gads, node);
})();
</script>
<script type='text/javascript'>
googletag.cmd.push(function() {
    // Set Mapping size for 728x90 banners - Leaderboard
    var mapping728x90 = googletag.sizeMapping().
    addSize([1200, 200], [728, 90]).
    addSize([992, 200], [617, 76]).
    addSize([768, 200], [728, 90]).
    addSize([0, 0], [0, 0]).
    build();

    // Set Mapping size for 300x250 banners - Medium Rectangle
    var mapping300x250 = googletag.sizeMapping().
    addSize([768, 200], [300, 250]).
    addSize([0, 0], [0, 0]).
    build();

    // Set Mapping size for 336x280 banners - Medium Rectangle 2
    var mapping336x280 = googletag.sizeMapping().
    addSize([1200, 200], [336, 280]).
    addSize([992, 200], [300, 250]).
    addSize([768, 200], [336, 280]).
    addSize([0, 0], [0, 0]).
    build();

    // Set Mapping size for 300x600 banners - Half Page
    var mapping300x600 = googletag.sizeMapping().
    addSize([768, 200], [300, 600]).
    addSize([0, 0], [0, 0]).
    build();

    // Set Mapping size for 300x100 banners - Custom size
    var mapping300x100 = googletag.sizeMapping().
    addSize([768, 200], [300, 100]).
    addSize([0, 0], [0, 0]).
    build();

    // Set Mapping size for 300x60 banners - Custom size
    var mapping300x60 = googletag.sizeMapping().
    addSize([768, 200], [300, 60]).
    addSize([0, 0], [0, 0]).
    build();

    // Set Mapping size for 300x90 banners - Custom size
    var mapping300x90 = googletag.sizeMapping().
    addSize([768, 200], [300, 90]).
    addSize([0, 0], [0, 0]).
    build();

    // Set Mapping size for 970x90 banners - Custom size
    var mapping970x90 = googletag.sizeMapping().
    addSize([768, 200], [970, 90]).
    addSize([0, 0], [0, 0]).
    build();

    // Set Mapping size for 970x250 banners - Custom size
    var mapping970x250 = googletag.sizeMapping().
    addSize([768, 200], [970, 250]).
    addSize([0, 0], [0, 0]).
    build();

    // MOBILE ONLY

    // Set Mapping size for 300x250 mobile banners - Custom size
    var mapping300x250m = googletag.sizeMapping().
    addSize([320, 400], [300, 250]).
    build();

    // Set Mapping size for 320x50 mobile banners - Custom size
    var mapping320x50m = googletag.sizeMapping().
    addSize([320, 400], [320, 50]).
    build();

                var LeaderboardAds = ["home_header_lb", "home_main_lb", "home_hl_lb", "home_history_lb", "home_health_lb", "home_lifestyle_lb", "home_footer_lb"];
            var MediumRectangleAds = ["home_main_mr", "home_top_mr", "home_top_mr2", "home_flow1_mr", "home_flow2_mr", "home_business_mr", "home_sports_mr", "home_culture_mr"];
            var MediumRectangle2Ads = ["home_top_lr1", "home_top_lr2", "home_culture_lr", "home_sports_lr", "home_business_lr", "home_flow1_lr", "home_flow2_lr"];
            var HalfPageAds = ["home_right_hp"];
            var MobileRectangleAds = ["mob_mr_1", "mob_mr_2"];
            // Home Top Custom Size 300x100
            var home_top_cs100 = googletag.defineSlot('/175029373/home_top_cs100', [300, 100], 'home_top_cs100').
                defineSizeMapping(mapping300x100).
                setCollapseEmptyDiv(true).
                addService(googletag.pubads());
        
    LeaderboardAds.forEach(function(bannerId) {
        var bannerId = googletag.defineSlot('/175029373/' + bannerId, [728, 90], bannerId).
        defineSizeMapping(mapping728x90).
        setCollapseEmptyDiv(true).
        addService(googletag.pubads());
    });

    MediumRectangleAds.forEach(function(bannerId) {
        var bannerId = googletag.defineSlot('/175029373/' + bannerId, [300, 250], bannerId).
        defineSizeMapping(mapping300x250).
        setCollapseEmptyDiv(true).
        addService(googletag.pubads());
    });

    MediumRectangle2Ads.forEach(function(bannerId) {
        var bannerId = googletag.defineSlot('/175029373/' + bannerId, [336, 280], bannerId).
        defineSizeMapping(mapping336x280).
        setCollapseEmptyDiv(true).
        addService(googletag.pubads());
    });

    HalfPageAds.forEach(function(bannerId) {
        var bannerId = googletag.defineSlot('/175029373/' + bannerId, [300, 600], bannerId).
        defineSizeMapping(mapping300x600).
        setCollapseEmptyDiv(true).
        addService(googletag.pubads());
    });

    // MOBILE ONLY
    MobileRectangleAds.forEach(function(bannerId) {
        var bannerId = googletag.defineSlot('/175029373/' + bannerId, [300, 250], bannerId).
        defineSizeMapping(mapping300x250m).
        setCollapseEmptyDiv(true).
        addService(googletag.pubads());
    });

    // CUSTOM SPECIALS BANNER
    var crete_top_billboard_970 = googletag.defineSlot('/175029373/crete_top_ll', [970, 90], 'crete_top_ll').
    defineSizeMapping(mapping970x90).
    setCollapseEmptyDiv(true).
    addService(googletag.pubads());

    var ros_top_billboard_970 = googletag.defineSlot('/175029373/ros_top_ll', [970, 90], 'ros_top_ll').
    defineSizeMapping(mapping970x90).
    setCollapseEmptyDiv(true).
    addService(googletag.pubads());

    var home_top_billboard_970 = googletag.defineSlot('/175029373/home_top_billboard', [970, 250], 'home_top_billboard').
    defineSizeMapping(mapping970x250).
    setCollapseEmptyDiv(true).
    addService(googletag.pubads());

    // CUSTOM MOBILE ONLY
    // ROS Flow Custom Size 320x50
    var ros_320m = googletag.defineSlot('/175029373/mob_ml', [320, 50], 'mob_ml').
    defineSizeMapping(mapping320x50m).
    setCollapseEmptyDiv(true).
    addService(googletag.pubads());

    // Enable Google Ad Services
    googletag.enableServices();
});
</script>
    <!-- Start Alexa Certify Javascript -->
    <script type="text/javascript">
    _atrk_opts = { atrk_acct:"ot0Ln1QolK10bm", domain:"cretalive.gr",dynamic: true};
    (function() { var as = document.createElement('script'); as.type = 'text/javascript'; as.async = true; as.src = "https://d31qbv1cthcecs.cloudfront.net/atrk.js"; var s = document.getElementsByTagName('script')[0];s.parentNode.insertBefore(as, s); })();
    </script>
    <noscript><img src="https://d5nxst8fruw4z.cloudfront.net/atrk.gif?account=ot0Ln1QolK10bm" style="display:none" height="1" width="1" alt="" /></noscript>
    <!-- End Alexa Certify Javascript -->

    <!-- Facebook Pixel Code -->
    <script>
    !function(f,b,e,v,n,t,s)
    {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
    n.callMethod.apply(n,arguments):n.queue.push(arguments)};
    if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
    n.queue=[];t=b.createElement(e);t.async=!0;
    t.src=v;s=b.getElementsByTagName(e)[0];
    s.parentNode.insertBefore(t,s)}(window,document,'script',
    'https://connect.facebook.net/en_US/fbevents.js');
    fbq('init', '2193215104239523');
    fbq('track', 'PageView');
    </script>
    <noscript>
    <img height="1" width="1" src="https://www.facebook.com/tr?id=2193215104239523&ev=PageView &noscript=1"/>
    </noscript>
    <!-- End Facebook Pixel Code -->

                <!-- Begin Cookie Consent plugin by Silktide - http://silktide.com/cookieconsent -->
<script type="text/javascript">
    window.cookieconsent_options = {"message":"Αυτός ο ιστότοπος χρησιμοποιεί cookies για να διασφαλίσει ότι θα έχετε την καλύτερη εμπειρία στην επίσκεψη σας","dismiss":"Κατάλαβα!","learnMore":"Περισσότερα","link":"http://www.cretalive.gr/pages/prosopika-dedomena","theme":"dark-floating"};
</script>

<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/1.0.9/cookieconsent.min.js"></script>
<!-- End Cookie Consent plugin -->    <meta name="google-site-verification" content="_npu7fchsVjZVVgVJgEJ3Di9WMcowprO3Bp53MB54Qc" />
    
    <!-- crazy egg -->
    <script type="text/javascript">
    setTimeout(function(){var a=document.createElement("script");
    var b=document.getElementsByTagName("script")[0];
    a.src=document.location.protocol+"//script.crazyegg.com/pages/scripts/0066/9020.js?"+Math.floor(new Date().getTime()/3600000);
    a.async=true;a.type="text/javascript";b.parentNode.insertBefore(a,b)}, 1);
    </script>
    <!-- OneSignal -->
    <script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async=""></script>
    <script>
      var OneSignal = window.OneSignal || [];
      OneSignal.push(function() {
        OneSignal.init({
          appId: "bad667df-95b3-4c3b-89ce-aaa161e3d758",
        });
      });
    </script>
  </head>
  <!-- Document Body-->
  <body style="">
    <!-- Google Tag Manager (noscript) -->
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-N3LVP5D" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <!-- End Google Tag Manager (noscript) -->
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/el_GR/sdk.js#xfbml=1&version=v2.5&appId=225875457439251";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script><!-- Wrapper Container-->
<div class="container" style="position: relative; background-color: #fff;">
            <!-- Header -->
    <!-- Header-->

<hr class="red-line hidden-xs">
<header>
    <div class="row no-margin header-details hidden-xs">
        <div class="col-xs-7 col-sm-6 hidden-md hidden-lg text-center">
                        <a href="https://www.cretalive.gr/"><img src="/img/logos/main_logo_2016-large.png" width="776" height="216" class="img-responsive"></a>
        </div>
        <div class="col-sm-6 col-md-4 header-left-box text-center hidden-xs">
            <div class="pull-left pt10">
                <a href="https://www.facebook.com/pages/Cretalivegr/136239276386619" target="_blank"><img src="/img/icons/facebook.png" width="32" height="32" alt=""></a>
                <a href="http://twitter.com/cretalive" target="_blank"><img src="/img/icons/twitter.png" width="32" height="32" alt=""></a>
                <a href="https://plus.google.com/+cretalivegr" target="_blank"><img src="/img/icons/google-plus.png" width="32" height="32" alt=""></a>
                <a href="https://www.youtube.com/c/CretaliveGr" target="_blank"><img src="/img/icons/youtube.png" width="32" height="32" alt=""></a>
            </div>
            <div id="displayMoment" class="dark-grey mt15 ml10"></div>
        </div>
        <div class="col-xs-5 col-sm-6 col-md-4 header-middle-box">
            <div id="forecastio" class="weather-top text-center dark-grey">
                <!-- Dynamically from json forecast -->
            </div>
        </div>
        <div class="col-md-4 header-right-box hidden-sm hidden-xs">
            <div class="text-right eortologio-top dark-grey">
                <span>Σήμερα γιορτάζουν<br /></span>
                <div id="eortologio">εύρεση γιορτών...</div>
            </div>
        </div>
    </div>
    <div class="row mt10 pb10 hidden-xs">
        <div class="col-md-4 hidden-sm hidden-xs main-logo">
                        <a href="https://www.cretalive.gr/"><img src="/img/logos/main_logo_2016-large.png" width="776" height="216" class="img-responsive"></a>
        </div>
        <div class="col-md-8 hidden-xs text-left">
            <!-- /175029373/home_header_lb -->
                            
    <div class="row hidden-xs" style="margin-top: 0px; margin-bottom: 0px;">
        <div class="col-md-12">
            <div id='home_header_lb' class='center-block ' style='height:90px; width:728px;'>
                <script type='text/javascript'>
                    googletag.cmd.push(function() {
                        googletag.display('home_header_lb');
                    });
                </script>
            </div><!-- /#div-gpt-ad... -->
        </div><!-- /.col-md-12 -->
    </div><!-- /.row .hidden-xs -->

        </div>
    </div>
    <nav id="navbar-main" class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" data-toggle="collapse" data-target="#navbar" aria-exapnded="false" aria-controls="navbar" class="navbar-toggle collapsed"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button><a href="//www.cretalive.gr/" class="navbar-brand visible-xs"><img src="/img/logos/main_logo_2016-large-i.png" height="36" /></a>
            </div>
            <div id="navbar" aria-expanded="false" style="height: 1px;" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="hidden-xs active"><a href="https://www.cretalive.gr/"><span class="glyphicon glyphicon-home"></span></a></li>
                    <li ><a href="https://www.cretalive.gr/news">Επικαιρότητα</a></li>
                    <li ><a href="https://www.cretalive.gr/crete">Κρήτη</a></li>
                    <li ><a href="https://www.cretalive.gr/ellada">Ελλάδα</a></li>
                    <li class="hidden-sm"><a href="https://www.cretalive.gr/business">Business</a></li>
                    <li class="hidden-sm"><a href="https://www.cretalive.gr/polites">Πολίτες</a></li>
                    <li class="hidden-sm"><a href="https://www.cretalive.gr/world">Κόσμος</a></li>
                                        <li class="hidden-sm hidden-md"><a href="https://www.cretalive.gr/culture">Πολιτισμός</a></li>
                    <li class="hidden-sm hidden-md"><a href="https://www.cretalive.gr/science">Επιστήμες</a></li>
                    <li class="hidden-sm hidden-md"><a href="https://www.cretalive.gr/health">Υγεία</a></li>
                    <li class="dropdown hidden-xs hidden-lg"><a href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" class="dropdown-toggle">Περισσότερα<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li class="hidden-md"><a href="https://www.cretalive.gr/business">Business</a></li>
                            <li class="hidden-md"><a href="https://www.cretalive.gr/polites">Πολίτες</a></li>
                            <li class="hidden-md"><a href="https://www.cretalive.gr/world">Κόσμος</a></li>
                                                        <li ><a href="https://www.cretalive.gr/culture">Πολιτισμός</a></li>
                            <li ><a href="https://www.cretalive.gr/science">Επιστήμες</a></li>
                            <li ><a href="https://www.cretalive.gr/lifestyle">Lifestyle</a></li>
                        </ul>
                    </li>
                </ul>
                <form action="https://www.cretalive.gr/search/results" role="search" class="navbar-form navbar-right">
                    <div class="form-group">
                                                <div class="inner-addon left-addon"><i class="glyphicon glyphicon-search"></i>
                            <input type="search" name="q" placeholder="Αναζήτηση" class="royal-blue form-control navbar-search" value="">
                        </div>
                                            </div>
                </form>
            </div>
        </div>
    </nav>
    <div class="visible-xs mb10"><div id='mob_ml' class="center-block" style='width:320px; margin-top: 0px; margin-bottom: 0px;'>
    <script type='text/javascript'>
        googletag.cmd.push(function() { googletag.display('mob_ml'); });
    </script>
</div>
</div>
    </header>
<!-- Content-->
                            <section id="main">
        <div class="row">
            <div class="col-md-8">
                                                                <div id="main-article" class="row">
                    <div class="col-md-12">
                                    <div class="img-container">
        <a href="//www.cretalive.gr/crete/makabrio-theama-thn-katasparaksan-agria-zoa">
            <picture>
    <!--[if IE 9]><video style="display: none;><![endif]-->
        <source
        data-srcset="https://cdn.cretalive.gr/_xsmall/ptoma-shteia-arxeio.jpg?mtime=20180318165515"
        media="(max-width: 480px)" />
                <source
        data-srcset="https://cdn.cretalive.gr/_largeImage/ptoma-shteia-arxeio.jpg?mtime=20180318165515" />
    <!--[if IE 9]></video><![endif]-->
    <img
        src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
        data-srcset="https://cdn.cretalive.gr/_largeImage/ptoma-shteia-arxeio.jpg?mtime=20180318165515"
        class="lazyload img-responsive"
        alt="Μακάβριο θέαμα: Την κατασπάραξαν άγρια ζώα" />
</picture>

        </a>
                    </div>
    <p class="main-article-title-xs">
        <a href="//www.cretalive.gr/crete/makabrio-theama-thn-katasparaksan-agria-zoa" class="primary-link">Μακάβριο θέαμα: Την κατασπάραξαν άγρια ζώα</a>
            </p>
    <div class="visible-xs" id="mainDetails">
                    </div>
    <p class="lead font18 hidden-xs"><a href="//www.cretalive.gr/crete/makabrio-theama-thn-katasparaksan-agria-zoa" class="primary-grey-link">Σε κατάσταση σοκ, ο αγρότης κάλεσε τις Αρχές και σύντομα στην περιοχή Πιλαλήματα  βρέθηκε κλιμάκιο της Αστυνομίας και ιατροδικαστής</a></p>                        </div><!-- /.col-md-12 -->
                </div><!-- /#main-article -->
                                                            </div>
            <div class="col-md-4">
                                <div class="row">
                    <div class="col-md-12 col-sm-6 mb20">
                        <div class="banner-wrapper hidden-xs">
                            <div id='home_top_lr1' class="center-block" style='width:336px; margin-top: 0px; margin-bottom: 0px;'>
    <script type='text/javascript'>
        googletag.cmd.push(function() { googletag.display('home_top_lr1'); });
    </script>
</div>

                        </div>
                    </div>
                    <div class='col-md-12 col-sm-6'>
                        <div class="banner-wrapper hidden-xs">
                            <div id='home_top_lr2' class="center-block" style='width:336px; margin-top: 0px; margin-bottom: 0px;'>
    <script type='text/javascript'>
        googletag.cmd.push(function() { googletag.display('home_top_lr2'); });
    </script>
</div>

                        </div>
                    </div>
                </div>
                            </div>
        </div>
        <div class="row mb15 mt15 hidden-xs" style="margin-left: 0px; margin-right: 0px;">
            <div class="rowHr mb15"></div>
            <div class="col-md-8">
                                                                            
    <div class="row hidden-xs" style="margin-top: 0px; margin-bottom: 0px;">
        <div class="col-md-12">
            <div id='home_main_lb' class='center-block styledBanner' style='height:100px; width:738px;'>
                <script type='text/javascript'>
                    googletag.cmd.push(function() {
                        googletag.display('home_main_lb');
                    });
                </script>
            </div><!-- /#div-gpt-ad... -->
        </div><!-- /.col-md-12 -->
    </div><!-- /.row .hidden-xs -->

            </div>
            <div class="col-md-4">
                <div class="banner-wrapper hidden-xs">
                    <div id='home_top_cs100' class="center-block" style='width:300px; margin-top: 0px; margin-bottom: 0px;'>
    <script type='text/javascript'>
        googletag.cmd.push(function() { googletag.display('home_top_cs100'); });
    </script>
</div>

                </div>
            </div>
            <div class="clearfix"></div>
            <div class="rowHr mt15"></div>
        </div>
        <div class="row">
            <div class="col-md-8">
                                                                                <div id="submain-article" class="row pt10 pb10">
                                    <div class="col-sm-7 col-md-7 clearfix">
                                <div class="img-container img-container-mob ">
            <a href="//www.cretalive.gr/crete/trochaio-me-egklobismo-sto-boak" class="img-primary-link" >
                                    <picture>
    <!--[if IE 9]><video style="display: none;><![endif]-->
        <source
        data-srcset="https://cdn.cretalive.gr/_xsmall/image1_180318_135658.jpeg?mtime=20180318135658"
        media="(max-width: 480px)" />
            <source
        data-srcset="https://cdn.cretalive.gr/_xsmall/image1_180318_135658.jpeg?mtime=20180318135658"
        media="(max-width: 767px)" />
            <source
        data-srcset="https://cdn.cretalive.gr/_largeImage/image1_180318_135658.jpeg?mtime=20180318135658"
        media="(max-width: 991px)" />
        <source
        data-srcset="https://cdn.cretalive.gr/_sectionThumb/image1_180318_135658.jpeg?mtime=20180318135658" />
    <!--[if IE 9]></video><![endif]-->
    <img
        src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
        data-srcset="https://cdn.cretalive.gr/_sectionThumb/image1_180318_135658.jpeg?mtime=20180318135658"
        class="lazyload img-responsive"
        alt="Τροχαίο με εγκλωβισμό στο ΒΟΑΚ" />
</picture>

                            </a>
        </div>
                                            <p class="full-section-article-title hidden-xs"><a href="//www.cretalive.gr/crete" class="primary-link">Κρήτη</a></p>
                                    <h3 class="mobileTag">
                        <a href="//www.cretalive.gr/crete/trochaio-me-egklobismo-sto-boak" class="primary-link" >            Τροχαίο με εγκλωβισμό στο ΒΟΑΚ</a>
                                            </h3>
                    <div class="divider-mob"></div>
            </div>

                        <div class="col-sm-5 col-md-5">
                                                <div id='home_main_mr' class="center-block" style='width:300px; margin-top: 0px; margin-bottom: 0px;'>
    <script type='text/javascript'>
        googletag.cmd.push(function() { googletag.display('home_main_mr'); });
    </script>
</div>

                    </div><!-- /.col-sm-6 .col-md-6 -->
                </div><!-- /#submain-article -->
                                                                                                                                <div id="highlights" class="row">
                    <div class="col-md-12">
                        <h4 class="section-heading mt0">Highlights</h4>
                        <div class="row no-margin" id="ajax-highlights">
                                                    </div><!-- /.row -->
                        <div class="visible-xs"><div id='mob_mr_1' class="center-block" style='width:300px; margin-top: 0px; margin-bottom: 0px;'>
    <script type='text/javascript'>
        googletag.cmd.push(function() { googletag.display('mob_mr_1'); });
    </script>
</div>
</div>
                    </div><!-- /.col-md-12  -->
                                                        
    <div class="row hidden-xs" style="margin-top: 10px; margin-bottom: 10px;">
        <div class="col-md-12">
            <div id='home_hl_lb' class='center-block ' style='height:90px; width:728px;'>
                <script type='text/javascript'>
                    googletag.cmd.push(function() {
                        googletag.display('home_hl_lb');
                    });
                </script>
            </div><!-- /#div-gpt-ad... -->
        </div><!-- /.col-md-12 -->
    </div><!-- /.row .hidden-xs -->

                </div><!-- /#highlights -->
                                                                                                                                <div id="top-stories">
                    <div class="row no-margin">
                        <div class="col-md-12 no-mp">
                            <h4 class="section-heading">Top Stories</h4>
                        </div><!-- /.col-md-12 no-mp -->
                    </div><!-- /.row no-margin -->
                    <div class="row">
                                                    <div class="col-xs-12 col-sm-6 col-md-6">
            <div class="media">
    <div class="media-left ">
        <a href="//www.cretalive.gr/crete/ksekinontas-thn-toyristikh-sezon-me-synodoiporo-to-5o-open-coffee-heraklion">
            <picture>
    <!--[if IE 9]><video style="display: none;><![endif]-->
                <source
        data-srcset="https://cdn.cretalive.gr/_galleryThumb/770.430cover.jpg?mtime=20180316141135" />
    <!--[if IE 9]></video><![endif]-->
    <img
        src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
        data-srcset="https://cdn.cretalive.gr/_galleryThumb/770.430cover.jpg?mtime=20180316141135"
        class="lazyload media-object"
        alt="Ξεκινώντας την τουριστική σεζόν με συνοδοιπόρο το 5o Open Coffee Heraklion!" />
</picture>

        </a>
    </div><!-- /.media-left -->
    <div class="media-body">
                <p class="top-story-p">
            <a href="//www.cretalive.gr/crete/ksekinontas-thn-toyristikh-sezon-me-synodoiporo-to-5o-open-coffee-heraklion" class="primary-link">Ξεκινώντας την τουριστική σεζόν με συνοδοιπόρο το 5o Open Coffee Heraklion!</a>
                                            </p>
    </div><!-- /.media-body -->
</div><!-- /.media -->

        </div><!-- /.col-xs-12 col-sm-6 col-md-6 -->
                    <div class="col-xs-12 col-sm-6 col-md-6">
            <div class="media">
    <div class="media-left ">
        <a href="//www.cretalive.gr/crete/food-expo-2018-h-paroysia-ths-krivek-stefthhke-me-epitychia">
            <picture>
    <!--[if IE 9]><video style="display: none;><![endif]-->
                <source
        data-srcset="https://cdn.cretalive.gr/_galleryThumb/krivekfoodexpo6.jpg?mtime=20180315160102" />
    <!--[if IE 9]></video><![endif]-->
    <img
        src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
        data-srcset="https://cdn.cretalive.gr/_galleryThumb/krivekfoodexpo6.jpg?mtime=20180315160102"
        class="lazyload media-object"
        alt="FOOD EXPO 2018: Η παρουσία της KRIVEK στέφθηκε με επιτυχία!" />
</picture>

        </a>
    </div><!-- /.media-left -->
    <div class="media-body">
                <p class="top-story-p">
            <a href="//www.cretalive.gr/crete/food-expo-2018-h-paroysia-ths-krivek-stefthhke-me-epitychia" class="primary-link">FOOD EXPO 2018: Η παρουσία της KRIVEK στέφθηκε με επιτυχία!</a>
                                            </p>
    </div><!-- /.media-body -->
</div><!-- /.media -->

        </div><!-- /.col-xs-12 col-sm-6 col-md-6 -->
                    <div class="col-xs-12 col-sm-6 col-md-6">
            <div class="media">
    <div class="media-left ">
        <a href="//www.cretalive.gr/ellada/24media-epishma-telos-sthn-synergasia-me-ton-iban-sabbidh">
            <picture>
    <!--[if IE 9]><video style="display: none;><![endif]-->
                <source
        data-srcset="https://cdn.cretalive.gr/_galleryThumb/24media_6.png?mtime=20180314151036" />
    <!--[if IE 9]></video><![endif]-->
    <img
        src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
        data-srcset="https://cdn.cretalive.gr/_galleryThumb/24media_6.png?mtime=20180314151036"
        class="lazyload media-object"
        alt="24MEDIA: Επίσημα τέλος στην συνεργασία με τον Ιβάν Σαββίδη" />
</picture>

        </a>
    </div><!-- /.media-left -->
    <div class="media-body">
                <p class="top-story-p">
            <a href="//www.cretalive.gr/ellada/24media-epishma-telos-sthn-synergasia-me-ton-iban-sabbidh" class="primary-link">24MEDIA: Επίσημα τέλος στην συνεργασία με τον Ιβάν Σαββίδη</a>
                                            </p>
    </div><!-- /.media-body -->
</div><!-- /.media -->

        </div><!-- /.col-xs-12 col-sm-6 col-md-6 -->
                    <div class="col-xs-12 col-sm-6 col-md-6">
            <div class="media">
    <div class="media-left ">
        <a href="//www.cretalive.gr/crete/entyposiase-h-paroysia-ths-saboidakhs-ae-sto-food-expo-greece">
            <picture>
    <!--[if IE 9]><video style="display: none;><![endif]-->
                <source
        data-srcset="https://cdn.cretalive.gr/_galleryThumb/20180310_150202_001.jpg?mtime=20180314133340" />
    <!--[if IE 9]></video><![endif]-->
    <img
        src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
        data-srcset="https://cdn.cretalive.gr/_galleryThumb/20180310_150202_001.jpg?mtime=20180314133340"
        class="lazyload media-object"
        alt="Εντυπωσίασε η παρουσία της Σαβοϊδάκης ΑΕ στο  «Food Expo Greece»" />
</picture>

        </a>
    </div><!-- /.media-left -->
    <div class="media-body">
                <p class="top-story-p">
            <a href="//www.cretalive.gr/crete/entyposiase-h-paroysia-ths-saboidakhs-ae-sto-food-expo-greece" class="primary-link">Εντυπωσίασε η παρουσία της Σαβοϊδάκης ΑΕ στο  «Food Expo Greece»</a>
                                            </p>
    </div><!-- /.media-body -->
</div><!-- /.media -->

        </div><!-- /.col-xs-12 col-sm-6 col-md-6 -->
                            </div><!-- /.row p15 -->
                </div><!-- /.top-stories -->
                                                                                                                <div id="isawihear-promoted">
                    <div class="row">
                        <div class="col-xs-6 col-sm-6 col-md-6 pl10 pr5">
                            <div class="promoted-article">
                                <h5><img src="/img/icons/isawihear-blue-icon.png" style="margin-right:3px;" width="27" height="24"><a href="/isawihear" class="primary-link">Είδα - Άκουσα</a></h5>
                                                            <div class=" clearfix">
                                <div class="img-container  ">
            <a href="//www.cretalive.gr/isawihear/kala-ta-nea-alla-ochi-gia-olo-to-dromo" class="img-primary-link" >
                                    <picture>
    <!--[if IE 9]><video style="display: none;><![endif]-->
        <source
        data-srcset="https://cdn.cretalive.gr/_xsmall/29339455_2284042661621632_6371754803055296512_n.jpg?mtime=20180318084533"
        media="(max-width: 480px)" />
            <source
        data-srcset="https://cdn.cretalive.gr/_xsmall/29339455_2284042661621632_6371754803055296512_n.jpg?mtime=20180318084533"
        media="(max-width: 767px)" />
            <source
        data-srcset="https://cdn.cretalive.gr/_largeImage/29339455_2284042661621632_6371754803055296512_n.jpg?mtime=20180318084533"
        media="(max-width: 991px)" />
        <source
        data-srcset="https://cdn.cretalive.gr/_sectionThumb/29339455_2284042661621632_6371754803055296512_n.jpg?mtime=20180318084533" />
    <!--[if IE 9]></video><![endif]-->
    <img
        src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
        data-srcset="https://cdn.cretalive.gr/_sectionThumb/29339455_2284042661621632_6371754803055296512_n.jpg?mtime=20180318084533"
        class="lazyload img-responsive"
        alt="Καλά τα νέα , αλλά όχι για όλο το δρόμο!" />
</picture>

                            </a>
        </div>
                                <h4 >
                        <a href="//www.cretalive.gr/isawihear/kala-ta-nea-alla-ochi-gia-olo-to-dromo" class="primary-link" >            Καλά τα νέα , αλλά όχι για όλο το δρόμο!</a>
                                            </h4>
            </div>

                                </div><!-- /.promoted-article -->
                        </div><!-- /.col-sm-6 col-md-6 -->
                        <div class="col-xs-6 col-sm-6 col-md-6 pl5 pr10">
                            <div class="promoted-article">
                                <h5>Promoted Stories</h5>
                                                            <div class=" clearfix">
                                <div class="img-container  ">
            <a href="//www.cretalive.gr/crete/theloyn-na-feroyn-kai-fetos-thn-anastash-se-oloys" class="img-primary-link" >
                                    <picture>
    <!--[if IE 9]><video style="display: none;><![endif]-->
        <source
        data-srcset="https://cdn.cretalive.gr/_xsmall/pasxa_180317_191741.jpg?mtime=20180317191740"
        media="(max-width: 480px)" />
            <source
        data-srcset="https://cdn.cretalive.gr/_xsmall/pasxa_180317_191741.jpg?mtime=20180317191740"
        media="(max-width: 767px)" />
            <source
        data-srcset="https://cdn.cretalive.gr/_largeImage/pasxa_180317_191741.jpg?mtime=20180317191740"
        media="(max-width: 991px)" />
        <source
        data-srcset="https://cdn.cretalive.gr/_sectionThumb/pasxa_180317_191741.jpg?mtime=20180317191740" />
    <!--[if IE 9]></video><![endif]-->
    <img
        src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
        data-srcset="https://cdn.cretalive.gr/_sectionThumb/pasxa_180317_191741.jpg?mtime=20180317191740"
        class="lazyload img-responsive"
        alt="Θέλουν να φέρουν, και φέτος, την Ανάσταση σε όλους!" />
</picture>

                            </a>
        </div>
                                            <p class="full-section-article-title hidden-xs"><a href="//www.cretalive.gr/crete" class="primary-link">Κρήτη</a></p>
                                    <h4 >
                        <a href="//www.cretalive.gr/crete/theloyn-na-feroyn-kai-fetos-thn-anastash-se-oloys" class="primary-link" >            Θέλουν να φέρουν, και φέτος, την Ανάσταση σε όλους!</a>
                                            </h4>
            </div>

                                </div><!-- /.promoted-article -->
                        </div><!-- /.col-sm-6 .col-md-6 -->
                    </div><!-- /.row .no-margin -->
                </div><!-- /#isawihear-promoted -->
                                                                            </div><!-- /.col-md-8 -->
            <div class="col-md-4 hidden-print">
        
    <div class="bordered-list">
        <a href="/news" class="primary-link"><h4 class="section-heading">Ροή Ειδήσεων</h4></a>
                        <div id="newsroom"></div>
            </div>

    <a href="/news" class="btn btn-small btn-default mb10" style="width:100%">Όλες οι ειδήσεις</a>

                    <div class="row">
            <div class="col-sm-6 col-md-12">
                <div class="banner-wrapper hidden-xs mb20">
                    <div id='home_flow1_lr' class="center-block" style='width:336px; margin-top: 0px; margin-bottom: 0px;'>
    <script type='text/javascript'>
        googletag.cmd.push(function() { googletag.display('home_flow1_lr'); });
    </script>
</div>

                </div>
            </div>
            <div class="col-sm-6 col-md-12">
                <div class="banner-wrapper hidden-xs">
                    <div id='home_flow2_lr' class="center-block" style='width:336px; margin-top: 0px; margin-bottom: 0px;'>
    <script type='text/javascript'>
        googletag.cmd.push(function() { googletag.display('home_flow2_lr'); });
    </script>
</div>

                </div>
            </div>
        </div>
                <div class="bordered-list mb20">
        <h4 class="section-heading">Διαβάζονται <span class="red">τώρα</span></h4>
        <div class="row" id="popular"></div>
    </div>
                        <div class="banner-wrapper hidden-xs mt10">
            <div id='home_right_hp' class="center-block" style='width:300px; margin-top: 0px; margin-bottom: 0px;'>
    <script type='text/javascript'>
        googletag.cmd.push(function() { googletag.display('home_right_hp'); });
    </script>
</div>

        </div>
            </div>
        </div><!-- /.row -->
    </section><!-- /#main -->
                                <section id="history-opinions" class="mt20 pb10">
        <div class="row no-margin">
            <div class="col-md-8">
                <div class="row">
                                    <div class="col-xs-6 col-sm-6 col-md-6 full-section-article clearfix">
                            <h6><a href="//www.cretalive.gr/history" class="primary-link">Ιστορία</a></h6>
                        <div class="img-container  ">
            <a href="//www.cretalive.gr/history/o-benizelos-kai-h-mikrh-toy-ekdikhsh-apo-thn-istoria" class="img-secondary-link" >
                                    <picture>
    <!--[if IE 9]><video style="display: none;><![endif]-->
        <source
        data-srcset="https://cdn.cretalive.gr/_xsmall/1a_180317_194625.jpg?mtime=20180317194625"
        media="(max-width: 480px)" />
            <source
        data-srcset="https://cdn.cretalive.gr/_xsmall/1a_180317_194625.jpg?mtime=20180317194625"
        media="(max-width: 767px)" />
            <source
        data-srcset="https://cdn.cretalive.gr/_largeImage/1a_180317_194625.jpg?mtime=20180317194625"
        media="(max-width: 991px)" />
        <source
        data-srcset="https://cdn.cretalive.gr/_sectionThumb/1a_180317_194625.jpg?mtime=20180317194625" />
    <!--[if IE 9]></video><![endif]-->
    <img
        src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
        data-srcset="https://cdn.cretalive.gr/_sectionThumb/1a_180317_194625.jpg?mtime=20180317194625"
        class="lazyload img-responsive"
        alt="Ο Βενιζέλος και η... μικρή του εκδίκηση από την ιστορία!" />
</picture>

                            </a>
        </div>
                                <h4 >
                        <a href="//www.cretalive.gr/history/o-benizelos-kai-h-mikrh-toy-ekdikhsh-apo-thn-istoria" class="secondary-link" >            Ο Βενιζέλος και η... μικρή του εκδίκηση από την ιστορία!</a>
                                            </h4>
            </div>


            <div class="col-xs-6 col-sm-6 col-md-6 full-section-article clearfix">
                            <h6><a href="//www.cretalive.gr/opinions" class="primary-link">Απόψεις</a></h6>
                        <div class="img-container  ">
            <a href="//www.cretalive.gr/opinions/oi-ellhnes-kratoymenoi-aksiomatikoi-kai-o-proedros-erntogan" class="img-secondary-link" >
                                    <picture>
    <!--[if IE 9]><video style="display: none;><![endif]-->
        <source
        data-srcset="https://cdn.cretalive.gr/_xsmall/720_563287_b3a6a1dc44-9da613c83d7c234b.jpg?mtime=20180304114322"
        media="(max-width: 480px)" />
            <source
        data-srcset="https://cdn.cretalive.gr/_xsmall/720_563287_b3a6a1dc44-9da613c83d7c234b.jpg?mtime=20180304114322"
        media="(max-width: 767px)" />
            <source
        data-srcset="https://cdn.cretalive.gr/_largeImage/720_563287_b3a6a1dc44-9da613c83d7c234b.jpg?mtime=20180304114322"
        media="(max-width: 991px)" />
        <source
        data-srcset="https://cdn.cretalive.gr/_sectionThumb/720_563287_b3a6a1dc44-9da613c83d7c234b.jpg?mtime=20180304114322" />
    <!--[if IE 9]></video><![endif]-->
    <img
        src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
        data-srcset="https://cdn.cretalive.gr/_sectionThumb/720_563287_b3a6a1dc44-9da613c83d7c234b.jpg?mtime=20180304114322"
        class="lazyload img-responsive"
        alt="Oι Έλληνες κρατούμενοι αξιωματικοί και ο Πρόεδρος Ερντογάν " />
</picture>

                            </a>
        </div>
                                        <p class="full-section-article-title hidden-xs"><a href="//www.cretalive.gr/authors/petros-mhliarakhs" class="primary-link">Πέτρος  Ι. Μηλιαράκης</a></p>
                        <h4 >
                        <a href="//www.cretalive.gr/opinions/oi-ellhnes-kratoymenoi-aksiomatikoi-kai-o-proedros-erntogan" class="secondary-link" ><img src="https://cdn.cretalive.gr/authors/_authorThumb/Petros-Miliarakis_copy_70_70_s_c1_center.jpg?mtime=20160325130408" width="40" height="40" class="pull-left img-circle mr5" />            Oι Έλληνες κρατούμενοι αξιωματικοί και ο Πρόεδρος Ερντογάν </a>
                                            </h4>
            </div>

                    </div><!-- /.row -->
                                
    <div class="row hidden-xs" style="margin-top: 20px; margin-bottom: 20px;">
        <div class="col-md-12">
            <div id='home_history_lb' class='center-block ' style='height:90px; width:728px;'>
                <script type='text/javascript'>
                    googletag.cmd.push(function() {
                        googletag.display('home_history_lb');
                    });
                </script>
            </div><!-- /#div-gpt-ad... -->
        </div><!-- /.col-md-12 -->
    </div><!-- /.row .hidden-xs -->

            </div><!-- /.col-md-8 -->
            <div class="col-md-4 hidden-xs">
                <div style="height:10px;" class="visible-xs"></div>
                <div class="row">
                                                    
        <div class="col-sm-6 col-md-12 mb20 mob-nombottom">
            <div class="media">
    <div class="media-left hidden-xs">
        <a href="//www.cretalive.gr/opinions/breite-nero">
            <picture>
    <!--[if IE 9]><video style="display: none;><![endif]-->
                <source
        data-srcset="https://cdn.cretalive.gr/authors/_authorThumb/anastasakos.jpg?mtime=20160331164729" />
    <!--[if IE 9]></video><![endif]-->
    <img
        src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
        data-srcset="https://cdn.cretalive.gr/authors/_authorThumb/anastasakos.jpg?mtime=20160331164729"
        class="lazyload media-object"
        alt="Βρείτε νερό! &lt;small&gt; Παναγιώτης Αναστασάκος&lt;/small&gt;" />
</picture>

        </a>
    </div><!-- /.media-left -->
    <div class="media-body">
                <p class="top-story-p mb0">
            <a href="//www.cretalive.gr/opinions/breite-nero" class="secondary-link">Βρείτε νερό! <small> Παναγιώτης Αναστασάκος</small></a>
                                            </p>
    </div><!-- /.media-body -->
</div><!-- /.media -->

        </div>
                            
        <div class="col-sm-6 col-md-12 mb20 mob-nombottom">
            <div class="media">
    <div class="media-left hidden-xs">
        <a href="//www.cretalive.gr/opinions/epitaktikh-h-anagkh-monimon-kai-aksiokratikon-diorismon-sthn-ekpaideysh">
            <picture>
    <!--[if IE 9]><video style="display: none;><![endif]-->
                <source
        data-srcset="https://cdn.cretalive.gr/authors/_authorThumb/s200_emmanouil.chalkiadakis.jpg?mtime=20180316072838" />
    <!--[if IE 9]></video><![endif]-->
    <img
        src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
        data-srcset="https://cdn.cretalive.gr/authors/_authorThumb/s200_emmanouil.chalkiadakis.jpg?mtime=20180316072838"
        class="lazyload media-object"
        alt="Επιτακτική η ανάγκη μόνιμων και αξιοκρατικών διορισμών στην Εκπαίδευση&lt;small&gt; Εμμανουήλ Χαλκιαδάκης&lt;/small&gt;" />
</picture>

        </a>
    </div><!-- /.media-left -->
    <div class="media-body">
                <p class="top-story-p mb0">
            <a href="//www.cretalive.gr/opinions/epitaktikh-h-anagkh-monimon-kai-aksiokratikon-diorismon-sthn-ekpaideysh" class="secondary-link">Επιτακτική η ανάγκη μόνιμων και αξιοκρατικών διορισμών στην Εκπαίδευση<small> Εμμανουήλ Χαλκιαδάκης</small></a>
                                            </p>
    </div><!-- /.media-body -->
</div><!-- /.media -->

        </div>
                            
        <div class="col-sm-6 col-md-12 mb20 mob-nombottom">
            <div class="media">
    <div class="media-left hidden-xs">
        <a href="//www.cretalive.gr/opinions/h-pikrh-alhtheia-kai-emeis">
            <picture>
    <!--[if IE 9]><video style="display: none;><![endif]-->
                <source
        data-srcset="https://cdn.cretalive.gr/authors/_authorThumb/karatzanis_160803_200619.jpg?mtime=20160803200618" />
    <!--[if IE 9]></video><![endif]-->
    <img
        src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
        data-srcset="https://cdn.cretalive.gr/authors/_authorThumb/karatzanis_160803_200619.jpg?mtime=20160803200618"
        class="lazyload media-object"
        alt="Η πικρή αλήθεια και εμείς&lt;small&gt; Δημήτρης Καρατζάνης&lt;/small&gt;" />
</picture>

        </a>
    </div><!-- /.media-left -->
    <div class="media-body">
                <p class="top-story-p mb0">
            <a href="//www.cretalive.gr/opinions/h-pikrh-alhtheia-kai-emeis" class="secondary-link">Η πικρή αλήθεια και εμείς<small> Δημήτρης Καρατζάνης</small></a>
                                            </p>
    </div><!-- /.media-body -->
</div><!-- /.media -->

        </div>
                            
        <div class="col-sm-6 col-md-12 mb20 mob-nombottom">
            <div class="media">
    <div class="media-left hidden-xs">
        <a href="//www.cretalive.gr/opinions/poios-kathorizei-thn-tychh-mas">
            <picture>
    <!--[if IE 9]><video style="display: none;><![endif]-->
                <source
        data-srcset="https://cdn.cretalive.gr/authors/_authorThumb/K_MALIOTAKI.jpg?mtime=20160331164858" />
    <!--[if IE 9]></video><![endif]-->
    <img
        src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
        data-srcset="https://cdn.cretalive.gr/authors/_authorThumb/K_MALIOTAKI.jpg?mtime=20160331164858"
        class="lazyload media-object"
        alt="Ποιος καθορίζει την τύχη μας;&lt;small&gt; Κατερίνα Μαλλιωτάκη&lt;/small&gt;" />
</picture>

        </a>
    </div><!-- /.media-left -->
    <div class="media-body">
                <p class="top-story-p mb0">
            <a href="//www.cretalive.gr/opinions/poios-kathorizei-thn-tychh-mas" class="secondary-link">Ποιος καθορίζει την τύχη μας;<small> Κατερίνα Μαλλιωτάκη</small></a>
                                            </p>
    </div><!-- /.media-body -->
</div><!-- /.media -->

        </div>
                        </div><!-- /.row -->
            </div><!-- /.col-md-4 -->
        </div><!-- /.row .no-margin -->
    </section><!-- /#history-opinions -->
                <section id="sectionBusiness" style="min-height: 100px;"><img src="/img/rolling.gif" class="center-block" height="30" style="margin-top: 50px;" /></section>
    <section id="sectionSports" style="min-height: 100px;"><img src="/img/rolling.gif" class="center-block" height="30" style="margin-top: 50px;" /></section>
    <section id="sectionHealth" style="min-height: 100px;"><img src="/img/rolling.gif" class="center-block" height="30" style="margin-top: 50px;" /></section>
    <section id="sectionCulture" style="min-height: 100px;"><img src="/img/rolling.gif" class="center-block" height="30" style="margin-top: 50px;" /></section>
    <section id="sectionLifestyle" style="min-height: 100px;"><img src="/img/rolling.gif" class="center-block" height="30" style="margin-top: 50px;" /></section>
    <!-- Footer -->
    <div class="visible-xs"><div id='mob_mr_2' class="center-block" style='width:300px; margin-top: 0px; margin-bottom: 0px;'>
    <script type='text/javascript'>
        googletag.cmd.push(function() { googletag.display('mob_mr_2'); });
    </script>
</div>
</div>
<!-- Footer-->
<footer id="footer" class="mt20">
    <div class="row p15 hidden-print">
        <div class="col-md-8" id="footerArticles"><img src="/img/rolling.gif" class="center-block" height="30" /></div>
        <div class="col-sm-6 col-md-4">
            <div class="row">
                <div class="col-xs-6 col-sm-6 col-md-6">
                    <ul class="list-unstyled">
                        <li><a href="https://www.cretalive.gr/" class="secondary-link font16">Αρχική</a></li>
                        <li><a href="https://www.cretalive.gr/news" class="secondary-link font16">Eπικαιρότητα</a></li>
                        <li><a href="https://www.cretalive.gr/crete" class="secondary-link font16">Κρήτη</a></li>
                        <li><a href="https://www.cretalive.gr/ellada" class="secondary-link font16">Ελλάδα</a></li>
                        <li><a href="https://www.cretalive.gr/business" class="secondary-link font16">Business</a></li>
                        <li><a href="https://www.cretalive.gr/polites" class="secondary-link font16">Πολίτες</a></li>
                        <li><a href="https://www.cretalive.gr/isawihear" class="secondary-link font16">Είδα - Άκουσα</a></li>
                        <li><a href="https://www.cretalive.gr/world" class="secondary-link font16">Κόσμος</a></li>
                    </ul>
                </div>
                <div class="col-xs-6 col-sm-6 col-md-6">
                    <ul class="list-unstyled">
                        <li><a href="https://www.cretalive.gr/science" class="secondary-link font16">Επιστήμες</a></li>
                                                <li><a href="https://www.cretalive.gr/opinions" class="secondary-link font16">Απόψεις</a></li>
                        <li><a href="https://www.cretalive.gr/culture" class="secondary-link font16">Πολιτισμός</a></li>
                        <li><a href="https://www.cretalive.gr/health" class="secondary-link font16">Υγεία</a></li>
                        <li><a href="https://www.cretalive.gr/lifestyle" class="secondary-link font16">Lifestyle</a></li>
                    </ul>
                    <a href="https://www.facebook.com/pages/Cretalivegr/136239276386619" target="_blank"><img src="/img/icons/facebook-i.png" width="24" height="24" alt=""></a>
                    <a href="http://twitter.com/cretalive" target="_blank"><img src="/img/icons/twitter-i.png" width="24" height="24" alt=""></a>
                    <a href="https://plus.google.com/+cretalivegr" target="_blank"><img src="/img/icons/google-plus-i.png" width="24" height="24" alt=""></a>
                    <a href="https://www.youtube.com/c/CretaliveGr" target="_blank"><img src="/img/icons/youtube-i.png" width="24" height="24" alt=""></a>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 col-lg-8 hidden-xs">
            <div class="banner-wrapper-with-margin bg-black text-center">
                                
    <div class="row hidden-xs" style="margin-top: 0px; margin-bottom: 0px;">
        <div class="col-md-12">
            <div id='home_footer_lb' class='center-block ' style='height:90px; width:728px;'>
                <script type='text/javascript'>
                    googletag.cmd.push(function() {
                        googletag.display('home_footer_lb');
                    });
                </script>
            </div><!-- /#div-gpt-ad... -->
        </div><!-- /.col-md-12 -->
    </div><!-- /.row .hidden-xs -->

            </div>
        </div>
        <div class="col-md-12 col-lg-4 text-center">
            <img src="/img/logos/CreataliveLogoInvertedPNG24.png" width="250" height="68" class="footer-logo" alt="Cretalive">
        </div>
    </div>
    <div class="row bt-white-1px mt10">
        <div class="col-md-8">
            <p class="copyright">
                <ul class="list-inline font16 ml10 white">
                    <li><i class="glyphicon glyphicon-copyright-mark"></i> 2010 - 2018 Cretalive ΕΠΕ, Δικτυακές Πύλες/Web Portal</li>
                    <li><a href="https://www.cretalive.gr/pages/oroi-chrhshs" class="white-link">Όροι χρήσης</a></li>
                    <li>|</li>
                    <li><a href="https://www.cretalive.gr/pages/prosopika-dedomena" class="white-link">Προσωπικά δεδομένα</a></li>
                    <li>|</li>
                    <li><a href="https://www.cretalive.gr/pages/epikoinonia" class="white-link">Επικοινωνία</a></li>
                    <li>|</li>
                    <li><a href="https://www.cretalive.gr/pages/statistika" class="white-link">Στατιστικά</a></li>
                </ul>
            </p>
        </div>
        <div class="col-md-4">
            <img src="/img/logos/awards2016.png" alt="Cretalive Awards" class="img-responsive">
        </div>
    </div>
</footer>
</div>
<!-- End Wrapper container -->

</div>
<!-- Document end-->
<script src="/js/min/common-min.js?v=1017"></script>
    


<!-- Google Analytics -->
<script>

(function(i, s, o, g, r, a, m) {
    i['GoogleAnalyticsObject'] = r;
    i[r] = i[r] || function() {
        (i[r].q = i[r].q || []).push(arguments)
    }, i[r].l = 1 * new Date();
    a = s.createElement(o),
        m = s.getElementsByTagName(o)[0];
    a.async = 1;
    a.src = g;
    m.parentNode.insertBefore(a, m)
})(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

ga('create', 'UA-1052676-25', 'auto');
ga('send', 'pageview');
</script>
<script type="text/javascript">
/*<![CDATA[*/
$(document).ready(function(){
        $.ajax(
            {
                url: "/ajax/section?sec=business",
                dataType: 'html',
                cache: true,
                success: function(data) {
                    $("#sectionBusiness").html(data);
                }
            }
        );
        $.ajax(
            {
                url: "/ajax/capitano",
                dataType: 'html',
                cache: true,
                success: function(data) {
                    $("#sectionSports").html(data);
                }
            }
        );
        $.ajax(
            {
                url: "/ajax/sectionAlt?sec=health",
                dataType: 'html',
                cache: true,
                success: function(data) {
                    $("#sectionHealth").html(data);
                }
            }
        );
        $.ajax(
            {
                url: "/ajax/section?sec=culture",
                dataType: 'html',
                cache: true,
                success: function(data) {
                    $("#sectionCulture").html(data);
                }
            }
        );
        $.ajax(
            {
                url: "/ajax/sectionAlt?sec=lifestyle",
                dataType: 'html',
                cache: true,
                success: function(data) {
                    $("#sectionLifestyle").html(data);
                }
            }
        );
    });

$(document).ready(function(){
        $.ajax(
            {
                url: "/ajax/footerArticles",
                dataType: 'html',
                cache: true,
                success: function(data) {
                    $("#footerArticles").html(data);
                }
            }
        );
    });
/*]]>*/
</script>
</body>

</html>