

<!DOCTYPE html>
<html lang="sk" xmlns:fb="http://www.facebook.com/2008/fbml" xmlns:og="http://opengraphprotocol.org/schema/">
<head>

    <title> Najlepšie recepty na každú príležitosť  | Kuchyňa Lidla </title>
    <meta http-equiv="X-UA-Compatible" content="IE=10" />
    <meta http-equiv="X-UA-Compatible" content="chrome=1" />
    <meta charset="UTF-8" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

    <!--[if lt IE 9]>
        <script src="/Scripts/html5shiv.js"></script>
    <![endif]-->
 



	<style>
    body {display: none;}
    </style>
   


    <link href="/bundles/content/print.css?v=XCBZA3WATHtpL93s-nkvaU9B465ZNcbCpT9jLzXVyFk1" rel="stylesheet" type="text/css" media="print" />

    
    <link href="/Content/images/nowyformat/favicon-16.ico" rel="shortcut icon" />
	<link href="/Content/images/nowyformat/favicon-64.ico" rel="apple-touch-icon" sizes="64x64" />
	<link href="/Content/images/nowyformat/favicon-48.ico" rel="apple-touch-icon" sizes="48x48" />
	<link href="/Content/images/nowyformat/favicon-32.ico" rel="apple-touch-icon" sizes="32x32" />
	
  
    <script src="/bundles/scripts/jquery.js?v=jyist1l_9DURXrnqT9ML2zNlKggLN8u_zVumH4lRjME1"></script>

    <script src="/bundles/scripts/portal.js?v=qmeAuiNe9pNpslu5uwxFKFofK9rn-_3N295IrwqGVBc1"></script>


  


  

  

  
  

  
    <meta name="description" content="Na stránke kuchynalidla.sk nájdeš recepty na každú príležitosť." />
    <meta property="og:title" content="Kuchyňa Lidla" />
    <meta property="og:description" content="Na stránke kuchynalidla.sk nájdeš recepty na každú príležitosť." />
    <meta property="og:image" content="https://kuchynalidla.sk/Content/images/nowyformat/og.png" />
    <meta name="p:domain_verify" content="ed61f676c00ef743a6328d1c8ff22807" />









  <meta property="og:url" content="https://kuchynalidla.sk/?utm_source=NLchefs&utm_medium=KW12&utm_campaign=kuchynalidla" /> 
   <script src='//www.google.com/recaptcha/api.js?onload=myCallBack&render=explicit' async defer></script>
    
	
 


</head>

<body class="start
    ">

<script>
    dataLayer = [{}];
        dataLayer.push({ 'pagetype': 'homepage' });
   
</script>

<!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-NV4QHZ"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function (w, d, s, l, i) {
w[l] = w[l] || []; w[l].push({
'gtm.start':
new Date().getTime(), event: 'gtm.js'
}); var f = d.getElementsByTagName(s)[0],
j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : ''; j.async = true; j.src =
'//www.googletagmanager.com/gtm.js?id=' + i + dl; f.parentNode.insertBefore(j, f);
})(window, document, 'script', 'dataLayer', 'GTM-NV4QHZ');</script>
<!-- End Google Tag Manager -->


<div id="#allpage">

<header>

    <div class="dark_panel clearfix container">
      <nav class="main_logo left"><a href="/"><img src="/Content/images/nowyformat/logo-lidl.png" alt="Lidl"> <span><img src="/Content/images/nowyformat/logo-kuchyna.png" alt="Kuchyňa Lidla"></span></a></nav>
      
		<nav class="header_logotypes left mobile2_hide">
		  <ul>



                <li class="priamo-header-ico"> <a href="/priamozpece"  ><img src="https://kuchynalidla.sk/img/SK/img/d8a0a0e9b05e-priamo-menu.png" alt="Priamo z pece"></a></li>
                <li class="cukraren-header-ico"> <a href="/lidl-cukraren"  ><img src="https://kuchynalidla.sk/img/SK/img/62316345de07-cukraren-menu.png" alt="Lidl Cukraren"></a></li>
                <li class="stanok-header-ico"> <a href="/lidl-stanok"  ><img src="https://kuchynalidla.sk/img/SK/img/99009e45677a-stanok-menu.png" alt="Lidl Stanok"></a></li>
                <li class="butcher-header-ico"> <a href="/maso"  ><img src="https://kuchynalidla.sk/img/SK/img/20170530033352-masiar_menu.png" alt="M&#228;siarova Čerstv&#225; Porcia"></a></li>
                <li class="grill-header-ico"> <a href="/grill"  ><img src="https://kuchynalidla.sk/img/SK/img/4a658a5874d4-grill-menu.png" alt="Grill &amp; Fun"></a></li>
                <li class="vinoteka-header-ico"> <a href="/lidl-vinoteka"  ><img src="https://kuchynalidla.sk/img/SK/img/a41d81871e22-vinoteka-menu.png" alt="Lidl Vinoteka"></a></li>

		  </ul>
		</nav>   

      <button class="desktop_hide search_trigger">Open Search</button>
      
      <div class="right">
      




   <nav class="main_menu left dl-menuwrapper" id="dl-menu">
       <button class="dl-trigger desktop_hide">Open Menu</button>
        <ul class="dl-menu">

<li class="dropdown"><a href="/recepty"  class=""><span>Recepty</span></a>
        <ul class="dl-submenu">   

<li class=" main-dish"><a href="/recepty/hlavne-jedla"  class="main-dish"><span>Hlavn&#233; jedl&#225;</span></a>
</li>



            
<li class=" soup"><a href="/recepty/polievky"  class="soup"><span>Polievky</span></a>
</li>



            
<li class=" salad"><a href="/recepty/salaty"  class="salad"><span>Šal&#225;ty</span></a>
</li>



            
<li class=" dessert"><a href="/recepty/dezerty"  class="dessert"><span>Dezerty</span></a>
</li>



            
<li class=" drink"><a href="/recepty/napoje"  class="drink"><span>N&#225;poje</span></a>
</li>



            
<li class=" chutovky"><a href="/recepty/chutovky"  class="chutovky"><span>Chuťovky</span></a>
</li>



            
<li class="dropdown"><a href="#"  class=""><span>Kuch&#225;r</span></a>
        <ul class="dl-submenu">   

<li class=""><a href="/recepty/paulus"  class=""><span>Roman Paulus</span></a>
</li>



            
<li class=""><a href="/recepty/ihnacak"  class=""><span>Marcel Ihnač&#225;k</span></a>
</li>



            
<li class=""><a href="/recepty/veronika-busova"  class=""><span>Veronika Bušov&#225;</span></a>
</li>



            
<li class=""><a href="/recepty/polakova"  class=""><span>Adriana Pol&#225;kov&#225;</span></a>
</li>



            
<li class=""><a href="/recepty/lidl"  class=""><span>Lidl</span></a>
</li>



                    </ul>          
</li>



            
<li class=" priamozpece"><a href="/priamozpece"  class="priamozpece"><span>Priamo z pece</span></a>
</li>



            
<li class="dropdown"><a href="#"  class=""><span>Pr&#237;ležitosť </span></a>
        <ul class="dl-submenu">   

<li class=""><a href="/recepty/gril-1"  class=""><span>Gril</span></a>
</li>



            
<li class=""><a href="/recepty/valentin"  class=""><span>Valent&#237;n</span></a>
</li>



            
<li class=""><a href="/recepty/deti"  class=""><span>Pre deti</span></a>
</li>



            
<li class=""><a href="/recepty/party"  class=""><span>Party</span></a>
</li>



            
<li class=""><a href="/recepty/velka-noc"  class=""><span>Veľk&#225; noc</span></a>
</li>



            
<li class=""><a href="/recepty/vianoce"  class=""><span>Vianoce</span></a>
</li>



                    </ul>          
</li>



            
<li class=""><a href="/recepty"  class=""><span>Všetko</span></a>
</li>



                    </ul>          
</li>



            
<li class="dropdown"><a href="/blogy"  class=""><span>Blog</span></a>
        <ul class="dl-submenu">   

<li class=" co-nowego"><a href="/blogy/novinky"  class="co-nowego"><span>Novinky</span></a>
</li>



            
<li class=" Triki"><a href="/blogy/triky"  class="Triki"><span>Triky</span></a>
</li>



            
<li class=" grill"><a href="/blogy/gril-2"  class="grill"><span>Grill &amp; Fun</span></a>
</li>



            
<li class=""><a href="/blogy/vinoteka"  class=""><span>Vinot&#233;ka</span></a>
</li>



            
<li class=""><a href="/blogy"  class=""><span>Všetko</span></a>
</li>



                    </ul>          
</li>



            
<li class=""><a href="http://www.lidl.sk/" target=&quot;_blank&quot; class=""><span>Lidl.sk</span></a>
</li>



            
          
                 <li class="desktop_hide" ><a href="https://kuchynalidla.sk/Account/Login?returnUrl=%2F">Prihlásenie</a></li>
         <li class="desktop_hide" ><a href="https://kuchynalidla.sk/Account/Register?returnUrl=%2F">Registrácia</a></li>


        <li class="dropdown desktop_hide2">
			<a href="#"><span>Kategórie</span></a>
			<ul class="dl-submenu">    


                <li class="priamo-header-ico"> <a href="/priamozpece"  ><img src="https://kuchynalidla.sk/img/SK/img/d8a0a0e9b05e-priamo-menu.png" alt="Priamo z pece"></a></li>
                <li class="cukraren-header-ico"> <a href="/lidl-cukraren"  ><img src="https://kuchynalidla.sk/img/SK/img/62316345de07-cukraren-menu.png" alt="Lidl Cukraren"></a></li>
                <li class="stanok-header-ico"> <a href="/lidl-stanok"  ><img src="https://kuchynalidla.sk/img/SK/img/99009e45677a-stanok-menu.png" alt="Lidl Stanok"></a></li>
                <li class="butcher-header-ico"> <a href="/maso"  ><img src="https://kuchynalidla.sk/img/SK/img/20170530033352-masiar_menu.png" alt="M&#228;siarova Čerstv&#225; Porcia"></a></li>
                <li class="grill-header-ico"> <a href="/grill"  ><img src="https://kuchynalidla.sk/img/SK/img/4a658a5874d4-grill-menu.png" alt="Grill &amp; Fun"></a></li>
                <li class="vinoteka-header-ico"> <a href="/lidl-vinoteka"  ><img src="https://kuchynalidla.sk/img/SK/img/a41d81871e22-vinoteka-menu.png" alt="Lidl Vinoteka"></a></li>
</ul>
		</li>
		
        </ul>
      </nav>
      <form method="get" action="/recepty" class="left search">                                    
        <input type="text" value="" placeholder="hľadaj&hellip;" name="SearchQuery"  class="text" onclick="dataLayer.push({ 'event': 'click-event', 'category': 'Menu', 'action': 'SearchLabel', 'label': '' })">
        <input type="submit" class="button" value="vyhľadávanie">
      </form>

      

      </div>

    
    
    <nav class="grey_menu right mobile_hide">
      <ul class="header_login right">
                <li class="" ><a href="https://kuchynalidla.sk/Account/Login?returnUrl=%2F">Prihlásenie</a></li>
         <li class="" ><a href="https://kuchynalidla.sk/Account/Register?returnUrl=%2F">Registrácia</a></li>

      </ul>
      <ul class="header_social right">
        <li><a href="https://www.facebook.com/lidlslovensko?fref=ts" target="_blank">Facebook</a></li>
        <li><a href="https://www.youtube.com/user/LIDLSlovensko?sub_confirmation=1" target="_blank">YouTube</a></li>
        <li><a href="https://instagram.com/lidlsk/" target="_blank">Instagram</a></li>
      </ul>
    </nav>

    </div>

</header>

<main>
<img src="/Content/images/nowyformat/kuchynalidla2.png" alt="Kuchyňa Lidla" class="logo_print">



<section class="cook_section">
  <div class="main_kv">
    <h1 class="hidden">Najchutnejšie recepty z Kuchyne Lidla od známych kuchárov</h1>
    
    <div class="clearfix">

          <div class="left cook_box col50 Pascal">

            <a href="/product/steak-s-cicerom--rukolou-a-parmezanom">
            <h2 class="cat">Marcel Ihnač&#225;k</h2>
            <h3>Steak s c&#237;cerom, rukolou a&#160;parmez&#225;nom</h3>
            <p><img src="https://kuchynalidla.sk/img/SK/376x276/20180314090614-09332 07605 lidl Kuchyna Lidla KW12 OBRAZOK HLAVNY RECEPT 653x414.jpg" alt="Steak s c&#237;cerom, rukolou a&#160;parmez&#225;nom"></p>
            </a>
          </div>
                   <div class="right cook_box col50 Okrasa">
            <a href="/product/cokoladove-cheesecake-vajicko">
            <h2 class="cat">Veronika Bušov&#225;</h2>
            <h3>Čokol&#225;dov&#233; cheesecake vaj&#237;čko</h3>
            <p><img src="https://kuchynalidla.sk/img/SK/376x276/20180314092829-09332 07605 lidl Kuchyna Lidla KW12 OBRAZOK SLADKY RECEPT 653x414.jpg" alt="Čokol&#225;dov&#233; cheesecake vaj&#237;čko"></p>
            </a>
          </div>         

    </div>
    
    <div class="search_panel">
      <h2>Vyhľadajte si recept</h2>
      <form method="get" action="/recepty" class="search">                                    
        <div class="search_panel_wrap">
          <input type="text" value="" placeholder="hľadaj&hellip;" name="SearchQuery" id="SearchQuery" class="text" onclick="dataLayer.push({ 'event': 'click-event', 'category': 'Top Recept', 'action': 'SearchLabel', 'label': '' })">
          <input type="submit" class="button" value="vyhľadávanie" >
        </div>
      </form>
    </div>

  </div> 

             <div class="cook_poster left"><p><img src="https://kuchynalidla.sk/img/SK/img/20180314102800-09332 07605 lidl Kuchyna Lidla KW12 HOMEPAGE 911x694 Marcel.jpg" alt="kuchár"></p></div>
                        <div class="cook_poster right"><p><img src="https://kuchynalidla.sk/img/SK/img/20180314102846-09332 07605 lidl Kuchyna Lidla KW12 HOMEPAGE 911x694 Veronika.jpg" alt="kuchár"></p></div>

</section>

<section class="main_cat_list_section">
<div class="container">
  <ul class="main_cat_list clearfix">
    <li class="ico_napoje"><a href="/recepty/napoje"><span><img src="Content/images/nowyformat/kategorie_napoje.png" alt="nápoje"></span> nápoje</a></li>
    <li class="ico_salaty"><a href="/recepty/salaty"><span><img src="Content/images/nowyformat/kategorie_salaty.png" alt="šaláty"></span> šaláty</a></li> 
    <li class="ico_polievky"><a href="/recepty/polievky"><span><img src="Content/images/nowyformat/kategorie_polievky.png" alt="polievky"></span> polievky</a></li>
    <li class="ico_hlavne"><a href="/recepty/hlavne-jedla"><span><img src="Content/images/nowyformat/kategorie_hlavne.png" alt="hlavné jedlá"></span> hlavné jedlá</a></li>
    <li class="ico_dezerty"><a href="/recepty/dezerty"><span><img src="Content/images/nowyformat/kategorie_dezerty.png" alt="dezerty"></span> dezerty</a></li>
  </ul>
</div>
</section>

<section>

<!-- mieso -->

<div class="clearfix container sweets_section meat_section" style="padding-top:0;">
    
	

	

    <div class="sweets_main_box left col50">
      <p><img src="Content/images/butcher/masiar.png" alt="Mäsiarova čerstvá porcia" class="sweets_main_logo"></p>
      <p>In&scaron;pirujte sa na&scaron;imi receptami a pripravte jedl&aacute; z r&ocirc;znych k&uacute;tov sveta s m&auml;som v hlavnej &uacute;lohe.</p>


      <p><a href="/maso" class="btn btn_burgundy btn_arrow">pozrite si</a></p>
      
	  <p><img src="Content/images/butcher/maso_home.png" alt="Mäso" class="sweets_main_poster"></p>

	  
    </div>
	
	
  <div class="top10_list right col50">
 
 <h3 class="subtitle">Najčítanejšie za 24 hod</h3>
 
    <div class="top10_list_wrap">
    <div class="nano"><div class="nano-content"> 

<div class="top10_box veronika-busova">
                <a href="/product/cokoladove-cheesecake-vajicko"> 
                    <p class="cat  ">Veronika Bušov&#225;</p> 
                    <h3>Čokol&#225;dov&#233; cheesecake vaj&#237;čko</h3>       
                    <p><img src="https://kuchynalidla.sk/img/SK/100x56/20180314092829-09332 07605 lidl Kuchyna Lidla KW12 OBRAZOK SLADKY RECEPT 653x414.jpg" alt="Čokol&#225;dov&#233; cheesecake vaj&#237;čko" class="top10_poster"></p>   
                </a>  
            </div>
<div class="top10_box polakova">
                <a href="/product/tvarohovy-cheesecake-s-jahodami"> 
                    <p class="cat  ">Adriana Pol&#225;kov&#225;</p> 
                    <h3>Tvarohov&#253; cheesecake s jahodam...</h3>       
                    <p><img src="https://kuchynalidla.sk/img/SK/100x56/201611071151-tvarohovy-cheesecake-s-jahodami_Adriana.jpg" alt="Tvarohov&#253; cheesecake s jahodami" class="top10_poster"></p>   
                </a>  
            </div>
<div class="top10_box polakova">
                <a href="/product/cheesecake-s-citronovym-kremom"> 
                    <p class="cat  ">Adriana Pol&#225;kov&#225;</p> 
                    <h3>Cheesecake s citr&#243;nov&#253;m kr&#233;mom</h3>       
                    <p><img src="https://kuchynalidla.sk/img/SK/100x56/201611071032-cheesecake-s-citronovym-kremom_Adriana.jpg" alt="Cheesecake s citr&#243;nov&#253;m kr&#233;mom" class="top10_poster"></p>   
                </a>  
            </div>
<div class="top10_box polakova">
                <a href="/product/tvarohovo-cokoladova-torta-s-ovocim"> 
                    <p class="cat  ">Adriana Pol&#225;kov&#225;</p> 
                    <h3>Tvarohovo-čokol&#225;dov&#225; torta s o...</h3>       
                    <p><img src="https://kuchynalidla.sk/img/SK/100x56/201611071044-tvarohovo-cokoladova-torta-s-ovocim_Adriana.jpg" alt="Tvarohovo-čokol&#225;dov&#225; torta s ovoc&#237;m" class="top10_poster"></p>   
                </a>  
            </div>
<div class="top10_box polakova">
                <a href="/product/lievance-na-tri-skvele-sposoby"> 
                    <p class="cat  ">Adriana Pol&#225;kov&#225;</p> 
                    <h3>Lievance na tri skvel&#233; sp&#244;soby</h3>       
                    <p><img src="https://kuchynalidla.sk/img/SK/100x56/201611071048-lievance-na-tri-skvele-sposoby_Adriana.jpg" alt="Lievance na tri skvel&#233; sp&#244;soby" class="top10_poster"></p>   
                </a>  
            </div>
<div class="top10_box lidl">
                <a href="/product/cesnakova-polievka"> 
                    <p class="cat  wege">Lidl</p> 
                    <h3>Cesnakov&#225; polievka</h3>       
                    <p><img src="https://kuchynalidla.sk/img/SK/100x56/201611071020-cesnakova-polievka_lidl.jpg" alt="Cesnakov&#225; polievka" class="top10_poster"></p>   
                </a>  
            </div>
<div class="top10_box ihnacak">
                <a href="/product/pizza-so-sunkou-a-salamou"> 
                    <p class="cat  ">Marcel Ihnač&#225;k</p> 
                    <h3>Pizza so šunkou a sal&#225;mou</h3>       
                    <p><img src="https://kuchynalidla.sk/img/SK/100x56/201611071028-pizza-so-sunkou-a-salamou_Marcel.jpg" alt="Pizza so šunkou a sal&#225;mou" class="top10_poster"></p>   
                </a>  
            </div>
<div class="top10_box paulus">
                <a href="/product/spagety-s-omackou-bolognese"> 
                    <p class="cat  ">Roman Paulus</p> 
                    <h3>Špagety s om&#225;čkou Bolognese</h3>       
                    <p><img src="https://kuchynalidla.sk/img/SK/100x56/201611071027-spagety-s-omackou-bolognese_Roman.jpg" alt="Špagety s om&#225;čkou Bolognese" class="top10_poster"></p>   
                </a>  
            </div>
<div class="top10_box polakova">
                <a href="/product/cokoladove-muffiny"> 
                    <p class="cat  ">Adriana Pol&#225;kov&#225;</p> 
                    <h3>Čokol&#225;dov&#233; muffiny</h3>       
                    <p><img src="https://kuchynalidla.sk/img/SK/100x56/7c8cbf3c7ff3-780109c22b88-Cokoladove_muffiny_Adriana_KW08_2017.jpg" alt="Čokol&#225;dov&#233; muffiny" class="top10_poster"></p>   
                </a>  
            </div>
<div class="top10_box ihnacak">
                <a href="/product/steak-s-cicerom--rukolou-a-parmezanom"> 
                    <p class="cat  ">Marcel Ihnač&#225;k</p> 
                    <h3>Steak s c&#237;cerom, rukolou a&#160;par...</h3>       
                    <p><img src="https://kuchynalidla.sk/img/SK/100x56/20180314090614-09332 07605 lidl Kuchyna Lidla KW12 OBRAZOK HLAVNY RECEPT 653x414.jpg" alt="Steak s c&#237;cerom, rukolou a&#160;parmez&#225;nom" class="top10_poster"></p>   
                </a>  
            </div>
      
          
    </div>
      </div></div>
  </div>



    
  </div>
<!---->
      
      
<div class="clearfix container sweets_section">
    <div class="col50 sweets_slider_col right">
     <div class="sweets_main_slider_wrapper carousel">
      <div id="sweets_main_slider" class="slides">
    


              <div class="sweets_main_slide slideItem Pawel">
                <a href="/product/cokoladove-cheesecake-vajicko">
                    <p><img src="https://kuchynalidla.sk/img/SK/280x295/20180314092829-09332 07605 lidl Kuchyna Lidla KW12 OBRAZOK SLADKY RECEPT 653x414.jpg" alt="Čokol&#225;dov&#233; cheesecake vaj&#237;čko" class="sweets_main_slide_poster"></p>  
                    <div class="sweets_main_slide_text">
                      <p class="cat">Veronika Bušov&#225;</p> 
                      <h3>Čokol&#225;dov&#233; cheesecake vaj&#237;čko</h3> 
                    </div>

                </a>
              </div>         
              <div class="sweets_main_slide slideItem Pawel">
                <a href="/product/briosky-s-vanilkovym-kremom">
                    <p><img src="https://kuchynalidla.sk/img/SK/280x295/20180307095416-09332 07454 lidl Kuchyna Lidla OBRAZOK SLADKY RECEPT 653x414.jpg" alt="Briošky s vanilkov&#253;m kr&#233;mom" class="sweets_main_slide_poster"></p>  
                    <div class="sweets_main_slide_text">
                      <p class="cat">Veronika Bušov&#225;</p> 
                      <h3>Briošky s vanilkov&#253;m kr&#233;mom</h3> 
                    </div>

                </a>
              </div>         
              <div class="sweets_main_slide slideItem Pawel">
                <a href="/product/rolada-s-jahodami-a-slahackou">
                    <p><img src="https://kuchynalidla.sk/img/SK/280x295/20180227020627-Rolada_s_jahodami_a_slahackou_busova.png" alt="Rol&#225;da s jahodami a šľahačkou" class="sweets_main_slide_poster"></p>  
                    <div class="sweets_main_slide_text">
                      <p class="cat">Veronika Bušov&#225;</p> 
                      <h3>Rol&#225;da s jahodami a šľahačkou</h3> 
                    </div>

                </a>
              </div>         
                        <div class="sweets_main_slide slideItem Pawel">
                <a href="/product/cokoladove-cheesecake-vajicko">
                    <p><img src="https://kuchynalidla.sk/img/SK/280x295/20180314092829-09332 07605 lidl Kuchyna Lidla KW12 OBRAZOK SLADKY RECEPT 653x414.jpg" alt="Čokol&#225;dov&#233; cheesecake vaj&#237;čko" class="sweets_main_slide_poster"></p>  
                    <div class="sweets_main_slide_text">
                      <p class="cat">Veronika Bušov&#225;</p> 
                      <h3>Čokol&#225;dov&#233; cheesecake vaj&#237;čko</h3> 
                    </div>

                </a>
              </div>         
              <div class="sweets_main_slide slideItem Pawel">
                <a href="/product/briosky-s-vanilkovym-kremom">
                    <p><img src="https://kuchynalidla.sk/img/SK/280x295/20180307095416-09332 07454 lidl Kuchyna Lidla OBRAZOK SLADKY RECEPT 653x414.jpg" alt="Briošky s vanilkov&#253;m kr&#233;mom" class="sweets_main_slide_poster"></p>  
                    <div class="sweets_main_slide_text">
                      <p class="cat">Veronika Bušov&#225;</p> 
                      <h3>Briošky s vanilkov&#253;m kr&#233;mom</h3> 
                    </div>

                </a>
              </div>         
              <div class="sweets_main_slide slideItem Pawel">
                <a href="/product/rolada-s-jahodami-a-slahackou">
                    <p><img src="https://kuchynalidla.sk/img/SK/280x295/20180227020627-Rolada_s_jahodami_a_slahackou_busova.png" alt="Rol&#225;da s jahodami a šľahačkou" class="sweets_main_slide_poster"></p>  
                    <div class="sweets_main_slide_text">
                      <p class="cat">Veronika Bušov&#225;</p> 
                      <h3>Rol&#225;da s jahodami a šľahačkou</h3> 
                    </div>

                </a>
              </div>         
          
      </div>
      
      </div>         
    </div>
    
    
    <div class="sweets_main_box col50 left">
      <p><img src="Content/images/nowyformat/cukraren_logo_modre.png" alt="Lidl Cukraren" class="sweets_main_logo"></p>
      <p>Vojdite do podmaniv&eacute;ho sveta pln&eacute;ho sladk&yacute;ch chut&iacute;. Odhaľte recepty na neodolateľn&eacute; torty, sladučk&eacute; kol&aacute;če a mnoho in&yacute;ch chutn&yacute;ch dobr&ocirc;t.</p>


      <p><a href="/lidl-cukraren" class="btn btn_blue btn_arrow">pozrite si</a></p>
      
	  <p><img src="Content/images/nowyformat/dezerty2.jpg" alt="dezerty" class="sweets_main_poster"></p>

	  
    </div>



    
  </div>


</section>

<section class="prod_slide_section">

<div class="container">

	   <h2>PODOBN&Eacute; RECEPTY</h2>

	<div class="prod_slide_wrapper clearfix">
	
    <div class="cycle-slideshow" 
      	data-cycle-fx="scrollHorz" 
      	data-cycle-timeout="0" 
      	data-cycle-prev=".prev-prod"
        data-cycle-next=".next-prod" 
      	data-cycle-slides=".prod_slide">
        
   



		<div class="prod_slide">
			

     <div class="prod_box  has_video ihnacak product1" data-id="3917">
        <a class="prod_box_wrap" href="/product/bravcove-stehno-plnene-susenou-sunkou--spenatom-a-gorgonzolou">
        
		<p class="img_wrap"><img alt="" src="https://kuchynalidla.sk/img/SK/263x148/201611071109-bravcove-stehno-plnene-susenou-sunkou-spenatom-a-gorgonzolou_Marcel.jpg" /></p>

        <ul class="meta clearfix"> 	
        
                <li title="čas" class="time">
1 <span>h</span>									</li>									
                <li title="úroveň" class="difficulty Medium">stredn&#253;</li>
                <li title="porcie" class="size">4  <span>porcie</span> </li>
        </ul> 
                <p class="cat">
                  Marcel Ihnač&#225;k</p>
               
				
				<h3>Bravčov&#233; stehno plnen&#233; sušenou šunkou, špen&#225;tom a gorgonzolou</h3>
                <p class="alignright"><span class="btn" onclick="dataLayer.push({ 'event': 'click-event', 'category': 'send', 'action': 'More', 'label': '' })">viac</span></p> 					
        </a>   
    </div>

     <div class="prod_box  has_video paulus product2" data-id="3918">
        <a class="prod_box_wrap" href="/product/bravcove-sote--s-pikantnou-klobasou-a-ryzou">
        
		<p class="img_wrap"><img alt="" src="https://kuchynalidla.sk/img/SK/263x148/201611071109-bravcove-sote-s-pikantnou-klobasou-a-ryzou_Roman.jpg" /></p>

        <ul class="meta clearfix"> 	
        
                <li title="čas" class="time">
					30 <span>min</span>				</li>									
                <li title="úroveň" class="difficulty Easy">jednoduch&#253;</li>
                <li title="porcie" class="size">4  <span>porcie</span> </li>
        </ul> 
                <p class="cat">
                  Roman Paulus</p>
               
				
				<h3>Bravčov&#233; sot&#233;  s pikantnou klob&#225;sou a ryžou</h3>
                <p class="alignright"><span class="btn" onclick="dataLayer.push({ 'event': 'click-event', 'category': 'send', 'action': 'More', 'label': '' })">viac</span></p> 					
        </a>   
    </div>

     <div class="prod_box  has_video ihnacak product3" data-id="5138">
        <a class="prod_box_wrap" href="/product/dusene-bravcove-kocky-s-balsamicom-a-hubami">
        
		<p class="img_wrap"><img alt="" src="https://kuchynalidla.sk/img/SK/263x148/201611071156-dusene-bravcove-kocky-s-balsamicom-a-hubami_Marcel.jpg" /></p>

        <ul class="meta clearfix"> 	
        
                <li title="čas" class="time">
1 <span>h</span>					15 <span>min</span>				</li>									
                <li title="úroveň" class="difficulty Medium">stredn&#253;</li>
                <li title="porcie" class="size">5  <span>porcií</span> </li>
        </ul> 
                <p class="cat">
                  Marcel Ihnač&#225;k</p>
               
				
				<h3>Dusen&#233; bravčov&#233; kocky s balsamicom a hubami</h3>
                <p class="alignright"><span class="btn" onclick="dataLayer.push({ 'event': 'click-event', 'category': 'send', 'action': 'More', 'label': '' })">viac</span></p> 					
        </a>   
    </div>

     <div class="prod_box  has_video paulus product4" data-id="5137">
        <a class="prod_box_wrap" href="/product/bravcove-kocky-na-vine-s-glazovanou-zeleninou">
        
		<p class="img_wrap"><img alt="" src="https://kuchynalidla.sk/img/SK/263x148/201611071156-bravcove-kocky-na-vine-s-glazovanou-zeleninou_Roman.jpg" /></p>

        <ul class="meta clearfix"> 	
        
                <li title="čas" class="time">
1 <span>h</span>					50 <span>min</span>				</li>									
                <li title="úroveň" class="difficulty Medium">stredn&#253;</li>
                <li title="porcie" class="size">4  <span>porcie</span> </li>
        </ul> 
                <p class="cat">
                  Roman Paulus</p>
               
				
				<h3>Bravčov&#233; kocky na v&#237;ne s glazovanou zeleninou</h3>
                <p class="alignright"><span class="btn" onclick="dataLayer.push({ 'event': 'click-event', 'category': 'send', 'action': 'More', 'label': '' })">viac</span></p> 					
        </a>   
    </div>
	   </div>
		<div class="prod_slide">
			

     <div class="prod_box  has_video ihnacak product5" data-id="5667">
        <a class="prod_box_wrap" href="/product/cicerovy-salat-s-konfitovanym-kralikom">
        
		<p class="img_wrap"><img alt="" src="https://kuchynalidla.sk/img/SK/263x148/20170323114145-cicerovy_salat_s_konfitovanym_kralikom_ihnacak.jpg" /></p>

        <ul class="meta clearfix"> 	
        
                <li title="čas" class="time">
2 <span>h</span>									</li>									
                <li title="úroveň" class="difficulty Medium">stredn&#253;</li>
                <li title="porcie" class="size">4  <span>porcie</span> </li>
        </ul> 
                <p class="cat">
                  Marcel Ihnač&#225;k</p>
               
				
				<h3>C&#237;cerov&#253; šal&#225;t s konfitovan&#253;m kr&#225;likom</h3>
                <p class="alignright"><span class="btn" onclick="dataLayer.push({ 'event': 'click-event', 'category': 'send', 'action': 'More', 'label': '' })">viac</span></p> 					
        </a>   
    </div>

     <div class="prod_box  has_video paulus product6" data-id="5803">
        <a class="prod_box_wrap" href="/product/krkovicka-so-zemiakmi--cuketou-a-pestom">
        
		<p class="img_wrap"><img alt="" src="https://kuchynalidla.sk/img/SK/263x148/20170822014104-Krkovicka_so_zemiakmi_cuketou_a_pestom_Roman_KW35_2017_24009_07082017_MJ1182_RGB_960x540.jpg" /></p>

        <ul class="meta clearfix"> 	
        
                <li title="čas" class="time">
					30 <span>min</span>				</li>									
                <li title="úroveň" class="difficulty Easy">jednoduch&#253;</li>
                <li title="porcie" class="size">4  <span>porcie</span> </li>
        </ul> 
                <p class="cat">
                  Roman Paulus</p>
               
				
				<h3>Krkovička so zemiakmi, cuketou a pestom</h3>
                <p class="alignright"><span class="btn" onclick="dataLayer.push({ 'event': 'click-event', 'category': 'send', 'action': 'More', 'label': '' })">viac</span></p> 					
        </a>   
    </div>

     <div class="prod_box  has_video ihnacak product7" data-id="2773">
        <a class="prod_box_wrap" href="/product/dusene-bravcove-s-paprikou-a-kyslou-kapustou">
        
		<p class="img_wrap"><img alt="" src="https://kuchynalidla.sk/img/SK/263x148/201611071048-dusene-bravcove-s-kyslou-kapustou_Marcel.jpg" /></p>

        <ul class="meta clearfix"> 	
        
                <li title="čas" class="time">
					50 <span>min</span>				</li>									
                <li title="úroveň" class="difficulty Easy">jednoduch&#253;</li>
                <li title="porcie" class="size">6  <span>porcií</span> </li>
        </ul> 
                <p class="cat">
                  Marcel Ihnač&#225;k</p>
               
				
				<h3>Dusen&#233; bravčov&#233; s paprikou a kyslou kapustou</h3>
                <p class="alignright"><span class="btn" onclick="dataLayer.push({ 'event': 'click-event', 'category': 'send', 'action': 'More', 'label': '' })">viac</span></p> 					
        </a>   
    </div>

     <div class="prod_box  has_video paulus product8" data-id="2774">
        <a class="prod_box_wrap" href="/product/bravcove-kocky-na-paprike">
        
		<p class="img_wrap"><img alt="" src="https://kuchynalidla.sk/img/SK/263x148/201611071048-bravcove-kocky-na-paprike_Roman.jpg" /></p>

        <ul class="meta clearfix"> 	
        
                <li title="čas" class="time">
1 <span>h</span>					30 <span>min</span>				</li>									
                <li title="úroveň" class="difficulty Easy">jednoduch&#253;</li>
                <li title="porcie" class="size">4  <span>porcie</span> </li>
        </ul> 
                <p class="cat">
                  Roman Paulus</p>
               
				
				<h3>Bravčov&#233; kocky na paprike</h3>
                <p class="alignright"><span class="btn" onclick="dataLayer.push({ 'event': 'click-event', 'category': 'send', 'action': 'More', 'label': '' })">viac</span></p> 					
        </a>   
    </div>
	   </div>




      
    </div><!-- /#prod_slide -->
  
		<a class="prev-prod" href="#">Prev</a> 
		<a class="next-prod" href="#">Next</a>
    
  </div> <!-- /prod_slide_wrapper -->
 </div> 
</section> 

<section>

<div class="clearfix container inne_prod_section">



    <h2>Iné recepty</h2>
	
	<div class="prod_slide_wrapper clearfix">
	
    <div class="cycle-slideshow" 
      	data-cycle-fx="scrollHorz" 
      	data-cycle-timeout="0" 
      	data-cycle-prev=".prev-prod2"
        data-cycle-next=".next-prod2" 
      	data-cycle-slides=".prod_slide">
        

  



		<div class="prod_slide">
			

     <div class="prod_box  has_video polakova product1" data-id="5007">
        <a class="prod_box_wrap" href="/product/sisky-so-smotanovym-kremom">
        
		<p class="img_wrap"><img alt="" src="https://kuchynalidla.sk/img/SK/263x148/201611071153-sisky-so-smotanovym-kremom_Adriana.jpg" /></p>

        <ul class="meta clearfix"> 	
        
                <li title="čas" class="time">
1 <span>h</span>									</li>									
                <li title="úroveň" class="difficulty Easy">jednoduch&#253;</li>
                <li title="porcie" class="size">20  <span>porcií</span> </li>
        </ul> 
                <p class="cat">
                  Adriana Pol&#225;kov&#225;</p>
               
				
				<h3>Šišky so smotanov&#253;m kr&#233;mom</h3>
                <p class="alignright"><span class="btn" onclick="dataLayer.push({ 'event': 'click-event', 'category': 'send', 'action': 'More', 'label': '' })">viac</span></p> 					
        </a>   
    </div>

     <div class="prod_box  lidl product2" data-id="1238">
        <a class="prod_box_wrap" href="/product/grilovany-camembert">
        
		<p class="img_wrap"><img alt="" src="https://kuchynalidla.sk/img/SK/263x148/201611071020-grilovany-camembert_lidl.jpg" /></p>

        <ul class="meta clearfix"> 	
        
                <li title="čas" class="time">
					45 <span>min</span>				</li>									
                <li title="úroveň" class="difficulty Easy">jednoduch&#253;</li>
                <li title="porcie" class="size">4  <span>porcie</span> </li>
        </ul> 
                <p class="cat">
                  Lidl</p>
                <span class="vege">  </span>
               
				
				<h3>Grilovan&#253; Camembert</h3>
                <p class="alignright"><span class="btn" onclick="dataLayer.push({ 'event': 'click-event', 'category': 'send', 'action': 'More', 'label': '' })">viac</span></p> 					
        </a>   
    </div>

     <div class="prod_box  has_video ihnacak product3" data-id="4753">
        <a class="prod_box_wrap" href="/product/domace-gnocchi-s-lososom-a-hraskom">
        
		<p class="img_wrap"><img alt="" src="https://kuchynalidla.sk/img/SK/263x148/201611071147-domace-gnocchi-s-lososom-a-hraskom_Marcel.jpg" /></p>

        <ul class="meta clearfix"> 	
        
                <li title="čas" class="time">
1 <span>h</span>					15 <span>min</span>				</li>									
                <li title="úroveň" class="difficulty Easy">jednoduch&#253;</li>
                <li title="porcie" class="size">4  <span>porcie</span> </li>
        </ul> 
                <p class="cat">
                  Marcel Ihnač&#225;k</p>
               
				
				<h3>Dom&#225;ce gnocchi s lososom a hr&#225;škom</h3>
                <p class="alignright"><span class="btn" onclick="dataLayer.push({ 'event': 'click-event', 'category': 'send', 'action': 'More', 'label': '' })">viac</span></p> 					
        </a>   
    </div>

     <div class="prod_box  has_video polakova product4" data-id="2772">
        <a class="prod_box_wrap" href="/product/lievance-na-tri-skvele-sposoby">
        
		<p class="img_wrap"><img alt="" src="https://kuchynalidla.sk/img/SK/263x148/201611071048-lievance-na-tri-skvele-sposoby_Adriana.jpg" /></p>

        <ul class="meta clearfix"> 	
        
                <li title="čas" class="time">
					20 <span>min</span>				</li>									
                <li title="úroveň" class="difficulty Easy">jednoduch&#253;</li>
                <li title="porcie" class="size">30  <span>porcií</span> </li>
        </ul> 
                <p class="cat">
                  Adriana Pol&#225;kov&#225;</p>
               
				
				<h3>Lievance na tri skvel&#233; sp&#244;soby</h3>
                <p class="alignright"><span class="btn" onclick="dataLayer.push({ 'event': 'click-event', 'category': 'send', 'action': 'More', 'label': '' })">viac</span></p> 					
        </a>   
    </div>
	   </div>
		<div class="prod_slide">
			

     <div class="prod_box  has_video paulus product5" data-id="5793">
        <a class="prod_box_wrap" href="/product/hovadzia-rostenka-na-hubach">
        
		<p class="img_wrap"><img alt="" src="https://kuchynalidla.sk/img/SK/263x148/20170810021217-Hovadzia_rostenka_na_hubach_KW_32_PAULUS_23776_0716_960x540.jpg" /></p>

        <ul class="meta clearfix"> 	
        
                <li title="čas" class="time">
2 <span>h</span>					30 <span>min</span>				</li>									
                <li title="úroveň" class="difficulty Hard">obtiažny</li>
                <li title="porcie" class="size">4  <span>porcie</span> </li>
        </ul> 
                <p class="cat">
                  Roman Paulus</p>
               
				
				<h3>Hov&#228;dzia roštenka na hub&#225;ch</h3>
                <p class="alignright"><span class="btn" onclick="dataLayer.push({ 'event': 'click-event', 'category': 'send', 'action': 'More', 'label': '' })">viac</span></p> 					
        </a>   
    </div>

     <div class="prod_box  lidl product6" data-id="2219">
        <a class="prod_box_wrap" href="/product/mrkvovo---jablkovy-salat">
        
		<p class="img_wrap"><img alt="" src="https://kuchynalidla.sk/img/SK/263x148/201611071037-mrkvovo-jablkovy-salat_lidl.jpg" /></p>

        <ul class="meta clearfix"> 	
        
                <li title="čas" class="time">
					20 <span>min</span>				</li>									
                <li title="úroveň" class="difficulty Easy">jednoduch&#253;</li>
                <li title="porcie" class="size">4  <span>porcie</span> </li>
        </ul> 
                <p class="cat">
                  Lidl</p>
                <span class="vege">  </span>
               
				
				<h3>Mrkvovo - jablkov&#253; šal&#225;t</h3>
                <p class="alignright"><span class="btn" onclick="dataLayer.push({ 'event': 'click-event', 'category': 'send', 'action': 'More', 'label': '' })">viac</span></p> 					
        </a>   
    </div>

     <div class="prod_box  has_video ihnacak product7" data-id="1607">
        <a class="prod_box_wrap" href="/product/pizza-so-sunkou-a-salamou">
        
		<p class="img_wrap"><img alt="" src="https://kuchynalidla.sk/img/SK/263x148/201611071028-pizza-so-sunkou-a-salamou_Marcel.jpg" /></p>

        <ul class="meta clearfix"> 	
        
                <li title="čas" class="time">
1 <span>h</span>									</li>									
                <li title="úroveň" class="difficulty Easy">jednoduch&#253;</li>
                <li title="porcie" class="size">2  <span>porcie</span> </li>
        </ul> 
                <p class="cat">
                  Marcel Ihnač&#225;k</p>
               
				
				<h3>Pizza so šunkou a sal&#225;mou</h3>
                <p class="alignright"><span class="btn" onclick="dataLayer.push({ 'event': 'click-event', 'category': 'send', 'action': 'More', 'label': '' })">viac</span></p> 					
        </a>   
    </div>

     <div class="prod_box  has_video paulus product8" data-id="1573">
        <a class="prod_box_wrap" href="/product/pecene-vykostene-kurca-so-zemlovou-plnkou">
        
		<p class="img_wrap"><img alt="" src="https://kuchynalidla.sk/img/SK/263x148/201611071028-pecene-vykostene-kurca-so-zemlovou-plnkou_Roman.jpg" /></p>

        <ul class="meta clearfix"> 	
        
                <li title="čas" class="time">
1 <span>h</span>					45 <span>min</span>				</li>									
                <li title="úroveň" class="difficulty Medium">stredn&#253;</li>
                <li title="porcie" class="size">4  <span>porcie</span> </li>
        </ul> 
                <p class="cat">
                  Roman Paulus</p>
               
				
				<h3>Pečen&#233; vykosten&#233; kurča so žemľovou plnkou</h3>
                <p class="alignright"><span class="btn" onclick="dataLayer.push({ 'event': 'click-event', 'category': 'send', 'action': 'More', 'label': '' })">viac</span></p> 					
        </a>   
    </div>
	   </div>




      
    </div><!-- /#prod_slide -->
  
		<a class="prev-prod2" href="#">Prev</a> 
		<a class="next-prod2" href="#">Next</a>
    
  </div> <!-- /prod_slide_wrapper -->
  
  
  
  <p class="aligncenter"><a href="/recepty" class="btn btn_arrow" onclick="dataLayer.push({ 'event': 'click-event', 'category': 'send', 'action': 'More', 'label': '' })">viac</a></p>
</div>  
  
</section>  


<script src="/Scripts/templates/Home/index-scripts.js" type="text/javascript" async defer></script>





          
          


<section id="newsletter_sidebox">
            <h3 class="subtitle">Newsletter <br><span>Zaregistrujte sa</span></h3>
				<h3>Newsletter</h3>
	
	
				<form class="form lidlnewsletter" name="lidlnewsletter" id="lidlnewsletter" method="post" action="https://www.fagms.net/c/n" autocomplete="off">
				
					<input type="hidden" name="PLAUSIBILITY_email" id="PLAUSIBILITY_email" value="FILLED;EMAIL">
					<input type="hidden" name="PLAUSIBILITY_RED_email" id="PLAUSIBILITY_RED_email" value="https://kuchynalidla.sk/?newsletter=error#newsletterbox&amp;utm_source=NLchefs&amp;utm_medium=KW12&amp;utm_campaign=kuchynalidla">
					<input type="hidden" name="RED" id="RED" value="https://kuchynalidla.sk/?newsletter=confirmation#newsletterbox&amp;utm_source=NLchefs&amp;utm_medium=KW12&amp;utm_campaign=kuchynalidla">
					<input type="hidden" name="EMID" value="##EMID##">
					<input type="hidden" name="ACTION" id="ACTION" value="NEW">
					<input type="hidden" name="AID" id="AID" value="82501">
					<input type="hidden" name="newsletter" id="newsletter" value="true">
					<input type="hidden" name="type" id="type" value="subscribe">         

					  <div><label><input type="checkbox"> Čítal som Ochranu osobných údajov a súhlasím</label></div>
					  <div><input id="email" name="email" class="text" placeholder="e-mail" type="email"></div>
					  <div><input name="submit" value="Poslať" class="btn" type="submit"></div>
				  
				</form> 

			
</section>



</main>







<footer>
  <nav class="dark_panel clearfix container">
                  <ul>
                      <li><a href="http://www.lidl.sk/" target="_blank">Lidl.sk</a></li>
                      <li><a href="https://www.facebook.com/lidlslovensko?fref=ts" target="_blank">Facebook</a></li>
                      <li><a href="https://www.youtube.com/user/LIDLSlovensko?sub_confirmation=1" target="_blank">YouTube</a></li>
					  <li><a href="https://instagram.com/lidlsk/" target="_blank">Instagram</a></li>
                  </ul>
                    


    <ul>        
                <li><a href="/Home/Privacy">Ochrana osobn&#253;ch &#250;dajov</a></li>
                <li><a href="/Home/Terms">Pravidl&#225;</a></li>
                <li><a href="/Home/Contact">Kontakt</a></li>
                <li><a href="/newsletter">Prihl&#225;siť sa na odber newslettra</a></li>
                <li><a href="/Home/Unsubscribe">Odhl&#225;siť zasielanie newslettra</a></li>

    </ul>   


                  
                  
  </nav>                
</footer>

</div>

<link href="/Content/css/nowyformat/carousel.css" rel="stylesheet" type="text/css" media="screen" />
  <link rel='stylesheet' href='/Scripts/fancybox/jquery.fancybox-1.3.4.css' type='text/css' media='all' />
 <link href='//fonts.googleapis.com/css?family=Noto+Serif:400,400italic,700,700italic&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
	 
  
  
  <script src="/Scripts/jquery.carousel-1.1.min.js" async defer></script>
  <script src="/Scripts/jquery.cycle2.min.js"></script>
  <script src="/Scripts/jquery.nanoscroller.min.js"></script>
  <script src="/Scripts/modernizr.custom.js" async defer></script>
  <script src="/Scripts/jquery.dlmenu.js" async defer></script>
  <script src="/Scripts/cookies.js" async defer></script>
  <script src="/Scripts/watermark.min.js" async defer></script>
  <script src="/Scripts/fancybox/jquery.fancybox-1.3.4.js" async defer></script>
  <script src="/Scripts/jquery.cookie.js" async defer></script>
  <script src="/Scripts/functions.js" async defer></script>

    <script type="text/javascript">

    //variables for scripts in Scripts/templates/layout-scripts.js START
	var url = "https://kuchynalidla.sk/Account/Login?returnUrl=%2F";
        //variables for scripts in Scripts/templates/layout-scripts.js STOP

		



    </script>
    <script src="/Scripts/templates/layout-scripts.js" type="text/javascript" async defer></script>
	
		<script src="/Scripts/jquery.scrolldepth.min.js"></script>
	<script>
	jQuery(function() {
	  jQuery.scrollDepth();
	});
	</script>
	
	<script src="/Scripts/screentime.js"></script>
	
    <script>
		$.screentime({
		  fields: [
			{ selector: '#allpage',
			  name: 'allpage'
			}
		  ],
		  googleAnalytics: true
		});  
    </script>
	

     
	
	
      

<form action="/" id="__AjaxAntiForgeryForm" method="post"><input name="__RequestVerificationToken" type="hidden" value="Hx5UGT5NB5vqUTgJoSdk4KoQbzZ4LVRS69jga8o2hOiQ4g6k1KYTWUDtzg7jAlZsU8Tp7JrG-Z0_szCjAV4_G1WircwOQkji_MKRuLDlYOU1" /></form>	
	<link href="/bundles/content/portal.css?v=9GPr8XZ5b4SYv5omeTj80i_bgUgHlhJMbo_KY8ui8OI1 " rel="stylesheet" type="text/css" media="screen" />
	<style>
    body {display: block;}
    </style>
	
</body>
</html>