<!DOCTYPE html>
<html><head>
	<meta charset="utf-8" />
	<meta http-equiv="Content-Type", content="text/html; charset=utf-8" />
	<meta name="googlebot" content="noindex">
<style type="text/css">
* {font-family:Arial,Helvetica,sans-serif;}
html, body {margin:0; padding: 0; width:100%; }
body {font-size:14px; background:#ccc; }
</style>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<link rel="stylesheet" type="text/css" href="/assets/1ff8374b/css/bootstrap.css" />
<link rel="stylesheet" type="text/css" href="/assets/1ff8374b/css/bootstrap-responsive.css" />
<link rel="stylesheet" type="text/css" href="/assets/1ff8374b/css/bootstrap-yii.css" />
<link rel="stylesheet" type="text/css" href="/css/v3.1.css?3" />
<style type="text/css">
/*<![CDATA[*/
body {
	background-color: #ffffff;
	color: #000000;
}
body, label, input, button, select, textarea {
	font-size: 13px;
	line-height: 18px;
}
#chat-box {
	height: 300px;
}.comments .comment .meta, .comments .comment .meta a, .translator .info, .translator .info a { color: #bbb; }
.comments .comment:hover .meta, .comments .comment:hover .meta a, .translator tr:hover .info, .translator tr:hover .info a { color: #888; }
/*]]>*/
</style>
<script type="text/javascript" src="/assets/3b772e87/jquery.min.js"></script>
<script type="text/javascript" src="/assets/1ff8374b/js/bootstrap.js"></script>
<script type="text/javascript" src="/js/jquery.form.js"></script>
<script type="text/javascript" src="/js/jquery.cookie.js"></script>
<script type="text/javascript" src="/js/global.js?16"></script>
<script type="text/javascript">
/*<![CDATA[*/
var User = new CUser({id: 0, login: 'anonymous'});

/*]]>*/
</script>
</head>
<body>
	<style type="text/css">
	p, form { text-align: center; line-height: 100%;}
	p { width:800px; }
	p, em { font-family:Georgia, Times, serif; font-size:20px; margin: 20px auto; }
	p.first { margin-top: 80px; font-size: 40px; }
	p.first em { display: block; font-size: 60px; font-style: normal; font-weight: bold; }

	p.how { font-size: 14px; color: #888; font-style: italic; }

	p.flash { width: 200px; padding: 20px; font-size: 15px; border-radius: 10px; }
	p.flash.error { background-color: #FAC6AB; color: #f00; }
	p.flash.success { background-color: #b4fa96; color: #000000; }

	p.flash, form { width: 200px; }
	form { margin: 40px auto; }
	form input, form button, form a { display: block; margin: 5px 0; }
	form input { width: 100%;  }
	form a { text-align: right; color: #777; text-decoration: underline; }
</style>
<p class="first">
	Секретный клуб переводчиков
	<em>&laquo;Notabenoid&raquo;</em>
	им. С. Я. Маршака
</p>
<p>
	Вход только для членов клуба.
</p>
<form method="post" action="/">
	<input type="text" name="login[login]" placeholder="Логин" class="form-control" autofocus
		   value=""><br>
	<input type="password" name="login[pass]" placeholder="Пароль" class="form-control"><br>
	<a href="/register/remind">забыли?</a>
	<button type="submit" class="btn btn-success"><i class="icon icon-ok-circle icon-white"></i></button>
</form>
<p class="how">
	Если у вас был аккаунт на notabenoid.com и вы успели там перевести более 500 фрагментов, не заработав при этом
	отрицательного рейтинга или кармы, вы, скорее всего, уже являетесь членом клуба.
</p><script type="text/javascript">
/*<![CDATA[*/
jQuery(function($) {
jQuery('a.tooltip').tooltip({'placement':'bottom'});
jQuery('a[rel="popover"]').popover();
});
/*]]>*/
</script>
</body>
</html>