<!DOCTYPE html>
<html lang="ru-RU" dir="ltr">
    <head>
        <meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>Главный новостной портал города Одесса</title>
<meta name="description" lang="ru-ru" content="Odessa.net.ua - Городской портал Одессы - события, новости, интервью. Все самое интересное в одном месте.">
<meta name="keywords" lang="ru-ru" content="Одесса, новости, город, события, люди">
<meta name="author" lang="ru-ru" content="odessa.net.ua">
<meta property="og:title" content='Главный новостной портал города Одесса'>
<meta property="og:type" content="website">
<meta property="og:url" content="//odessa.net.ua/">
<meta property="og:image" content="//odessa.net.ua/Media/pic/logo.png">
<meta property="og:description" content='Odessa.net.ua - Городской портал Одессы - события, новости, интервью. Все самое интересное в одном месте.'>
<meta property="og:site_name" content="odessa.net.ua">
<meta name="HandheldFriendly" content="True">
<meta name="MobileOptimized" content="320">
<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="format-detection" content="telephone=no">
<meta name="format-detection" content="address=no">
<link rel="apple-touch-icon" sizes="57x57" href="/Media/favicons/apple-touch-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/Media/favicons/apple-touch-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/Media/favicons/apple-touch-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/Media/favicons/apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/Media/favicons/apple-touch-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/Media/favicons/apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/Media/favicons/apple-touch-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/Media/favicons/apple-touch-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/Media/favicons/apple-touch-icon-180x180.png">
<link rel="icon" type="image/png" href="/Media/favicons/favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="/Media/favicons/favicon-96x96.png" sizes="96x96">
<link rel="icon" type="image/png" href="/Media/favicons/android-chrome-192x192.png" sizes="192x192">
<link rel="icon" type="image/png" href="/Media/favicons/favicon-16x16.png" sizes="16x16">
<link rel="manifest" href="/Media/favicons/manifest.json">
<meta name="msapplication-config" content="/browserconfig.xml">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/Media/favicons/mstile-144x144.png">
<meta name="theme-color" content="#ffffff">
<meta name="apple-mobile-web-app-title" content="Главный новостной портал города Одесса">
<meta name="application-name" content="odessa.net.ua">
<meta name="msapplication-tooltip" content="Odessa.net.ua - Городской портал Одессы - события, новости, интервью. Все самое интересное в одном месте.">
<meta property="fb:pages" content="415864295238212" />
    <link type="text/css" href="//odessa.net.ua/Media/cache/minify_e419ea5446cd6bf9.css" rel="stylesheet" />
<!--[if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
    <script type="text/javascript" src="//odessa.net.ua/Media/cache/minify_c4d7b41cf3f1f804.js"></script>
                    <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-78263423-1', 'auto');
  ga('send', 'pageview');
  ga('create', 'UA-97190174-1', 'auto','guardnw');
  ga('guardnw.send', 'pageview');
</script>                    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-6543744359815149",
    enable_page_level_ads: true
  });
</script>                    </head>
    <body>
                <div class="wWrapper">
            <script>
    (function (d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id))
            return;
        js = d.createElement(s);
        js.id = id;
        js.src = "//connect.facebook.net/ru_RU/all.js#xfbml=1&version=v2.5&appId=1721025601465853";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
</script>
<div class="page-top">
    <div class="baddb page-top__baddb"><div class="baddb__item"><script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- odessa.net.ua -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-6543744359815149"
     data-ad-slot="4958027114"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script></div></div>    <header class="page-header">
        <div class="page-header__top">
            <div class="wSize">
                <div class="page-header__left">
                                            <div class="logo page-header__logo"><img src="/Media/pic/logo.png" alt="Logo"></div>
                                    </div>
                <div class="page-header__right">
                    <div class="page-header__right-item page-header__search-container">
                        <form action="/search" class="page-header__search wForm wFormSearch" data-form="true">
                            <div class="wFormInput">
                                <input type="search" class="wInput" id="header-search" name="query" required data-msg-required="Что будем искать?" data-rule-minlength="2" data-msg-minlength="Чтобы начать поиск нужно минимум 2 символа" placeholder="Поиск">
                                <button type="submit" class="wSubmit wBtn lg primary"><span class="svgHolder"><svg><use xlink:href="#icon_search" /></svg></span></button>
                            </div>
                        </form>
                    </div>
                    <div class="page-header__right-item page-header__socials-container">
                        <div class="socials">
                            <ul class="socials__list">
                                                                    <li class="socials__item">
                                        <a href=" https://www.facebook.com/odessa.net.ua/?ref=bookmarks" title="facebook" target="_blank">
                                            <svg>
                                            <use xlink:href="#icon_fb" />
                                            </svg>
                                        </a>
                                    </li>
                                                                                                                                                                                                    <li class="socials__item">
                                        <a href="https://t.me/odessa_net_ua" title="Telegram - kherson.net.ua" target="_blank">
                                            <svg>
                                            <use xlink:href="#icon_telegram" />
                                            </svg>
                                        </a>
                                    </li>
                                                                <li class="socials__item">
                                    <a href="/rss" title="RSS - kherson.net.ua" target="_blank">
                                        <svg>
                                        <use xlink:href="#icon_rss" />
                                        </svg>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="page-header__right-item page-header__mobile-btns-container">
                        <span class="link-btn link-btn--color3 page-header__link-btn js-header-search-toggle" title="Поиск"><i><svg><use xlink:href="#icon_search" /></svg></i><span>Поиск</span></span>
                        <a href="#mobile-menu" class="link-btn link-btn--color3 page-header__link-btn" title="Меню"><i><svg><use xlink:href="#icon_burger" /></svg></i><span>Меню</span></a>
                    </div>
                </div>
                <div class="page-header__middle">
                    <div class="cityList">
                        <div class="current-city">Другие регионы</div>
                        <div class="cityListBlock">
                            <ul>
                                                                                                            <li><a target="_blank" href="https://kherson.net.ua">Херсон</a></li>
                                                                                                                                                                                                                    <li><a target="_blank" href="http://dnepr24.com.ua">Днепр</a></li>
                                                                                                                                                <li><a target="_blank" href="http://gazeta.zp.ua">Запорожье</a></li>
                                                                                                                                                <li><a target="_blank" href="http://kr24.com.ua">Кривой Рог</a></li>
                                                                                                                                                <li><a target="_blank" href="http://nikolaev24.com.ua">Николаев</a></li>
                                                                                                </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="page-header__bottom">
            <div class="wSize">
                <nav class="main-nav">
                    <span class="main-nav__toggle js-main-nav-toggle" data-show="Ещё" data-hide="Скрыть"></span>
                    <ul class="main-nav__list">
                                                    <li class="main-nav__item ">
                                <a href="/news/fakty-ob-odesse" title="Факты об Одессе"><span>Факты об Одессе</span></a>
                            </li>
                                                    <li class="main-nav__item ">
                                <a href="/news/odessa-i-oblast" title="Одесса и область"><span>Одесса и область</span></a>
                            </li>
                                                    <li class="main-nav__item ">
                                <a href="/news/odessa-naiznanku" title="Одесса наизнанку"><span>Одесса наизнанку</span></a>
                            </li>
                                                    <li class="main-nav__item ">
                                <a href="/news/proisshestvija" title="Происшествия"><span>Происшествия</span></a>
                            </li>
                                                    <li class="main-nav__item ">
                                <a href="/news/sport" title="Спорт"><span>Спорт</span></a>
                            </li>
                                                    <li class="main-nav__item ">
                                <a href="/news/novoe_o_nas_" title="Новое о нас "><span>Новое о нас </span></a>
                            </li>
                                                    <li class="main-nav__item ">
                                <a href="/news/intervju" title="Интервью"><span>Интервью</span></a>
                            </li>
                                                    <li class="main-nav__item ">
                                <a href="/news/afisha" title="Афиша"><span>Афиша</span></a>
                            </li>
                                                    <li class="main-nav__item ">
                                <a href="/news/monitoring" title="Мониторинг"><span>Мониторинг</span></a>
                            </li>
                                                <li class="main-nav__item ">
                            <a href="/contacts" title="Контакты"><span>Контакты</span></a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
</div>
<div class="subscribe js-subscription" style="display:none">
    <div class="subscribe__inner">
        <div class="subscribe__close js-subscription__close"></div>
        <div class="subscribe__arrowBorder"></div>
        <div class="subscribe__arrow"></div>
        <div class="subscribe__text">Подписаться на уведомления от odessa.net.ua</div>
        <div class="subscribe__buttons">
            <div class="subscribe__buttons__button js-subscription__start">Подписаться</div>
            <div class="subscribe__buttons__button subscribe__buttons__button--decline js-subscription__decline">Отказаться</div>
        </div>
    </div>
</div>            <div class="wConteiner">
                <a target="_blank" href="http://lester.ua/?utm_source=odessa.net.ua&utm_medium=banner" class="full-page-ad" style="background: url(/Media/banners/images/3e0c417aaaa9d3fe5768abb6da459499.jpg) no-repeat center top;"></a>                <div class="top-baddb wSize"><div class="top-baddb__item"><img src="/Media/banners/images/844e5106202f15a169288ee29cbb0abf.jpg" alt="08.12.2017(1)" title="08.12.2017(1)" /></div></div>                <div class="page-content wSize">
                    <div class="page-section">
                        <div class="wRight">
                            <div class="wRight__item">
    <div class="news-aside">
        <div class="section-title"><span>Новости дня 18.03</span></div>
        <ul class="news-aside__list">
                                                            <li class="news-aside__item ">
                    <span class="news-aside__time">11:01</span>
                    <a href="/news/chempion-mira-po-boksu-iz-odesschiny-smotrit-v-buduschee-s-optimizmom" class="news-aside__heading" title="Чемпион мира по боксу из Одесщины смотрит в будущее с оптимизмом">
                        <span>Чемпион мира по боксу из Одесщины смотрит в будущее с оптимизмом</span>
                                                    <i><svg><use xlink:href="#icon_photo"/></svg></i>
                                                                    </a>
                </li>
                                                            <li class="news-aside__item ">
                    <span class="news-aside__time">10:22</span>
                    <a href="/news/v-odesse-proshlis-po-razdevalke-junyh-futbolistov--unesli-dazhe-dver" class="news-aside__heading" title="В Одессе «прошлись» по раздевалке юных футболистов — унесли даже дверь">
                        <span>В Одессе «прошлись» по раздевалке юных футболистов — унесли даже дверь</span>
                                                    <i><svg><use xlink:href="#icon_photo"/></svg></i>
                                                                    </a>
                </li>
                                                            <li class="news-aside__item ">
                    <span class="news-aside__time">09:41</span>
                    <a href="/news/priznanie-pravitelstva-v-odesskoj-oblasti-poluchilo-uzhe-12-gromad" class="news-aside__heading" title="Признание правительства в Одесской области получило уже 12 громад">
                        <span>Признание правительства в Одесской области получило уже 12 громад</span>
                                                                    </a>
                </li>
                                                            <li class="news-aside__item ">
                    <span class="news-aside__time">09:00</span>
                    <a href="/news/delo-pjanoj-odesskoj-chinovnitsy-svideteli-uvereny-chto-nakazanija-ne-budet" class="news-aside__heading" title="Дело пьяной одесской чиновницы: свидетели уверены, что наказания не будет">
                        <span>Дело пьяной одесской чиновницы: свидетели уверены, что наказания не будет</span>
                                                                    </a>
                </li>
                                                            <li class="news-aside__item ">
                    <span class="news-aside__time">08:30</span>
                    <a href="/news/neadekvat-pronik-k-odessitke-v-chastnyj-dom-video-18" class="news-aside__heading" title="Неадекват проник к одесситке в частный дом (ВИДЕО 18+)">
                        <span>Неадекват проник к одесситке в частный дом (ВИДЕО 18+)</span>
                                                                            <i><svg><use xlink:href="#icon_play"/></svg></i>
                                            </a>
                </li>
                                                            <li class="news-aside__item ">
                    <span class="news-aside__time">08:00</span>
                    <a href="/news/odesskim-medikam-kupjat-smartfonov-na-poltora-milliona" class="news-aside__heading" title="Одесским медикам купят смартфонов на полтора миллиона">
                        <span>Одесским медикам купят смартфонов на полтора миллиона</span>
                                                                    </a>
                </li>
                                                            <li class="news-aside__item ">
                    <span class="news-aside__time">07:30</span>
                    <a href="/news/za-titul-miss-vesna-borolis-pochtennye-odessitki" class="news-aside__heading" title="За титул "Мисс весна" боролись почтенные одесситки">
                        <span>За титул "Мисс весна" боролись почтенные одесситки</span>
                                                    <i><svg><use xlink:href="#icon_photo"/></svg></i>
                                                                    </a>
                </li>
                                                            <li class="news-aside__item ">
                    <span class="news-aside__time">07:00</span>
                    <a href="/news/iz-za-sostojanija-dorog-v-tarutinskom-rajone-prodovolstvie-postavljajut-spasateli-foto" class="news-aside__heading" title="Из-за состояния дорог в Тарутинском районе продовольствие поставляют спасатели (ФОТО)">
                        <span>Из-за состояния дорог в Тарутинском районе продовольствие поставляют спасатели (ФОТО)</span>
                                                    <i><svg><use xlink:href="#icon_photo"/></svg></i>
                                                                    </a>
                </li>
                                                            <li class="news-aside__item ">
                    <span class="news-aside__time">06:30</span>
                    <a href="/news/kak-odessity-den-svjatogo-patrika-otmechali-foto" class="news-aside__heading" title="Как одесситы День святого Патрика отмечали (ФОТО)">
                        <span>Как одесситы День святого Патрика отмечали (ФОТО)</span>
                                                    <i><svg><use xlink:href="#icon_photo"/></svg></i>
                                                                    </a>
                </li>
                                                                                    <div class="section-title"><span>Новости дня 17.03</span></div>
                                <li class="news-aside__item ">
                    <span class="news-aside__time">23:00</span>
                    <a href="/news/odesskoj-dolgozhitelnitse-ispolnilsja-101-god" class="news-aside__heading" title="Одесской долгожительнице исполнился 101 год">
                        <span>Одесской долгожительнице исполнился 101 год</span>
                                                                    </a>
                </li>
                                                        </ul>
    </div>
    <div class="baddb"><div class="baddb__item"><script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- http://odessa.net.ua/ -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-6543744359815149"
     data-ad-slot="2118115517"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script></div></div>            <div class="news-aside">
            <ul class="news-aside__list">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <li class="news-aside__item ">
                        <span class="news-aside__time">22:22</span>
                        <a href="/news/na-cheremushkah-dva-zhivodera-istjazali-i-ubili-malenkih-schenkov-foto-video" class="news-aside__heading" title="На Черёмушках два живодера истязали и убили маленьких щенков (ФОТО, ВИДЕО)">
                            <span>На Черёмушках два живодера истязали и убили маленьких щенков (ФОТО, ВИДЕО)</span>
                                                                                        <i><svg><use xlink:href="#icon_play"/></svg></i>
                                                    </a>
                    </li>
                                                                            <li class="news-aside__item ">
                        <span class="news-aside__time">21:42</span>
                        <a href="/news/zhk-v-rajone-tolbuhina-sdelajut-vdvoe-vyshe-chem-bylo-zadumano-" class="news-aside__heading" title="ЖК в районе Толбухина сделают вдвое выше, чем было задумано ">
                            <span>ЖК в районе Толбухина сделают вдвое выше, чем было задумано </span>
                                                                                </a>
                    </li>
                                                                            <li class="news-aside__item ">
                        <span class="news-aside__time">21:01</span>
                        <a href="/news/dtp-na-poselke-kotovskogo17032018" class="news-aside__heading" title="ДТП на посёлке Котовского">
                            <span>ДТП на посёлке Котовского</span>
                                                                                </a>
                    </li>
                                                                            <li class="news-aside__item ">
                        <span class="news-aside__time">20:20</span>
                        <a href="/news/s-etogo-uchebnogo-goda-odesskie-pervoklassniki-ne-budut-poluchat-otsenki" class="news-aside__heading" title="С этого учебного года одесские первоклассники не будут получать оценки">
                            <span>С этого учебного года одесские первоклассники не будут получать оценки</span>
                                                                                </a>
                    </li>
                                                                            <li class="news-aside__item ">
                        <span class="news-aside__time">19:38</span>
                        <a href="/news/top-5-elitnyh-domov-kotorye-prodajutsja-v-odesse" class="news-aside__heading" title="Топ-5 элитных домов, которые продаются в Одессе">
                            <span>Топ-5 элитных домов, которые продаются в Одессе</span>
                                                            <i><svg><use xlink:href="#icon_photo"/></svg></i>
                                                                                </a>
                    </li>
                                                                            <li class="news-aside__item ">
                        <span class="news-aside__time">19:00</span>
                        <a href="/news/novyj-transport-dlja-politsii-odessy-foto" class="news-aside__heading" title="Новый транспорт для полиции Одессы (ФОТО)">
                            <span>Новый транспорт для полиции Одессы (ФОТО)</span>
                                                            <i><svg><use xlink:href="#icon_photo"/></svg></i>
                                                                                </a>
                    </li>
                                                                            <li class="news-aside__item ">
                        <span class="news-aside__time">18:18</span>
                        <a href="/news/v-odesse-demontirovali-avarijnyj-balkon-foto" class="news-aside__heading" title="В Одессе демонтировали аварийный балкон (ФОТО)">
                            <span>В Одессе демонтировали аварийный балкон (ФОТО)</span>
                                                            <i><svg><use xlink:href="#icon_photo"/></svg></i>
                                                                                </a>
                    </li>
                                                                            <li class="news-aside__item ">
                        <span class="news-aside__time">17:37</span>
                        <a href="/news/odesskoj-politsii-planirujut-kupit-vertolet" class="news-aside__heading" title="Одесской полиции планируют купить вертолёт">
                            <span>Одесской полиции планируют купить вертолёт</span>
                                                                                </a>
                    </li>
                                                                            <li class="news-aside__item ">
                        <span class="news-aside__time">17:02</span>
                        <a href="/news/odesse-startoval-otborochnyj-etap-v-sbornuju-ukrainy-igr-nepokorennyh" class="news-aside__heading" title="В Одессе стартовал отборочный этап в сборную Украины "Игр Непокорённых"">
                            <span>В Одессе стартовал отборочный этап в сборную Украины "Игр Непокорённых"</span>
                                                                                </a>
                    </li>
                                                                            <li class="news-aside__item ">
                        <span class="news-aside__time">16:20</span>
                        <a href="/news/v-fevrale-odessity-tratili-na-pokupku-novogo-avto-35-tysjach-dollarov" class="news-aside__heading" title="В феврале одесситы тратили на покупку нового авто 35 тысяч долларов">
                            <span>В феврале одесситы тратили на покупку нового авто 35 тысяч долларов</span>
                                                                                </a>
                    </li>
                            </ul>
        </div>
    </div>                                 <div class="wRight__item mb15px">
        <div class="social-widgets">
            <div class="tabs social-widgets__tabs">
                <div class="tabs__nav">
                                            <span class="tabs__switcher js-tabs__switcher active" data-tab-container="tabs__items-container" data-tab-link="social-widgets__fb"><i><svg><use xlink:href="#icon_fb"/></svg></i></span>
                                                                                                </div>
                <div class="tabs__items-container">
                                                                <div class="tabs__item social-widgets__fb active"><div class="fb-page" data-href="https://www.facebook.com/odessa.net.ua/?ref=bookmarks" data-tabs="timeline" data-width="300" data-height="300" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><div class="fb-xfbml-parse-ignore"><blockquote cite="https://www.facebook.com/odessa.net.ua/?ref=bookmarks"><a href="https://www.facebook.com/odessa.net.ua/?ref=bookmarks">Odessa.net.ua</a></blockquote></div></div></div>
                                                                            </div>
            </div>
        </div>
    </div>
                            <div id="SinoptikInformer" style="width:100%;" class="SinoptikInformer type1">
    <div class="siHeader">
        <div class="siLh">
            <div class="siMh">
                <a onmousedown="siClickCount();" href="//sinoptik.ua" target="_blank">Погода</a>
                <a onmousedown="siClickCount();" class="siLogo" href="sinoptik.ua" target="_blank"> </a>
                <span id="siHeader"></span>
            </div>
        </div>
    </div>
    <div class="siBody">
        <div class="siCity">
            <div class="siCityName">
                <a onmousedown="siClickCount();" href="//sinoptik.ua/погода-одесса" target="_blank">Погода в <span>Одессе</span></a>
            </div>
            <div id="siCont0" class="siBodyContent">
                <div class="siLeft">
                    <div class="siTerm"></div>
                    <div class="siT" id="siT0"></div>
                    <div id="weatherIco0"></div></div>
                <div class="siInf">
                    <p>влажность:
                        <span id="vl0"></span>
                    </p>
                    <p>давление:
                        <span id="dav0"></span>
                    </p>
                    <p>ветер:
                        <span id="wind0"></span>
                    </p>
                </div>
            </div>
        </div>
        <div class="siLinks">
            <span>
                <a onmousedown="siClickCount();" href="//sinoptik.ua/погода-николаев" target="_blank">Погода в Николаеве</a> 
            </span>
            <span>
                <a onmousedown="siClickCount();" href="//sinoptik.ua/погода-херсон" target="_blank">Погода в Херсоне</a> 
            </span>
        </div>
    </div>
    <div class="siFooter">
        <div class="siLf">
            <div class="siMf"></div>
        </div>
    </div>
</div>
<script async type="text/javascript" charset="UTF-8" src="//sinoptik.ua/informers_js.php?title=4&wind=3&cities=303018950&lang=ru"></script>
<script src="http://s01.strichka.com/uploads/strichka/js/informer/city/od_5.js"></script>                        </div>
                        <div class="wMiddle">
    <div class="wMiddle__item">
        <div class="news-tiles">
            <ul class="news-tiles__list">
                                                                                                <li class="news-tiles__item ">
    <a class="news-tiles__item-inner" href="/news/dtp-na-balkovskoj-voditelja-posadili-v-sizo-bez-prava-na-zalog">
        <div class="news-tiles__img-container">
            <img src="/Media/images/news/small/4243db52528d514f8134c89ad670832d.jpg" alt="ДТП на Балковской: водителя посадили в СИЗО без права на залог" title="ДТП на Балковской: водителя посадили в СИЗО без права на залог">
        </div>
        <div class="news-tiles__info">
            <div class="news-tiles__info-top">
                                                            </div>
            <div class="news-tiles__title">
                                    <span>ДТП на Балковской: водителя посадили в СИЗО без права на залог</span>
                            </div>
            <div class="news-tiles__info-bottom">
                <span class="news-tiles__time">16 марта 2018, 17:02</span>
                <span class="news-tiles__views"><i><svg><use xlink:href="#icon_eye"/></svg></i><span>369</span></span>
            </div>
            <div class="news-tiles__info-short">
                                    <p>Виновника смертельного ДТП на Пересыпи, в результате которого двое пешеходов скончались на месте, а сам водитель с многочисленными травмами попал в больницу, посадили в СИЗО на&nbsp;два месяца, пока идёт следствие, без права выхода под залог</p>
                            </div>
        </div>
    </a>
</li>                                            <li class="news-tiles__item news-tiles__item--wide">
    <a class="news-tiles__item-inner" href="/news/ezhegodnyj-otchet-gennadija-truhanova-o-prodelannoj-rabote">
        <div class="news-tiles__img-container">
            <img src="/Media/images/news/big/f5eac90a0a9efe70a134259e5824cc1f.jpg" alt="Ежегодный отчёт Геннадия Труханова о проделанной работе" title="Ежегодный отчёт Геннадия Труханова о проделанной работе">
        </div>
        <div class="news-tiles__info">
            <div class="news-tiles__info-top">
                                                            </div>
            <div class="news-tiles__title">
                                    <span>Ежегодный отчёт Геннадия Труханова о проделанной работе</span>
                            </div>
            <div class="news-tiles__info-bottom">
                <span class="news-tiles__time">16 марта 2018, 15:38</span>
                <span class="news-tiles__views"><i><svg><use xlink:href="#icon_eye"/></svg></i><span>182</span></span>
            </div>
            <div class="news-tiles__info-short">
                                    <p>В здании Одесской&nbsp;евромэрии на&nbsp;Косовской, 2А, проходит отчёт городского головы Геннадия Труханова о проделанной за прошедший год работе</p>
                            </div>
        </div>
    </a>
</li>                                                                                    <li class="news-tiles__item ">
    <a class="news-tiles__item-inner" href="/news/initsiator-smertelnogo-dtp-v-odesse-uchastvoval-v-nezakonnyh-gonkah-foto">
        <div class="news-tiles__img-container">
            <img src="/Media/images/news/small/7921fa0e96d77597cfa7aab2b971febd.jpg" alt="Инициатор смертельного ДТП в Одессе участвовал в незаконных гонках (ФОТО)" title="Инициатор смертельного ДТП в Одессе участвовал в незаконных гонках (ФОТО)">
        </div>
        <div class="news-tiles__info">
            <div class="news-tiles__info-top">
                                    <span class="news-tiles__tag" style="background-color: #63c296;">Одесса и область</span>
                                                            </div>
            <div class="news-tiles__title">
                                    <span>Инициатор смертельного ДТП в Одессе участвовал в незаконных гонках (ФОТО)</span>
                            </div>
            <div class="news-tiles__info-bottom">
                <span class="news-tiles__time">11 марта 2018, 21:39</span>
                <span class="news-tiles__views"><i><svg><use xlink:href="#icon_eye"/></svg></i><span>3888</span></span>
            </div>
            <div class="news-tiles__info-short">
                                    <p>Коллеги-гонщики с тематических форумов Одессы и Украины признали в убийце &ldquo;своего&rdquo;</p>
                            </div>
        </div>
    </a>
</li>                                                                            <li class="news-tiles__item ">
    <a class="news-tiles__item-inner" href="/news/na-meste-dvuh-stolbov-v-odesse-sdelajut-mnogourovnevuju-razvjazku">
        <div class="news-tiles__img-container">
            <img src="/Media/images/news/small/c694a5086bb20ebe9bfa699dd65a1dd7.jpg" alt="На месте «Двух столбов» в Одессе сделают многоуровневую развязку" title="На месте «Двух столбов» в Одессе сделают многоуровневую развязку">
        </div>
        <div class="news-tiles__info">
            <div class="news-tiles__info-top">
                                    <span class="news-tiles__tag" style="background-color: #63c296;">Одесса и область</span>
                                                            </div>
            <div class="news-tiles__title">
                                    <span>На месте «Двух столбов» в Одессе сделают многоуровневую развязку</span>
                            </div>
            <div class="news-tiles__info-bottom">
                <span class="news-tiles__time">11 марта 2018, 07:00</span>
                <span class="news-tiles__views"><i><svg><use xlink:href="#icon_eye"/></svg></i><span>3524</span></span>
            </div>
            <div class="news-tiles__info-short">
                                    <p>Депутат Одесского облсовета Роман Сеник рассказал о планах на &laquo;Два столба&raquo;</p>
                            </div>
        </div>
    </a>
</li>                                                                            <li class="news-tiles__item ">
    <a class="news-tiles__item-inner" href="/news/odessu-ozhidaet-uhudshenie-pogodnyh-uslovij">
        <div class="news-tiles__img-container">
            <img src="/Media/images/news/small/c2b0ee4a870b3473006cd0db4834f3ea.jpeg" alt="Одессу ожидает ухудшение погодных условий" title="Одессу ожидает ухудшение погодных условий">
        </div>
        <div class="news-tiles__info">
            <div class="news-tiles__info-top">
                                    <span class="news-tiles__tag" style="background-color: #63c296;">Одесса и область</span>
                                                            </div>
            <div class="news-tiles__title">
                                    <span>Одессу ожидает ухудшение погодных условий</span>
                            </div>
            <div class="news-tiles__info-bottom">
                <span class="news-tiles__time">14 марта 2018, 20:01</span>
                <span class="news-tiles__views"><i><svg><use xlink:href="#icon_eye"/></svg></i><span>2978</span></span>
            </div>
            <div class="news-tiles__info-short">
                                    <p>Об этом официально сообщили синоптики Черного и Азовского морей</p>
                            </div>
        </div>
    </a>
</li>                                                                            <li class="news-tiles__item ">
    <a class="news-tiles__item-inner" href="/news/v-odesse-na-detskoj-ploschadke-zamechen-podozritelnyj-muzhchina-foto">
        <div class="news-tiles__img-container">
            <img src="/Media/images/news/small/30160d81dd3544d9827f6382e535b3df.jpg" alt="В Одессе на детской площадке замечен подозрительный мужчина (ФОТО)" title="В Одессе на детской площадке замечен подозрительный мужчина (ФОТО)">
        </div>
        <div class="news-tiles__info">
            <div class="news-tiles__info-top">
                                    <span class="news-tiles__tag" style="background-color: #63c296;">Одесса и область</span>
                                                            </div>
            <div class="news-tiles__title">
                                    <span>В Одессе на детской площадке замечен подозрительный мужчина (ФОТО)</span>
                            </div>
            <div class="news-tiles__info-bottom">
                <span class="news-tiles__time">11 марта 2018, 19:36</span>
                <span class="news-tiles__views"><i><svg><use xlink:href="#icon_eye"/></svg></i><span>2864</span></span>
            </div>
            <div class="news-tiles__info-short">
                                    <p>Мамочки бьют тревогу</p>
                            </div>
        </div>
    </a>
</li>                                                                            <li class="news-tiles__item ">
    <a class="news-tiles__item-inner" href="/news/aktivisty-predlagajut-szhech-magazin-za-georgievskie-tsveta">
        <div class="news-tiles__img-container">
            <img src="/Media/images/news/small/5a2257291ae3ecb63a34216c7ecd2785.jpg" alt="Активисты предлагают сжечь магазин за «георгиевские» цвета" title="Активисты предлагают сжечь магазин за «георгиевские» цвета">
        </div>
        <div class="news-tiles__info">
            <div class="news-tiles__info-top">
                                    <span class="news-tiles__tag" style="background-color: #63c296;">Одесса и область</span>
                                                            </div>
            <div class="news-tiles__title">
                                    <span>Активисты предлагают сжечь магазин за «георгиевские» цвета</span>
                            </div>
            <div class="news-tiles__info-bottom">
                <span class="news-tiles__time">10 марта 2018, 21:47</span>
                <span class="news-tiles__views"><i><svg><use xlink:href="#icon_eye"/></svg></i><span>4007</span></span>
            </div>
            <div class="news-tiles__info-short">
                                    <p>&laquo;От с***, спалити нах**&raquo;, &mdash; комментирует под фотографией активиста Штефана Фила другой активист Ромчик Гуцал запечатлённый на ней магазин с украшением из воздушных шаров &laquo;георгиевского&raquo; цвета</p>
                            </div>
        </div>
    </a>
</li>                                                                            <li class="news-tiles__item ">
    <a class="news-tiles__item-inner" href="/news/odessity-ischut-dengi-sprjatannye-po-vsemu-gorodu-foto">
        <div class="news-tiles__img-container">
            <img src="/Media/images/news/small/a88f0cec4961edb6391321b34400344d.jpeg" alt="Одесситы ищут деньги, спрятанные по всему городу (ФОТО)" title="Одесситы ищут деньги, спрятанные по всему городу (ФОТО)">
        </div>
        <div class="news-tiles__info">
            <div class="news-tiles__info-top">
                                    <span class="news-tiles__tag" style="background-color: #63c296;">Одесса и область</span>
                                                            </div>
            <div class="news-tiles__title">
                                    <span>Одесситы ищут деньги, спрятанные по всему городу (ФОТО)</span>
                            </div>
            <div class="news-tiles__info-bottom">
                <span class="news-tiles__time">13 марта 2018, 08:00</span>
                <span class="news-tiles__views"><i><svg><use xlink:href="#icon_eye"/></svg></i><span>2281</span></span>
            </div>
            <div class="news-tiles__info-short">
                                    <p>В популярной как за рубежом, так и у нас в стране соцсети Instsgram появилась новая страничка, которая популяризируется весьма необычным способом</p>
                            </div>
        </div>
    </a>
</li>                                                                            <li class="news-tiles__item ">
    <a class="news-tiles__item-inner" href="/news/odessitka-rasskazala-o-neprijatnom-intsidente-so-sluzhboj-dostavki-tsvetov">
        <div class="news-tiles__img-container">
            <img src="/Media/images/news/small/d0c0b39e1fcde79276f2d25dd9c64853.jpg" alt="Одесситка рассказала о неприятном инциденте со службой доставки цветов" title="Одесситка рассказала о неприятном инциденте со службой доставки цветов">
        </div>
        <div class="news-tiles__info">
            <div class="news-tiles__info-top">
                                    <span class="news-tiles__tag" style="background-color: #63c296;">Одесса и область</span>
                                                            </div>
            <div class="news-tiles__title">
                                    <span>Одесситка рассказала о неприятном инциденте со службой доставки цветов</span>
                            </div>
            <div class="news-tiles__info-bottom">
                <span class="news-tiles__time">11 марта 2018, 23:00</span>
                <span class="news-tiles__views"><i><svg><use xlink:href="#icon_eye"/></svg></i><span>2148</span></span>
            </div>
            <div class="news-tiles__info-short">
                                    <p>Подробности читайте в нашей статье</p>
                            </div>
        </div>
    </a>
</li>                                                                            <li class="news-tiles__item ">
    <a class="news-tiles__item-inner" href="/news/voennosluzhaschij-28-j-odesskoj-mehbrigady-ubil-cheloveka-video">
        <div class="news-tiles__img-container">
            <img src="/Media/images/news/small/25123437da2c36d99a2e3d27039030a5.jpg" alt="Военнослужащий 28-й одесской мехбригады убил человека (ВИДЕО)" title="Военнослужащий 28-й одесской мехбригады убил человека (ВИДЕО)">
        </div>
        <div class="news-tiles__info">
            <div class="news-tiles__info-top">
                                    <span class="news-tiles__tag" style="background-color: #63c296;">Одесса и область</span>
                                                            </div>
            <div class="news-tiles__title">
                                    <span>Военнослужащий 28-й одесской мехбригады убил человека (ВИДЕО)</span>
                            </div>
            <div class="news-tiles__info-bottom">
                <span class="news-tiles__time">12 марта 2018, 16:03</span>
                <span class="news-tiles__views"><i><svg><use xlink:href="#icon_eye"/></svg></i><span>2024</span></span>
            </div>
            <div class="news-tiles__info-short">
                                    <p>Парень скончался от потери крови по дороге в больницу</p>
                            </div>
        </div>
    </a>
</li>                                                                            <li class="news-tiles__item ">
    <a class="news-tiles__item-inner" href="/news/vnimaniju-odesskih-voditelej-ustanovlen-rjad-novyh-dorozhnyh-znakov">
        <div class="news-tiles__img-container">
            <img src="/Media/images/news/small/1fcda6a0ad32de3d9a70b7b2499654cf.jpg" alt="Вниманию одесских водителей: установлен ряд новых дорожных знаков" title="Вниманию одесских водителей: установлен ряд новых дорожных знаков">
        </div>
        <div class="news-tiles__info">
            <div class="news-tiles__info-top">
                                    <span class="news-tiles__tag" style="background-color: #63c296;">Одесса и область</span>
                                                            </div>
            <div class="news-tiles__title">
                                    <span>Вниманию одесских водителей: установлен ряд новых дорожных знаков</span>
                            </div>
            <div class="news-tiles__info-bottom">
                <span class="news-tiles__time">13 марта 2018, 22:03</span>
                <span class="news-tiles__views"><i><svg><use xlink:href="#icon_eye"/></svg></i><span>1985</span></span>
            </div>
            <div class="news-tiles__info-short">
                                    <p>Сотрудники КМ СМЭП установили в Одессе ряд новых дорожных знаков</p>
                            </div>
        </div>
    </a>
</li>                            </ul>
        </div>
    </div>
    <div class="wMiddle__item"><div class="baddb"><div class="banner__item"><script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- odessa.net.ua/news/odessa-i-oblast -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-6543744359815149"
     data-ad-slot="6646583110"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script></div></div></div>    <div class="wMiddle__item">
        <div class="news-tiles">
            <ul class="news-tiles__list">
                                                                                            <li class="news-tiles__item ">
    <a class="news-tiles__item-inner" href="/news/nochju-v-odesse-proizoshlo-dtp-est-pogibshie-foto">
        <div class="news-tiles__img-container">
            <img src="/Media/images/news/small/600167cce8000caaba0426fd5c9bd53d.jpg" alt="Ночью в Одессе произошло ДТП: есть погибшие (ФОТО)" title="Ночью в Одессе произошло ДТП: есть погибшие (ФОТО)">
        </div>
        <div class="news-tiles__info">
            <div class="news-tiles__info-top">
                                    <span class="news-tiles__tag" style="background-color: #63c296;">Одесса и область</span>
                                                            </div>
            <div class="news-tiles__title">
                                    <span>Ночью в Одессе произошло ДТП: есть погибшие (ФОТО)</span>
                            </div>
            <div class="news-tiles__info-bottom">
                <span class="news-tiles__time">11 марта 2018, 12:46</span>
                <span class="news-tiles__views"><i><svg><use xlink:href="#icon_eye"/></svg></i><span>1774</span></span>
            </div>
            <div class="news-tiles__info-short">
                                    <p>Легковушка сбила двоих и врезалась в столб</p>
                            </div>
        </div>
    </a>
</li>                                                                            <li class="news-tiles__item ">
    <a class="news-tiles__item-inner" href="/news/neravnodushnyj-odessit-sam-ubral-park-foto">
        <div class="news-tiles__img-container">
            <img src="/Media/images/news/small/62afb61c3a995e7d0fe93af6340a5573.jpg" alt="Неравнодушный одессит сам убрал парк (ФОТО)" title="Неравнодушный одессит сам убрал парк (ФОТО)">
        </div>
        <div class="news-tiles__info">
            <div class="news-tiles__info-top">
                                    <span class="news-tiles__tag" style="background-color: #63c296;">Одесса и область</span>
                                                            </div>
            <div class="news-tiles__title">
                                    <span>Неравнодушный одессит сам убрал парк (ФОТО)</span>
                            </div>
            <div class="news-tiles__info-bottom">
                <span class="news-tiles__time">11 марта 2018, 10:43</span>
                <span class="news-tiles__views"><i><svg><use xlink:href="#icon_eye"/></svg></i><span>1702</span></span>
            </div>
            <div class="news-tiles__info-short">
                                    <p>Одессит по имени Руслан, не выдержав бездействия коммунальных служб, сам убрал Артиллерийский парк</p>
                            </div>
        </div>
    </a>
</li>                                                                            <li class="news-tiles__item ">
    <a class="news-tiles__item-inner" href="/news/v-odesskoj-oblasti-muzhchina-poprosil-druga-pokatatsja--razbil-ego-avtomobil">
        <div class="news-tiles__img-container">
            <img src="/Media/images/news/small/2971eb580a020ee531dabaae449437c6.jpg" alt="В Одесской области мужчина попросил друга покататься и разбил его автомобиль" title="В Одесской области мужчина попросил друга покататься и разбил его автомобиль">
        </div>
        <div class="news-tiles__info">
            <div class="news-tiles__info-top">
                                    <span class="news-tiles__tag" style="background-color: #63c296;">Одесса и область</span>
                                                            </div>
            <div class="news-tiles__title">
                                    <span>В Одесской области мужчина попросил друга покататься и разбил его автомобиль</span>
                            </div>
            <div class="news-tiles__info-bottom">
                <span class="news-tiles__time">12 марта 2018, 21:40</span>
                <span class="news-tiles__views"><i><svg><use xlink:href="#icon_eye"/></svg></i><span>1662</span></span>
            </div>
            <div class="news-tiles__info-short">
                                    <p>Хозяин Mercedes отдал разбитую машину виновнику ДТП и запросил $11000</p>
                            </div>
        </div>
    </a>
</li>                                                                            <li class="news-tiles__item ">
    <a class="news-tiles__item-inner" href="/news/na-trasse-odessa--chernomorsk-razbilsja-lexus">
        <div class="news-tiles__img-container">
            <img src="/Media/images/news/small/24487a5c991944c17abe14697ed8c8c2.jpg" alt="На трассе «Одесса – Черноморск» разбился Lexus" title="На трассе «Одесса – Черноморск» разбился Lexus">
        </div>
        <div class="news-tiles__info">
            <div class="news-tiles__info-top">
                                    <span class="news-tiles__tag" style="background-color: #63c296;">Одесса и область</span>
                                                            </div>
            <div class="news-tiles__title">
                                    <span>На трассе «Одесса – Черноморск» разбился Lexus</span>
                            </div>
            <div class="news-tiles__info-bottom">
                <span class="news-tiles__time">16 марта 2018, 17:41</span>
                <span class="news-tiles__views"><i><svg><use xlink:href="#icon_eye"/></svg></i><span>1679</span></span>
            </div>
            <div class="news-tiles__info-short">
                                    <p>Серьёзная авария случилась на трассе &laquo;Одесса &ndash; Черноморск&raquo; у поворота на Сухой лиман</p>
                            </div>
        </div>
    </a>
</li>                                                            <li class="no-bg news-tiles__item news-tiles__item--ads"><div class="news-tiles__item-inner"><div class="news-tiles__banner"><script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- http://odessa.net.ua/ -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-6543744359815149"
     data-ad-slot="2118115517"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script></div></div></li>                                                                                    <li class="news-tiles__item ">
    <a class="news-tiles__item-inner" href="/news/v-odesse-zamecheny-inomarki-s-odinakovymi-nomernymi-znakami">
        <div class="news-tiles__img-container">
            <img src="/Media/images/news/small/5423be7918eea75753c7b3d919311e8a.jpg" alt="В Одессе замечены иномарки с одинаковыми номерными знаками" title="В Одессе замечены иномарки с одинаковыми номерными знаками">
        </div>
        <div class="news-tiles__info">
            <div class="news-tiles__info-top">
                                    <span class="news-tiles__tag" style="background-color: #63c296;">Одесса и область</span>
                                                            </div>
            <div class="news-tiles__title">
                                    <span>В Одессе замечены иномарки с одинаковыми номерными знаками</span>
                            </div>
            <div class="news-tiles__info-bottom">
                <span class="news-tiles__time">12 марта 2018, 19:01</span>
                <span class="news-tiles__views"><i><svg><use xlink:href="#icon_eye"/></svg></i><span>1555</span></span>
            </div>
            <div class="news-tiles__info-short">
                                    <p>Одесская полиция в центре города задержала два Range Rover с идентичными номерами</p>
                            </div>
        </div>
    </a>
</li>                                                                            <li class="news-tiles__item ">
    <a class="news-tiles__item-inner" href="/news/ljudoed-iz-gorlovki-rasskazal-kak-sovershal-prestuplenija">
        <div class="news-tiles__img-container">
            <img src="/Media/images/news/small/471028908620b57bd04cd8ff17c94ddb.jpg" alt="Людоед из Горловки рассказал, как совершал преступления" title="Людоед из Горловки рассказал, как совершал преступления">
        </div>
        <div class="news-tiles__info">
            <div class="news-tiles__info-top">
                                    <span class="news-tiles__tag" style="background-color: #63c296;">Одесса и область</span>
                                                            </div>
            <div class="news-tiles__title">
                                    <span>Людоед из Горловки рассказал, как совершал преступления</span>
                            </div>
            <div class="news-tiles__info-bottom">
                <span class="news-tiles__time">15 марта 2018, 16:16</span>
                <span class="news-tiles__views"><i><svg><use xlink:href="#icon_eye"/></svg></i><span>1488</span></span>
            </div>
            <div class="news-tiles__info-short">
                                    <p>&laquo;Глянь, какая печенка, надо ее&nbsp;вырезать&hellip; Чи&nbsp;сварить, чи&nbsp;пожарить. Два дня ели, ха-ха&hellip;&raquo;&nbsp;</p>
                            </div>
        </div>
    </a>
</li>                                                                            <li class="news-tiles__item ">
    <a class="news-tiles__item-inner" href="/news/tarify-na-holodnuju-vodu-v-marte-po-odesse">
        <div class="news-tiles__img-container">
            <img src="/Media/images/news/small/5d839bbda02e9edc959b752b17300993.jpg" alt="Тарифы на холодную воду в марте по Одессе" title="Тарифы на холодную воду в марте по Одессе">
        </div>
        <div class="news-tiles__info">
            <div class="news-tiles__info-top">
                                                            </div>
            <div class="news-tiles__title">
                                    <span>Тарифы на холодную воду в марте по Одессе</span>
                            </div>
            <div class="news-tiles__info-bottom">
                <span class="news-tiles__time">12 марта 2018, 23:00</span>
                <span class="news-tiles__views"><i><svg><use xlink:href="#icon_eye"/></svg></i><span>1434</span></span>
            </div>
            <div class="news-tiles__info-short">
                                    <p>В марте жителям областного центра придётся считать воду по новым тарифам</p>
                            </div>
        </div>
    </a>
</li>                                                                            <li class="news-tiles__item ">
    <a class="news-tiles__item-inner" href="/news/odessitam-na-zametku-pered-poezdkami-za-rubezh-nuzhno-zaregestrirovatsja">
        <div class="news-tiles__img-container">
            <img src="/Media/images/news/small/f31f556a5746917dabb03772f371606e.jpg" alt="Одесситам на заметку: перед поездками за рубеж нужно зарегистрироваться" title="Одесситам на заметку: перед поездками за рубеж нужно зарегистрироваться">
        </div>
        <div class="news-tiles__info">
            <div class="news-tiles__info-top">
                                    <span class="news-tiles__tag" style="background-color: #63c296;">Одесса и область</span>
                                                            </div>
            <div class="news-tiles__title">
                                    <span>Одесситам на заметку: перед поездками за рубеж нужно зарегистрироваться</span>
                            </div>
            <div class="news-tiles__info-bottom">
                <span class="news-tiles__time">17 марта 2018, 12:22</span>
                <span class="news-tiles__views"><i><svg><use xlink:href="#icon_eye"/></svg></i><span>1494</span></span>
            </div>
            <div class="news-tiles__info-short">
                                    <p>МИД Украины запускает новый сервис добровольной регистрации граждан страны во время путешествий за границу</p>
                            </div>
        </div>
    </a>
</li>                                                                            <li class="news-tiles__item ">
    <a class="news-tiles__item-inner" href="/news/videokamery-zapechatleli-nedobrosovestnuju-odesskuju-mamochku-video">
        <div class="news-tiles__img-container">
            <img src="/Media/images/news/small/f995b9debbe4c785bfd0d38c47dbbaa4.jpg" alt="Видеокамеры запечатлели недобросовестную одесскую мамочку (ВИДЕО)" title="Видеокамеры запечатлели недобросовестную одесскую мамочку (ВИДЕО)">
        </div>
        <div class="news-tiles__info">
            <div class="news-tiles__info-top">
                                    <span class="news-tiles__tag" style="background-color: #63c296;">Одесса и область</span>
                                                            </div>
            <div class="news-tiles__title">
                                    <span>Видеокамеры запечатлели недобросовестную одесскую мамочку (ВИДЕО)</span>
                            </div>
            <div class="news-tiles__info-bottom">
                <span class="news-tiles__time">15 марта 2018, 23:00</span>
                <span class="news-tiles__views"><i><svg><use xlink:href="#icon_eye"/></svg></i><span>1370</span></span>
            </div>
            <div class="news-tiles__info-short">
                                    <p>Дама подняла выпавший кошелёк и проигнорировала владельца вещи</p>
                            </div>
        </div>
    </a>
</li>                                                                            <li class="news-tiles__item ">
    <a class="news-tiles__item-inner" href="/news/alabai-napavshie-na-pensionerku-v-sanzhejke-v-tot-den-isterzali-esche-odnogo-cheloveka-foto">
        <div class="news-tiles__img-container">
            <img src="/Media/images/news/small/fd1aacdbdf3a7347e8cb4d6a3c55e515.jpg" alt="Алабаи, напавшие на пенсионерку в Санжейке, в тот день истерзали ещё одного человека (ФОТО)" title="Алабаи, напавшие на пенсионерку в Санжейке, в тот день истерзали ещё одного человека (ФОТО)">
        </div>
        <div class="news-tiles__info">
            <div class="news-tiles__info-top">
                                    <span class="news-tiles__tag" style="background-color: #63c296;">Одесса и область</span>
                                                            </div>
            <div class="news-tiles__title">
                                    <span>Алабаи, напавшие на пенсионерку в Санжейке, в тот день истерзали ещё одного человека (ФОТО)</span>
                            </div>
            <div class="news-tiles__info-bottom">
                <span class="news-tiles__time">14 марта 2018, 19:19</span>
                <span class="news-tiles__views"><i><svg><use xlink:href="#icon_eye"/></svg></i><span>1319</span></span>
            </div>
            <div class="news-tiles__info-short">
                                    <p>Ранее мы сообщали&nbsp;о том, что в курортном посёлке Санжейка алабаи искусали пожилую женщину, которая работала уборщицей</p>
                            </div>
        </div>
    </a>
</li>                                                                            <li class="news-tiles__item ">
    <a class="news-tiles__item-inner" href="/news/ubijstvo-v-odesskom-sizo-podsudimyj-sdelal-rezonansnoe-zajavlenie">
        <div class="news-tiles__img-container">
            <img src="/Media/images/news/small/854675bea2212745cb79c3798099c90f.jpg" alt="Убийство в Одесском СИЗО: подсудимый сделал резонансное заявление" title="Убийство в Одесском СИЗО: подсудимый сделал резонансное заявление">
        </div>
        <div class="news-tiles__info">
            <div class="news-tiles__info-top">
                                    <span class="news-tiles__tag" style="background-color: #63c296;">Одесса и область</span>
                                                            </div>
            <div class="news-tiles__title">
                                    <span>Убийство в Одесском СИЗО: подсудимый сделал резонансное заявление</span>
                            </div>
            <div class="news-tiles__info-bottom">
                <span class="news-tiles__time">12 марта 2018, 18:18</span>
                <span class="news-tiles__views"><i><svg><use xlink:href="#icon_eye"/></svg></i><span>1301</span></span>
            </div>
            <div class="news-tiles__info-short">
                                    <p>Василий Чемериз, который убил, а затем расчленил сотрудницу Одесского СИЗО, в суде заявил, что его вынудили пойти на преступление</p>
                            </div>
        </div>
    </a>
</li>                                                                            <li class="news-tiles__item ">
    <a class="news-tiles__item-inner" href="/news/v-tsentre-odessy-patrulnye-oshtrafovali-avtohama-foto">
        <div class="news-tiles__img-container">
            <img src="/Media/images/news/small/364a7b492762f845026f9846f309dd22.jpg" alt="В центре Одессы патрульные оштрафовали автохама (ФОТО)" title="В центре Одессы патрульные оштрафовали автохама (ФОТО)">
        </div>
        <div class="news-tiles__info">
            <div class="news-tiles__info-top">
                                    <span class="news-tiles__tag" style="background-color: #63c296;">Одесса и область</span>
                                                            </div>
            <div class="news-tiles__title">
                                    <span>В центре Одессы патрульные оштрафовали автохама (ФОТО)</span>
                            </div>
            <div class="news-tiles__info-bottom">
                <span class="news-tiles__time">15 марта 2018, 07:30</span>
                <span class="news-tiles__views"><i><svg><use xlink:href="#icon_eye"/></svg></i><span>1273</span></span>
            </div>
            <div class="news-tiles__info-short">
                                    <p>Одесситка Наталья в течение 40 минут не могла найти водителя-автохама и, когда у неё закончилось терпение, вызвала полицию</p>
                            </div>
        </div>
    </a>
</li>                            </ul>
        </div>
    </div>
</div>                    </div>
                    <div class="page-section">
                        <div class="wMiddle">
                            <div class="wMiddle__item"><div class="baddb"><div class="banner__item"><script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- odessa.net.ua/news/odessa-i-oblast -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-6543744359815149"
     data-ad-slot="6646583110"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script></div></div></div>                            <div class="wMiddle__item">
                                <div class="news-row">
    <div class="news-row__header">
        <div class="news-row__header-left">
            <div class="news-row__main-title">
                <a href="https://avtoblog.ua" title="Объявления" target="_blank">Автоблог</a>
            </div>
        </div>
        <div class="news-row__header-right">
            <div class="news-row__logo news-row__logo--color2">
                <img src="/Media/pic/avtoblog-logo.png">
            </div>
            <div class="news-row__nav">
                <div class="news-row__nav-toggle js-news-row__nav-toggle"><span>Категории</span></div>
                <ul>
                                                                        <li><a href="https://avtoblog.ua/news" title="Новости" target="_blank">Новости</a></li>
                                                                                                <li><a href="https://avtoblog.ua/overviews" title="Обзоры" target="_blank">Обзоры</a></li>
                                                                                                <li><a href="https://avtoblog.ua/technologies" title="Технологии" target="_blank">Технологии</a></li>
                                                                                                <li><a href="https://avtoblog.ua/tuning" title="Звук и тюнинг" target="_blank">Звук и тюнинг</a></li>
                                                                                                <li><a href="https://avtoblog.ua/useful" title="Полезные советы" target="_blank">Полезные советы</a></li>
                                                                                                <li><a href="https://avtoblog.ua/reviews" title="Отзывы" target="_blank">Отзывы</a></li>
                                                                                                <li><a href="https://avtoblog.ua/video" title="Видео" target="_blank">Видео</a></li>
                                                                                                <li><a href="https://avtoblog.ua/forum" title="Форум" target="_blank">Форум</a></li>
                                                            </ul>
            </div>
        </div>
    </div>
    <ul class="news-row__list news-row__list--large-items">
                                    <li class="news-row__item news-row__item--large">
                    <a href="https://avtoblog.ua/news/v-ukraine-snizhaetsja-kolichestvo-dtp" class="news-row__item-inner" title="В Украине снижается количество ДТП" target="_blank">
                        <div class="news-row__item-img-wrap" style="background: none;">
                                                            <img src="https://avtoblog.ua/Media/images/news/smallcover/2e39c0d167bbc99de543c367907272c9.jpg" alt="В Украине снижается количество ДТП">
                                                    </div>
                        <div class="news-row__item-title">
                            <span>В Украине снижается количество ДТП</span>
                        </div>
                    </a>
                </li>
                                                <li class="news-row__item news-row__item--large">
                    <a href="https://avtoblog.ua/news/skazochnaja-printsessa-vytolknula-politsejskij-gruzovik-iz-snezhnogo-plena" class="news-row__item-inner" title="Сказочная принцесса вытолкнула полицейский грузовик из снежного плена" target="_blank">
                        <div class="news-row__item-img-wrap" style="background: none;">
                                                            <img src="https://avtoblog.ua/Media/images/news/smallcover/610048452990e4722586da547dd65827.jpg" alt="Сказочная принцесса вытолкнула полицейский грузовик из снежного плена">
                                                    </div>
                        <div class="news-row__item-title">
                            <span>Сказочная принцесса вытолкнула полицейский грузовик из снежного плена</span>
                        </div>
                    </a>
                </li>
                                                <li class="news-row__item news-row__item--large">
                    <a href="https://avtoblog.ua/news/staryj-ikarus-s-dagestanskimi-nomerami-shokiroval-zhitelej-dubaja" class="news-row__item-inner" title="Старый «Икарус» с дагестанскими номерами шокировал жителей Дубая" target="_blank">
                        <div class="news-row__item-img-wrap" style="background: none;">
                                                            <img src="https://avtoblog.ua/Media/images/news/smallcover/bbca5022b2a29bf164dcee1c0de25119.jpg" alt="Старый «Икарус» с дагестанскими номерами шокировал жителей Дубая">
                                                    </div>
                        <div class="news-row__item-title">
                            <span>Старый «Икарус» с дагестанскими номерами шокировал жителей Дубая</span>
                        </div>
                    </a>
                </li>
                                                                                        <li class="news-row__item news-row__item--nest">
                                                                                                                                    <div class="news-row__item-row">
                        <a href="https://avtoblog.ua/news/avtomobili-maserati-prevratilis-v-derevjannye-mashinki" class="news-row__item-inner" title="Автомобили Maserati «превратились» в деревянные машинки" target="_blank">
                            <div class="news-row__item-img-wrap">
                                                                    <img src="https://avtoblog.ua/Media/images/news/smallcover/1aa8cc01ec70a025826da7e71a1000d0.jpg" alt="Автомобили Maserati «превратились» в деревянные машинки">
                                                            </div>
                            <div class="news-row__item-title">
                                <span>Автомобили Maserati «превратились» в деревянные машинки</span>
                            </div>
                        </a>
                    </div>
                                                                <div class="news-row__item-row">
                        <a href="https://avtoblog.ua/news/volkswagen-arteon-stanet-universalom" class="news-row__item-inner" title="Volkswagen Arteon станет универсалом" target="_blank">
                            <div class="news-row__item-img-wrap">
                                                                    <img src="https://avtoblog.ua/Media/images/news/smallcover/d27ff243688be47d70baae794c416197.jpeg" alt="Volkswagen Arteon станет универсалом">
                                                            </div>
                            <div class="news-row__item-title">
                                <span>Volkswagen Arteon станет универсалом</span>
                            </div>
                        </a>
                    </div>
                                                                <div class="news-row__item-row">
                        <a href="https://avtoblog.ua/news/avtomobil-iz-prezidentskogo-kortezha-vystavili-na-torgi" class="news-row__item-inner" title="Автомобиль из президентского кортежа выставили на торги" target="_blank">
                            <div class="news-row__item-img-wrap">
                                                                    <img src="https://avtoblog.ua/Media/images/news/smallcover/ce84a7d2bee32176b38efe6f4861139c.jpg" alt="Автомобиль из президентского кортежа выставили на торги">
                                                            </div>
                            <div class="news-row__item-title">
                                <span>Автомобиль из президентского кортежа выставили на торги</span>
                            </div>
                        </a>
                    </div>
                                    </li>
    </ul>
</div>                                <div class="news-row">
    <div class="news-row__header">
        <div class="news-row__header-left">
            <div class="news-row__main-title">
                <a href="https://bdzhola.com" title="Объявления" target="_blank">Бджола</a>
            </div>
        </div>
        <div class="news-row__header-right">
            <div class="news-row__logo news-row__logo--color2">
                <img src="/Media/pic/bdjola-logo.png">
            </div>
            <div class="news-row__nav">
                <div class="news-row__nav-toggle js-news-row__nav-toggle"><span>Категории</span></div>
                <ul>
                                                                        <li><a href="https://bdzhola.com/news/novini" title="Новини" target="_blank">Новини</a></li>
                                                                                                <li><a href="https://bdzhola.com/news/zhittja" title="Життя" target="_blank">Життя</a></li>
                                                                                                <li><a href="https://bdzhola.com/news/svoboda" title="Свобода" target="_blank">Свобода</a></li>
                                                                                                <li><a href="https://bdzhola.com/news/tvorchist" title="Творчість" target="_blank">Творчість</a></li>
                                                                                                <li><a href="https://bdzhola.com/news/video" title="Відео" target="_blank">Відео</a></li>
                                                            </ul>
            </div>
        </div>
    </div>
    <ul class="news-row__list news-row__list--large-items">
                                    <li class="news-row__item news-row__item--large">
                    <a href="https://bdzhola.com/news/feericheskaja-pobeda-ukrainskij-bokser-nokautiroval-sopernika-v-pervom-raunde-video" class="news-row__item-inner" title="Феерическая победа: украинский боксер нокаутировал соперника в первом раунде (видео)" target="_blank">
                        <div class="news-row__item-img-wrap" style="background: none;">
                                                            <img src="https://bdzhola.com/Media/images/news/small/16cb7d173021460766fbc9d9fbe3ef6e.jpg" alt="Феерическая победа: украинский боксер нокаутировал соперника в первом раунде (видео)">
                                                    </div>
                        <div class="news-row__item-title">
                            <span>Феерическая победа: украинский боксер нокаутировал соперника в первом раунде (видео)</span>
                        </div>
                    </a>
                </li>
                                                <li class="news-row__item news-row__item--large">
                    <a href="https://bdzhola.com/news/opleski-stojachi-amerikanski-kongresmeni-vrazheni-vid-peregljadu-strichki-kiborgi" class="news-row__item-inner" title="Оплески стоячи: американські конгресмени вражені від перегляду стрічки «Кіборги»" target="_blank">
                        <div class="news-row__item-img-wrap" style="background: none;">
                                                            <img src="https://bdzhola.com/Media/images/news/small/e6304368082fb15d61048c071e386f21.jpg" alt="Оплески стоячи: американські конгресмени вражені від перегляду стрічки «Кіборги»">
                                                    </div>
                        <div class="news-row__item-title">
                            <span>Оплески стоячи: американські конгресмени вражені від перегляду стрічки «Кіборги»</span>
                        </div>
                    </a>
                </li>
                                                <li class="news-row__item news-row__item--large">
                    <a href="https://bdzhola.com/news/novye-mahinatsii-ot-imeni-privatbanka-ukraintsev-preduprezhdajut-o-afere-v-seti" class="news-row__item-inner" title="Новые махинации от имени ПриватБанка: украинцев предупреждают о афере в сети" target="_blank">
                        <div class="news-row__item-img-wrap" style="background: none;">
                                                            <img src="https://bdzhola.com/Media/images/news/small/d1a2aae15b8abdbec1533f43f7267914.jpg" alt="Новые махинации от имени ПриватБанка: украинцев предупреждают о афере в сети">
                                                    </div>
                        <div class="news-row__item-title">
                            <span>Новые махинации от имени ПриватБанка: украинцев предупреждают о афере в сети</span>
                        </div>
                    </a>
                </li>
                                                                                        <li class="news-row__item news-row__item--nest">
                                                                                                                                    <div class="news-row__item-row">
                        <a href="https://bdzhola.com/news/mistsja-kozatskoji-slavi-jaki-maje-vidvidati-kozhen-ukrajinets-podorozh-ukrajinoju" class="news-row__item-inner" title="Місця козацької слави, які має відвідати кожен українець: подорож Україною" target="_blank">
                            <div class="news-row__item-img-wrap">
                                                                    <img src="https://bdzhola.com/Media/images/news/small/a7e0d7f03ae1044147fd4eeca6706462.jpg" alt="Місця козацької слави, які має відвідати кожен українець: подорож Україною">
                                                            </div>
                            <div class="news-row__item-title">
                                <span>Місця козацької слави, які має відвідати кожен українець: подорож Україною</span>
                            </div>
                        </a>
                    </div>
                                                                <div class="news-row__item-row">
                        <a href="https://bdzhola.com/news/golodnye-igry-po-ukrainski-kak-vygljadeli-by-geroi-izvestnogo-filma-v-nashej-strane" class="news-row__item-inner" title="«Голодные игры» по-украински: как выглядели бы герои известного фильма в нашей стране?" target="_blank">
                            <div class="news-row__item-img-wrap">
                                                                    <img src="https://bdzhola.com/Media/images/news/small/b1f881b52bd4a889275516d6643a25cc.jpg" alt="«Голодные игры» по-украински: как выглядели бы герои известного фильма в нашей стране?">
                                                            </div>
                            <div class="news-row__item-title">
                                <span>«Голодные игры» по-украински: как выглядели бы герои известного фильма в нашей стране?</span>
                            </div>
                        </a>
                    </div>
                                                                <div class="news-row__item-row">
                        <a href="https://bdzhola.com/news/politsejski-shukajut-paru-jaka-zajnjalasja-seksom-na-pljazhi-v-tajilandi-video-18" class="news-row__item-inner" title="Поліцейські шукають пару, яка зайнялася сексом на пляжі в Таїланді: відео 18+" target="_blank">
                            <div class="news-row__item-img-wrap">
                                                                    <img src="https://bdzhola.com/Media/images/news/small/ea3908557b53796e0faede1bf703ed49.jpg" alt="Поліцейські шукають пару, яка зайнялася сексом на пляжі в Таїланді: відео 18+">
                                                            </div>
                            <div class="news-row__item-title">
                                <span>Поліцейські шукають пару, яка зайнялася сексом на пляжі в Таїланді: відео 18+</span>
                            </div>
                        </a>
                    </div>
                                    </li>
    </ul>
</div>                            </div>
                                                    </div>
                    </div>
                    <div class="page-section">
                        <div class="wRight"><div class="wRight__item"><div class="baddb sticky"><div class="banner__item"><script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- http://odessa.net.ua/ -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-6543744359815149"
     data-ad-slot="2118115517"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script></div></div></div></div>                        <div class="wMiddle">
    <div class="wMiddle__item">
        <div class="news-tiles">
            <ul class="news-tiles__list" id="newsLoadHere">
                                                                                            <li class="news-tiles__item ">
    <a class="news-tiles__item-inner" href="/news/zaderzhan-predpolagaemyj-ubijtsa-i-kannibal-rodom-iz-odesschiny">
        <div class="news-tiles__img-container">
            <img src="/Media/images/news/small/d708752ef3f2f934e53ed9e964d8c14a.jpg" alt="Задержан предполагаемый убийца и каннибал родом из Одесщины" title="Задержан предполагаемый убийца и каннибал родом из Одесщины">
        </div>
        <div class="news-tiles__info">
            <div class="news-tiles__info-top">
                                    <span class="news-tiles__tag" style="background-color: #63c296;">Одесса и область</span>
                                                            </div>
            <div class="news-tiles__title">
                                    <span>Задержан предполагаемый убийца и каннибал родом из Одесщины</span>
                            </div>
            <div class="news-tiles__info-bottom">
                <span class="news-tiles__time">15 марта 2018, 12:59</span>
                <span class="news-tiles__views"><i><svg><use xlink:href="#icon_eye"/></svg></i><span>1216</span></span>
            </div>
            <div class="news-tiles__info-short">
                                    <p>В Горловке Донецкой области местные жители задержали предполагаемого убийцу и каннибала</p>
                            </div>
        </div>
    </a>
</li>                                                                            <li class="news-tiles__item ">
    <a class="news-tiles__item-inner" href="/news/avtohama-na-litovskih-nomerah-prouchili-evakuatorom-foto">
        <div class="news-tiles__img-container">
            <img src="/Media/images/news/small/1c5513a4c882c430764c8b928c9d275a.jpg" alt="Автохама на литовских номерах проучили эвакуатором (ФОТО)" title="Автохама на литовских номерах проучили эвакуатором (ФОТО)">
        </div>
        <div class="news-tiles__info">
            <div class="news-tiles__info-top">
                                    <span class="news-tiles__tag" style="background-color: #63c296;">Одесса и область</span>
                                                            </div>
            <div class="news-tiles__title">
                                    <span>Автохама на литовских номерах проучили эвакуатором (ФОТО)</span>
                            </div>
            <div class="news-tiles__info-bottom">
                <span class="news-tiles__time">12 марта 2018, 21:02</span>
                <span class="news-tiles__views"><i><svg><use xlink:href="#icon_eye"/></svg></i><span>1194</span></span>
            </div>
            <div class="news-tiles__info-short">
                                    <p>Напротив ЖК &laquo;Альтаир&raquo; проучили автохамов</p>
                            </div>
        </div>
    </a>
</li>                                                                            <li class="news-tiles__item ">
    <a class="news-tiles__item-inner" href="/news/na-lanzherone-odessit-ljubovalsja-pljazhnymi-vidami-iz-salona-avtomobilja">
        <div class="news-tiles__img-container">
            <img src="/Media/images/news/small/5c899854b3ed7957f4afedc511033943.jpg" alt="На Ланжероне одессит любовался пляжными видами... из салона автомобиля" title="На Ланжероне одессит любовался пляжными видами... из салона автомобиля">
        </div>
        <div class="news-tiles__info">
            <div class="news-tiles__info-top">
                                    <span class="news-tiles__tag" style="background-color: #63c296;">Одесса и область</span>
                                                            </div>
            <div class="news-tiles__title">
                                    <span>На Ланжероне одессит любовался пляжными видами... из салона автомобиля</span>
                            </div>
            <div class="news-tiles__info-bottom">
                <span class="news-tiles__time">13 марта 2018, 12:00</span>
                <span class="news-tiles__views"><i><svg><use xlink:href="#icon_eye"/></svg></i><span>1166</span></span>
            </div>
            <div class="news-tiles__info-short">
                                    <p>Очередной одессит посетил пляж &laquo;Ланжерон&raquo;, чтобы полюбоваться видами моря... оставаясь в своём авто</p>
                            </div>
        </div>
    </a>
</li>                                                                            <li class="news-tiles__item ">
    <a class="news-tiles__item-inner" href="/news/v-odesse-proizoshlo-dtp-s-uchastiem-marshrutki-foto">
        <div class="news-tiles__img-container">
            <img src="/Media/images/news/small/a458c7665406ba3413921fef0010c39c.jpg" alt="В Одессе произошло ДТП с участием маршрутки (ФОТО)" title="В Одессе произошло ДТП с участием маршрутки (ФОТО)">
        </div>
        <div class="news-tiles__info">
            <div class="news-tiles__info-top">
                                    <span class="news-tiles__tag" style="background-color: #7b97bb;">Одесса наизнанку</span>
                                                            </div>
            <div class="news-tiles__title">
                                    <span>В Одессе произошло ДТП с участием маршрутки (ФОТО)</span>
                            </div>
            <div class="news-tiles__info-bottom">
                <span class="news-tiles__time">11 марта 2018, 15:30</span>
                <span class="news-tiles__views"><i><svg><use xlink:href="#icon_eye"/></svg></i><span>1135</span></span>
            </div>
            <div class="news-tiles__info-short">
                                    <p>В ДТП попала маршрутка №242</p>
                            </div>
        </div>
    </a>
</li>                                                            <li class="no-bg news-tiles__item news-tiles__item--ads"><div class="news-tiles__item-inner"><div class="news-tiles__banner"><script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- http://odessa.net.ua/ -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-6543744359815149"
     data-ad-slot="2118115517"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script></div></div></li>                                                                                    <li class="news-tiles__item ">
    <a class="news-tiles__item-inner" href="/news/sereznoe-dtp-na-chernomorskoj-trasse-video">
        <div class="news-tiles__img-container">
            <img src="/Media/images/news/small/90a9d20bd5b12e3932dde979384d1ffc.jpg" alt="Серьёзное ДТП на Черноморской трассе (ВИДЕО)" title="Серьёзное ДТП на Черноморской трассе (ВИДЕО)">
        </div>
        <div class="news-tiles__info">
            <div class="news-tiles__info-top">
                                    <span class="news-tiles__tag" style="background-color: #63c296;">Одесса и область</span>
                                                            </div>
            <div class="news-tiles__title">
                                    <span>Серьёзное ДТП на Черноморской трассе (ВИДЕО)</span>
                            </div>
            <div class="news-tiles__info-bottom">
                <span class="news-tiles__time">17 марта 2018, 09:39</span>
                <span class="news-tiles__views"><i><svg><use xlink:href="#icon_eye"/></svg></i><span>1155</span></span>
            </div>
            <div class="news-tiles__info-short">
                                    <p>Водитель Lexus врезалась в дерево</p>
                            </div>
        </div>
    </a>
</li>                                                                            <li class="news-tiles__item ">
    <a class="news-tiles__item-inner" href="/news/v-rajone-gorbatogo-mosta-proizoshlo-smertelnoe-dtp-video">
        <div class="news-tiles__img-container">
            <img src="/Media/images/news/small/e5640540c0765e37f786eb92eb9b23e2.jpg" alt="В районе Горбатого моста произошло смертельное ДТП (ВИДЕО)" title="В районе Горбатого моста произошло смертельное ДТП (ВИДЕО)">
        </div>
        <div class="news-tiles__info">
            <div class="news-tiles__info-top">
                                    <span class="news-tiles__tag" style="background-color: #63c296;">Одесса и область</span>
                                                            </div>
            <div class="news-tiles__title">
                                    <span>В районе Горбатого моста произошло смертельное ДТП (ВИДЕО)</span>
                            </div>
            <div class="news-tiles__info-bottom">
                <span class="news-tiles__time">14 марта 2018, 16:39</span>
                <span class="news-tiles__views"><i><svg><use xlink:href="#icon_eye"/></svg></i><span>1096</span></span>
            </div>
            <div class="news-tiles__info-short">
                                    <p>Видеозаписью поделились очевидцы происшествия</p>
                            </div>
        </div>
    </a>
</li>                                                                            <li class="news-tiles__item ">
    <a class="news-tiles__item-inner" href="/news/top-5-elitnyh-domov-kotorye-prodajutsja-v-odesse">
        <div class="news-tiles__img-container">
            <img src="/Media/images/news/small/cc064b4201f6d6210a22b7c0a3fab694.jpg" alt="Топ-5 элитных домов, которые продаются в Одессе" title="Топ-5 элитных домов, которые продаются в Одессе">
        </div>
        <div class="news-tiles__info">
            <div class="news-tiles__info-top">
                                    <span class="news-tiles__tag" style="background-color: #7b97bb;">Факты об Одессе</span>
                                                            </div>
            <div class="news-tiles__title">
                                    <span>Топ-5 элитных домов, которые продаются в Одессе</span>
                            </div>
            <div class="news-tiles__info-bottom">
                <span class="news-tiles__time">17 марта 2018, 19:38</span>
                <span class="news-tiles__views"><i><svg><use xlink:href="#icon_eye"/></svg></i><span>1230</span></span>
            </div>
            <div class="news-tiles__info-short">
                                    <p>В данной статье вы сможете увидеть пятёрку самых роскошных и дорогих домов, которые продаются в Одессе на данный момент</p>
                            </div>
        </div>
    </a>
</li>                                                                            <li class="news-tiles__item ">
    <a class="news-tiles__item-inner" href="/news/mnogoletnjuju-traditsiju-kupanij-v-chernom-more-odessitu-prerval-jad-sneg">
        <div class="news-tiles__img-container">
            <img src="/Media/images/news/small/b60b79a5b2609d91035244b97f9e47c6.jpg" alt="Многолетнюю традицию купаний в Чёрном море одесситу прервал «яд-снег»" title="Многолетнюю традицию купаний в Чёрном море одесситу прервал «яд-снег»">
        </div>
        <div class="news-tiles__info">
            <div class="news-tiles__info-top">
                                    <span class="news-tiles__tag" style="background-color: #63c296;">Одесса и область</span>
                                                            </div>
            <div class="news-tiles__title">
                                    <span>Многолетнюю традицию купаний в Чёрном море одесситу прервал «яд-снег»</span>
                            </div>
            <div class="news-tiles__info-bottom">
                <span class="news-tiles__time">12 марта 2018, 14:48</span>
                <span class="news-tiles__views"><i><svg><use xlink:href="#icon_eye"/></svg></i><span>1033</span></span>
            </div>
            <div class="news-tiles__info-short">
                                    <p>Одессит, 10 лет купавшийся в Чёрном море, отказался от своей традиции &mdash; он заподозрил&nbsp;его в загрязнении ядовитыми веществами</p>
                            </div>
        </div>
    </a>
</li>                                                                            <li class="news-tiles__item ">
    <a class="news-tiles__item-inner" href="/news/odesskij-miting-pod-stividornoj-kompaniej-chut-ne-pereros-v-draku">
        <div class="news-tiles__img-container">
            <img src="/Media/images/news/small/dca4987752df3b87bd660e90c91cdfa2.jpg" alt="Одесский митинг под стивидорной компанией чуть не перерос в драку" title="Одесский митинг под стивидорной компанией чуть не перерос в драку">
        </div>
        <div class="news-tiles__info">
            <div class="news-tiles__info-top">
                                    <span class="news-tiles__tag" style="background-color: #63c296;">Одесса и область</span>
                                                            </div>
            <div class="news-tiles__title">
                                    <span>Одесский митинг под стивидорной компанией чуть не перерос в драку</span>
                            </div>
            <div class="news-tiles__info-bottom">
                <span class="news-tiles__time">16 марта 2018, 08:30</span>
                <span class="news-tiles__views"><i><svg><use xlink:href="#icon_eye"/></svg></i><span>997</span></span>
            </div>
            <div class="news-tiles__info-short">
                                    <p>В четверг, 15 марта, под офисом стивидорной компании&nbsp;&laquo;Олимпекс Купе Интернешнл&raquo; Одесского морпорта митинговали активисты</p>
                            </div>
        </div>
    </a>
</li>                            </ul>
        </div>
    </div>
    <div class="wMiddle__item">
        <div class="tac">
            <button data-main-page="1" data-id="38242" class="show-more-btn js-show-more-btn"><i><img src="/Media/pic/preloader.GIF"></i><span>Показать еще...</span></button>
        </div>
    </div>
</div>                    </div>
                    <div class="page-section"><div class="wMiddle"><div class="wMiddle__item"><div class="baddb"><div class="banner__item"><script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- odessa.net.ua -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-6543744359815149"
     data-ad-slot="4958027114"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script></div></div></div></div></div>                </div>
                <div id="page-scroll-up" class="page-scroll-up">
                    <svg><use xlink:href="#icon_scroll_up" /></svg>
                </div>
            </div>
        </div>
        <footer class="page-footer">
    <div class="wSize page-footer__inner">
        <div class="page-footer__item">
            <div class="logo page-footer__logo">
                <img src="/Media/pic/logo--small.png" alt="">
            </div>
            <div class="page-footer__copy-txt">
                <p>© Odessa.net.ua, 2016 Все права защищены</p>
            </div>
        </div>
        <div class="page-footer__item">
            <div class="page-footer__links-container">
                <div class="page-footer__links">
                    <span><a href="/reklama" title="Реклама на сайте">Реклама на сайте</a></span>
                    <span><a href="/pravila_polzovanija_sajtom" title="Правила пользования сайтом">Правила</a></span>
                    <span><a href="/contacts" title="Контакты">Контакты</a></span>
                    <span><a class="mfiA" href="#" data-url="/popup/contacts" title="Связаться с нами">Связаться с нами</a></span>
                    <span><a href="/sitemap" title="Карта сайта">Карта сайта</a></span>
                </div>
                <div class="page-footer__copy-txt">
                    <a href="http://lester.ua" class="" target="_blank">Продажа шин в Украине - Lester.ua</a>
                </div>
                <div class="page-footer__copy-txt">
                    <p>Использование любых материалов, размещённых на сайте, разрешается при условии ссылки на Odessa.net.ua</p>
                </div>
            </div>
        </div>
        <div class="page-footer__item">
            <div class="socials socials--round page-footer__socials">
                <ul class="socials__list">
                                            <li class="socials__item">
                            <a href=" https://www.facebook.com/odessa.net.ua/?ref=bookmarks" title="facebook" target="_blank">
                                <svg>
                                <use xlink:href="#icon_fb" />
                                </svg>
                            </a>
                        </li>
                                                                                                                            <li class="socials__item">
                            <a href="https://t.me/odessa_net_ua" title="Telegram - kherson.net.ua" target="_blank">
                                <svg>
                                <use xlink:href="#icon_telegram" />
                                </svg>
                            </a>
                        </li>
                                        <li class="socials__item">
                        <a href="/rss" title="RSS - kherson.net.ua" target="_blank">
                            <svg>
                            <use xlink:href="#icon_rss" />
                            </svg>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div style="display: none;">
            <div id="socialGroups">
                <div class="title">Подписывайтесь и оставайтесь в курсе всех новостей!</div>
                <div class="groups">
                                                                <div class="g_face"><div class="fb-page" data-href="https://www.facebook.com/odessa.net.ua/?ref=bookmarks" data-tabs="timeline" data-width="300" data-height="300" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><div class="fb-xfbml-parse-ignore"><blockquote cite="https://www.facebook.com/odessa.net.ua/?ref=bookmarks"><a href="https://www.facebook.com/odessa.net.ua/?ref=bookmarks">Odessa.net.ua</a></blockquote></div></div></div>
                                                        </div>
                <div class="clear"></div>
                <div class="socText">Подписывайтесь и оставайтесь в курсе всех новостей вместе с Odessa.net.ua!</div>
                <a href="#" class="cboxClose">мне уже нравится Odessa.net.ua</a>
            </div>
        </div>
        <div class="page-footer__item">
            <div class="page-footer__metric">
                                                            <!--LiveInternet counter--><script type="text/javascript"><!--
document.write("<a href='//www.liveinternet.ru/click' "+
"target=_blank><img src='//counter.yadro.ru/hit?t14.6;r"+
escape(document.referrer)+((typeof(screen)=="undefined")?"":
";s"+screen.width+"*"+screen.height+"*"+(screen.colorDepth?
screen.colorDepth:screen.pixelDepth))+";u"+escape(document.URL)+
";"+Math.random()+
"' alt='' title='LiveInternet: показано число просмотров за 24"+
" часа, посетителей за 24 часа и за сегодня' "+
"border='0' width='88' height='31'><\/a>")
//--></script><!--/LiveInternet-->                                            <!-- Yandex.Metrika informer -->
<a href="https://metrika.yandex.ua/stat/?id=37604850&amp;from=informer"
target="_blank" rel="nofollow"><img src="https://informer.yandex.ru/informer/37604850/3_1_FFFFFFFF_EFEFEFFF_0_pageviews"
style="width:88px; height:31px; border:0;" alt="Яндекс.Метрика" title="Яндекс.Метрика: данные за сегодня (просмотры, визиты и уникальные посетители)" onclick="try{Ya.Metrika.informer({i:this,id:37604850,lang:'ru'});return false}catch(e){}" /></a>
<!-- /Yandex.Metrika informer -->

<!-- Yandex.Metrika counter -->
<script type="text/javascript">
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter37604850 = new Ya.Metrika({
                    id:37604850,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true
                });
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script"),
            f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = "https://mc.yandex.ru/metrika/watch.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/37604850" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->                                                </div>
        </div>
        <div class="page-footer__item">
            <a href="http://wezom.com.ua/" class="page-footer__develop" title="Wezom" target="_blank">
                <div class="svgHolder">
                    <svg>
                    <use xlink:href="#icon_wezom" />
                    </svg>
                </div>
                <div class="page-footer__copy-txt">
                    <p>Разработка сайта –<br>студия wezom</p>
                </div>
            </a>
        </div>
    </div>
</footer>        <div id="mobile-menu" class="hideIt" data-menu-title="odessa.net.ua">
    <ul>
                    <li><a href="/news/fakty-ob-odesse">Факты об Одессе</a></li>
                    <li><a href="/news/odessa-i-oblast">Одесса и область</a></li>
                    <li><a href="/news/odessa-naiznanku">Одесса наизнанку</a></li>
                    <li><a href="/news/proisshestvija">Происшествия</a></li>
                    <li><a href="/news/sport">Спорт</a></li>
                    <li><a href="/news/novoe_o_nas_">Новое о нас </a></li>
                    <li><a href="/news/intervju">Интервью</a></li>
                    <li><a href="/news/afisha">Афиша</a></li>
                    <li><a href="/news/monitoring">Мониторинг</a></li>
            </ul>
</div>
<svg id="sprite" xmlns="http://www.w3.org/2000/svg" style="height:0;width:0;visibility:hidden;position:absolute;top:0;left:0;" onload="spriteSvg.initialize(this, '/Media/js/sprite-svg.json')"></svg>
<!-- end SVG-SPRITE -->

    </body>
</html>