<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
	<title>O.Π.Ε.Κ.Ε.Π.Ε.</title>
	<meta http-equiv="Content-Type" content="text/html; charset=windows-1253">
	<link rel="stylesheet" type="text/css" href="css/styles.css" />
	
	<!--BACKGROUND IMAGE-->
	<style>
		<!--
			body {
				background-image: url(images/bb_OPEKEPE.png);
				background-repeat: repeat;
				background-attachment: fixed;
				//tabs
				margin: 0;
				padding: 0;
			}
		//-->
	</style>

	<!--CENTRAL MENU-->
	<link rel="stylesheet" type="text/css" href="css/anylinkmenu.css" />
	<script type="text/javascript" src="js/anylinkmenu.js"></script>
	<script type="text/javascript">
		//anylinkmenu.init("menu_anchors_class") //Pass in the CSS class of anchor links (that contain a sub menu)
		anylinkmenu.init("menuanchorclass")
	</script>
	<!--END OF MENU-->

	
		<!--FIRST PAGE TABS-->
		<link rel="stylesheet" type="text/css" href="css/tabs.css" />
		<script type="text/javascript" src="js/tabs_n.js"></script>
		<script src="js/utils.js" type="text/javascript"></script>
		<script src="js/tabs.js" type="text/javascript"></script>
		<script type="text/javascript">
		// <![CDATA[

			function init(){
				tabInit();
				//function pointer to function myFunction().
				tabsChanged = function(){

					window.status= 
						"activeTab= "
						+this.activeTab.id
						+"; relatedTab= "
						+this.relatedTab.id;
				}	
				TabSystem.list["body"].addEventListener("onchange", tabsChanged);
			}

		// ]]>
		</script>
		<!--END OF TABS-->
	

</head>

<body topmargin="0" onload="init()">
	<table border="0" width="998" cellpadding="0" cellspacing="0" align="center">
		<!--HEADER IMAGE--->
		<tr><td>
			<table  cellpadding="0" cellspacing="0" width="998" border="0">
				<tr><td><img src="images/image-head.jpg" height="226" width="998"></td></tr>
			</table>
		</td></tr>
		<!--TELOS-->

		<tr><td>
			<!--TO KENTRIKO TABLE ME TO BORDER-->
			<table bgcolor="9f9d9d" width="100%" cellpadding="1" cellspacing="0">
				<tr><td>
					<table border="0" bgcolor="#FFFFFF" width="100%" cellspacing="0" cellpadding="0">
						<!--MENU-->
												<tr><td height="55" valign="top">
							<table  border="0" cellpadding="0" cellspacing="0" valign="top" class="menu" width="100%">
								<!---EDW XEKINAW-->
								<tr>
									<td>
										<script type="text/javascript">
											var anylinkmenu3={divclass:'anylinkmenucols', inlinestyle:'', linktarget:'secwin'} //Third menu variable. Same precaution.
											anylinkmenu3.cols={divclass:'column', inlinestyle:''} //menu.cols if defined creates columns of menu links segmented by keyword "efc"
											anylinkmenu3.items=[
												["Ιστορία", "history.asp"],
												["Σκοπός", "aim.asp"],
												["Αρμοδιότητες", "armodiotites.asp"],
												["Διάρθρωση Κεντρικής Υπηρεσίας", "dieuthunseis.asp"],
												["Περιφερειακή Διάρθρωση", "diar8rwsh.asp"],
												["Διοικητικό Συμβούλιο", "sumboulio.asp"],
												["Οργανόγραμμα", "domh.asp"],
                                                                                                ["Εκπαιδευτική Πολιτική", "ekpaid_politikh.asp"]
											]
										</script>
										<a href="index.asp" class="menuanchorclass myownclass" rel="anylinkmenu3"><img src="images/menu/opekepe_m.jpg" border="0" width="127" height="55"></a>
									</td>
									<td>
										<a href="applications.asp"><img id="Εφαρμογές" alt="Εφαρμογές" src="images/menu/applications_m.jpg" border="0" width="140" height="55"></a>
									</td>
									<td>
										<a href="controls.asp"><img id="Έλεγχοι" alt="Έλεγχοι" src="images/menu/controls_m.jpg" border="0" width="123" height="55"></a>
									</td>
									<td>
										<a href="epikoinwnia.asp"><img id="Πρόσβαση" alt="Πρόσβαση" src="images/menu/access_m.jpg" border="0" width="142" height="55"></a>
									</td>
									<td>
										<a href="telephones.asp"><img id="Επικοινωνία" alt="Επικοινωνία" src="images/menu/telephones_m.jpg" border="0" width="146" height="55"></a>
									</td>
									<td>
										<a href="links.asp"><img id="Σύνδεσμοι" alt="Σύνδεσμοι" src="images/menu/links_m.jpg" border="0" width="136" height="55"></a>
									</td>
									<td>
										<a href="index.asp"><img id="Αρχική Σελίδα" alt="Αρχική Σελίδα" src="images/menu/home_m.jpg" border="0" width="53" height="55"></a>
									</td>
									<td>
										<a href="sitemap.asp"><img id="Χάρτης Ιστού" alt="Χάρτης Ιστού" src="images/menu/sitemap_m.jpg" border="0" width="39" height="55"></a>
									</td>
									<td>
										<a href="index.asp"><img id="Ελληνικά" alt="Ελληνικά" src="images/menu/greek_f_m.jpg" border="0" width="34" height="55"></a>
									</td>
									<td>
										<a href="/english"><img id="English" alt="English" src="images/menu/english_f_m.jpg" border="0" width="37" height="55"></a>
									</td>
									<td>
										<img src="images/menu/teleiwma_m.jpg" border="0" width="19" height="55">
									</td>
								</tr>

								<!--EDW TELEIWNEI-->
							</table>
							</td>
						</tr>
						<!--TELOS TOU MENU-->
						<!--OLO TO KENTRIKO KOUTI-->
						<tr><td valign="top">
							<table border="0" width="100%" cellpadding="0" cellspacing="0" bgcolor="#FFFFFF">
								<tr>

									<!--- WIDTH ARISTERA APO BORDER MEXRI HMEROLOGIO -->
									<td width="12">&nbsp;</td>

									<!--ARISTERO MENU-->
									<td width="317" valign="top">
										<table border="0" cellpadding="0" cellspacing="0" width="317" valign="top">
											<tr><td><img src="images/space_height.gif" alt="space" height="12"></td></tr>
											<tr><td><a href=mini_calendar.asp?day=current&month=3><img src=images/leftmenu/hmerologio.jpg alt=hmerologio border=0 width=156 height=109></a></td>

												<td><a href="plhrwmes.asp?year=2018"><img src="images/leftmenu/plhrwmes.jpg" alt="payments" border="0" width="161" height="109"></a></td>
											</tr>
											<tr><td><a href="maae.asp"><img src="images/leftmenu/maae.jpg" alt="register" border="0" width="156" height="118"></a></td>
												<td><a href="sdip.asp"><img src="images/leftmenu/enimerosi.jpg" alt="e_pay" border="0" width="161" height="118"></a></td>
											</tr>
											<tr><td><a href="vamvaki.asp"><img src="images/leftmenu/vamvaki.jpg" alt="cotton" border="0" width="156" height="118"></a></td>
												<td><a href="diavouleusi.asp"><img src="images/leftmenu/diakiriksi.jpg" alt="talk" border="0" width="161" height="118"></a></td>
											</tr>
											<tr><td><a href="kathestwta.asp"><img src="images/leftmenu/kathestota.jpg" alt="conditions" border="0" width="156" height="118"></a></td>
												<td><a href="vivliothiki.asp?id=1"><img src="images/leftmenu/vivliothiki.jpg" alt="book" border="0" width="161" height="118"></a></td>
											</tr>
											<tr><td><a href="faq.asp"><img src="images/leftmenu/erotiseis.jpg" alt="questions" border="0" width="156" height="118"></a></td>
												<td><a href="entypa.asp"><img src="images/leftmenu/entypa.jpg" alt="leaflets" border="0" width="156" height="118"></a></td>
											</tr>

									
		




										</table>
									</td>
									<!--GRAMMH ME KOUKIDES-->
									<td background="images/dot.gif" bgcolor="#FFFFFF" width="1"><img src="images/dot.gif" title="dot" alt="dot" name="dot" border="0"></td>
									<td width="13">&nbsp;</td>
									<!--KENTRIKO PERIEXOMENO. Sthn prwth selida perilambanei kai to de3i kommati me ta eikonidia-->
									<td valign="top" width="449">
										<table border="0" cellspacing="0" cellpadding="0">
											<tr><td><img src="images/space_height.gif" alt="space" height="12"></td></tr>
											
											<!--<tr><td><marquee BEHAVIOR="SLIDE" ALIGN="Top" LOOP="1" BGCOLOR="WHITE" DIRECTION="right" HEIGHT=23 WIDTH=439><font class="title-marquee">On-line Ηλεκτρονική Υποβολή</FONT></marquee></td></tr><!--
											<!--<tr><td><img src="images/titlos.gif" width="449" height="23" alt=""></td></tr>-->
											
											<tr><td>&nbsp;</td></tr>
											<tr><td valign="top" class="link">
													<table width="449" background="images/back.gif" height="205" border="0" class="text" cellspacing="0" align="justify" cellpadding="0">
												
													
													
													<!--<tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="eae2016.asp"><font color="red" ><b>Ενιαία Αίτηση Ενίσχυσης 2016</b></font></a></td></tr>-->
												<!--<tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="eae2016.asp">Ενιαία Αίτηση Ενίσχυσης 2016</a></td></tr>
													<tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="http://www.opekepe.gr/bpe.asp">Κοινοποίηση της Ατομικής Πράξης Προσδιορισμού των Οριστικών Δικαιωμάτων Βασικής Ενίσχυσης</a></td></tr> 
													<tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="metavivaseis_2016.asp">Μεταβιβάσεις Δικαιωμάτων Βασικής Ενίσχυσης 2016</a></td></tr>
													<tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="http://www.opekepe.gr/one.asp?id=1452693093&year=2015&cat=P">Πιστοποίηση-Αναγνώριση Φορέων Α' στα πλαίσια του ΟΣΔΕ για τα έτη 2016-2020</a></td></tr>
																								
												   <tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="eae2015.asp">Ενιαία Αίτηση Ενίσχυσης 2015</a></td></tr>
															
												    <tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="doc/June2010/24805_14032017_odhgies_ypovolis_eae2017_energ_dbe.pdf"><b>Οδηγίες Υποβολής ΕΑΕ 2017 & Ενεργοποίησης Δικαιωμάτων Βασικής Ενίσχυσης</b></a></td></tr>
													<tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="proslipsi_epoxikou.asp"><b>Αποτελέσματα Πρόσληψης Εποχικού Προσωπικού</b></a></td></tr>		
															
															
															-->
													<tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="http://www.opekepe.gr/eae2018.asp"><b>Ενιαία Αίτηση Ενίσχυσης 2018</b></a></td></tr>
													<tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="pistopoihsh_KYD_2018.asp"><b>Συμπληρωματική Πρόσκληση Εκδήλωσης Ενδιαφέροντος για το έτος 2018 Πιστοποίηση-Αναγνώριση ΚΥΔ στα πλαίσια του ΟΣΔΕ για τα έτη 2018-2020</b></a></td></tr>
													<tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="https://registration.dikaiomata.gr/user_registration"><b>Εγγραφή και Πρόσβαση στις Online Εφαρμογές του ΟΠΕΚΕΠΕ</b></a></td></tr>		
													<tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="metavivaseis_2018.asp"><b>Μεταβιβάσεις Δικαιωμάτων Βασικής Ενίσχυσης 2018</b></a></td></tr>
													
													<!--<tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="https://p2.dikaiomata.gr/M1018Registration/"><b>Εγγραφή και Υποβολή Αιτήσεων στήριξης για τη Δράση 10.1.08 «Εφαρμογή της μεθόδου σεξουαλικής σύγχυσης των μικρολεπιδόπτερων (ΚΟΜΦΟΥΖΙΟ)»</b></a></td></tr>-->
													<!--<tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="https://p2.dikaiomata.gr/Organics16Registration"><b>Υποβολή Αιτήσεων Μέτρου 11-Βιολογικές καλλιέργειες</b></a></td></tr>-->
													
													<tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="https://osdeopekepe.dikaiomata.gr/registrationUsrMngOsde/">Εφαρμογή Συνδεδεμένων Καθεστώτων Άμεσων Ενισχύσεων</a></td></tr>
													<tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="https://tax-attestation.opekepe.gr">Βεβαίωση Εφορίας Ποσών Επιδότησης</a></td></tr>
														<tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="https://iris.gov.gr/webcenter/portal/irisgov/applications/payments/single-aid">Συνοπτική Ενιαία Αίτηση Ενίσχυσης</a></td></tr>		
													<tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="Draseis_metrou_214.asp">Δράσεις του Μέτρου 214 (Γεωργοπεριβαλλοντικές Δράσεις)</a></td></tr>
													<tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="prwth_daswsh.asp">Πρώτη Δάσωση Γεωργικών Γαιών</a></td></tr>		
													<tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="mhtrwo_sunallassomenwn.asp">Μηχανογραφικό Μητρώο Συναλλασσομένων</a></td></tr>
													<tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="https://iris.gov.gr/webcenter/portal/irisgov/applications/certificates/maee-certificate">Βεβαίωση Εγγραφής ΜΑΑΕ</a></td></tr>
													<!--<tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="pistopoihsh_forewn_2017.asp">Συμπληρωματική Πρόσκληση Εκδήλωσης Ενδιαφέροντος για το έτος 2017 Πιστοποίηση-Αναγνώριση Φορέων Α' στα πλαίσια του ΟΣΔΕ για τα έτη 2017-2020</a></td></tr>
													
													
													<tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="kkea.asp">Διαδικτυακή Εκτύπωση Βεβαίωσης Εγγραφής ΜΑΑΕ και Βεβαίωσης Κατά Κύριο Επάγγελμα Αγρότη</a></td></tr>
													
													<tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="applydim.asp"><b>Ανακοίνωση Πλήρωσης διακοσίων εξήντα (260) θέσεων με σύμβαση εργασίας ιδιωτικού δικαίου ορισμένου χρόνου, διάρκειας δύο (2) μηνών,για την κάλυψη κατεπειγουσών αναγκών</b></a></td></tr>
													<!--<tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="https://microkal.opekepe.gr">Γεωργοί ενταγμένοι στο καθεστώς των μικρών καλλιεργητών το 2015</a></td></tr>-->															
													<!--<tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="rejections.asp">Διαδικτυακή ενημέρωση των γεωργών επί των αποτελεσμάτων διασταύρωσης των στοιχείων των λογαριασμών τους με το τραπεζικό ίδρυμα στο οποίο ανήκουν-ΕΑΕ 2015</a></td></tr>-->													
													<!--<tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="doc/June2010/Ενημερωτικό Σημείωμα για την  Ατομική Πράξη Προσδιορισμού των Προσωρινών Δικαιωμάτων Βασικής Ενίσχυσης.pdf"><b>Ενημερωτικό Σημείωμα σχετικά με την Ατομική Πράξη Προσδιορισμού των Προσωρινών Δικαιωμάτων Βασικής Ενίσχυσης</b></a></td></tr>-->												
												<!--<tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="https://mnap.opekepe.gr/"><b>Αναλυτική Καταγραφή Δικαιούχων Παραγωγών για τα Ειδικά Μέτρα Στήριξης στα Μικρά Νησιά Αιγαίου Πελάγους</b></a></td></tr>-->																												
													<!--<tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="https://eaegroups.opekepe.gr/">Εφαρμογή Καταχώρησης Μελών των Ομάδων Παραγωγών (ΕΑΕ 2015)</a></td></tr>-->					
													<!--<tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="dbe2015.asp">Αιτήσεις Μεταβολών για Χορήγηση Δικαιωμάτων Βασικής Ενίσχυσης 2015</a></td></tr>-->
													<!--<tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="mdbe.asp">Ενημέρωση Αποδεκτών Εγκεκριμένων Αιτήσεων Μεταβιβάσεων ΔΕΕ λόγω Κληρονομιάς 2014</a></td></tr>--.													
													<!--<tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="https://eaegroups.opekepe.gr/">Εφαρμογή Καταχώρησης Μελών των Ομάδων Παραγωγών (ΕΑΕ 2014)</a></td></tr>-->												
													<!--<tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="exisotiki.asp">Ενημέρωση των δικαιούχων για την Εξισωτική Αποζημίωση</a></td></tr>-->									
													<!--<tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="ea.asp">Εφαρμογή διαδικτυακής ενημέρωσης σχετικά με την Κατανομή Εθνικού Αποθέματος 2013</a></td></tr>-->
													<!--<tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="poreia_elegxou.asp">Εφαρμογή διαδικτυακής ενημέρωσης των ενδιαφερομένων παραγωγών για την πορεία της αίτησης τους στο Μέτρο της Εξισωτικής Αποζημίωσης 2013</a></td></tr>-->														
													<!--<tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="aee2014_online.asp">Εφαρμογή διαδικτυακής υποβολής Ενιαίας Αίτησης Εκμετάλλευσης 2014</a></td></tr>-->
                                                           <!-- <tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="aee2014_online.asp"><font class="routesmall"><b>Εφαρμογή διαδικτυακής υποβολής Ενιαίας Αίτησης Εκμετάλλευσης 2014</b></font></a></td></tr>-->													
														<!--<tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="aee2013_online.asp"><b>Εφαρμογή διαδικτυακής υποβολής Ενιαίας Αίτησης Εκμετάλλευσης 2013</b></a></td></tr>-->
														<!--<tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="pistopoihsh.asp"><font class="routesmall">Πιστοποίηση – Αναγνώριση Φορέων Α' Βαθμού, Φορέων Β' Βαθμού & Φορέα Συντονισμού στα πλαίσια του ΟΣΔΕ για τα έτη 2014-2020 (Πρόσκληση,Συχνές Ερωτήσεις & Ανακοινώσεις)</font></a></td></tr>-->										
														<!--<tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="jobresults.asp"><b>Προσωρινοί Πίνακες Κατάταξης για την απόκτηση εργασιακής εμπειρίας για 445 άνεργους επιστήμονες με ειδίκευση/εξειδίκευση στον αγροτικό χώρο</b></a></td></tr>
													  <!--<tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="rejections.asp">Διαδικτυακή ενημέρωση των δικαιούχων επί των αποτελεσμάτων διασταύρωσης των στοιχείων των λογαριασμών τους με την Τράπεζα «ΠΕΙΡΑΙΩΣ»</a></td></tr>
                                                        <!--<tr>							<td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="applyjob.asp">Αίτηση για συμμετοχή στο σύστημα απόκτησης εργασιακής εμπειρίας</a></td></tr>														
														<!--<tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="epistrofh_fpa_2012.asp">Επιστροφή ΦΠΑ στους αγρότες του ειδικού καθεστώτος για το έτος 2012</a></td></tr>															
														<!--<tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="efk.asp">Ενημέρωση των δικαιούχων για την Επιστροφή του Ειδικού Φόρου Κατανάλωσης Πετρελαίου </a></td></tr>														
														<!--<tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="efk_2012.asp">Ενημέρωση των δικαιούχων για την Επιστροφή του Ειδικού Φόρου Πετρελαίου 2012</a></td></tr>
														<!--<tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="sunoptikh2012.asp">Εκτύπωση Συνοπτικής Αίτησης Ενιαίας Ενίσχυσης 2012</a></td></tr>										
														<tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="http://it.opekepe.gr/sugar">Διαδικτυακή υποβολή αίτησης ένταξης στη Δράση 2.3 (Β) "Σύστημα Ολοκληρωμένης Διαχείρισης στην Παραγωγή Σακχαροτεύτλων"</a></td></tr>																										
														<tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="http://elgo.opekepe.gr">Πληροφοριακό σύστημα καταχώρησης Πιστοποιημένων Εκτάσεων και Παραδόσεων Ελιάς - 'Αρθρο 68</a></td></tr>
														<tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="kapnos.asp">Αίτηση Γ&#39; Δόσης Μέτρου 144 – Αναδιάρθρωση Καπνού</a></td></tr>												
														<tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="metavivaseis.asp">Μεταβιβάσεις δικαιωμάτων ενιαίας ενίσχυσης</a></td></tr>														
														<tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="pistopoihsh_sump.asp">Συμπληρωματική Πρόσκληση Εκδήλωσης Ενδιαφέροντος για το έτος 2015 - Πιστοποίηση Αναγνώριση Φορέων στα πλαίσια του ΟΣΔΕ για τα έτη 2014-2020</a></td></tr>
														<tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="pistopoihsh.asp">Πιστοποίηση – Αναγνώριση Φορέων Α' Βαθμού, Φορέων Β' Βαθμού & Φορέα Συντονισμού στα πλαίσια του ΟΣΔΕ για τα έτη 2014-2020</a></td></tr>													
														<tr><td valign="top"><img src="images/arrow.png" alt="" width="12" height="14"></td>
															<td width="3">&nbsp;</td>
															<td class="link" valign="top" ><a href="finalresults.asp">Πίνακες Κατάταξης για την απόκτηση εργασιακής εμπειρίας για 445 άνεργους επιστήμονες με ειδίκευση/εξειδίκευση στον αγροτικό χώρο</a></td></tr>-->
													
													
													</tbody></table>
												</td>
											</tr>
											<tr><td>&nbsp;</td></tr>
											<tr><td>
												<div class="tabs">
													<!--<img id="tab1" class="tab tabActive" src="images/tabs_anakoinwseis.jpg" alt="anakoinwseis" width="127" height="34" />	
													<img id="tab2" class="tab" src="images/tabs_deltia.jpg" alt="deltia" width="123" height="34"  />
													<img id="tab3" class="tab" src="images/tabs_prokirixeis.jpg" alt="prokirixeis" width="131" height="34"  />-->
													<img id="tab4" class="tab tabActive" src="images/tabs_pliromes1o.jpg" alt="plirwmes" width="86" height="33" />
													<img id="tab1" class="tab" src="images/tabs_anakoinwseis1o.jpg" alt="anakoinwseis" width="112" height="33" />	
													<img id="tab2" class="tab" src="images/tabs_deltia1o.jpg" alt="deltia" width="114" height="33"  />
													<img id="tab3" class="tab" src="images/tabs_prokirixeis1o.jpg" alt="prokirixeis" width="110" height="33"  />
												</div>
												

												<div id="content4" class="content">
													<div class="main">
														<table  width="455" cellpadding="0" cellspacing="0">
														<tr><td>&nbsp;</td></tr>
																<tr><td><font class="routesmall"> 15/3/2018</font>, 
																	<font class="text">Από τις 14/03/2018 έως τις 15/03/2018 ο Ο.Π.Ε.Κ.Ε.Π.Ε. πραγματοποίησε τις παρακάτω πληρωμές ύψους 11.901.613,19 €:<img src="/NEW/images/pdf_white.jpg" alt="pdf" border="0"> <a href="doc/pliromes/PAYMENTS_OPEKEPE_14032018-15032018.pdf"target="_blank">ΠΛΗΡΩΜΕΣ Ο.Π.Ε.Κ.Ε.Π.Ε. 14/03/2018-15/03/2018</a></font></td></tr>
																	
																<tr><td><font class="routesmall"> 14/3/2018</font>, 
																	<font class="text">Από τις 09/03/2018 έως τις 13/03/2018 ο Ο.Π.Ε.Κ.Ε.Π.Ε. πραγματοποίησε τις παρακάτω πληρωμές ύψους 4.053.398,56 €:<img src="/NEW/images/pdf_white.jpg" alt="pdf" border="0"> <a href="doc/pliromes/PAYMENTS_OPEKEPE_09032018-13032018.pdf"target="_blank">ΠΛΗΡΩΜΕΣ Ο.Π.Ε.Κ.Ε.Π.Ε. 09/03/2018-13/03/2018</a></font></td></tr>
																	
																<tr><td><font class="routesmall"> 9/3/2018</font>, 
																	<font class="text">Από τις 02/03/2018 έως τις 08/03/2018 ο Ο.Π.Ε.Κ.Ε.Π.Ε. πραγματοποίησε τις παρακάτω πληρωμές ύψους 4.822.987,42 €:<img src="/NEW/images/pdf_white.jpg" alt="pdf" border="0"> <a href="doc/pliromes/PAYMENTS_OPEKEPE_02032018-08032018.pdf"target="_blank">ΠΛΗΡΩΜΕΣ Ο.Π.Ε.Κ.Ε.Π.Ε. 02/03/2018-08/03/2018</a></font></td></tr>
																	
																<tr><td><font class="routesmall"> 2/3/2018</font>, 
																	<font class="text">Από τις 28/02/2018 έως τις 01/03/2018 ο Ο.Π.Ε.Κ.Ε.Π.Ε. πραγματοποίησε τις παρακάτω πληρωμές ύψους 3.661.199,59 €:<img src="/NEW/images/pdf_white.jpg" alt="pdf" border="0"> <a href="doc/pliromes/PAYMENTS_OPEKEPE_28022018-01032018.pdf"target="_blank">ΠΛΗΡΩΜΕΣ Ο.Π.Ε.Κ.Ε.Π.Ε. 28/02/2018-01/03/2018</a></font></td></tr>
																	
																<tr><td><font class="routesmall"> 28/2/2018</font>, 
																	<font class="text">Από τις 23/02/2018 έως τις 27/02/2018 ο Ο.Π.Ε.Κ.Ε.Π.Ε. πραγματοποίησε τις παρακάτω πληρωμές ύψους 12.417.608,12 €:<img src="/NEW/images/pdf_white.jpg" alt="pdf" border="0"> <a href="doc/pliromes/PAYMENTS_OPEKEPE_23022018-27022018.pdf"target="_blank">ΠΛΗΡΩΜΕΣ Ο.Π.Ε.Κ.Ε.Π.Ε. 23/02/2018-27/02/2018</a></font></td></tr>
																	
														<tr><td align="right"><img src="images/arrow.png" alt="" width="12" height="14"> <a href="plhrwmes.asp?year=2018" class="link">Περισσότερες Πληρωμές...</a></td></tr>
														<tr><td>&nbsp;</td></tr>
														</table>
													</div>
												</div>
												
												<div id="content1" class="content">
													<div class="main">
													<table width="455" cellpadding="0" cellspacing="0">
														<tr><td>&nbsp;</td></tr>
																<tr><td><font class="routesmall"> 19/3/2018</font>, 
																	<font class="link"><a href="one.asp?id=1521467771&year=2018&cat=A">Ανακοίνωση σχετικά με την έναρξη της Διαδικασίας Μεταβίβασης Δικαιωμάτων Βασικής Ενίσχυσης 2018 </a></font></td></tr>
																	
																<tr><td><font class="routesmall"> 16/3/2018</font>, 
																	<font class="link"><a href="one.asp?id=-1760877020&year=2018&cat=A">Αξιολόγηση ενστάσεων των Υποψηφίων ΚΥΔ για την υπ΄ αρ. 16869/12-02-2018 «Συμπληρωματική Πρόσκληση Εκδήλωσης Ενδιαφέροντος για το έτος 2018 Πιστοποίηση - Αναγνώριση ΚΥΔ στα πλαίσια του ΟΣΔΕ για τα έτη 2018-2020», κατά το δεύτερο στάδιο αξιολόγησης.</a></font></td></tr>
																	
																<tr><td><font class="routesmall"> 16/3/2018</font>, 
																	<font class="link"><a href="one.asp?id=1521205135&year=2018&cat=A">Ανακοίνωση σχετικά με διευκρίνιση επί των Ενδικοφανών Προσφυγών Μ10.1.08(Κομφούζιο)</a></font></td></tr>
																	
																<tr><td><font class="routesmall"> 14/3/2018</font>, 
																	<font class="link"><a href="one.asp?id=666494678&year=2018&cat=A">Επικαιροποίηση καταλόγου της από 6/3/2018 Ανακοίνωσης σχετικά με την Υποχρεωτική Αναγραφή του ΑΡΙΘΜΟΥ ΤΑΥΤΟΤΗΤΑΣ ΑΚΙΝΗΤΟΥ (Α.Τ.ΑΚ) στην Ενιαία Αίτηση Ενίσχυσης 2018</a></font></td></tr>
																	
																<tr><td><font class="routesmall"> 13/3/2018</font>, 
																	<font class="link"><a href="one.asp?id=1520932066&year=2018&cat=A">Ανακοίνωση σχετικά με τους Δασικούς Χάρτες </a></font></td></tr>
																	
																<tr><td><font class="routesmall"> 12/3/2018</font>, 
																	<font class="link"><a href="one.asp?id=1007537256&year=2018&cat=A">ΠΡΟΣΚΛΗΣΗ ΕΚΠΑΙΔΕΥΤΙΚΟ ΣΕΜΙΝΑΡΙΟ - ΠΡΟΓΡΑΜΜΑ ΕΞΕΤΑΣΩΝ ΥΠΟΨΗΦΙΩΝ ΚΥΔ ΚΑΤΟΠΙΝ ΑΞΙΟΛΟΓΗΣΗΣ ΕΝΣΤΑΣΕΩΝ</a></font></td></tr>
																	
														<tr><td align="right"><img src="images/arrow.png" alt="" width="12" height="14"> <a href="nea.asp?year=2018&cat=A" class="link">Παλαιότερες Ανακοινώσεις...</a></td></tr>
														<tr><td>&nbsp;</td></tr>
													</table>
													</div>
												</div>
												
												<div id="content2" class="content">
													<div class="main">
														<table  width="455" cellpadding="0" cellspacing="0">
														<tr><td>&nbsp;</td></tr>
																<tr><td><font class="routesmall"> 14/3/2018</font>, 
																<font class="link"><a href="one.asp?id=1521015400&year=2018&cat=D">ΔΕΛΤΙΟ ΤΥΠΟΥ: Ενημέρωση των παραγωγών σχετικά με ανάρτηση Δασικών Χαρτών</a></font></td></tr>	
																	
																<tr><td><font class="routesmall"> 6/12/2017</font>, 
																<font class="link"><a href="one.asp?id=607739915&year=2018&cat=D">ΔΕΛΤΙΟ ΤΥΠΟΥ:Ενημερωτική-Εκπαιδευική Εκδήλωση(workshop) για το ευρωπαϊκό ερευνητικό πρόγραμμα RECAP</a></font></td></tr>	
																	
																<tr><td><font class="routesmall"> 23/6/2017</font>, 
																<font class="link"><a href="one.asp?id=1498212443&year=2018&cat=D">ΔΕΛΤΙΟ ΤΥΠΟΥ:<b>Δεν απαιτείται προσκόμιση βεβαίωσης κατ΄ επάγγελμα αγρότη από το Μητρώο Αγροτών και Αγροτικών Εκμεταλλεύσεών (ΜΑΑΕ) στις φορολογικές αρχές</b> </a></font></td></tr>	
																	
																<tr><td><font class="routesmall"> 16/5/2017</font>, 
																<font class="link"><a href="one.asp?id=1494935680&year=2018&cat=D">ΔΕΛΤΙΟ ΤΥΠΟΥ:<b>Ενημέρωση των παραγωγών σχετικά με την ανάρτηση των Δασικών χαρτών</b> </a></font></td></tr>	
																	
																<tr><td><font class="routesmall"> 15/5/2017</font>, 
																<font class="link"><a href="one.asp?id=1494841434&year=2018&cat=D">ΔΕΛΤΙΟ ΤΥΠΟΥ:<b>Παράταση χρόνου υποβολής των δηλώσεων Ενιαίας Ενίσχυσης έτους 2017</b></a></font></td></tr>	
																	
														<tr><td align="right"><img src="images/arrow.png" alt="" width="12" height="14"> <a href="nea.asp?year=2018&cat=D" class="link">Παλαιότερα Δελτία Τύπου...</a></td></tr>
														<tr><td>&nbsp;</td></tr>
														</table>
													</div>
												</div>

												<div id="content3" class="content">
													<div class="main">
														<table width="455" cellpadding="0" cellspacing="0">
															<!--<tr><td>&nbsp;</td></tr>
															<tr><td><font class="routesmall"> <b>[Προκηρύξεις Υποέργων Πράξης :<< Υψηλής Προστιθέμενης Αξίας Αγροτικές Ψηφιακές Υπηρεσίες (eΥπΑΑΤ)>>  με ΟΠΣ: 302037]</b></font> 
															<font class="link"><a href="diathesit.asp">Διάθεση Τευχών</a></font></td></tr>
															<tr><td>&nbsp;</td></tr>
															<tr><td><font class="routesmall"> <b>[Προκηρύξεις Υποέργων Πράξης: <<Ψηφιακές Υπηρεσίες Ενιαίας Αίτησης Ενίσχυσης στο Ανανεωμένο Σύστημα Αναγνώρισης Αγροτεμαχίων>> με ΟΠΣ: 379473]</b></font> 
															<font class="link"><a href="pshfiakes_yphresies_2.asp">Διάθεση Τευχών</a></font></td></tr>
															<tr><td>&nbsp;</td></tr>
															<tr><td><font class="routesmall"> <b>[Προκηρύξεις Υποέργων Πράξης: <<Απλοποίηση Διαδικασίας Ολοκληρωμένου Συστήματος Διαχείρισης & Ελέγχου Αγροτικών Ενισχύσεων>> με ΟΠΣ: 374879]</b></font> 
															<font class="link"><a href="aplopoihsh_diadikasias_2.asp">Διάθεση Τευχών</a></font></td></tr>-->
															<tr><td>&nbsp;</td></tr>
														
																<tr><td><font class="routesmall"> 6/3/2018</font>, 
																<font class="link"><a href="one.asp?id=1520332495&year=2018&cat=P">«Προμήθεια Δικτυακού Εξοπλισμού για την Κεντρική Υπηρεσία του Ο.Π.Ε.Κ.Ε.Π.Ε.» με την διαδικασία της απευθείας ανάθεσης σύμφωνα με τον Ν.4412/2016.</a></font></td></tr>
																
																<tr><td><font class="routesmall"> 15/2/2018</font>, 
																<font class="link"><a href="one.asp?id=414820749&year=2018&cat=P">Προμήθεια φωτοαντιγραφικού χαρτιού Α4 & Α3 με την διαδικασία της απευθείας ανάθεσης σύμφωνα με τον Ν.4412/2016 </a></font></td></tr>
																
																<tr><td><font class="routesmall"> 24/1/2018</font>, 
																<font class="link"><a href="one.asp?id=-530724143&year=2018&cat=P">Παροχή Υπηρεσιών καθαρισμού των γραφείων του Ο.Π.Ε.Κ.Ε.Π.Ε. με την διαδικασία της απευθείας ανάθεσης σύμφωνα με τον Ν.4412/2016 </a></font></td></tr>
																
																<tr><td><font class="routesmall"> 27/12/2017</font>, 
																<font class="link"><a href="one.asp?id=1514376215&year=2018&cat=P">«Ματαίωση και Επαναπροκήρυξη διαγωνισμού για την παροχή υπηρεσιών Ιατρού Εργασίας & Τεχνικού Ασφαλείας στην Κεντρική Υπηρεσία και στις Περιφερειακές Διευθύνσεις του Ο.Π.Ε.Κ.Ε.Π.Ε. για το ετός 2018»</a></font></td></tr>
																
																<tr><td><font class="routesmall"> 19/12/2017</font>, 
																<font class="link"><a href="one.asp?id=-1058274694&year=2018&cat=P">Παροχή Υπηρεσιών καθαρισμού των γραφείων του Ο.Π.Ε.Κ.Ε.Π.Ε. με την διαδικασία της απευθείας ανάθεσης σύμφωνα με τον Ν.4412/2016 </a></font></td></tr>
																
														<tr><td align="right"><img src="images/arrow.png" alt="" width="12" height="14"> <a href="nea.asp?year=2018&cat=P" class="link">Παλαιότερες Προκηρύξεις...</a></td></tr>
														<tr><td>&nbsp;</td></tr>
														</table>
													</div>
												</div>
											</td></tr>
										</table>
									</td>
									<td width="13">&nbsp;</td>
									<!--DOT-->
									<td background="images/dot.gif" bgcolor="#FFFFFF" width="1"><img src="images/dot.gif" title="dot" alt="dot" name="dot" border="0"></td>
									<!--<td width="10">&nbsp;</td>-->
									<!--RIGHT MENU-->
									<td width="180" valign="top">
										<table border="0" cellspacing="5" cellpadding="0" width="180" align="center">
											<tr><td width=10>&nbsp;</td>
												<td><table>
														<tr>
															<td><a href="nea_kap.asp"><img src="images/right/nea_kap.jpg" alt="nea kap" border="0" align="center"></a></td>
															
														</tr>
														<tr>
															<td><a href="doc/June2010/SHORT_CHARTA_EKSUPHRETHSHS_20101021_Final.pdf" target="_blank"><img src="images/right/harta.jpg" alt="harta" border="0" align="center"></td>
														</tr>
														
														<tr>
															<td><a href="frouta_new.asp"><img src="images/right/frouta.png" alt="frouta" border="0" align="center"></a></td>
														</tr>
														<!-- <tr>
															<td><a href="episitistikh.asp"><img src="images/right/programma_aporwn.jpg" alt="episitistiki" border="0" align="center"></a></td>
														</tr> -->
														
														<tr>
															<td><a href="https://diavgeia.gov.gr/search" target="_blank"><img src="images/right/diavgia.jpg" alt="diavgia" border="0" align="center"></a></td>
														</tr>									
														<tr>
															<td><a href="program_agrotikhs_anaptukshs_2014_2020.asp"><img src="images/right/prog_agt_14.jpg" alt="ΠΑΑ 2014-2020" border="0" align="center"></a></td>
														</tr>
														<!--<tr>
															<td><a href="smartagrifood.asp"><img src="images/right/smartagrifood.jpg" alt="smartagrifood" border="0" align="center"></a></td>
														</tr>-->
														
														<!-- <tr>
															<td><a href="agrotemaxia_new.asp"><img src="images/right/agrotemaxia.jpg" alt="agrotemaxia" border="0" align="center"></a></td>
														</tr> -->
														<tr>
															<td><a href="fispace.asp"><img src="images/right/fispace-logo.png" alt="FIspace_logo" border="0" align="center" style="margin: 10px 0;"></a></td>
														</tr>
														<tr>
															<td><a href="recap.asp"><img src="images/right/recap-logo.png" alt="recap_logo" border="0" align="center" style="margin: 10px 0;"></a></td>
														</tr>
														<tr>
														<td><a href="espa.asp"><img src="images/espa.jpg" alt="espa" border="0" border="0" align="center"></a></td>
														</tr>
														
												</table></td>
											</tr>
										</table>
									</td>
									
								</tr>
								
				 			</table>
						</td></tr>

						<!--FOOTER-->
						<tr><td width="100%">
							<table cellpadding="0" cellspacing="0" width="100%">
								<tr><td width="13">&nbsp;</td>
									<td><table border="0" width="100%" cellspacing="0" cellpadding="0">
											<tr><td><img src="images/space.gif" alt="space" border="0"></td></tr>
											<tr><td background="images/dot_footer.gif" bgcolor="#FFFFFF" height="1"><img src="images/dot_footer.gif" title="dot" alt="dot" name="dot" border="0"></td></tr>
											<tr><td align="center">
												<table border="0" cellpadding="5" cellspacing="5">
													<tr>										
														<td width="212">&nbsp;</td>
														<td class="footer">&copy; Copyright 2004-2018 Ο.Π.Ε.Κ.Ε.Π.Ε. All rights reserved.</td>
														<td width="220">&nbsp;</td>
													</tr>
												</table>
											</td></tr>
											<tr><td class="textnew"><a href="oroi_xrhshs.asp">Όροι Χρήσης</a> &#47;<a href="politikh_aporrhtou.asp"> Πολιτική Απορρήτου</a></td></tr>
										</table>
									</td>
									<td width="13">&nbsp;</td>
								</tr>
							</table>
						</td></tr>
						<!--TELOS FOOTER-->
					</table>
				</td></tr>
				
			</table>
		</td></tr>
		<!--------TELOS------->
	</table>
</body>
</html>