<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"><meta http-equiv="Content-Type" content="text/html; charset=utf-8">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    
    <title>Навчально-методичний кабінет</title>
<meta name="keywords" content="навчальні матеріали, дидактичні матеріали, позакласні заходи, розмальовки, загадки, вікторини, класні години, сценарії, свята, дитяче творчість, розвиваючі ігри, вітання, поради дачникам, дизайн інтер'єру, поради класним керівникам, поради вожатим, ПДР, етикет" /> 
<meta name="description" content="Виховання і розвиток дітей, організація дозвілля для дошкільнят і школярів, позакласна робота з школярами, розвиток творчих здібностей дитини, допомогу класним керівникам і вихователям" /> 
<meta name="generator" content="InstantCMS - www.instantcms.ru" />
<script type="text/javascript" src="includes/jquery/jquery.js"></script>
<script type="text/javascript" src="core/js/common.js"></script>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <link href="templates/cabinet/css/reset.css" rel="stylesheet" type="text/css" />
    <link href="templates/cabinet/css/text.css" rel="stylesheet" type="text/css" />
    <link href="templates/cabinet/css/960.css" rel="stylesheet" type="text/css" />
    <link href="templates/cabinet/css/styles.css" rel="stylesheet" type="text/css" />
	<link href="templates/cabinet/css/more_blog.css" rel="stylesheet" type="text/css" />

	<script language="JavaScript" type="text/javascript" src="includes/jquery/jquery.jslatex.js"></script>
	<script language="JavaScript" type="text/javascript" src="includes/jquery/lightbox/js/jquery.lightbox.js"></script>
    <link href="includes/jquery/lightbox/css/jquery.lightbox.css" rel="stylesheet" type="text/css" />
<script language="JavaScript" type="text/javascript">
$(document).ready(function() {
      $(".latex").latex();
});
</script>

<style>
#fixed {
	color: #fff;
	padding:1px;
	}
</style>

<script language="JavaScript" type="text/javascript" src="includes/jquery/lightbox/js/jquery.lightbox.js"></script>
<link href="includes/jquery/lightbox/css/jquery.lightbox.css" rel="stylesheet" type="text/css" />
<link rel="shortcut icon" href="favicon.ico"> 	
<link rel="icon" href="favicon.ico" type="image/x-icon">


	
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-53236016-1', 'auto');
  ga('send', 'pageview');

</script>



<script type="text/javascript">
    (function () {
        var w = window,
                d = document,
                protocol = /https/i.test(w.location.protocol) ? 'https:' : 'http:',
                aml = typeof admixerML !== 'undefined' ? admixerML : {};
        aml.fn = aml.fn || [];
        aml.invPath = aml.invPath || (protocol + '//inv-nets.admixer.net/');
        aml.cdnPath = aml.cdnPath || (protocol + '//cdn.admixer.net/');
        if (!w.admixerML) {
            var lodash = document.createElement('script');
            lodash.id = 'amlScript';
            lodash.async = true;
            lodash.type = 'text/javascript';
            lodash.src = aml.cdnPath + 'scripts3/loader2.js';
            var node = d.getElementsByTagName('script')[0];
            node.parentNode.insertBefore(lodash, node);
            w.admixerML = aml;
        }
    })();
</script>


<script type="text/javascript">
    admixerML.fn.push(function () {
        admixerML.defineSlot({
            z: 'ed80a3df-6b83-44f0-ae5f-fb15c3d0c709',
            ph: 'admixer_ed80a3df6b8344f0ae5ffb15c3d0c709_zone_698_sect_550_site_537',
            i: 'inv-nets'
        });
        admixerML.singleRequest();
    });
</script>
 

<script type="text/javascript">
    admixerML.fn.push(function () {
           admixerML.defineSlot({
            z: '2f015565-45f5-4566-a347-071931d9baa8',
            ph: 'admixer_2f01556545f54566a347071931d9baa8_zone_1686_sect_550_site_537',
            i: 'inv-nets'
        });
                        admixerML.singleRequest();
    });
</script>

 

<script type="text/javascript">
    admixerML.fn.push(function () { 
            admixerML.defineSlot({
            z: 'd677566a-56bf-4792-ac41-c552bbc12c43',
            ph: 'admixer_d677566a56bf4792ac41c552bbc12c43_zone_2948_sect_550_site_537',
            i: 'inv-nets'
        });
        admixerML.singleRequest();
    });
</script>


</head>

<body>
<div id="wrapper">
    <div class="caContainer">
        <div class="caHeader">
            <div class="heaLogo">
                <a class="heaLogo" href="index.htm" title="Навчально-методичний кабінет"></a>
 </div>
            
        </div>
        <div class="caMenu" id="topmenu">
            <div class="module">
        <div class="modulebody"><link href="includes/jquery/treeview/jquery.treeview.css" rel="stylesheet" type="text/css" />

<div>
    <ul id="mainmenu" class="menu">

                    <li class="selected">
                <a href="/index.htm" class="selected"><span>Головна</span></a>
 </li>
        
                        
                
                                   
                                    
                                    <li>
                        <a href="/photos/index.htm" target="_self"><span>Фото і картинки</span></a>
 <ul>
                                                                                
                
                                    <li>
                        <a href="/photos/latest.html" target="_self"><span>Нові фото</span></a>
 </li>
                                                                                
                
                                    <li>
                        <a href="/photos/top.html" target="_self"><span>Кращі фото</span></a>
 </li>
                                                                                
                                    
                    
                                            </ul></li>
                                    
                                    <li>
                        <a href="/blogs/index.htm" target="_self"><span>Блоги</span></a>
 </li>
                                                                                                                                                                                                                                                                                                        
                
                                    <li>
                        <a href="/obuchenie-malyshei/index.htm" target="_self"><span>Дітям</span></a>
 <ul>
                                                                                
                
                                    <li>
                        <a href="/stihi-dlja-detei/index.htm" target="_self"><span>Вірші для дітей</span></a>
 </li>
                                                                                
                
                                    <li>
                        <a href="/photos/1052.htm" target="_self"><span>Розмальовки для дітей</span></a>
 </li>
                                                                                
                
                                    <li>
                        <a href="/photos/1044.htm" target="_self"><span>Розвиваючі завдання</span></a>
 </li>
                                                                                
                
                                    <li>
                        <a href="/photos/1062.htm" target="_self"><span>Дитячі вироби</span></a>
 </li>
                                                                                
                
                                    <li>
                        <a href="/shkolnikam/index.htm" target="_self"><span>Школярам</span></a>
 </li>
                                                                                
                                    
                    
                                            </ul></li>
                                    
                                    <li>
                        <a href="/vneklasnaja-rabota/index.htm" target="_self"><span>Позакласна робота</span></a>
 <ul>
                                                                                
                
                                    <li>
                        <a href="/shkolnye-prazdniki/index.htm" target="_self"><span>Шкільні свята</span></a>
 </li>
                                                                                
                
                                    <li>
                        <a href="/igry-konkursy-razvlechenija/index.htm" target="_self"><span>Ігри, конкурси, розваги</span></a>
 </li>
                                                                                
                
                                    <li>
                        <a href="/detskoe-tvorchestvo/index.htm" target="_self"><span>Дитяча творчість</span></a>
 </li>
                                                                                
                
                                    <li>
                        <a href="/letnii-otdyh/index.htm" target="_self"><span>Літній відпочинок</span></a>
 </li>
                                                                                
                
                                    <li>
                        <a href="/letnii-lager/index.htm" target="_self"><span>Літній табір</span></a>
 </li>
                                                                                
                                    
                    
                                            </ul></li>
                                    
                                    <li>
                        <a href="/semeinaja-biblioteka/index.htm" target="_self"><span>Бібліотека</span></a>
 <ul>
                                                                                
                
                                    <li>
                        <a href="/psihologija/index.htm" target="_self"><span>Психологія</span></a>
 </li>
                                                                                
                
                                    <li>
                        <a href="/pedagogika/index.htm" target="_self"><span>Педагогіка</span></a>
 </li>
                                                                                
                
                                    <li>
                        <a href="/sovremenyi-urok/index.htm" target="_self"><span>Сучасний урок</span></a>
 </li>
                                                                                
                
                                    <li>
                        <a href="/klasnomu-rukovoditelyu/index.htm" target="_self"><span>Класному керівнику</span></a>
 </li>
                                                                                
                
                                    <li>
                        <a href="/vs-ob-yetikete/index.htm" target="_self"><span>Все про етикет</span></a>
 </li>
                                                                                
                
                                    <li>
                        <a href="/poslovicy-i-pogovorki/index.htm" target="_self"><span>Прислів'я та приказки</span></a>
 </li>
                                                                                                                    
                                    
                    
                                            </ul></li>
                                    
                                    <li>
                        <a href="/kalendar/index.htm" target="_self"><span>Календар</span></a>
 <ul>
                                                                                
                
                                    <li>
                        <a href="/kalendar/vesna/index.htm" target="_self"><span>Весна</span></a>
 </li>
                                                                                                                                                                                                                                                                                                                                            
                                    
                    
                                            </ul></li>
                                    
                                    <li>
                        <a href="/pedagogika/metodika/index.htm" target="_self"><span>Методика</span></a>
 <ul>
                                                                                
                
                                    <li>
                        <a href="/vospitateljam/index.htm" target="_self"><span>Вихователям</span></a>
 </li>
                                                                                
                
                                    <li>
                        <a href="/uchiteljam-predmetnikam/index.htm" target="_self"><span>Вчителям-предметникам</span></a>
 </li>
                                                                                
                
                                    <li>
                        <a href="/nachalnaja-shkola/index.htm" target="_self"><span>Початкова школа</span></a>
 </li>
                                                                                
                
                                    <li>
                        <a href="/roditeljam/index.htm" target="_self"><span>Батькам</span></a>
 </li>
                                                                                
                                    
                    
                                            </ul></li>
      <li><a href="https://spusk.com.ua" target="_blank" title="Купить украинские сувениры в Киеве недорого"><span>Интернет магазин подарков и сувениров</span></a></li>                              
                                  
        </ul>
</div>


</div>

</div>
        </div>
    </div>
        <div class="caContainer">
        <div class="caWhitePage">
            <div class="caPathway">
                            </div>
            <div class="caMainPage">
                <div class="caRight">

<div class="style3">
    <div class="module">
                    <div class="moduletitle">
 Реклама 
 </div>
                <div class="modulebody"><div align="center" style="margin-left:-4px; padding-left:-4px">
							<!-- Vertikal-PED -->
				
<div id='admixer_2f01556545f54566a347071931d9baa8_zone_1686_sect_550_site_537'></div>
<script type="text/javascript">
    admixerML.fn.push(function () { admixerML.display('admixer_2f01556545f54566a347071931d9baa8_zone_1686_sect_550_site_537'); });
</script>
			
<br /><br />
<noindex>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Vertikal-PED1 -->
<ins class="adsbygoogle"
     style="display:inline-block;width:300px;height:600px"
     data-ad-client="ca-pub-1706281365004807"
     data-ad-slot="7396536976"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>

<br /><br />
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Vertikal-PED1 -->
<ins class="adsbygoogle"
     style="display:inline-block;width:300px;height:600px"
     data-ad-client="ca-pub-1706281365004807"
     data-ad-slot="7396536976"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
</noindex>

				
				</div></div>
    </div>
</div>





                </div>
                <div class="
                                    caCenter
                
                ">
                    <div class="centerBlock">
                        <div class="summerBlock">

<div class="summerItem1">
<p><strong>Навчально-методичний кабінет</strong> - це сайт для педагогів, вчителів, вихователів, студентів, батьків та всіх тих, хто займається вихованням і навчанням дітей.</p>
<p>Навчально-методичний кабінет - це освітній портал, на якому можна отримати багато цікавої та корисної інформації, а також обмінятися з колегами своїм педагогічним досвідом і майстерністю.</p>
<p>Ми сподіваємося, що матеріали нашого сайту допоможуть вам знайти відповіді на питання, що цікавлять вас про виховання, розвитку та навчанні дітей.</p>
</div>
<div class="summerItem2">
<p><strong><span style="font-family: Verdana; "><a title="Батькам про виховання та розвитку дітей" href="roditeljam/index.htm">Виховання дитини</a></span></strong><span style="font-family: Verdana; "> - це система накопичених суспільством теоретичних і методичних знань, наукових психолого-педагогічних розробок, досвіду народної <a title="Педагогіка" href="pedagogika/index.htm"><strong>педагогіки</strong></a>, індивідуальних батьківських знахідок. Ці знання безрозмірні, вони постійно трансформуються, змінюються, збагачуються новими фарбами. І, як будь-які знання, змушують людину думати, міркувати, шукати відповіді на питання, які виникають в ході оволодіння новими знаннями. «Примножуючи знання, множу скорботу», говорив пророк Еклезіаст.</span></p>
<p><span style="font-family: Verdana; ">Батько, замислюється про виховання своєї дитини, відповідально підходить до результатів цього процесу, поводиться як дослідник. Він проникає в глибини педагогіки, <a title="Психологія" href="psihologija/index.htm"><strong>психології</strong></a>, фізіології, намагаючись отримати відповіді на виникаючі в ході виховання питання. Сам процес виховання настільки великий, що знайдений відповідь на одне з питань, розсовує межі пізнання, створюючи ще тисячу нових питань, що стосуються уточнення, поглиблення і розширення отриманих даних.</span></p>
<p><span style="font-family: Verdana; ">Пропоновані Вашій увазі матеріали нашого сайту містять, безумовно, не весь перелік питань і відповідей по складним проблемам виховання. Але це неможливо! Але в якійсь мірі, вони допоможуть уважного і серйозного батькові побудувати свою систему пріоритетів у питаннях виховання своєї дитини.</span></p>
<p><span style="font-family: Verdana; ">Крім того ми пропонуємо цікаві ідея <a title="Шкільні свята, сценарії" href="shkolnye-prazdniki/index.htm"><strong>організації дозвілля</strong></a> та розвитку <a title="Дитячу творчість" href="detskoe-tvorchestvo/index.htm"><strong>творчого потенціалу дітей</strong></a>, а також скарбничку корисних порад та ідей для батьків, вихователів, <a title="Підказки та поради класному керівнику" href="klasnomu-rukovoditelyu/index.htm"><strong>класних керівників</strong></a> та викладачів.</span></p>
<p><span style="font-family: Verdana; ">Ми сподіваємося, що, дотримуючись наших порад, ви обов'язково виховаєте людини, различающего, що добре і що погано, тим самим підготувавши дитини до життя в суспільстві. У вашій родині зникнуть сварки, з'являться взаєморозуміння і взаємоповага. Успіхів вам у цьому!</span></p>
</div>

</div>
                                                
                        
                        

<div class="module">
    <div class="absPen"></div>
            <div class="moduletitle">
 Нове в блогах 
 </div>
        <div class="modulebody">    
            <div class="mod_latest_blog_entry">

            <a class="mod_latest_blog_title" href="blogs/gulnaz-masgutovna-nuriahmetova/razvitie-logicheskogo-myshlenija.html" title="Развитие логического мышления">Розвиток логічного мислення</a>


 <p>Нуриахметова Гульназ Масгутовна вихователь Муніципальне автономне дошкільна освітня установа «Дитячий сад комбінованого виду № 35 «Соловейко» 
Конспект «Розвиток логічного мислення» 
Актуальність. 
Психологами всього світу визнано, що найбільш інтенсивне інтелектуальне розвитк...</p>

        </div>
            <div class="mod_latest_blog_entry">

            <a class="mod_latest_blog_title" href="blogs/sokolovskaja-ina/literaturnaja-viktorina-cherez-pravoslavnuyu-knigu-k-duhovnosti-po-knige-paterik-pecherskii-ili-otechnik.html" title="Литературная  викторина  «Через православную книгу – к духовности&quot;.  По книге «Патерик Печерский, или Отечник»">Літературна вікторина «Через православну книгу - до духовності". По книзі «Патерик Печерський, або Отечник»</a>


 <p>Автор: Соколовська Інна Владиславівна, педагог - бібліотекар, педагог додаткової освіти з Основ православної культури МБОУ Тацинская ЗОШ № 3. Ростовська область 
Опис матеріалу: Пропоную вам літературну вікторину по книзі «Патерик Печерський, або Отечник». "Києво-Печерський Патер...</p>

        </div>
            <div class="mod_latest_blog_entry">

            <a class="mod_latest_blog_title" href="blogs/olga-germanovna-sabitova/razvlechenie-dlja-doshkolnikov-spasateli-strany-dorozhnyh-znakov.html" title="Развлечение для дошкольников &quot;Спасатели страны дорожных знаков&quot;">Розвага для дошкільнят "Рятувальники країни дорожніх знаків"</a>


 <p>Розвага «Рятувальники країни дорожніх знаків » 
Підготувала і провела: Сабітова Ольга Германівна 
Вихователь МБДОУ «Дитячий садок № 1» 
Даний матеріал можна використовувати для роботи з дітьми дошкільного віку 5-7 лет.Материал призначений для вихователів ДНЗ, физинструкторов, педагогів доповніть...</p>

        </div>
            <div class="mod_latest_blog_entry">

            <a class="mod_latest_blog_title" href="blogs/irina-ivanovna-vasileva/staraja-skazka-na-novyi-lad-repka-s-ispolzovaniem-poslovic-i-pogovorok.html" title="Старая сказка на новый лад &quot;Репка&quot; ( с использованием пословиц и поговорок.)">Стара казка на новий лад "Ріпка" ( з використанням прислів'їв і приказок.)</a>


 <p>Опис роботи:для всіх, хто любить сказки.Все ми знаємо і любимо казку "Ріпка",але не менше ми любимо прислів'я та приказки. У своїй роботі я використовувала 33 прислів'я та приказки. 

Ріпка. 

Ця історія сталася в родині старого фермера. Якось ранньою весною задумав фермер посадити ріпу і зібрати...</p>

        </div>
            <div class="mod_latest_blog_entry">

            <a class="mod_latest_blog_title" href="blogs/galina-nikolaevna-suetenko/konspekt-nod-v-starshei-grupe-na-temu-vesna.html" title="Конспект НОД в старшей группе на тему «Весна»">Конспект НОД у старшій групі на тему «Весна»</a>


 <p>Конспект НОД у старшій групі на тему «Весна» 
Автор: Суетенко Галина Миколаївна вихователь ГБОУ ЗОШ № 842, місто Москва 
Опис роботи: Пропоную вам конспект безпосередньо освітньої діяльності на тему «Весна» для дітей старшого дошкільного віку (5-7 років). Даний матеріал буде підлогу...</p>

        </div>
            
           
    
    
    <div class="mod_latest_blog_all" align="right">
        <a href="blogs/index.htm">всі повідомлення »</a>
 </div>


</div>

</div>
                    </div>
                </div>
                <div class="clear"></div>
                <div class="moduleUser">
                    <div class="module">
            <div class="moduletitle">
 Новинки фотогалереї 
 </div>
        <div class="modulebody">        <table cellspacing="2" border="0" style="margin:0px">
              	
                                          <tr>                 <td align="center" valign="middle" class="mod_lp_photo" width="">
				<table width="100%" height="100" cellspacing="0" cellpadding="0">
								<tr>
					  <td valign="middle" align="center">
						<a href="photos/photo6791.html" title="Петунья цветет.">
							<div class="photo_thumb">
                                         <img class="photo_thumb_img" src="images/photos/small/46e471782e305347ffaedb55818276d7.jpg" alt="Петунья цветет." border="0" />
                                          </div>
						</a>
				</td></tr>
								</table>
				
				</td> 
                    			                              <td align="center" valign="middle" class="mod_lp_photo" width="">
				<table width="100%" height="100" cellspacing="0" cellpadding="0">
								<tr>
					  <td valign="middle" align="center">
						<a href="photos/photo6790.html" title="Петунья цветет.">
							<div class="photo_thumb">
                                         <img class="photo_thumb_img" src="images/photos/small/bc5779250e6f98689129ead93f66d426.jpg" alt="Петунья цветет." border="0" />
                                          </div>
						</a>
				</td></tr>
								</table>
				
				</td> 
                    			                              <td align="center" valign="middle" class="mod_lp_photo" width="">
				<table width="100%" height="100" cellspacing="0" cellpadding="0">
								<tr>
					  <td valign="middle" align="center">
						<a href="photos/photo6789.html" title="Пестрые тюльпаны.">
							<div class="photo_thumb">
                                         <img class="photo_thumb_img" src="images/photos/small/b322eae932a8053642e997ef82d1cfd4.jpg" alt="Пестрые тюльпаны." border="0" />
                                          </div>
						</a>
				</td></tr>
								</table>
				
				</td> 
                    			                              <td align="center" valign="middle" class="mod_lp_photo" width="">
				<table width="100%" height="100" cellspacing="0" cellpadding="0">
								<tr>
					  <td valign="middle" align="center">
						<a href="photos/photo6788.html" title="Тюльпан.">
							<div class="photo_thumb">
                                         <img class="photo_thumb_img" src="images/photos/small/bf4f586b9cee9dca4d2dbc64ba0c322b.jpg" alt="Тюльпан." border="0" />
                                          </div>
						</a>
				</td></tr>
								</table>
				
				</td> 
                    			                              <td align="center" valign="middle" class="mod_lp_photo" width="">
				<table width="100%" height="100" cellspacing="0" cellpadding="0">
								<tr>
					  <td valign="middle" align="center">
						<a href="photos/photo6787.html" title="Солнышко в свду.">
							<div class="photo_thumb">
                                         <img class="photo_thumb_img" src="images/photos/small/239056572dad8efae638709e63abea67.jpg" alt="Солнышко в свду." border="0" />
                                          </div>
						</a>
				</td></tr>
								</table>
				
				</td> 
                    			                              <td align="center" valign="middle" class="mod_lp_photo" width="">
				<table width="100%" height="100" cellspacing="0" cellpadding="0">
								<tr>
					  <td valign="middle" align="center">
						<a href="photos/photo6786.html" title="Весна.">
							<div class="photo_thumb">
                                         <img class="photo_thumb_img" src="images/photos/small/feabb43bf0316036e7c90b828c4b6b56.jpg" alt="Весна." border="0" />
                                          </div>
						</a>
				</td></tr>
								</table>
				
				</td> 
                    			                              <td align="center" valign="middle" class="mod_lp_photo" width="">
				<table width="100%" height="100" cellspacing="0" cellpadding="0">
								<tr>
					  <td valign="middle" align="center">
						<a href="photos/photo6785.html" title="Белая сирень.">
							<div class="photo_thumb">
                                         <img class="photo_thumb_img" src="images/photos/small/8dcc9b6eabf4f73a12cc9ea42ec4699f.jpg" alt="Белая сирень." border="0" />
                                          </div>
						</a>
				</td></tr>
								</table>
				
				</td> 
                 </tr>    			                            <tr>                 <td align="center" valign="middle" class="mod_lp_photo" width="">
				<table width="100%" height="100" cellspacing="0" cellpadding="0">
								<tr>
					  <td valign="middle" align="center">
						<a href="photos/photo6784.html" title="Весна.">
							<div class="photo_thumb">
                                         <img class="photo_thumb_img" src="images/photos/small/eb1a9154f3658ceec5addf8592af8be5.jpg" alt="Весна." border="0" />
                                          </div>
						</a>
				</td></tr>
								</table>
				
				</td> 
                    			                              <td align="center" valign="middle" class="mod_lp_photo" width="">
				<table width="100%" height="100" cellspacing="0" cellpadding="0">
								<tr>
					  <td valign="middle" align="center">
						<a href="photos/photo6783.html" title="Весна">
							<div class="photo_thumb">
                                         <img class="photo_thumb_img" src="images/photos/small/88c5dd11eb7a6605829af130c1d61bd3.jpg" alt="Весна" border="0" />
                                          </div>
						</a>
				</td></tr>
								</table>
				
				</td> 
                    			                              <td align="center" valign="middle" class="mod_lp_photo" width="">
				<table width="100%" height="100" cellspacing="0" cellpadding="0">
								<tr>
					  <td valign="middle" align="center">
						<a href="photos/photo6782.html" title="Весна">
							<div class="photo_thumb">
                                         <img class="photo_thumb_img" src="images/photos/small/ea9121a0af858d5610226f88b90e774a.jpg" alt="Весна" border="0" />
                                          </div>
						</a>
				</td></tr>
								</table>
				
				</td> 
                    			                              <td align="center" valign="middle" class="mod_lp_photo" width="">
				<table width="100%" height="100" cellspacing="0" cellpadding="0">
								<tr>
					  <td valign="middle" align="center">
						<a href="photos/photo6781.html" title="Маки">
							<div class="photo_thumb">
                                         <img class="photo_thumb_img" src="images/photos/small/3f20f3d881289bb68aa3249766256c8f.jpg" alt="Маки" border="0" />
                                          </div>
						</a>
				</td></tr>
								</table>
				
				</td> 
                    			                              <td align="center" valign="middle" class="mod_lp_photo" width="">
				<table width="100%" height="100" cellspacing="0" cellpadding="0">
								<tr>
					  <td valign="middle" align="center">
						<a href="photos/photo6780.html" title="Розы.">
							<div class="photo_thumb">
                                         <img class="photo_thumb_img" src="images/photos/small/4f40fb181113d1a11fc5e31869325c84.jpg" alt="Розы." border="0" />
                                          </div>
						</a>
				</td></tr>
								</table>
				
				</td> 
                    			                              <td align="center" valign="middle" class="mod_lp_photo" width="">
				<table width="100%" height="100" cellspacing="0" cellpadding="0">
								<tr>
					  <td valign="middle" align="center">
						<a href="photos/photo6779.html" title="Красавица-Весна.">
							<div class="photo_thumb">
                                         <img class="photo_thumb_img" src="images/photos/small/a0fc94180aa67c75c425f28149640af0.jpg" alt="Красавица-Весна." border="0" />
                                          </div>
						</a>
				</td></tr>
								</table>
				
				</td> 
                    			                              <td align="center" valign="middle" class="mod_lp_photo" width="">
				<table width="100%" height="100" cellspacing="0" cellpadding="0">
								<tr>
					  <td valign="middle" align="center">
						<a href="photos/photo6778.html" title="&quot;Оленята&quot;.">
							<div class="photo_thumb">
                                         <img class="photo_thumb_img" src="images/photos/small/6a82c282bf7ab5f334f8ab354713d6b6.jpg" alt="&quot;Оленята&quot;." border="0" />
                                          </div>
						</a>
				</td></tr>
								</table>
				
				</td> 
                 </tr>    						</table>
			</div>

</div>
<div class="module">
    <div class="threeBook">
        <div class="threeBookItem">
            <div class="threeBorder">
                <div class="inThreeBorder book1">
                    <ul>
                                    <li>
                        <a href="psihologija/index.htm" target="_self"><span>Психологія</span></a>
 </li>
                                                                                
                
                                    <li>
                        <a href="pedagogika/index.htm" target="_self"><span>Педагогіка</span></a>
 </li>
                                                                                
                
                                    <li>
                        <a href="sovremenyi-urok/index.htm" target="_self"><span>Сучасний урок</span></a>
 </li>
                                                                                
                
                                    <li>
                        <a href="klasnomu-rukovoditelyu/index.htm" target="_self"><span>Класному керівнику</span></a>
 </li>
                                                                                
                
                                    <li>
                        <a href="obuchenie-malyshei/index.htm" target="_self"><span>Навчання малюків</span></a>
 </li>
                                                                                
                                    <li>
                        <a href="poslovicy-i-pogovorki/index.htm" target="_self"><span>Прислів'я та приказки</span></a>
 </li>
                
                                    <li>
                        <a href="raznoe/index.htm" target="_self"><span>Різне</span></a>
 </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="threeBookItem">
            <div class="threeBorder">
                <div class="inThreeBorder book2">
                    <ul>
                                    <li>
                        <a href="vneklasnaja-rabota/index.htm" target="_self"><span>Позакласна робота</span></a>
 </li>
                                                                                
                
                                    <li>
                        <a href="vospitateljam/index.htm" target="_self"><span>Вихователям</span></a>
 </li>
                                                                                
                
                                    <li>
                        <a href="roditeljam/index.htm" target="_self"><span>Батькам</span></a>
 </li>
                                                                                
                
                                    <li>
                        <a href="nachalnaja-shkola/index.htm" target="_self"><span>Початкова школа</span></a>
 </li>
                                                                                
                
                                    <li>
                        <a href="uchiteljam-predmetnikam/index.htm" target="_self"><span>Вчителям-предметникам</span></a>
 </li>
                                                                                
                
                                    <li>
                        <a href="shkolnikam/index.htm" target="_self"><span>Школярам</span></a>
 </li>
                                    <li>
                        <a href="semeinaja-biblioteka/index.htm" target="_self"><span>Сімейна бібліотека</span></a>
 </li>

                    </ul>
                </div>
            </div>
        </div>
        <div class="threeBookItem">
            <div class="threeBorder">
                <div class="inThreeBorder book3">
                    <ul>

                                    <li>
                        <a href="shkolnye-prazdniki/index.htm" target="_self" class="selected"><span>Шкільні свята</span></a>
 </li>
                                                                                
                
                                    <li>
                        <a href="igry-konkursy-razvlechenija/index.htm" target="_self"><span>Ігри, конкурси, розваги</span></a>
 </li>
                                                                                
                
                                    <li>
                        <a href="vs-ob-yetikete/index.htm" target="_self"><span>Все про етикет</span></a>
 </li>
                                                                                
                
                                    <li>
                        <a href="detskoe-tvorchestvo/index.htm" target="_self"><span>Дитяча творчість</span></a>
 </li>
                                                                                
                
                                    <li>
                        <a href="letnii-otdyh/index.htm" target="_self"><span>Літній відпочинок</span></a>
 </li>
                                                                                
                
                                    <li>
                        <a href="letnii-lager/index.htm" target="_self"><span>Літній табір</span></a>
 </li>
                                    <li>
                        <a href="stihi-dlja-detei/index.htm" target="_self"><span>Вірші для дітей</span></a>
 </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
                </div>
            </div>
        </div>
    		<div style="margin:0em 6em 0em 3em;">

		<!-- Footer-PED -->


<div id='admixer_ed80a3df6b8344f0ae5ffb15c3d0c709_zone_698_sect_550_site_537'></div>
<script type="text/javascript">
    admixerML.fn.push(function () { admixerML.display('admixer_ed80a3df6b8344f0ae5ffb15c3d0c709_zone_698_sect_550_site_537'); });
</script><br />
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Footer-PED -->
<ins class="adsbygoogle"
     style="display:inline-block;width:580px;height:400px"
     data-ad-client="ca-pub-1706281365004807"
     data-ad-slot="2173787773"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>

</div> <br /><br /><noindex>

</noindex>
    </div><div class="pad">
	  
	</div>
</div>

<div id="footer">
                            
        <div style="padding-top: 50px; color: #794D20; font-size: 11px; text-align: center;">© 2014 <strong>Навчально-методичний кабінет</strong></div>

</div>
</body>
</html>