













    










<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        

        
            
        

        

        <title>Pneumatiky pre vaše vozidlo na pneu eshope POPGOM.sk</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="Content-Language" content="sk-SK" />
        
        <meta name="keywords" content="" />
        <meta name="description" content="Pneumatiky pre vaše vozidlo na pneu eshpe POPGOM.sk  Každý mesiac nové akcie, pneumtiky za skvelé ceny." />
        <meta name="robots" content="index, follow" />
        <meta name="author" content="Popgom / Tyredating" />
        <meta http-equiv="pragma" content="no-cache" />
        
      	<link rel="alternate" href="https://www.popgom.fr/" hreflang="fr-fr" />
      	<link rel="alternate" href="https://www.popgom.es/" hreflang="es-es" />
     	<link rel="alternate" href="https://www.reifen-popgom.de/" hreflang="de-de" />
      	<link rel="alternate" href="https://www.reifen-popgom.at/" hreflang="de-at" />
      	<link rel="alternate" href="https://www.pneus-popgom.ch/" hreflang="fr-ch" />
      	<link rel="alternate" href="https://www.reifen-popgom.ch/" hreflang="de-ch" />
      	<link rel="alternate" href="https://www.banden-popgom.nl/" hreflang="nl-nl" />
      	<link rel="alternate" href="https://www.pneus-popgom.be/" hreflang="fr-be" />
      	<link rel="alternate" href="https://www.banden-popgom.be/" hreflang="nl-be" />
      	<link rel="alternate" href="https://www.pneumatiky-popgom.sk/" hreflang="sk-sk" />
      	<link rel="alternate" href="https://www.pneu-popgom.cz/" hreflang="cs-cz" />
      	<link rel="alternate" href="https://www.gumi-popgom.hu/" hreflang="hu-hu" />
      	<link rel="alternate" href="https://www.gume-popgom.si/" hreflang="sl-si" />
      	<link rel="alternate" href="https://www.dack-popgom.se/" hreflang="sv-se" />
      	<link rel="alternate" href="https://www.daekshop-popgom.dk/" hreflang="da-dk" />
      	<link rel="alternate" href="https://www.anvelope-popgom.ro/" hreflang="ro-ro" />
        
        <link rel="apple-touch-icon" href="https://md.proty.re/v/v_2018_03_16_1438/8121034/img/store/popgom/apple-touch-icon.png" />
        <link rel="apple-touch-icon" sizes="72x72" href="https://md.proty.re/v/v_2018_03_16_1438/8121034/img/store/popgom/apple-touch-icon72.png" />
        <link rel="apple-touch-icon" sizes="114x114" href="https://md.proty.re/v/v_2018_03_16_1438/8121034/img/store/popgom/apple-touch-icon114.png" />
        <link rel="icon shortcut" href="https://md.proty.re/v/v_2018_03_16_1438/8121034/img/store/popgom/favicon.ico" type="image/x-icon" />
        
            <link rel="canonical" href="https://www.pneumatiky-popgom.sk/" />
        

        
        
        
        
        
        
        
        
        
        
        
        
        
            <link charset="UTF-8" rel="stylesheet" href="https://md.proty.re/v/v_2018_03_16_1438/8121034/g/css/v201201/default.css/css/v201201/engagement.css/css/v201xxx/header.css/css/jquery/jquery.qtip-2.0.0.css/css/basket/popups.css/css/v201201/contenuhome.css/css/v201xxx/tyreSelector.css/css/v201201/footer.css/css/v201xxx/drapeau.css/css/newsletter.css/css/prospect_ajax.css/css/alert.css/css/popupOrderProcess.css/css/201507/partials/buttons.css/css/201507/partials/helpers.css/css/basket/color-box.css" type="text/css" />
        

        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
            <script type="text/javascript" src="https://md.proty.re/v/v_2018_03_16_1438/8121034/g/js/jquery/jquery-1.8.3.min.js/js/common/popgom.js/js/util.js/js/jquery/jquery.cookie.js/js/jquery/jquery.json-2.3.min.js/js/jquery/jquery.base64.js/js/ppgcookie.js/js/store/popgom/popgom-home.js/js/jquery/jquery.cycle-1.5.all.js/js/tooltip.js/js/jquery/jquery.qtip-2.0.0.min.js/js/common/buttons.js/js/ppgSearchCookie.js/js/jquery/jquery.colorbox-min.js/js/BwLibraryIO/Bw/core-io-xml.js/js/popup/popup.js/js/td-interne.js/js/common/utilPopgom.js"></script>
        
        




<script type="text/javascript">
    popgom.localeData.langPrefix = '';
    popgom.localeData.language = 'sk';
    popgom.localeData.country = 'SK';
    popgom.localeData.shop = '';
    popgom.localeData.simpleShop = false;
    popgom.localeData.orderDomain = 'https://www.pneumatiky-popgom.sk';
    popgom.localeData.currencySymbol = '&euro;';
    popgom.localeData.production = true;
    popgom.localeData.store = 'POPGOM';
    popgom.localeData.mobile = false;
    popgom.localeData.responsive = false;
    popgom.localeData.mobilePageNotExist = true;
    popgom.localeData.urlBasket = 'https://www.pneumatiky-popgom.sk/basket/';
    popgom.localeData.urlBasketFitterAppointment = 'https://www.pneumatiky-popgom.sk/basket/fitter-appointment';

    
    
    

    
    popgom.parameters.orderProcessInABTesting = 'true';
    

    popgom.localeData.dictionnary['bulle-aide-roulage-a-plat'] = 'Ak m\u00E1te na va\u0161om vozidle pneumatiky, ktor\u00E9 umo\u017E\u0148uj\u00FA jazdu na plocho (nosn\u00E9 boky typu ZP, RunFlat, SSR, at\u010F.).';
    popgom.localeData.dictionnary['roulage-a-plat'] = 'Runflat (RFT)';
    popgom.localeData.dictionnary['largeur'] = '\u0160\u00EDrka';
    popgom.localeData.dictionnary['mobile-page-not-exist'] = 'Spletna stran ne obstaja za\u00A0mobilno verzijo ali Vas preusmerimo?';
    popgom.localeData.dictionnary['diametre'] = 'Priemer';
    popgom.localeData.dictionnary['flans-renforces'] = 'Zosilnen\u00E9 (XL)';
    popgom.localeData.dictionnary['bulle-aide-flans-renforces'] = 'Ak m\u00E1 va\u0161e vozidlo pneumatiky extra load, reinforced, XL, REINF.';
    popgom.localeData.dictionnary['hauteur'] = 'V\u00FD\u0161ka';
    
    
</script>


    <script>window['adrum-start-time'] = new Date().getTime();</script>




<script type="text/javascript">
    var kameleoonLoadingTimeout = 1000;

    if (! document.getElementById("kameleoonLoadingStyleSheet") && ! window.kameleoonDisplayPageTimeOut){
    var kameleoonS = document.getElementsByTagName("script")[0];var kameleoonCc = "* { visibility: hidden !important; background-image: none !important; }";
    var kameleoonStn = document.createElement("style");kameleoonStn.type = "text/css";kameleoonStn.id = "kameleoonLoadingStyleSheet";
    if (kameleoonStn.styleSheet){kameleoonStn.styleSheet.cssText = kameleoonCc;}else{kameleoonStn.appendChild(document.createTextNode(kameleoonCc));}kameleoonS.parentNode.insertBefore(kameleoonStn, kameleoonS);
    window.kameleoonDisplayPage = function(){if (kameleoonStn.parentNode){kameleoonStn.parentNode.removeChild(kameleoonStn);}};
    window.kameleoonDisplayPageTimeOut = window.setTimeout(window.kameleoonDisplayPage, kameleoonLoadingTimeout);}
</script>

<script src="//static.kameleoon.com/css/customers/uak8r9uzza/0/kameleoon.js" async="true"></script>
    </head>
    <body id="blocBody">
    	

















	
	    
	    
	    	
	    	
	    
	




<script type="text/javascript">
<!--
dataLayer = [{
    
    eventAction : '',
    eventCategory : '',
    eventInteraction : '',
    eventLabel : '',
    eventValue : '',
	customerCity : '',
	customerEmail : '',
	customerFirstName : '',
	customerLastName : '',
    customerEmailMD5 : '',
	customerPostalCode : '',
	articleDimension : '',
	deliveryType : '',
	fittingNetwork : '',
	hasPreviousOrder : '',
	nbProducts : '',
	paymentMethod : '',
	unitPrice : '',
	unitPriceExclVAT : '',
	reinforced : '',
	runflat : '',
	servicesTotalPrice : '',
	transactionAffiliation : '',
	transactionId : '',
	transactionShipping : 0,
	transactionTax : 0,
	transactionTotal : 0,
	transactionTotalExclVAT : 0,
	transactionGoodsTotalExclVAT : '',
	articleType : '',
	articleSku : '',
	articleId : '',
	articleName : '',
	articleQuantity : '',
	articleBrand : '',
	articleModel : '',
	articleSeason : '',
	device : 'DESKTOP',
	language : 'sk',
	locale : 'sk_SK',
	countryCode : 'SK',
	orderDate : '',
	shippingDate : '',
	deliveryDate : '',
	totalDiscount : '',
	vehicleGroup : 'TOURISM',
	
	
	isInBVersion : (typeof popgom !== 'undefined' && popgom !== undefined && popgom.userdata && popgom.userdata.abtesting && popgom.userdata.abtesting.isInBConfiguration())? 'B2':'A2',
	
	
	transactionProducts : []
	} ];










	var elementDataLayer = {};
	

	elementDataLayer.ecommerce = {};
	
		elementDataLayer.ecommerce.currencyCode = 'EUR';
	
	
		elementDataLayer.ecommerce['impressions'] = [];
		
		elementDataLayer.ecommerce['impressions'].push({
			    id : '138578',
			    name : 'Hankook Ventus Prime 3 K125',
			    category : 'Tires\/Tourism\/Summer',
			    price : '50.00',
			    brand : 'Hankook',
			    list : 'Home pushed',
			    variant : '205\/55 R16 91V',
			    position : '1'
			});
		
		elementDataLayer.ecommerce['impressions'].push({
			    id : '39774',
			    name : 'Dunlop Sport BluResponse',
			    category : 'Tires\/Tourism\/Summer',
			    price : '62.50',
			    brand : 'Dunlop',
			    list : 'Home pushed',
			    variant : '205\/55 R16 91V',
			    position : '2'
			});
		
		elementDataLayer.ecommerce['impressions'].push({
			    id : '148942',
			    name : 'Sebring Formula Sporty+',
			    category : 'Tires\/Tourism\/Summer',
			    price : '38.20',
			    brand : 'Sebring',
			    list : 'Home pushed',
			    variant : '225\/45 R17 91Y',
			    position : '3'
			});
		
		elementDataLayer.ecommerce['impressions'].push({
			    id : '37938',
			    name : 'Michelin Energy Saver +',
			    category : 'Tires\/Tourism\/Summer',
			    price : '57.60',
			    brand : 'Michelin',
			    list : 'Home pushed',
			    variant : '195\/65 R15 91H',
			    position : '4'
			});
		
		elementDataLayer.ecommerce['impressions'].push({
			    id : '35086',
			    name : 'Continental PremiumContact 5 ',
			    category : 'Tires\/Tourism\/Summer',
			    price : '65.70',
			    brand : 'Continental',
			    list : 'Home pushed',
			    variant : '205\/55 R16 91V',
			    position : '5'
			});
		
		elementDataLayer.ecommerce['impressions'].push({
			    id : '9429',
			    name : 'Prva cena Yellow Sea YS618',
			    category : 'Tires\/Tourism\/Summer',
			    price : '39.10',
			    brand : 'Prva cena',
			    list : 'Home pushed',
			    variant : '235\/45 ZR17 97W',
			    position : '6'
			});
		
	
	
	window.dataLayer.push(elementDataLayer);
	


//-->
</script>



<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-7H8N"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-7H8N');</script>





	<script type="text/javascript">
	    popgom.userdata.tracking.setTrackingVisitCookie();
	</script>


    
        <script type="text/javascript" src="https://md.proty.re/v/v_2018_03_16_1438/8121034/js/adrum.js" async></script>
    

<!-- SITE UP www.pneumatiky-popgom.sk -->
        <div id="container">
            













<div class="headerHelp noprint">
    <div class="headerHelpChangeLanguage">
        
            
            
            
            
            
        
    </div>

    







    
    
    
        
    


    
    
        
    



    <div class="headerInfo noprint">
        <div class="headerIdentification headerIdentification-sk_SK" >
            <div class="headerMenuIdentification">
                <a href="#comp" title="">
                    <b style="float:left;">Môj účet</b>&nbsp;
                    <span style="color: black; font-size: 8px; margin-top: 2px; font-family: 'Lucida Grande'">&#9660;&nbsp;&nbsp;</span>
                </a>
            </div>
            <div style="display:none;" class="headerMenuSub">
                <div class="headerMenuSubBody">
                    <div style="padding-left:5px; padding-right:5px;">
                    	<a  href="https://www.pneumatiky-popgom.sk/pneumatiky-POPGOM/moj-ucet?account=true" onmousedown='popgom.button.effectOnMouseDown(this);' onmouseup='popgom.button.effectOnMouseUp(this);' onmousemove='popgom.button.effectOnMouseUp(this);' onmouseover='popgom.button.effectOnMouseUp(this);' id="customerConnection" class="button button-cta1 small buttonUp "><span>Prihlásenie </span></a>

                        <div id="customerDeconnection" class="hide">
                        	<a  href="https://www.pneumatiky-popgom.sk/" onmousedown='popgom.button.effectOnMouseDown(this);' onmouseup='popgom.button.effectOnMouseUp(this);' onmousemove='popgom.button.effectOnMouseUp(this);' onmouseover='popgom.button.effectOnMouseUp(this);' onclick="popgom.localeData.user.disconnectCustomer();return false;" id="customerConnection" class="button button-cta1 small buttonUp "><span>Odhlásiť sa </span></a>
                        </div>
                    </div>
                    <div class="headerMenuDefault" id="newCustomer"><a class="headerMenuDefaultLink" href="https://www.pneumatiky-popgom.sk/pneumatiky-POPGOM/moj-ucet?account=true">
                           Nový zákazník?
                        </a></div>
                    <div class="headerMenuSeparator"></div>
                    <div class="headerMenuDefault">
                        <a href="https://www.pneumatiky-popgom.sk/pneumatiky-POPGOM/moj-ucet?account=true" title="">
                            <span>
                                Môj účet
                            </span>
                        </a>
                    </div>
                    <div class="headerMenuDefault">
                        <a href="https://www.pneumatiky-popgom.sk/pneumatiky-POPGOM/moj-ucet?account=true&action=su">
                            <span>
                                Moje objednávky
                            </span>
                        </a>
                    </div>
                    <div class="headerMenuDefault">
                        <a href="https://www.pneumatiky-popgom.sk/contactCenter" title="">
                            FAQ
                        </a>
                    </div>
                </div>
                <div class="headerMenuSubBottom"></div>
            </div>


        </div>
    </div>

    <script type="text/javascript">

        $(document).ready(function() {
            $(".headerIdentification").hover(function(){ $(".headerMenuSub").show("fast");}, function(){$(".headerMenuSub").hide();});
        });

    </script>


    <div class="headerHelpLink">
        <img src="https://md.proty.re/v/v_2018_03_16_1438/8121034/img/key.png" id="callCenterKey" style="display: none;" alt="Call center" width="16" height="16" width="16" id="callCenterKey" />
        <a href="#" onclick="popgom.ajax.container.loadNewsletter();return false;" title="">
            Odoberať newsletter
        </a>
        <span class="greySeparator">
            &nbsp;|&nbsp;
        </span>
    </div>
    <div class="headerHelpLink">
        <img src="https://md.proty.re/v/v_2018_03_16_1438/8121034/img/key.png" id="callCenterKey" style="display: none;" alt="Call center" width="16" height="16" width="16" id="callCenterKey" />
        
        <a href="https://www.pneumatiky-popgom.sk/pneumatiky-online/faq" style="text-decoration: underline;" title="">
            Potrebujete poradiť?
        </a>
        <span class="greySeparator">
            &nbsp;|&nbsp;
        </span>
    </div>
</div>

<div id="headerLogoBloc">
    <div class="headerLogo" title="Pneumatiky POPGOM" onclick="window.location = 'https://www.pneumatiky-popgom.sk';">
        <a id="ppgLogo" class="ppgLogo ppgLogo-red sprite" href="https://www.pneumatiky-popgom.sk" title="POPGOM.sk">
        </a>
        <div id="extensionSite">
            .sk
        </div>
        <div id="popgomLogoBaseLine">
            PNEUMATIKY - jednoducho!
        </div>
        <div class="clearboth"></div>
    </div>
    <div id="telAndCart">
        
            <div class="headerCart headerCart-sk_SK">
                <div class="headerCartLogo headerCartLogo-red"></div>
                <div class="headerCartInfo">
                    <a href="https://www.pneumatiky-popgom.sk/basket/" id="headerCartLink" title="">
                        <div id="headerCartInfoEmpty" style="display:none;">Váš košík je prázdny. Vyberte si pneumatiky pre objednávku.</div>
                        <div class="headerMenuIdentificationButton_SK">Košík</div>
                        <div id="headerCartInfoArt" style="display:none;">
                            <span id="headerCartInfoArtQty" class="headerCartInfoArt"></span>
                            <span id="headerCartInfoArtOne" class="headerCartInfoArt">Tovar</span>
                            <span id="headerCartInfoArtMany" class="headerCartInfoArt">položky</span>
                        </div>
                     </a>
                </div>
            </div>
        
        <div class="headerHelpCoPhoneDes">
            <a href="https://www.pneumatiky-popgom.sk/pneumatiky-POPGOM/kontaktujte-nas" title="" class="noStyle"
               onclick="openNavigatorCenteredWindow('https://www.pneumatiky-popgom.sk/pneumatiky-POPGOM/kontaktujte-nas','POPGOM','720','600', 'menubar=no,  status=yes, scrollbars=yes, location=no');return false;" title="02/ 3233 3312  - Náš zákaznícky servis je Vám k dispozícii v pracovných dňoch od 08:00 do 16:30.">
                <div id="prospectPhone">
                    <div style="float: left;">
                        02/ 3233 3312
                    </div>
                    
                        
                        
                        
                            <div id="phone_logo"></div>
                        
                    
                </div>
                <div class="clearboth"></div>
                <div id="service-commercial-header">
                    Zákaznícky servis 
                </div>
            </a>
        </div>
        
    </div>
    








    <div id="searchTabBloc" class="noprint">
        
            <a class="searchTab searchTabPromo-red" href="/lacne-pneumatiky">
                AKČNÁ PONUKA
            </a>
            
        
        
            
            
            
            <a style="margin-right: 1px;" title="" class="searchTab" href="/lacne-pneumatiky/michelin-crossclimate">
                <div style='color:#fbe601;background:#2f3f74;-webkit-border-radius: 4px;-moz-border-radius: 4px;border-radius: 4px;border-bottom:2px solid #ffffff;' onmouseover="this.style.background='#160582';" onmouseout="this.style.color='#fbe601';this.style.background='#2f3f74';">CROSSCLIMATE</div>
            </a>
        
            
            
            
            <a style="margin-right: 1px;" title="" class="searchTab" href="/4x4-suv">
                <div style='color:#ffffff;background:#be1922;border-top:1px solid #ffffff;border-right:1px solid #ffffff;border-left:1px solid #ffffff;-webkit-border-radius: 4px;-moz-border-radius: 4px;border-radius: 4px;border-bottom:2px solid #ffffff;' onmouseover="this.style.color='#ffffff';this.style.background='#be1922';" onmouseout="this.style.color='#ffffff';this.style.background='#be1922';this.style.borderTopColor='#ffffff';this.style.borderRightColor='#ffffff';this.style.borderLeftColor='#ffffff';"><strong>4x4 PNEU</strong></div>
            </a>
        
            
            
            
            <a style="margin-right: 1px;" title="" class="searchTab" href="/zimne-pneumatiky">
                <div style='color:#ffffff;background:#1043cf;border-top:1px solid #ffffff;border-right:1px solid #ffffff;border-left:1px solid #ffffff;-webkit-border-radius: 4px;-moz-border-radius: 4px;border-radius: 4px;border-bottom:2px solid #ffffff;' onmouseover="this.style.color='#ffffff';this.style.background='#5562ad';" onmouseout="this.style.color='#ffffff';this.style.background='#1043cf';this.style.borderTopColor='#ffffff';this.style.borderRightColor='#ffffff';this.style.borderLeftColor='#ffffff';"><strong>ZIMNÉ PNEU</strong></div>
            </a>
        
            
            
            
            <a style="margin-right: 1px;" title="" class="searchTab" href="/letne-pneumatiky">
                <div style='color:#f7f7f2;background:#be1922;border-top:1px solid #ffffff;border-right:1px solid #ffffff;border-left:1px solid #ffffff;-webkit-border-radius: 4px;-moz-border-radius: 4px;border-radius: 4px;border-bottom:2px solid #ffffff;' onmouseover="this.style.color='#ffffff';this.style.background='#be1922';" onmouseout="this.style.color='#f7f7f2';this.style.background='#be1922';this.style.borderTopColor='#ffffff';this.style.borderRightColor='#ffffff';this.style.borderLeftColor='#ffffff';"><strong>LETNÉ PNEU</strong></div>
            </a>
        
        
    </div>


    
</div>
<div class="clearboth"></div>

            <div style="float: left;">
                













	<div id="searchBloc"  class="searchBloc-red noprint">
	    
	        <div id="searchHeader" class="searchHeader searchHeader-red">
	            <div style="float: left;padding-top: 5px;">
	                <h1 id="searchByHeader">Hľadajte pneu podľa:</h1>
	            </div>
	            <div class="searchTypeTabActive" style="float: left;margin-left: 10px;">
	                <span style="color: black;">&#9658;</span>rozmeru
	            </div>
	            
	            <div style="float: left;">
                    <a class="searchTypeTabLink" title="" href="/nakup-pneumatiky-auto">
	                    vozidla
	                </a>
	            </div>
	            <div style="float: right;">
                    <a id="searchBlocHelp" href="/readadimension" title="" onclick="openNavigatorCenteredWindow('/readadimension','POPGOM','620','650', 'menubar=no,  status=no, scrollbars=yes, location=no');return false;">
	                    Neviete rozmery pneumatík?
	                </a>
	            </div>
	        </div>
	        <div class="clearboth"></div>
	    
		    <div>
		        <form style="float: left;width: 982px;" method="get" id="searchForm" action="/find" onsubmit="return popgom.localeData.searchParams.checkDimensionData();" autocomplete="off">
		            <div>
		                <input type="hidden" name="mode"           value="size"/>
		            </div>
		            <div id="warning-message">
		                <p style="font-size:11px;">
		                    Nasledujúce políčka nie sú správne:
		                </p>
		                <p id="label-error">
		                    &nbsp;
		                </p>
		            </div>
		            <div id="dimensionProfileOptionTable">
		                <div id="dimensionProfileOptionTableSelectCase">
		                    <div class="dimensionProfileOptionTableSelect">







    
    
        
    




<select name="season" onchange="popgom.localeData.searchParams.saveSearchProperty(this);" id="season" class="clignote-action"><option value="hiver">Zimné pneu</option>
    
    <option value="ete" selected="selected">Letné pneu</option>
    
        <option value="toutes">Celoročné pneu</option>
    
    <option value="tous">Všetky</option></select>
</div>
		                    <div class="dimensionProfileOptionTableSelect">
		                        
		                            
		                        







    
    



<select name="manufacturer" id="manufacturer"  onchange="popgom.localeData.searchParams.saveSearchProperty(this);">
    
        <option value="" style="text-align: center;">Značka</option>
    
    <option value="">Všetky značky</option>
    
        <option class="manufacturersPremiumGroup" value="PREMIUM" >Prémiové</option>
        
            <option class="manufacturersPremiumItem" value="1" >&nbsp;&nbsp;&nbsp;&nbsp;Michelin</option>
        
            <option class="manufacturersPremiumItem" value="3" >&nbsp;&nbsp;&nbsp;&nbsp;Continental</option>
        
            <option class="manufacturersPremiumItem" value="6" >&nbsp;&nbsp;&nbsp;&nbsp;Pirelli</option>
        
            <option class="manufacturersPremiumItem" value="5" >&nbsp;&nbsp;&nbsp;&nbsp;Dunlop</option>
        
            <option class="manufacturersPremiumItem" value="4" >&nbsp;&nbsp;&nbsp;&nbsp;GoodYear</option>
        
            <option class="manufacturersPremiumItem" value="2" >&nbsp;&nbsp;&nbsp;&nbsp;Bridgestone</option>
        
    
    
        <option class="manufacturersQualityGroup" value="QUALITY" >Kvalita</option>
        
            <option class="manufacturersQualityItem" value="8" >&nbsp;&nbsp;&nbsp;&nbsp;BFGoodrich</option>
        
            <option class="manufacturersQualityItem" value="30" >&nbsp;&nbsp;&nbsp;&nbsp;Barum</option>
        
            <option class="manufacturersQualityItem" value="37" >&nbsp;&nbsp;&nbsp;&nbsp;Cooper</option>
        
            <option class="manufacturersQualityItem" value="14" >&nbsp;&nbsp;&nbsp;&nbsp;Falken</option>
        
            <option class="manufacturersQualityItem" value="12" >&nbsp;&nbsp;&nbsp;&nbsp;Firestone</option>
        
            <option class="manufacturersQualityItem" value="13" >&nbsp;&nbsp;&nbsp;&nbsp;Fulda</option>
        
            <option class="manufacturersQualityItem" value="15" >&nbsp;&nbsp;&nbsp;&nbsp;General Tire</option>
        
            <option class="manufacturersQualityItem" value="10" >&nbsp;&nbsp;&nbsp;&nbsp;Hankook</option>
        
            <option class="manufacturersQualityItem" value="7" >&nbsp;&nbsp;&nbsp;&nbsp;Kleber</option>
        
            <option class="manufacturersQualityItem" value="11" >&nbsp;&nbsp;&nbsp;&nbsp;Kumho</option>
        
            <option class="manufacturersQualityItem" value="27" >&nbsp;&nbsp;&nbsp;&nbsp;Matador</option>
        
            <option class="manufacturersQualityItem" value="32" >&nbsp;&nbsp;&nbsp;&nbsp;Nokian</option>
        
            <option class="manufacturersQualityItem" value="41" >&nbsp;&nbsp;&nbsp;&nbsp;Sava</option>
        
            <option class="manufacturersQualityItem" value="24" >&nbsp;&nbsp;&nbsp;&nbsp;Semperit</option>
        
            <option class="manufacturersQualityItem" value="28" >&nbsp;&nbsp;&nbsp;&nbsp;Toyo</option>
        
            <option class="manufacturersQualityItem" value="9" >&nbsp;&nbsp;&nbsp;&nbsp;Uniroyal</option>
        
            <option class="manufacturersQualityItem" value="31" >&nbsp;&nbsp;&nbsp;&nbsp;Vredestein</option>
        
            <option class="manufacturersQualityItem" value="29" >&nbsp;&nbsp;&nbsp;&nbsp;Yokohama</option>
        
    
    
        <option class="manufacturersFirstPriceGroup" value="FIRSTPRICE" >Lacné</option>
        
            <option class="manufacturersFirstPriceItem" value="68" >&nbsp;&nbsp;&nbsp;&nbsp;Achilles</option>
        
            <option class="manufacturersFirstPriceItem" value="63" >&nbsp;&nbsp;&nbsp;&nbsp;Autoguard</option>
        
            <option class="manufacturersFirstPriceItem" value="38" >&nbsp;&nbsp;&nbsp;&nbsp;Debica</option>
        
            <option class="manufacturersFirstPriceItem" value="25" >&nbsp;&nbsp;&nbsp;&nbsp;GT Radial</option>
        
            <option class="manufacturersFirstPriceItem" value="16" >&nbsp;&nbsp;&nbsp;&nbsp;Gislaved</option>
        
            <option class="manufacturersFirstPriceItem" value="64" >&nbsp;&nbsp;&nbsp;&nbsp;Imperial</option>
        
            <option class="manufacturersFirstPriceItem" value="39" >&nbsp;&nbsp;&nbsp;&nbsp;Kormoran</option>
        
            <option class="manufacturersFirstPriceItem" value="65" >&nbsp;&nbsp;&nbsp;&nbsp;Landsail</option>
        
            <option class="manufacturersFirstPriceItem" value="66" >&nbsp;&nbsp;&nbsp;&nbsp;Lanvigator</option>
        
            <option class="manufacturersFirstPriceItem" value="40" >&nbsp;&nbsp;&nbsp;&nbsp;Marangoni</option>
        
            <option class="manufacturersFirstPriceItem" value="26" >&nbsp;&nbsp;&nbsp;&nbsp;Maxxis</option>
        
            <option class="manufacturersFirstPriceItem" value="35" >&nbsp;&nbsp;&nbsp;&nbsp;Meteor</option>
        
            <option class="manufacturersFirstPriceItem" value="42" >&nbsp;&nbsp;&nbsp;&nbsp;Nexen</option>
        
            <option class="manufacturersFirstPriceItem" value="36" >&nbsp;&nbsp;&nbsp;&nbsp;Sebring</option>
        
            <option class="manufacturersFirstPriceItem" value="44" >&nbsp;&nbsp;&nbsp;&nbsp;Taurus</option>
        
            <option class="manufacturersFirstPriceItem" value="22" >&nbsp;&nbsp;&nbsp;&nbsp;Prva cena</option>
        
    
</select>

		                    </div>
		                    
		                        
		                        
		                        
		                    
		                    <div class="dimensionProfileOptionTableSelect">
                                
                                <select name="vehicleType" onchange="popgom.localeData.searchParams.saveSearchProperty(this);" id="vehicleType" class=""><option value="" style="text-align: center;">Typ</option>
                                    <option value="0">Osobné</option>
                                    <option value="1">4x4</option>
                                    <option value="2">Dodávkové (C)</option>
                                    <option value="3">Kempingové auto</option>
                                    <option value="-1">Všetky</option></select>
		                    </div>
		
		                    <div id="dimensionProfileOptionTableRR">
		                        <div class="dimensionProfileOptionTableRRRunflat">
		                            
		                                
		                                
		                            
		                            <input type="checkbox" class="radiofdrouge inputRR checkbox" name="runFlat" id="runFlat" onclick="popgom.localeData.searchParams.saveSearchProperty(this);"  />
		                            <label for="runFlat" class="labelRR labelRR-sk_SK">Runflat (RFT)</label>
		                            <span class="dimensionProfileOptionTableRRRunflatToolTip">(?)</span>
		                        </div>
		                            <div class="clearboth"></div>
		                        <div class="dimensionProfileOptionTableRRReinforced">
		                            
		                                
		                                
		                            
                                    <input type="checkbox" name="reinforced" value="on" onclick="popgom.localeData.searchParams.saveSearchProperty(this);" id="reinforced" class="radiofdrouge inputRR checkbox" />
		                            <label for="reinforced" class="labelRR labelRR-sk_SK">Zosilnené (XL)</label>
		                            <span class="dimensionProfileOptionTableRRReinforcedToolTip">(?)</span>
		                        </div>
		                    </div>
		                </div>
		            </div>
		            <div  id="tyreDimensionTable">
		                <div class="tyreDimensionTableLabel">
		                    <div class="tdValue">
		                        <label id="label-width" for="width" class="labelrecherche">Šírka</label>
		                    </div>
		                    <div class="tdValue">
		                        <label id="label-ratio" for="ratio" class="labelrecherche">Výška</label>
		                     </div>
		                    <div class="tdValue">
		                        <label id="label-diameter" for="diameter" class="labelrecherche">Priemer</label>
		                    </div>
		                    <div class="tdValue">
		                        <label for="load" class="labelrecherche labelrechercheload-sk_SK">Záťaž</label>
		                    </div>
		                    <div class="tdValue">
		                        <label id="label-speed" for="speed" class="labelrecherche labelrecherchespeed-sk_SK">Rýchlosť</label>
		                    </div>
		                </div>
		                <div class="tyreDimensionTableSelector">
		                    <div class="tdValue" onmouseover="popgom.localeData.searchParams.changeTyredOnOver('Width');" onmouseout="popgom.localeData.searchParams.changeTyredOnOut('Width');">
		                        <img src="https://md.proty.re/v/v_2018_03_16_1438/8121034/img/pictos/black-arrow.gif" id="direction-width" class="searchArrow" alt="" id="direction-width" class="searchArrow" />
		                        
		                            
		                            
		                                
		                            
		                        
                                <select name="width" onchange="popgom.localeData.searchParams.changeComboValue(this);" id="width"><option value="">...</option>
                                    <option value="105">105</option>
<option value="115">115</option>
<option value="120">120</option>
<option value="125">125</option>
<option value="135">135</option>
<option value="140">140</option>
<option value="145">145</option>
<option value="155">155</option>
<option value="160">160</option>
<option value="165">165</option>
<option value="170">170</option>
<option value="175">175</option>
<option value="180">180</option>
<option value="185">185</option>
<option value="190">190</option>
<option value="195">195</option>
<option value="200">200</option>
<option value="205" selected="selected">205</option>
<option value="210">210</option>
<option value="215">215</option>
<option value="220">220</option>
<option value="225">225</option>
<option value="230">230</option>
<option value="235">235</option>
<option value="240">240</option>
<option value="245">245</option>
<option value="255">255</option>
<option value="265">265</option>
<option value="270">270</option>
<option value="275">275</option>
<option value="285">285</option>
<option value="295">295</option>
<option value="300">300</option>
<option value="305">305</option>
<option value="315">315</option>
<option value="325">325</option>
<option value="335">335</option>
<option value="345">345</option>
<option value="355">355</option>
<option value="365">365</option>
<option value="375">375</option>
<option value="450">450</option>
<option value="500">500</option>
<option value="600">600</option>
<option value="640">640</option>
<option value="700">700</option>
<option value="750">750</option>
<option value="30">30 (4x4)</option>
<option value="31">31 (4x4)</option>
<option value="31.11">31.11 (4x4)</option>
<option value="32">32 (4x4)</option>
<option value="33">33 (4x4)</option>
<option value="34">34 (4x4)</option>
<option value="35">35 (4x4)</option>
<option value="36">36 (4x4)</option>
<option value="37">37 (4x4)</option>
<option value="38">38 (4x4)</option>
<option value="39">39 (4x4)</option>
<option value="40">40 (4x4)</option>
<option value="64">64 (4x4)</option>
<option value="70">70 (4x4)</option>
<option value="75">75 (4x4)</option>
<option value="82">82 (4x4)</option>
<option value="95">95 (4x4)</option>
<option value="0">0</option>
<option value="1">1</option>
<option value="2.45">2.45</option>
<option value="4.5">4.5</option>
<option value="4.75">4.75</option>
<option value="5">5</option>
<option value="5.2">5.2</option>
<option value="5.25">5.25</option>
<option value="5.5">5.5</option>
<option value="5.6">5.6</option>
<option value="5.9">5.9</option>
<option value="6">6</option>
<option value="6.4">6.4</option>
<option value="6.5">6.5</option>
<option value="6.7">6.7</option>
<option value="7">7</option>
<option value="7.25">7.25</option>
<option value="7.5">7.5</option>
<option value="8">8</option>
<option value="8.2">8.2</option>
<option value="8.5">8.5</option>
<option value="8.75">8.75</option>
<option value="9">9</option>
<option value="9.5">9.5</option>
<option value="10">10</option>
<option value="10.5">10.5</option>
<option value="11">11</option>
<option value="11.5">11.5</option>
<option value="12">12</option>
<option value="12.5">12.5</option>
<option value="13">13</option>
<option value="13.5">13.5</option>
<option value="14">14</option>
<option value="15">15</option>
<option value="16">16</option>
<option value="17">17</option>
<option value="18">18</option>
<option value="23">23</option>
<option value="27">27</option></select>
		                    </div>
		                    <div class="tdValue" onmouseover="popgom.localeData.searchParams.changeTyredOnOver('Ratio');" onmouseout="popgom.localeData.searchParams.changeTyredOnOut('Ratio');">
		                        <img src="https://md.proty.re/v/v_2018_03_16_1438/8121034/img/pictos/black-arrow.gif" id="direction-ratio" class="searchArrow" alt="" id="direction-ratio" class="searchArrow" />
		                        
		                            
		                            
		                                
		                            
		                        
		                        <select name="ratio" id="ratio"  onchange="popgom.localeData.searchParams.changeComboValue(this);">
		                            <option value="">...</option>
		                            
		                                <option value="6.4" >6.4</option>
		                            
		                                <option value="16" >16</option>
		                            
		                                <option value="35" >35</option>
		                            
		                                <option value="40" >40</option>
		                            
		                                <option value="45" >45</option>
		                            
		                                <option value="50" >50</option>
		                            
		                                <option value="55" selected="selected">55</option>
		                            
		                                <option value="60" >60</option>
		                            
		                                <option value="65" >65</option>
		                            
		                                <option value="66" >66</option>
		                            
		                                <option value="70" >70</option>
		                            
		                                <option value="75" >75</option>
		                            
		                                <option value="76" >76</option>
		                            
		                                <option value="80" >80</option>
		                            
		                                <option value="82" >82</option>
		                            
		                                <option value="85" >85</option>
		                            
		                        </select>
		                    </div>
		                    <div class="tdValue" onmouseover="popgom.localeData.searchParams.changeTyredOnOver('Diameter');" onmouseout="popgom.localeData.searchParams.changeTyredOnOut('Diameter');">
		                        <img src="https://md.proty.re/v/v_2018_03_16_1438/8121034/img/pictos/black-arrow.gif" id="direction-diameter" class="searchArrow" alt="" id="direction-diameter" class="searchArrow" />
		                        
		                            
		                            
		                                
		                            
		                        
		                        <select name="diameter" id="diameter"  onchange="popgom.localeData.searchParams.changeComboValue(this);">
		                            <option value="">...</option>
		                            
		                                <option value="14" >R14</option>
		                            
		                                <option value="15" >R15</option>
		                            
		                                <option value="16" selected="selected">R16</option>
		                            
		                                <option value="17" >R17</option>
		                            
		                                <option value="18" >R18</option>
		                            
		                                <option value="19" >R19</option>
		                            
		                        </select>
		                    </div>
		                    <div class="tdValue" onmouseover="popgom.localeData.searchParams.changeTyredOnOver('Load');" onmouseout="popgom.localeData.searchParams.changeTyredOnOut('Load');">
		                        <img src="https://md.proty.re/v/v_2018_03_16_1438/8121034/img/pictos/black-arrow.gif" id="direction-load" class="searchArrow" alt="" id="direction-load" class="searchArrow" />
		                        
		                            
		                            
		                                
		                            
		                        
		                        <select name="load" id="load" onchange="popgom.localeData.searchParams.changeComboValue(this);">
		                            <option value="">...</option>
		                            
		                                <option value="55" >55</option>
		                            
		                                <option value="79" >79</option>
		                            
		                                <option value="81" >81</option>
		                            
		                                <option value="89" >89</option>
		                            
		                                <option value="90" >90</option>
		                            
		                                <option value="91" selected="selected">91</option>
		                            
		                                <option value="92" >92</option>
		                            
		                                <option value="94" >94</option>
		                            
		                                <option value="95" >95</option>
		                            
		                                <option value="98" >98</option>
		                            
		                                <option value="99" >99</option>
		                            
		                                <option value="0" >0</option>
		                            
		                            <option value="tous" >Všetky</option>
		                        </select>
		                     </div>
		                    <div class="tdValue" onmouseover="popgom.localeData.searchParams.changeTyredOnOver('Speed');" onmouseout="popgom.localeData.searchParams.changeTyredOnOut('Speed');">
		                        <img src="https://md.proty.re/v/v_2018_03_16_1438/8121034/img/pictos/black-arrow.gif" id="direction-speed" class="searchArrow" alt="" id="direction-speed" class="searchArrow" />
		                        
		                            
		                            
		                                
		                            
		                        
		                        <select name="speed" id="speed" onchange="popgom.localeData.searchParams.changeComboValue(this);">
		                            <option value="">...</option>
		                            
		                            
		                                
		                                    
		                                    
		                                        <option value="Q" >Q</option>
		                                    
		                                
		                            
		                                
		                                    
		                                    
		                                        <option value="R" >R</option>
		                                    
		                                
		                            
		                                
		                                    
		                                    
		                                        <option value="S" >S</option>
		                                    
		                                
		                            
		                                
		                                    
		                                    
		                                        <option value="T" >T</option>
		                                    
		                                
		                            
		                                
		                                    
		                                    
		                                        <option value="H" >H</option>
		                                    
		                                
		                            
		                                
		                                    
		                                    
		                                        <option value="V" selected="selected">V</option>
		                                    
		                                
		                            
		                                
		                                    
		                                        
		                                    
		                                    
		                                
		                            
		                                
		                                    
		                                        
		                                    
		                                    
		                                
		                            
		                                
		                                    
		                                    
		                                        <option value="W" >W</option>
		                                    
		                                
		                            
		                                
		                                    
		                                    
		                                        <option value="Y" >Y</option>
		                                    
		                                
		                            
		                                
		                                    
		                                    
		                                        <option value="Y" >ZR(Y)</option>
		                                    
		                                
		                            
		                            
		                                <option value="Z-ZR" >Z-ZR</option>
		                            
		                            <option value="tous" >Všetky</option>
		                        </select>
		                     </div>
		                </div>
		            </div>
		            <div style="float: left;">
		                <div id="tyreDimensionImg" class="defaultTyreDimension tyreDimension-red-205_55R16_91V"></div>
		            </div>
		            <a  href="#" onmousedown='popgom.button.effectOnMouseDown(this);' onmouseup='popgom.button.effectOnMouseUp(this);' onmousemove='popgom.button.effectOnMouseUp(this);' onmouseover='popgom.button.effectOnMouseUp(this);' onclick="popgom.localeData.searchParams.executeSearch(this); return false;" class="button button-cta1 xx-large buttonUp tyre-selector-button-home"><span>Vyhľadať </span></a>
		        </form>
		    </div>
	</div>

<div class="clearboth"></div>


    <div id="searchFooter" class="searchFooter-red">
        <center> Rýchly výber:

<a href="https://www.pneumatiky-popgom.sk/pneumatiky/pneumatiky-205-55-16-91-v" style="color:white">205/55R16 91V </a> &bull;
<a href="https://www.pneumatiky-popgom.sk/pneumatiky/pneumatiky-195-65-15-91-h" style="color:white">195/65R15 91H </a> &bull;
<a href="https://www.pneumatiky-popgom.sk/pneumatiky/pneumatiky-175-65-14-82-t" style="color:white">175/65R14 82T </a> &bull;
<a href="https://www.pneumatiky-popgom.sk/pneumatiky/pneumatiky-165-70-14-81-t" style="color:white">165/70R14 81T </a> &bull;
<a href="https://www.pneumatiky-popgom.sk/pneumatiky/pneumatiky-185-60-14-82-h" style="color:white">185/60R14 82H </a> &bull;
<a href="https://www.pneumatiky-popgom.sk/pneumatiky/pneumatiky-195-60-15-88-h" style="color:white">195/60R15 88H </a> &bull;
<a href="https://www.pneumatiky-popgom.sk/pneumatiky/pneumatiky-185-65-14-86-t" style="color:white">185/65R14 86T </a> &bull;
<a href="https://www.pneumatiky-popgom.sk/pneumatiky/pneumatiky-205-55-16-91-h" style="color:white">205/55R16 91H </a> &bull;
<a href="https://www.pneumatiky-popgom.sk/pneumatiky/pneumatiky-165-70-13-79-t" style="color:white">165/70R13 79T </a> &bull;
<a href="https://www.pneumatiky-popgom.sk/pneumatiky/pneumatiky-195-50-15-82-v" style="color:white">195/50R15 82V </a> &bull;
</center>
    </div>
    <div class="clearboth"></div>




<script type="text/javascript">
    $(document).ready(function() {
	popgom.tooltips.createTooltipOnPosWithOptionsAndTitle( $(".dimensionProfileOptionTableRRRunflatToolTip"),
                            popgom.localeData.dictionnary['bulle-aide-roulage-a-plat'],
                            popgom.tooltips.positionTooltipLCRC,true,
                            {html: popgom.localeData.dictionnary['roulage-a-plat'], style :'red' });
	popgom.tooltips.createTooltipOnPosWithOptionsAndTitle( $(".dimensionProfileOptionTableRRReinforcedToolTip"),
                            popgom.localeData.dictionnary['bulle-aide-flans-renforces'],
                            popgom.tooltips.positionTooltipLCRC,true,
                            {html: popgom.localeData.dictionnary['flans-renforces'], style :'red' });
                            
                           popgom.localeData.searchParams.changeTyredOnOver('Width');
    });

</script>

                <script type="text/javascript">
                    popgom.localeData.searchParams.initSelector();
                </script>
            </div>
            <div id="pagecontent" style="float: left;">
                <div class="zone" id="zone-content"><div id="contenuHomeHeader">
    <div id="blocPromiseHeader" class="encartsBlocsContenuHome">
        
            
            
                







    
    
    
    <div class="blocManufHome">
        <a class="blocManufHomeLink" href="/najlacnejsie-pneu/michelin">
            <img src="https://md.proty.re/v/v_2018_03_16_1438/8121034/img/manufacturiers/logo-big-white/michelin.jpg" alt="Michelin" width="122" height="40" width="122" />
        </a>
    </div>

    
    
    
    <div class="blocManufHome">
        <a class="blocManufHomeLink" href="/najlacnejsie-pneu/continental">
            <img src="https://md.proty.re/v/v_2018_03_16_1438/8121034/img/manufacturiers/logo-big-white/continental.jpg" alt="Continental" width="122" height="40" width="122" />
        </a>
    </div>

    
    
    
    <div class="blocManufHome">
        <a class="blocManufHomeLink" href="/najlacnejsie-pneu/pirelli">
            <img src="https://md.proty.re/v/v_2018_03_16_1438/8121034/img/manufacturiers/logo-big-white/pirelli.jpg" alt="Pirelli" width="122" height="40" width="122" />
        </a>
    </div>

    
    
    
    <div class="blocManufHome">
        <a class="blocManufHomeLink" href="/najlacnejsie-pneu/dunlop">
            <img src="https://md.proty.re/v/v_2018_03_16_1438/8121034/img/manufacturiers/logo-big-white/dunlop.jpg" alt="Dunlop" width="122" height="40" width="122" />
        </a>
    </div>

    
    
    
    <div class="blocManufHome">
        <a class="blocManufHomeLink" href="/najlacnejsie-pneu/goodyear">
            <img src="https://md.proty.re/v/v_2018_03_16_1438/8121034/img/manufacturiers/logo-big-white/goodyear.jpg" alt="GoodYear" width="122" height="40" width="122" />
        </a>
    </div>

    
    
    
    <div class="blocManufHome">
        <a class="blocManufHomeLink" href="/najlacnejsie-pneu/bridgestone">
            <img src="https://md.proty.re/v/v_2018_03_16_1438/8121034/img/manufacturiers/logo-big-white/bridgestone.jpg" alt="Bridgestone" width="122" height="40" width="122" />
        </a>
    </div>

    
    
    
    <div class="blocManufHome">
        <a class="blocManufHomeLink" href="/najlacnejsie-pneu/matador">
            <img src="https://md.proty.re/v/v_2018_03_16_1438/8121034/img/manufacturiers/logo-big-white/matador.jpg" alt="Matador" width="122" height="40" width="122" />
        </a>
    </div>

    
    
    
    <div class="blocManufHome">
        <a class="blocManufHomeLink" href="/najlacnejsie-pneu/barum">
            <img src="https://md.proty.re/v/v_2018_03_16_1438/8121034/img/manufacturiers/logo-big-white/barum.jpg" alt="Barum" width="122" height="40" width="122" />
        </a>
    </div>

    
    
    
    <div class="blocManufHome">
        <a class="blocManufHomeLink" href="/najlacnejsie-pneu/kleber">
            <img src="https://md.proty.re/v/v_2018_03_16_1438/8121034/img/manufacturiers/logo-big-white/kleber.jpg" alt="Kleber" width="122" height="40" width="122" />
        </a>
    </div>

    
    
    
    <div class="blocManufHome">
        <a class="blocManufHomeLink" href="/najlacnejsie-pneu/uniroyal">
            <img src="https://md.proty.re/v/v_2018_03_16_1438/8121034/img/manufacturiers/logo-big-white/uniroyal_ue.jpg" alt="Uniroyal" width="122" height="40" width="122" />
        </a>
    </div>

    
    
    
    <div class="blocManufHome">
        <a class="blocManufHomeLink" href="/najlacnejsie-pneu/hankook">
            <img src="https://md.proty.re/v/v_2018_03_16_1438/8121034/img/manufacturiers/logo-big-white/hankook.jpg" alt="Hankook" width="122" height="40" width="122" />
        </a>
    </div>

<div class="blocManufHome">

    <a href="https://www.pneumatiky-popgom.sk/najlacnejsie-pneu" title=""
       class="blocManufHomeLinkFirstPrice">
        ďalšie značky...
    </a>
</div>


            
        
    </div>
    
        
        
            <div id="blocHighlight" class="encartsBlocsContenuHome">
                
                    
                        
                        
                            
                        
                    
                    
                        
                            <a 
                                 href="/lacne-pneumatiky/letne-pneu-v-akcii">
                                <img src="https://md.proty.re/u/8121034/popgom/highlightStamps/sk_SK/sk-hl-chgt-pneus-printemps.gif" title="" alt="" />
                            </a>
                        
                        
                    
                
                    
                        
                        
                            
                        
                    
                    
                        
                            <a style="display: none"
                                 href="https://www.pneumatiky-popgom.sk/lacne-pneumatiky/matador-pneumatiky">
                                <img src="https://md.proty.re/u/8121034/popgom/highlightStamps/sk_SK/sk-hl-matador-vente-privee.gif" title="" alt="" />
                            </a>
                        
                        
                    
                
                    
                        
                        
                            
                        
                    
                    
                        
                            <a style="display: none"
                                 href="/lacne-pneumatiky/osobna-ponuka">
                                <img src="https://md.proty.re/u/8121034/popgom/highlightStamps/sk_SK/sk-hl-vente-privee.gif" title="" alt="" />
                            </a>
                        
                        
                    
                
                    
                        
                        
                            
                        
                    
                    
                        
                            <a style="display: none"
                                 href="/lacne-pneumatiky/adac-letnych-pneumatiky">
                                <img src="https://md.proty.re/u/8121034/popgom/highlightStamps/sk_SK/hl-sk-ete.gif" title="ADAC letné 2017" alt="ADAC letné 2017" />
                            </a>
                        
                        
                    
                
            </div>
            <div id="highlightNav"></div>
            
            <script type="text/javascript">
                $(document).ready(function() {
                    $('#blocHighlight').cycle({
                        fx:                 'fade',
                        pager:              '#highlightNav',
                        //autostop:           true,
                        pause:              true,
                        pagerAnchorBuilder: function (idx, slide)
                        {
                             return '<a href="#"  class="headerBgdImage-red"></a>';
                         }
                    });
                });
            </script>
        
        
    
    <div id="blocMarques" class="encartsBlocsContenuHome">
        







    
    
    
    <div class="blocManufHome">
        <a class="blocManufHomeLink" href="/najlacnejsie-pneu/michelin">
            <img src="https://md.proty.re/v/v_2018_03_16_1438/8121034/img/manufacturiers/logo-big-white/michelin.jpg" alt="Michelin" width="122" height="40" width="122" />
        </a>
    </div>

    
    
    
    <div class="blocManufHome">
        <a class="blocManufHomeLink" href="/najlacnejsie-pneu/continental">
            <img src="https://md.proty.re/v/v_2018_03_16_1438/8121034/img/manufacturiers/logo-big-white/continental.jpg" alt="Continental" width="122" height="40" width="122" />
        </a>
    </div>

    
    
    
    <div class="blocManufHome">
        <a class="blocManufHomeLink" href="/najlacnejsie-pneu/pirelli">
            <img src="https://md.proty.re/v/v_2018_03_16_1438/8121034/img/manufacturiers/logo-big-white/pirelli.jpg" alt="Pirelli" width="122" height="40" width="122" />
        </a>
    </div>

    
    
    
    <div class="blocManufHome">
        <a class="blocManufHomeLink" href="/najlacnejsie-pneu/dunlop">
            <img src="https://md.proty.re/v/v_2018_03_16_1438/8121034/img/manufacturiers/logo-big-white/dunlop.jpg" alt="Dunlop" width="122" height="40" width="122" />
        </a>
    </div>

    
    
    
    <div class="blocManufHome">
        <a class="blocManufHomeLink" href="/najlacnejsie-pneu/goodyear">
            <img src="https://md.proty.re/v/v_2018_03_16_1438/8121034/img/manufacturiers/logo-big-white/goodyear.jpg" alt="GoodYear" width="122" height="40" width="122" />
        </a>
    </div>

    
    
    
    <div class="blocManufHome">
        <a class="blocManufHomeLink" href="/najlacnejsie-pneu/bridgestone">
            <img src="https://md.proty.re/v/v_2018_03_16_1438/8121034/img/manufacturiers/logo-big-white/bridgestone.jpg" alt="Bridgestone" width="122" height="40" width="122" />
        </a>
    </div>

    
    
    
    <div class="blocManufHome">
        <a class="blocManufHomeLink" href="/najlacnejsie-pneu/matador">
            <img src="https://md.proty.re/v/v_2018_03_16_1438/8121034/img/manufacturiers/logo-big-white/matador.jpg" alt="Matador" width="122" height="40" width="122" />
        </a>
    </div>

    
    
    
    <div class="blocManufHome">
        <a class="blocManufHomeLink" href="/najlacnejsie-pneu/barum">
            <img src="https://md.proty.re/v/v_2018_03_16_1438/8121034/img/manufacturiers/logo-big-white/barum.jpg" alt="Barum" width="122" height="40" width="122" />
        </a>
    </div>

    
    
    
    <div class="blocManufHome">
        <a class="blocManufHomeLink" href="/najlacnejsie-pneu/kleber">
            <img src="https://md.proty.re/v/v_2018_03_16_1438/8121034/img/manufacturiers/logo-big-white/kleber.jpg" alt="Kleber" width="122" height="40" width="122" />
        </a>
    </div>

    
    
    
    <div class="blocManufHome">
        <a class="blocManufHomeLink" href="/najlacnejsie-pneu/uniroyal">
            <img src="https://md.proty.re/v/v_2018_03_16_1438/8121034/img/manufacturiers/logo-big-white/uniroyal_ue.jpg" alt="Uniroyal" width="122" height="40" width="122" />
        </a>
    </div>

    
    
    
    <div class="blocManufHome">
        <a class="blocManufHomeLink" href="/najlacnejsie-pneu/hankook">
            <img src="https://md.proty.re/v/v_2018_03_16_1438/8121034/img/manufacturiers/logo-big-white/hankook.jpg" alt="Hankook" width="122" height="40" width="122" />
        </a>
    </div>

<div class="blocManufHome">

    <a href="https://www.pneumatiky-popgom.sk/najlacnejsie-pneu" title=""
       class="blocManufHomeLinkFirstPrice">
        ďalšie značky...
    </a>
</div>


    </div>
</div>
<div class="clearboth"></div>










<div class="engagementContainer">
    <div class="headerProfilesPopularities">
        <h2 class="h2Home">POPGOM sa zaväzuje</h2>
    </div>
    <div class="homeEngagementBloc"id="homeEngagementBloc1">
        <div id="homeEngagementBloc1Txt" class="homeEngagementBloc1 homeEngagementBloc-sk_SK">
            <div class="homeEngagementBloc1Txt"><table class="homeEngagementBlocTxtTable"><tr><td>Najlepšie pneumatiky za najlepšie ceny</td></tr></table></div>
        </div>
        <div class ="homeEngagementBloc1Bullet homeEngagementBloc1Bullet-sk_SK" id="homeEngagementBloc1Bullet" >
            <div class="homeEngagementPoint">&#8226;&nbsp;1 000 000 pneumatík skladom</div>
            <div class="homeEngagementPoint">&#8226;&nbsp;Všetky značky za internetové ceny</div>
            <div class="homeEngagementPoint">&#8226;&nbsp;Doručenie domov alebo do montážneho strediska</div>
            <div class="homeEngagementPoint">&#8226;&nbsp;Zákaznícky servis Vám poradí.</div>
            <div class="homeEngagementPoint">&#8226;&nbsp;POPGOM-Záruka najnižšej ceny</div>
         </div>
    </div>
    <div class="homeEngagementBlocSpace">&nbsp;</div>
    <div class="homeEngagementBloc" id="homeEngagementBloc2">
        <div id="homeEngagementBloc2Txt" class="homeEngagementBloc2  homeEngagementBloc-sk_SK">
            <div class="homeEngagementBloc2Txt"><table class="homeEngagementBlocTxtTable"><tr><td>Dodanie rýchlo a jednoducho</td></tr></table></div>
        </div>
        <div class ="homeEngagementBloc2Bullet homeEngagementBloc2Bullet-sk_SK" id="homeEngagementBloc2Bullet">
            <div class="homeEngagementPoint">&#8226;&nbsp;Rýchle dodanie pneumatík</div>
            <div class="homeEngagementPoint">&#8226;&nbsp;Za jednotnú cenu po celej SR</div>
            <div class="homeEngagementPoint">&#8226;&nbsp;S kuriérskou službou</div>
            <div class="homeEngagementPoint">&#8226;&nbsp;Domov alebo na Vami zadanú adresu</div>
            <div class="homeEngagementPoint">&#8226;&nbsp;Už od 24h podľa dostupnosti tovaru</div>
        </div>
    </div>
    <div class="homeEngagementBlocSpace">&nbsp;</div>
    <div class="homeEngagementBloc" id="homeEngagementBloc3">
        <div id="homeEngagementBloc3Txt" class="homeEngagementBloc3  homeEngagementBloc-sk_SK">
            <div class="homeEngagementBloc3Txt"><table class="homeEngagementBlocTxtTable"><tr><td>Bezpečne na všetkých štyroch kolesách</td></tr></table></div>
        </div>
        <div class ="homeEngagementBloc3Bullet homeEngagementBloc3Bullet-sk_SK" id="homeEngagementBloc3Bullet">
            <div class="homeEngagementPoint">&#8226;&nbsp;Nové pneumatiky - garantované výrobcom</div>
            <div class="homeEngagementPoint">&#8226;&nbsp;Rýchle a bezpečné dodanie na vybranú adresu</div>
            <div class="homeEngagementPoint">&#8226;&nbsp;Bezpečná online platba</div>
            <div class="homeEngagementPoint">&#8226;&nbsp;Sledovanie balíkov, až po dodanie</div>
            <div class="homeEngagementPoint">&#8226;&nbsp;Spoľahlivé testy a prehľadné informácie o pneumatikách.</div>
         </div>
    </div>

    <div class="clearboth"></div>
    
<script type="text/javascript">

function showBullet(blocName){
                    $("#" + blocName + "Txt").stop().animate({top:'-182px'},{queue:false,duration:1000});
                    $("#" + blocName + "Bullet").stop().filter(':not(:animated)').animate({top:'0px'},{queue:false,duration:1000});
            };
function showTxt(blocName){
                    $("#" + blocName + "Txt").stop().animate({top:'0px'},{queue:false,duration:350});
                    $("#" + blocName + "Bullet").stop().animate({top:'-182px'},{queue:false,duration:350});
            };
    $(document).ready(function() {
	// find the div.fade elements and hook the hover event
	$("#homeEngagementBloc1").hover(function(){showBullet('homeEngagementBloc1')}, function(){showTxt('homeEngagementBloc1')});
        $("#homeEngagementBloc2").hover(function(){showBullet('homeEngagementBloc2')}, function(){showTxt('homeEngagementBloc2')});
        $("#homeEngagementBloc3").hover(function(){showBullet('homeEngagementBloc3')}, function(){showTxt('homeEngagementBloc3')});
    });

</script>



</div>


<div>
    <div id="contenuHomeContentLine1">
        <div class="encartsBlocsContenuHome" id="blocHomeDelivery" onclick="openNavigatorCenteredWindow('/pneumatiky-POPGOM/dodavka-domov','popgom','890','500', 'menubar=no,  status=no, scrollbars=yes, location=no');return false;">
            <div class="headerProfilesPopularities">
                <h2 class="h2Home">Doprava za 2€/ks</h2>
            </div>
            <div class="clearboth"></div>
            <div>
                <div class="freeHomeDelivery freeHomeDelivery-sk_SK">

                </div>
                <div style="float: left; width: 115px; margin-left: 10px;height: 66px;margin-top: 10px;">
                    <table style="height: 66px;border-collapse : collapse;">
                        <tr>
                            <td>
                                <a href="/pneumatiky-POPGOM/dodavka-domov" onclick="openNavigatorCenteredWindow('/pneumatiky-POPGOM/dodavka-domov','popgom','890','500', 'menubar=no,  status=no, scrollbars=yes, location=no');return false;">
                                    Doprava za 2€/ks s kuriérskou službou
                                </a>
                            </td>
                        </tr>
                    </table>
                </div>
                <div class="freeDeliveryPlusInfo-sk_SK">

                </div>
            </div>
        </div>
        <div class="encartsBlocsContenuHome" id="tyreHighlightContent">
            









    <div id="profilesPopularities">
        <div class="headerProfilesPopularities">
            <h2 class="h2Home">
                Naše najpredávanejšie produkty
            </h2>
        </div>
        <div class="profilesPopularitiesContent">
            
                
                    
                    
                        
                    
                
                
                
                
                
                <div class="profilePopularity " onclick="popgom.resultList.googleEvents.productClickAction('138578','Hankook Ventus Prime 3 K125', '1' , 'Search pushed');window.location = '/najlacnejsie-pneu/hankook/ventus-prime-3/205-55-r16-91-v';">
                    <div class="profilePopularityDescription">
                        <p class="profilePopularityImg">
                            <a class="profilePopularityDimension" href="/najlacnejsie-pneu/hankook/ventus-prime-3/205-55-r16-91-v">
                                <img src="https://md.proty.re/u/8121034/popgom/profiles/25127_FullViewStudio/f1f1f1_home_manuf.jpg" alt="Hankook Ventus Prime 3 K125 205/55 R16 91V" width="80" height="58" width="80" />
                            </a>
                        </p>
                        <p>
                            205/55 R16 91V
                        </p>
                        <h3 class="h2Home profilePopularityName">
                            Ventus Prime 3 K125
                        </h3>
                    </div>
                    <div class="profilePopularityPrice">
                        <p>
                            <div class="profilePopularityMinPrice">
                                <span class="profilePopularityMinPriceValue">50,00 €</span>
                            </div>
                        </p>
                    </div>
                </div>
            
                
                    
                    
                        
                    
                
                
                
                
                
                <div class="profilePopularity profilePopularityMargin" onclick="popgom.resultList.googleEvents.productClickAction('39774','Dunlop Sport BluResponse', '2' , 'Search pushed');window.location = '/najlacnejsie-pneu/dunlop/sp-sport-blue-response/205-55-r16-91-v';">
                    <div class="profilePopularityDescription">
                        <p class="profilePopularityImg">
                            <a class="profilePopularityDimension" href="/najlacnejsie-pneu/dunlop/sp-sport-blue-response/205-55-r16-91-v">
                                <img src="https://md.proty.re/u/8121034/popgom/profiles/08529/f1f1f1_home_manuf.jpg" alt="Dunlop Sport BluResponse 205/55 R16 91V" width="80" height="58" width="80" />
                            </a>
                        </p>
                        <p>
                            205/55 R16 91V
                        </p>
                        <h3 class="h2Home profilePopularityName">
                            Sport BluResponse
                        </h3>
                    </div>
                    <div class="profilePopularityPrice">
                        <p>
                            <div class="profilePopularityMinPrice">
                                <span class="profilePopularityMinPriceValue">62,50 €</span>
                            </div>
                        </p>
                    </div>
                </div>
            
                
                    
                    
                        
                    
                
                
                
                
                
                <div class="profilePopularity profilePopularityMargin" onclick="popgom.resultList.googleEvents.productClickAction('148942','Sebring Formula Sporty+', '3' , 'Search pushed');window.location = '/najlacnejsie-pneu/sebring/formula-sporty-plus/225-45-r17-91-y';">
                    <div class="profilePopularityDescription">
                        <p class="profilePopularityImg">
                            <a class="profilePopularityDimension" href="/najlacnejsie-pneu/sebring/formula-sporty-plus/225-45-r17-91-y">
                                <img src="https://md.proty.re/u/8121034/popgom/profiles/SebFoSpo/f1f1f1_home_manuf.jpg" alt="Sebring Formula Sporty+ 225/45 R17 91Y" width="80" height="58" width="80" />
                            </a>
                        </p>
                        <p>
                            225/45 R17 91Y
                        </p>
                        <h3 class="h2Home profilePopularityName">
                            Formula Sporty+
                        </h3>
                    </div>
                    <div class="profilePopularityPrice">
                        <p>
                            <div class="profilePopularityMinPrice">
                                <span class="profilePopularityMinPriceValue">38,20 €</span>
                            </div>
                        </p>
                    </div>
                </div>
            
                
                    
                    
                        
                    
                
                
                
                
                
                <div class="profilePopularity profilePopularityMargin" onclick="popgom.resultList.googleEvents.productClickAction('37938','Michelin Energy Saver +', '4' , 'Search pushed');window.location = '/najlacnejsie-pneu/michelin/energy-saver-plus/195-65-r15-91-h';">
                    <div class="profilePopularityDescription">
                        <p class="profilePopularityImg">
                            <a class="profilePopularityDimension" href="/najlacnejsie-pneu/michelin/energy-saver-plus/195-65-r15-91-h">
                                <img src="https://md.proty.re/u/8121034/popgom/profiles/05982/f1f1f1_home_manuf.jpg" alt="Michelin Energy Saver + 195/65 R15 91H" width="80" height="58" width="80" />
                            </a>
                        </p>
                        <p>
                            195/65 R15 91H
                        </p>
                        <h3 class="h2Home profilePopularityName">
                            Energy Saver +
                        </h3>
                    </div>
                    <div class="profilePopularityPrice">
                        <p>
                            <div class="profilePopularityMinPrice">
                                <span class="profilePopularityMinPriceValue">57,60 €</span>
                            </div>
                        </p>
                    </div>
                </div>
            
                
                    
                    
                        
                    
                
                
                
                
                
                <div class="profilePopularity profilePopularityMargin" onclick="popgom.resultList.googleEvents.productClickAction('35086','Continental PremiumContact 5 ', '5' , 'Search pushed');window.location = '/najlacnejsie-pneu/continental/premiumcontact5/205-55-r16-91-v';">
                    <div class="profilePopularityDescription">
                        <p class="profilePopularityImg">
                            <a class="profilePopularityDimension" href="/najlacnejsie-pneu/continental/premiumcontact5/205-55-r16-91-v">
                                <img src="https://md.proty.re/u/8121034/popgom/profiles/05503/f1f1f1_home_manuf.jpg" alt="Continental PremiumContact 5  205/55 R16 91V" width="80" height="58" width="80" />
                            </a>
                        </p>
                        <p>
                            205/55 R16 91V
                        </p>
                        <h3 class="h2Home profilePopularityName">
                            PremiumContact 5 
                        </h3>
                    </div>
                    <div class="profilePopularityPrice">
                        <p>
                            <div class="profilePopularityMinPrice">
                                <span class="profilePopularityMinPriceValue">65,70 €</span>
                            </div>
                        </p>
                    </div>
                </div>
            
                
                    
                    
                        
                    
                
                
                
                
                
                <div class="profilePopularity profilePopularityMargin" onclick="popgom.resultList.googleEvents.productClickAction('9429','Prva cena Yellow Sea YS618', '6' , 'Search pushed');window.location = '/najlacnejsie-pneu/first-price/yellow-sea-ys618/235-45-zr17-97-w';">
                    <div class="profilePopularityDescription">
                        <p class="profilePopularityImg">
                            <a class="profilePopularityDimension" href="/najlacnejsie-pneu/first-price/yellow-sea-ys618/235-45-zr17-97-w">
                                <img src="https://md.proty.re/u/8121034/popgom/profiles/Yellow Sea YS618/f1f1f1_home_manuf.jpg" alt="Prva cena Yellow Sea YS618 235/45 ZR17 97W" width="80" height="58" width="80" />
                            </a>
                        </p>
                        <p>
                            235/45 ZR17 97W
                        </p>
                        <h3 class="h2Home profilePopularityName">
                            Yellow Sea YS618
                        </h3>
                    </div>
                    <div class="profilePopularityPrice">
                        <p>
                            <div class="profilePopularityMinPrice">
                                <span class="profilePopularityMinPriceValue">39,10 €</span>
                            </div>
                        </p>
                    </div>
                </div>
            
        </div>
    </div>

        </div>
    </div>
    <div class="clearboth"></div>
    <div class="topBorder">
        <div class="blocInsuranceFacebook">
            <div class="blocSocialNetwork encartsBlocsContenuHome">
                <div id="satisfaction-garantie-img"></div>
                <div id="satisfaction-garantie-txt">
                    Spokojnosť zaručená
                </div>
            </div>
            <div class="blocSocialNetwork encartsBlocsContenuHome topMargin">
                <div style="margin: 0 0 0 33px;">
                    <a href="https://www.youtube.com/user/POPGOM" target="_blank" class="youtubePicture"></a>
                </div>
                <div id="uTubeHomeTxt">
                    Nájdete nás na Youtube
                </div>
            </div>
        </div>
        <div class="encartsBlocsContenuHome blocPromesseContenuHome leftMargin">
            <div style="padding-left: 10px; padding-top: 5px;">
                <h2 class="h2Home">Novinky</h2>
            </div>
            <div style="margin-top: 10px; padding-left: 20px; padding-right: 20px;height: 44px;overflow: hidden;text-align: justify;">
                
                    
                    
                        
                            
                            
                        
                        
                    
                    "Najdôležitejším faktorom pre zachovanie čerstvosti pneumatík je zabránenie priameho slnečného žiaren..."
                
            </div>
            <p style="margin-top: 10px; text-align: right; padding-right: 10px;">
                <a href="/pneumatiky-online/novinky" style="text-decoration:underline;"  title="">
                    > Všetky novinky
                </a>
            </p>
        </div>
        <div class="encartsBlocsContenuHome blocPromesseContenuHome leftMargin">
            <div>
                <div style="padding-left: 10px; padding-top: 5px;float: left;">
                    <h2 class="h2Home">Recenzie zákazníkov</h2>
                </div>
                
                    
                    
                        <div id="customerOpinionBloc" style="float: right; margin-right: 5px; margin-top: 5px;">
                            










    
        
            <div class="starFill sprite"></div>
        
            <div class="starFill sprite"></div>
        
            <div class="starFill sprite"></div>
        
            <div class="starFill sprite"></div>
        
            <div class="starFill sprite"></div>
        
        
    
    


                        </div>
                    
                
            </div>
            <div class="clearboth"></div>
            <div style="margin-top: 10px; padding-left: 20px; padding-right: 20px;height: 44px;overflow: hidden;">
                
                    
                    <div style="height: 15px;overflow: hidden;">
                        Sedmák B. (Žilina- 01 )
                    </div>
                    <div style="margin-top: 10px;height: 15px;overflow: hidden;">
                        
                        
                        
                        "Nič. Ste TOP dodávateľ."
                    </div>
                
            </div>
            <p style="margin-top: 10px; text-align: right; padding-right: 10px;">
                <a href="/popgom-recenzie" title="" style="text-decoration:underline;">
                    > Ďalšie recenzie
                </a>
            </p>
        </div>
        <div class="encartsBlocsContenuHome blocPromesseContenuHome leftMargin" style="width: 244px;">
            










<a href="https://www.pneumatiky-popgom.sk/pneumatiky-online/uhradarozdielu#promo" style="text-decoration: none;">
    <div style="padding-left: 10px; padding-top: 5px;">
        <h2 class="h2Home">Záruka najlepšej ceny</h2>
    </div>
    <div id="scroller-popgom-est-recommande-par">
	     <a>
	        <div id="trustPilotLogo">
	        	<img src="https://md.proty.re/v/v_2018_03_16_1438/8121034/img/v201201/trust-pilot-sans-avis.png" title="trust pilot" alt="trust pilot" />
	        </div>
	    </a>
	</div>
</a>

        </div>
    </div>
</div></div>
            </div>
            
                
            






	
	


<div id="footer">
    <div id="footerTop">
        <div id="logosTest">
            






    <div id="menuLine">
        <div class="footerButtonDiv" style="width: 196px;">
            <div class="centeredElement">
                <div id="firstFooterItem" class="firstFooterItem-sk_SK sprite">
        
                </div>
            </div>
            <div>
                1 000 000 pneumatík
            </div>
        </div>
        <div class="footerButtonDiv" style="width: 196px;">
            <div class="centeredElement">
                <a id="thirdFooterItem" title="" class="thirdFooterItem-sk_SK sprite" onclick="openNavigatorCenteredWindow('https://www.pneumatiky-popgom.sk/pneumatiky-POPGOM/dodavka-domov','popgom','890','500', 'menubar=no, status=no, scrollbars=yes, location=no');return false;" href="https://www.pneumatiky-popgom.sk/pneumatiky-POPGOM/dodavka-domov" title="">
        
                </a>
            </div>
            <div>
                Doprava za 2€/ks
            </div>
        </div>
        <div class="footerButtonDiv" style="width: 196px;">
            <div class="centeredElement">
                <a id="fourthFooterItem" title="" class="fourthFooterItem-sk_SK sprite" target="_blank" href="https://www.pneumatiky-popgom.sk/pneumatiky-online/uhradarozdielu#promo">
        
                </a>
            </div>
            <div>
                Záruka najlepšej ceny POPGOM
            </div>
        </div>
        <div class="footerButtonDiv" style="width: 196px;">
            <div class="centeredElement">
                <a id="fifFooterItem" class="fifFooterItem-sk_SK sprite" target="_blank" href="https://www.pneumatiky-popgom.sk/sprievodca-pneumatik" title="" title="Sprievodca pneumatikami">
        
                </a>
            </div>
            <div>
                POPGOM – sprievodca svetom pneumatík
            </div>
        </div>
        <div class="footerButtonDiv" style="width: 196px;">
            <div class="centeredElement">
                <div id="qualityFooterItem"></div>
            </div>
            <div>
                Kvalita
            </div>
        </div>
    </div>


<div id="paymentLogo" style="padding: 20px 36px;">
    <a href="https://www.pneumatiky-popgom.sk/pneumatiky-POPGOM/bezpecna-platba" onclick="openNavigatorCenteredWindow('https://www.pneumatiky-popgom.sk/pneumatiky-POPGOM/bezpecna-platba','POPGOM','720','600', 'menubar=no,  status=no, scrollbars=yes, location=no');return false;">
        <div id="visa" style="margin: 0 65px 0 0;"></div>
        <div id="mastercard" style="margin: 0 65px 0 0;"></div>
        <div id="payPal" style="margin: 0 65px 0 0;"></div>
        <div id="transfertBancaire-sk_SK" style="margin: 0 65px 0 0;"></div>
        <div id="paymentArrows" style="margin: 0;"></div>
    </a>
</div>

<div id="sslPayment" style="margin: 18px 32px;" onclick="openNavigatorCenteredWindow('/pneumatiky-POPGOM/bezpecna-platba','POPGOM','720','600', 'menubar=no,  status=no, scrollbars=yes, location=no');return false;">
    <div id="sslPaymentLeftImg"></div>
    <div id="sslPaymentTxt">
        <div id="sslPaymentTxtBlue">
            Platba so 100 %-ným bezpečím
        </div>
        Kontrola proti podvodom<br/>
        Bezpečný protokol SSL
    </div>
    <div id="sslPaymentRightImg"></div>
</div>

<div class="clearboth"></div>

        </div>
    </div>
    <div class="clearboth"></div>
    
        <div class="footerBloc" id="footerComment">
            
            <div id="footerBaseLine">
            	
            		
            		
            			<a href="/najlacnejsie-pneu/">Nákup pneumatík</a> <a href="/celorocne-pneumatiky"><strong>celorocne pneumatik</strong></a> <a href="/pneumatiky-pre-kempingove-vozidla"><strong>pneumatiky pre kempingove vozidla</strong></a>  pre automobily: behom okamihu nájdete typ, ktorý Vám vyhovuje! Spoločnosť POPGOM Vám umožňuje kúpiť pneu zo širokej ponuky značiek a modelov. Porovnávajte ceny, hodnoťte výkonnosť, objavujte technické vlastnosti každého z našich produktov: tu sú podmienky pre realizáciu avizovaného nákupu pneu. POPGOM sa postará o každú z etáp Vášho nákupu osobných, off-road i ľahkých nákladných pneumatík, od výberu po platbe so samozrejmosťou dodania. Každý mesiac ponúkame akčné pneumatiky za skvelé ceny. Zaregistrujte sa teraz na www.pneumatiky-popgom.sk a objednajte pneumatiky. Porovnajte gumy a čítajte testy a <a href="https://www.pneumatiky-popgom.sk/sprievodca-pneumatik" title="návody">návody</a> na stránke. 
            		
            	
            </div>
        </div>
        <div class="clearboth"></div>
    
    <div class="clearboth"></div>
    <div class="footerBloc noprint" id="footerNav">
        
            
            
                












<div id="bottomnav">
    
    
    <ul class="bottomnavlinks columns-4">
        
            <li>
                <ul>
                    
                        <li>
                            
                                
                                    
                                
                                
                            
                            <a href="https://www.pneumatiky-popgom.sk/pneumatiky-POPGOM/vop" title="Všeobecné obchodné podmienky"
                                    
                                        onclick="openNavigatorCenteredWindow('https://www.pneumatiky-popgom.sk/pneumatiky-POPGOM/vop', '', '720', '600', 'menubar=no, status=no, scrollbars=yes, location=no');return false;"
                                    
                            >Všeobecné obchodné podmienky</a>
                        </li>
                    
                        <li>
                            
                                
                                    
                                
                                
                            
                            <a href="https://www.pneumatiky-popgom.sk/pneumatiky-online/cookies" title="Cookies"
                                    
                            >Cookies</a>
                        </li>
                    
                </ul>
            </li>
        
            <li>
                <ul>
                    
                        <li>
                            
                                
                                    
                                
                                
                            
                            <a href="https://www.pneumatiky-popgom.sk/pneumatiky-POPGOM/mapa-stranky" title="Mapa stránky"
                                    
                            >Mapa stránky</a>
                        </li>
                    
                        <li>
                            
                                
                                    
                                
                                
                            
                            <a href="https://www.pneumatiky-popgom.sk/popgom-recenzie" title="POPGOM recenzie"
                                    
                            >POPGOM recenzie</a>
                        </li>
                    
                        <li>
                            
                                
                                    
                                
                                
                            
                            <a href="https://www.pneumatiky-popgom.sk/pneumatiky-POPGOM/bezpecna-platba" title="Bezpečná platba"
                                    
                                        onclick="openNavigatorCenteredWindow('https://www.pneumatiky-popgom.sk/pneumatiky-POPGOM/bezpecna-platba', '', '720', '600', 'menubar=no, status=no, scrollbars=yes, location=no');return false;"
                                    
                            >Bezpečná platba</a>
                        </li>
                    
                </ul>
            </li>
        
            <li>
                <ul>
                    
                        <li>
                            
                                
                                
                                    
                                
                            
                            <a href="/lacne-pneumatiky/adac-letnych-pneumatiky" title=""
                                    
                            >ADAC Test Pneumatiky</a>
                        </li>
                    
                        <li>
                            
                                
                                
                                    
                                
                            
                            <a href="/lacne-pneumatiky/Pneumatiky-letne" title="Lacné letné pneumatiky"
                                    
                            >Bestseller Letné Pneumatiky</a>
                        </li>
                    
                </ul>
            </li>
        
            <li>
                <ul>
                    
                        <li>
                            
                                
                                    
                                
                                
                            
                            <a href="https://www.pneumatiky-popgom.sk/pneumatiky-POPGOM/kto-sme" title="Kto sme?"
                                    
                                        onclick="openNavigatorCenteredWindow('https://www.pneumatiky-popgom.sk/pneumatiky-POPGOM/kto-sme', '', '720', '600', 'menubar=no, status=no, scrollbars=yes, location=no');return false;"
                                    
                            >Kto sme?</a>
                        </li>
                    
                        <li>
                            
                                
                                    
                                
                                
                            
                            <a href="https://www.pneumatiky-popgom.sk/contactCenter" title="Kontaktujte nás!"
                                    
                            >Kontaktujte nás!</a>
                        </li>
                    
                </ul>
            </li>
        
    </ul>
    <hr style="clear:both;width:100%;visibility:hidden"/>
    
</div>
 

            
        
    </div>
   
        <div class="footerBloc">
            <table id="table-drapeaux-footer" cellpadding="0px" cellspacing="0px;">
                <tr>
                    <td class="table-drapeaux-footerTD">
                    	<div id="clipLinkFR" class="clipLink"></div>
                        <a href="https://www.popgom.fr/" title="">
                        	POPGOM.fr
                        </a>
                    </td>
                    <td class="table-drapeaux-footerTD">
                    	<div id="clipLinkES" class="clipLink"></div>
                        <a href="https://www.popgom.es/" title="">
                       		 POPGOM.es
                        </a>
                    </td>
                    <td class="table-drapeaux-footerTD">
                    	<div id="clipLinkDE" class="clipLink"></div>
                        <a href="https://www.reifen-popgom.de/" title="">
                        	POPGOM.de
                        </a>
                    </td>
                    <td class="table-drapeaux-footerTD">
                    	<div id="clipLinkAT" class="clipLink"></div>
                        <a href="https://www.reifen-popgom.at/" title="">
                        	POPGOM.at
                        </a>
                    </td>
                    <td class="table-drapeaux-footerTD">
                    	<div id="clipLinkCH" class="clipLink"></div>
                    	<a href="https://www.pneus-popgom.ch/" title="">
                        	POPGOM.ch&nbsp;(FR)
                        </a>
                        <a href="https://www.reifen-popgom.ch/" title="">
                        	POPGOM.ch&nbsp;(DE)
                        </a>
                    </td>
                    <td class="table-drapeaux-footerTD">
                    	<div id="clipLinkNL" class="clipLink"></div>
                        <a href="https://www.banden-popgom.nl/" title="">
                        	POPGOM.nl
                        </a>
                    </td>
                    <td class="table-drapeaux-footerTD">
                    	<div id="clipLinkBE" class="clipLink"></div>
                    	 <a href="https://www.pneus-popgom.be/" title="">
                    	 	POPGOM.be&nbsp;(FR)
                        </a>
                        <a href="https://www.banden-popgom.be/" title="">
                    	 	POPGOM.be&nbsp;(NL)
                        </a>
                    </td>
                    <td class="table-drapeaux-footerTD">
                    	<div id="clipLinkSK" class="clipLink"></div>
                       <a href="https://www.pneumatiky-popgom.sk/" title="">
                        	POPGOM.sk
                        </a>
                    </td>
                    <td class="table-drapeaux-footerTD">
                    	<div id="clipLinkCZ" class="clipLink"></div>
                        <a href="https://www.pneu-popgom.cz/" title="">
                        	POPGOM.cz
                        </a>
                    </td>
                    <td class="table-drapeaux-footerTD">
                    	<div id="clipLinkHU" class="clipLink"></div>
                        <a href="https://www.gumi-popgom.hu/" title="">
                        	POPGOM.hu
                        </a>
                    </td>
                    <td class="table-drapeaux-footerTD">
                    	<div id="clipLinkSI" class="clipLink"></div>
                        <a href="https://www.gume-popgom.si/" title="">
                        	POPGOM.si
                        </a>
                    </td>
                    <td class="table-drapeaux-footerTD">
                    	<div id="clipLinkSE" class="clipLink"></div>
                        <a href="https://www.dack-popgom.se/"title="">
                        	POPGOM.se
                        </a>
                    </td>
                    <td class="table-drapeaux-footerTD">
                    	<div id="clipLinkDK" class="clipLink"></div>
                        <a href="https://www.daekshop-popgom.dk/" title="">
                        	POPGOM.dk
                        </a>
                    </td>
                    <td class="table-drapeaux-footerTD">
                    	<div id="clipLinkRO" class="clipLink"></div>
                        <a href="https://www.anvelope-popgom.ro/" title="">
                        	POPGOM.ro
                        </a>
                    </td>
                </tr>
            </table>
        </div>
    
</div>


	<div id="layerCookiesPopgom" class="noprint">
		<div class="innerDiv">
		    <div class="crossContainer left">
			    <div class="cross"></div>
		    </div>
		    <div class="consent">Pre pokračovanie vo vyhľadávaní stránok musíte súhlasíť s používaním súborov cookies.</div>
		    <div class="crossContainer right">
			    <div class="cross"></div>
		    </div>
		</div>
	</div>
	<script type="text/javascript">
		var cookieCookie = $.cookie("hasClosedCookie");

		if(!cookieCookie)
		{
			$("#layerCookiesPopgom").prependTo( "body" ).show();
			$("#layerCookiesPopgom .cross").click(function()
			{
				$("#layerCookiesPopgom").hide();
				$.cookie("hasClosedCookie", true, { expires: 1, path: '/' });
			});
		}
	</script>





            <div class="clearboth"></div>
            <div id="footer-externe">
                <p>
                    
                </p>
                <br/>
            </div>
        </div>
        
       
        
    		
            
            
                <script type="text/javascript">
                    $(document).ready(function (){displayBackgroundOnBody("https://md.proty.re/v/v_2018_03_16_1438/8121034/img/home/background.jpg","#FFFFFF","no-repeat center top");});
                </script>
            
        
        
        







	
    </body>
</html>