<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1251">
<title>Поштові індекси України</title>
<meta name="description" content="Поштові індекси України – це унікальна довідкова система. Ви можете швидко знайти поштовий індекс чи поштове відділення будь якого населеного пункту України, міста, вулиці">
<meta name="keywords" content="Поштові індекси, коди, Поштовий індекс, код, Міст, Міста, Населених пунктів, Сіл, Села, Вулиць, Вул., Проспект, Провулок, Поштове відділення зв'язку, найбільша база, Старий поштовий індекс">
<meta name="google-site-verification" content="Hb_R1uzIgT0w6mpQkR-OJkbDvpTiRIWDwczm6aBM6YM">
<link rel="shortcut icon" href="http://postcode.in.ua/favicon.ico">
<link href="http://postcode.in.ua/css-30tye/global.css" rel="stylesheet" type="text/css">
<link href="http://postcode.in.ua/css-30tye/main.css" rel="stylesheet" type="text/css">
<script type="text/javascript" src="http://postcode.in.ua/js/global.js.php"></script>
<meta name="viewport" content="width=923">
<meta name="MobileOptimized" content="923">
<!--[if !lte IE 6]> <style type="text/css">
body {overflow-y:scroll;}
.list_st_obl_rn {width:auto;}
#full_fon {position:fixed;}
#ed_box {position:fixed;}
</style> <![endif]-->
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-29766116-1']);
  _gaq.push(['_trackPageview']);
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s); })();
</script>
</head>
<body>
<table border="0" cellpadding="0" cellspacing="0" style="height:100%; width:100%;">
  <tr>
    <td style="height:94px;" align="center">
      <table border="0" cellpadding="0" cellspacing="0" style="height:94px; width:923px;">
        <tr>
		  <td style="height:94px; width:300px; padding-left:10px;" align="left" valign="middle"><a href="http://postcode.in.ua/ua"><img src="http://postcode.in.ua/images/logo_ua.gif" height="50" width="284" border="0" alt="Поштові індекси України"></a>
          </td>
          <td align="right" valign="middle" style="height:94px; width:623px; background: url(http://postcode.in.ua/images/clouds.gif) right top no-repeat;">
          </td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td style="height:1px; background:#bcd3f0;"></td>
  </tr>
  <tr>
    <td style="height:1px; background:#fff;"></td>
  </tr>
  <tr>
    <td align="center" valign="top">
      <table border="0" cellpadding="0" cellspacing="0" style="width:923px;">
        <tr>
          <td style="width:10px;"> </td>
          <td colspan="3" style="height:18px;" align="right" valign="bottom">
<span class="box_lang"><font class="lang_neutral">Укр</font></span><span class="box_lang"><a href="http://postcode.in.ua/ru" class="lang_link" onmouseover="tooltip.show('<b>Русский</b><br><img src=http://postcode.in.ua/images/flag_ru.png border=0>')">Рус</a></span>          </td>
          <td style="width:10px;"> </td>
        </tr>
        <tr>
          <td style="width:10px;"> </td>
          <td style="width:728px;" valign="top" align="left">
<div style="padding:0 0 20px 0;"><table border="0" cellpadding="0" cellspacing="0"><tr><td style="padding:0 4px 0 0;"><a href="http://postcode.in.ua/ua" class="text_head_link_1">Україна</a></td><td style="width:30px;" align="center"><img src="http://postcode.in.ua/images/marker3.png" border="0" width="14" height="13" alt=""></td><td><img src="http://postcode.in.ua/images/button_7.gif" border="0" width="16" height="13" alt="" onmouseover="tooltip.show('<b>Обрати область</b>')"></td><td style="width:13px;"><div class="button_6" onmouseover="tooltip.show('<b>Обрати область</b>')" onClick="list_show('list_2')" onMouseOut="list_hide('list_2')" style="cursor:pointer;"></div></td></tr><tr><td> </td>    <td> </td>

    <td> </td>
    <td>
<div class="list_st_obl_rn" style="display:none;" id="list_2" onMouseOver="list_hide_stop('list_2')" onMouseOut="list_hide('list_2')"><div><img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/codes/region/1">АР Крим</a></div>
<div><img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/codes/region/2">Вінницька обл.</a></div>
<div><img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/codes/region/3">Волинська обл.</a></div>
<div><img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/codes/region/4">Дніпропетровська обл.</a></div>
<div><img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/codes/region/5">Донецька обл.</a></div>
<div><img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/codes/region/6">Житомирська обл.</a></div>
<div><img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/codes/region/7">Закарпатська обл.</a></div>
<div><img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/codes/region/8">Запорізька обл.</a></div>
<div><img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/codes/region/9">Івано-Франківська обл.</a></div>
<div><img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/codes/region/10">Київська обл.</a></div>
<div><img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/codes/region/11">Кіровоградська обл.</a></div>
<div><img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/codes/region/12">Луганська обл.</a></div>
<div><img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/codes/region/13">Львівська обл.</a></div>
<div><img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/codes/region/14">Миколаївська обл.</a></div>
<div><img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/codes/region/15">Одеська обл.</a></div>
<div><img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/codes/region/16">Полтавська обл.</a></div>
<div><img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/codes/region/17">Рівненська обл.</a></div>
<div><img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/codes/region/18">Сумська обл.</a></div>
<div><img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/codes/region/19">Тернопільська обл.</a></div>
<div><img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/codes/region/20">Харківська обл.</a></div>
<div><img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/codes/region/21">Херсонська обл.</a></div>
<div><img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/codes/region/22">Хмельницька обл.</a></div>
<div><img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/codes/region/23">Черкаська обл.</a></div>
<div><img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/codes/region/24">Чернівецька обл.</a></div>
<div><img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/codes/region/25">Чернігівська обл.</a></div>
</div>    </td>
    <td> </td>

    <td> </td>
    <td>
    </td>
  </tr>
</table>
</div>
<div style="padding: 0 0 20px 0;" align="left">
<form action="http://postcode.in.ua/ua" name="form_1" method="GET" autocomplete="off">
<table border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td rowspan="2" style="width:29px;"><img src="http://postcode.in.ua/images/search.png" border="0" alt=""></td>
    <td rowspan="2" style="width:9px;"></td>
    <td align="left" style="width:690px;"><div class="text_5">Введіть кілька літер з назви населенного пункту або поштовий індекс</div></td>
  </tr>
  <tr>
    <td style="width:690px;"><input type ="hidden" name="_type" id="_type" value="all"><input type ="hidden" name="_lang" id="_lang" value="ua">      <table border="0"  cellpadding="0" cellspacing="0">
        <tr>
          <td rowspan="3" style="width:2px; height:24px; background:#f99350;"><img src="http://postcode.in.ua/images/button_1_.png" border="0" width="2" height="24" alt=""></td>
          <td colspan="4" style="height:1px; background:#f99350;"> </td>
          <td rowspan="3" style="width:2px; height:24px; background:#f99350;"><img src="http://postcode.in.ua/images/button_2_.png" border="0" width="2" height="24" alt=""></td>
        </tr>
        <tr>
          <td style="width:598px; height:22px;">
            <div style="height:18px;"><input type ="text" id="search" name="search" value="" maxlength="30" class="input_1" onkeyup="send_request()"></div>
          </td>
          <td style="width:22px; height:22px;" align="center" valign="middle"><div style="display:none;" id="wait_search"><img src="http://postcode.in.ua/images/wait.gif" width="16" height="16" border="0" alt=""></div></td>          
          <td style="width:1px; height:22px; background:#f99350;"> </td>
          <td style="width:65px; height:22px; background:#fff url(http://postcode.in.ua/images/button_3.png) bottom repeat-x;"><a href="javascript:send_request_button();" class="button_text_1" title="">Пошук</a></td>
        </tr>
        <tr>
          <td colspan="4" style="height:1px; background:#f99350;"> </td>
       </tr>
      </table>
    </td>
  </tr>
</table>
</form>
<div class="text_5" align="left" style="padding:2px 0 0 55px;"><img src="http://postcode.in.ua/images/ico_info_mini.png" border="0" width="9" height="9" alt="">&nbsp;Для пошуку індексів по вулицям міст, спочатку оберіть місто</div></div><div id="content_page"><div class="city_box">
<span class="city_text_4"><a href="http://postcode.in.ua/ua/codes/city/1001" class="city_text_link">Вінниця</a></span>
<span class="city_text_2"><a href="http://postcode.in.ua/ua/codes/city/1002" class="city_text_link">Дніпропетровськ</a></span>
<span class="city_text_3"><a href="http://postcode.in.ua/ua/codes/city/1003" class="city_text_link">Донецьк</a></span>
<span class="city_text_5"><a href="http://postcode.in.ua/ua/codes/city/1004" class="city_text_link">Житомир</a></span>
<span class="city_text_3"><a href="http://postcode.in.ua/ua/codes/city/1005" class="city_text_link">Запоріжжя</a></span>
<span class="city_text_6"><a href="http://postcode.in.ua/ua/codes/city/1006" class="city_text_link">Івано-Франківськ</a></span>
<span class="city_text_1"><a href="http://postcode.in.ua/ua/codes/city/1007" class="city_text_link">Київ</a></span>
<span class="city_text_5"><a href="http://postcode.in.ua/ua/codes/city/1008" class="city_text_link">Кіровоград</a></span>
<span class="city_text_4"><a href="http://postcode.in.ua/ua/codes/city/1009" class="city_text_link">Луганськ</a></span>
<span class="city_text_6"><a href="http://postcode.in.ua/ua/codes/city/1010" class="city_text_link">Луцьк</a></span>
<span class="city_text_3"><a href="http://postcode.in.ua/ua/codes/city/1011" class="city_text_link">Львів</a></span>
<span class="city_text_4"><a href="http://postcode.in.ua/ua/codes/city/1012" class="city_text_link">Миколаїв</a></span>
<span class="city_text_2"><a href="http://postcode.in.ua/ua/codes/city/1013" class="city_text_link">Одеса</a></span>
<span class="city_text_4"><a href="http://postcode.in.ua/ua/codes/city/1014" class="city_text_link">Полтава</a></span>
<span class="city_text_5"><a href="http://postcode.in.ua/ua/codes/city/1015" class="city_text_link">Рівне</a></span>
<span class="city_text_4"><a href="http://postcode.in.ua/ua/codes/city/1016" class="city_text_link">Севастополь</a></span>
<span class="city_text_4"><a href="http://postcode.in.ua/ua/codes/city/1017" class="city_text_link">Сімферополь</a></span>
<span class="city_text_5"><a href="http://postcode.in.ua/ua/codes/city/1018" class="city_text_link">Суми</a></span>
<span class="city_text_6"><a href="http://postcode.in.ua/ua/codes/city/1019" class="city_text_link">Тернопіль</a></span>
<span class="city_text_6"><a href="http://postcode.in.ua/ua/codes/city/1020" class="city_text_link">Ужгород</a></span>
<span class="city_text_2"><a href="http://postcode.in.ua/ua/codes/city/1021" class="city_text_link">Харків</a></span>
<span class="city_text_4"><a href="http://postcode.in.ua/ua/codes/city/1022" class="city_text_link">Херсон</a></span>
<span class="city_text_3"><a href="http://postcode.in.ua/ua/codes/city/1023" class="city_text_link">Хмельницький</a></span>
<span class="city_text_5"><a href="http://postcode.in.ua/ua/codes/city/1024" class="city_text_link">Черкаси</a></span>
<span class="city_text_5"><a href="http://postcode.in.ua/ua/codes/city/1025" class="city_text_link">Чернівці</a></span>
<span class="city_text_5"><a href="http://postcode.in.ua/ua/codes/city/1026" class="city_text_link">Чернігів</a></span>
</div>
<div align="center" style="padding:20px 0 20px 0;"><img src="http://postcode.in.ua/images/map_ua_ua.gif" border="0" usemap="#ukr" alt=""><map name="ukr"><area shape="poly" coords="372,268,413,286,431,302,449,297,467,304,454,319,432,316,411,327,386,345,364,337,366,315,343,307,333,302,368,278
" href="http://postcode.in.ua/ua/codes/region/1" onmouseover="tooltip.show('<b>АР Крим</b><br>Обл.&nbsp;центр:&nbsp;<b>Сімферополь</b>')"  alt="">
<area shape="poly" coords="219,115,226,128,242,119,246,144,257,171,248,186,212,191,180,176,174,167,176,147,190,143,187,120
" href="http://postcode.in.ua/ua/codes/region/2" onmouseover="tooltip.show('<b>Вінницька</b>&nbsp;обл.<br>Обл.&nbsp;центр:&nbsp;<b>Вінниця</b>')"  alt="">
<area shape="poly" coords="117,29,118,50,131,60,129,79,102,94,66,81,63,38
" href="http://postcode.in.ua/ua/codes/region/3" onmouseover="tooltip.show('<b>Волинська</b>&nbsp;обл.<br>Обл.&nbsp;центр:&nbsp;<b>Луцьк</b>')"  alt="">
<area shape="poly" coords="412,143,466,167,473,183,463,197,448,198,410,191,410,208,388,216,350,212,351,193,368,180,378,156,391,163,394,149
" href="http://postcode.in.ua/ua/codes/region/4" onmouseover="tooltip.show('<b>Дніпропетровська</b>&nbsp;обл.<br>Обл.&nbsp;центр:&nbsp;<b>Дніпропетровськ</b>')"  alt="">
<area shape="poly" coords="503,142,541,199,520,213,512,235,481,239,473,223,485,215,463,197,473,183,466,167,480,160
" href="http://postcode.in.ua/ua/codes/region/5" onmouseover="tooltip.show('<b>Донецька</b>&nbsp;обл.<br>Обл.&nbsp;центр:&nbsp;<b>Донецьк</b>')"  alt="">
<area shape="poly" coords="236,48,242,119,226,128,219,115,187,120,168,86,186,43
" href="http://postcode.in.ua/ua/codes/region/6" onmouseover="tooltip.show('<b>Житомирська</b>&nbsp;обл.<br>Обл.&nbsp;центр:&nbsp;<b>Житомир</b>')"  alt="">
<area shape="poly" coords="26,147,54,163,82,180,84,198,34,196,7,173
" href="http://postcode.in.ua/ua/codes/region/7" onmouseover="tooltip.show('<b>Закарпатська</b>&nbsp;обл.<br>Обл.&nbsp;центр:&nbsp;<b>Ужгород</b>')"  alt="">
<area shape="poly" coords="410,191,448,198,463,197,485,215,473,223,481,239,423,267,405,254,404,236,388,216,410,208
" href="http://postcode.in.ua/ua/codes/region/8" onmouseover="tooltip.show('<b>Запорізька</b>&nbsp;обл.<br>Обл.&nbsp;центр:&nbsp;<b>Запоріжжя</b>')"  alt="">
<area shape="poly" coords="90,129,120,165,117,178,106,181,98,205,84,198,82,180,54,163,63,147,80,143
" href="http://postcode.in.ua/ua/codes/region/9" onmouseover="tooltip.show('<b>Івано-Франківська</b>&nbsp;обл.<br>Обл.&nbsp;центр:&nbsp;<b>Івано-Франківськ</b>')"  alt="">
<area shape="poly" coords="263,44,273,54,290,78,321,92,321,104,308,115,297,108,287,133,246,144,242,119,236,48
" href="http://postcode.in.ua/ua/codes/region/10" onmouseover="tooltip.show('<b>Київська</b>&nbsp;обл.<br>Обл.&nbsp;центр:&nbsp;<b>Київ</b>')"  alt="">
<area shape="poly" coords="341,138,378,156,368,180,351,193,330,203,312,194,267,188,248,186,257,171,300,162,344,150
" href="http://postcode.in.ua/ua/codes/region/11" onmouseover="tooltip.show('<b>Кіровоградська</b>&nbsp;обл.<br>Обл.&nbsp;центр:&nbsp;<b>Кіровоград</b>')"  alt="">
<area shape="poly" coords="522,106,574,127,572,183,562,202,541,199,503,142,510,110
" href="http://postcode.in.ua/ua/codes/region/12" onmouseover="tooltip.show('<b>Луганська</b>&nbsp;обл.<br>Обл.&nbsp;центр:&nbsp;<b>Луганськ</b>')"  alt="">
<area shape="poly" coords="66,81,102,94,109,107,90,129,80,143,63,147,54,163,26,147,24,129
" href="http://postcode.in.ua/ua/codes/region/13" onmouseover="tooltip.show('<b>Львівська</b>&nbsp;обл.<br>Обл.&nbsp;центр:&nbsp;<b>Львів</b>')"  alt="">
<area shape="poly" coords="267,188,312,194,330,203,351,193,350,212,349,238,326,244,313,258,293,252,297,234,269,208
" href="http://postcode.in.ua/ua/codes/region/14" onmouseover="tooltip.show('<b>Миколаївська</b>&nbsp;обл.<br>Обл.&nbsp;центр:&nbsp;<b>Миколаїв</b>')"  alt="">
<area shape="poly" coords="248,186,267,188,269,208,297,234,293,252,249,295,249,310,239,303,214,311,201,295,226,254,244,257,253,245,228,213,212,191
" href="http://postcode.in.ua/ua/codes/region/15" onmouseover="tooltip.show('<b>Одеська</b>&nbsp;обл.<br>Обл.&nbsp;центр:&nbsp;<b>Одеса</b>')"  alt="">
<area shape="poly" coords="352,86,389,90,412,103,423,120,424,134,412,143,394,149,391,163,378,156,341,138,343,127,321,104,321,92,341,94
" href="http://postcode.in.ua/ua/codes/region/16" onmouseover="tooltip.show('<b>Полтавська</b>&nbsp;обл.<br>Обл.&nbsp;центр:&nbsp;<b>Полтава</b>')"  alt="">
<area shape="poly" coords="117,29,186,43,168,86,139,100,109,107,102,94,129,79,131,60,118,50
" href="http://postcode.in.ua/ua/codes/region/17" onmouseover="tooltip.show('<b>Рівненська</b>&nbsp;обл.<br>Обл.&nbsp;центр:&nbsp;<b>Рівне</b>')"  alt="">
<area shape="poly" coords="366,11,396,37,396,54,424,63,433,93,412,103,389,90,352,86
" href="http://postcode.in.ua/ua/codes/region/18" onmouseover="tooltip.show('<b>Сумська</b>&nbsp;обл.<br>Обл.&nbsp;центр:&nbsp;<b>Суми</b>')"  alt="">
<area shape="poly" coords="139,100,137,157,146,172,120,165,90,129,109,107
" href="http://postcode.in.ua/ua/codes/region/19" onmouseover="tooltip.show('<b>Тернопільська</b>&nbsp;обл.<br>Обл.&nbsp;центр:&nbsp;<b>Тернопіль</b>')"  alt="">
<area shape="poly" coords="448,89,459,97,491,91,510,110,503,142,480,160,466,167,412,143,424,134,423,120,412,103,433,93
" href="http://postcode.in.ua/ua/codes/region/20" onmouseover="tooltip.show('<b>Харківська</b>&nbsp;обл.<br>Обл.&nbsp;центр:&nbsp;<b>Харків</b>')"  alt="">
<area shape="poly" coords="350,212,388,216,404,236,405,254,423,267,411,276,413,286,372,268,368,278,316,268,313,258,326,244,349,238
" href="http://postcode.in.ua/ua/codes/region/21" onmouseover="tooltip.show('<b>Херсонська</b>&nbsp;обл.<br>Обл.&nbsp;центр:&nbsp;<b>Херсон</b>')"  alt="">
<area shape="poly" coords="168,86,187,120,190,143,176,147,174,167,146,172,137,157,139,100
" href="http://postcode.in.ua/ua/codes/region/22" onmouseover="tooltip.show('<b>Хмельницька</b>&nbsp;обл.<br>Обл.&nbsp;центр:&nbsp;<b>Хмельницький</b>')"  alt="">
<area shape="poly" coords="321,104,343,127,341,138,344,150,300,162,257,171,246,144,287,133,297,108,308,115
" href="http://postcode.in.ua/ua/codes/region/23" onmouseover="tooltip.show('<b>Черкаська</b>&nbsp;обл.<br>Обл.&nbsp;центр:&nbsp;<b>Черкаси</b>')"  alt="">
<area shape="poly" coords="120,165,146,172,174,167,180,176,142,196,98,205,106,181,117,178
" href="http://postcode.in.ua/ua/codes/region/24" onmouseover="tooltip.show('<b>Чернівецька</b>&nbsp;обл.<br>Обл.&nbsp;центр:&nbsp;<b>Чернівці</b>')"  alt="">
<area shape="poly" coords="366,11,352,86,341,94,321,92,290,78,273,54,273,39,287,23,322,22,334,12" href="http://postcode.in.ua/ua/codes/region/25" onmouseover="tooltip.show('<b>Чернігівська</b>&nbsp;обл.<br>Обл.&nbsp;центр:&nbsp;<b>Чернігів</b>')"  alt="">
</map></div><table border="0" cellpadding="0" cellspacing="0" style="width:100%;">
  <tr>
    <td align="left" valign="top">
<img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/codes/region/1" class="box1_text_link">АР Крим</a><br>
<img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/codes/region/2" class="box1_text_link">Вінницька область</a><br>
<img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/codes/region/3" class="box1_text_link">Волинська область</a><br>
<img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/codes/region/4" class="box1_text_link">Дніпропетровська область</a><br>
<img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/codes/region/5" class="box1_text_link">Донецька область</a><br>
<img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/codes/region/6" class="box1_text_link">Житомирська область</a><br>
<img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/codes/region/7" class="box1_text_link">Закарпатська область</a><br>
    </td>
    <td align="left" valign="top">
<img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/codes/region/8" class="box1_text_link">Запорізька область</a><br>
<img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/codes/region/9" class="box1_text_link">Івано-Франківська область</a><br>
<img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/codes/region/10" class="box1_text_link">Київська область</a><br>
<img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/codes/region/11" class="box1_text_link">Кіровоградська область</a><br>
<img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/codes/region/12" class="box1_text_link">Луганська область</a><br>
<img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/codes/region/13" class="box1_text_link">Львівська область</a><br>
    </td>
    <td align="left" valign="top">
<img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/codes/region/14" class="box1_text_link">Миколаївська область</a><br>
<img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/codes/region/15" class="box1_text_link">Одеська область</a><br>
<img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/codes/region/16" class="box1_text_link">Полтавська область</a><br>
<img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/codes/region/17" class="box1_text_link">Рівненська область</a><br>
<img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/codes/region/18" class="box1_text_link">Сумська область</a><br>
<img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/codes/region/19" class="box1_text_link">Тернопільська область</a><br>
    </td>
    <td align="left" valign="top">
<img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/codes/region/20" class="box1_text_link">Харківська область</a><br>
<img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/codes/region/21" class="box1_text_link">Херсонська область</a><br>
<img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/codes/region/22" class="box1_text_link">Хмельницька область</a><br>
<img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/codes/region/23" class="box1_text_link">Черкаська область</a><br>
<img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/codes/region/24" class="box1_text_link">Чернівецька область</a><br>
<img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/codes/region/25" class="box1_text_link">Чернігівська область</a><br>
    </td>
  </tr>
</table>
<div style="margin:5px 0 10px 0;" align="right"><table border="0" cellpadding="0" cellspacing="0" ><tr><td><div class="text_1">Поділитися:</div></td><td>
<script type="text/javascript" src="//yandex.st/share/share.js" charset="utf-8"></script> <div class="yashare-auto-init" data-yashareL10n="uk" data-yashareType="none" data-yashareQuickServices="vkontakte,facebook,twitter,odnoklassniki,moimir,lj,friendfeed,yaru,gplus"></div>
</td></tr></table>
</div></div><div style="margin:20px 0 20px 0;" align="center"><script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- 728x90, создано 07.03.13 -->
<ins class="adsbygoogle"
     style="display:inline-block;width:728px;height:90px"
     data-ad-client="ca-pub-3057864862569550"
     data-ad-slot="2879928385"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
</div><div style="margin:20px 0 20px 0;">
<div align="left" class="text_head_1" style="margin:10px 0 5px 0;">Довідкова інформація:</div><div align="left">
<table width="100%"><tr><td align="left" valign="top">
<div><img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/pages/codes_info" class="box_info_link">Система поштової індексації України</a></div>
<div><img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/pages/codes_allocation" class="box_info_link">Розподілення індексів по Україні</a></div>
<div><img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/pages/translit" class="box_info_link">Таблиця транслітерації</a></div>
</td><td align="left" valign="top">
<div><img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/pages/zakon_ukr" class="box_info_link">Закон України про поштовий зв'язок</a></div>
<div><img src="http://postcode.in.ua/images/marker2.png" border="0" alt=""> <a href="http://postcode.in.ua/ua/pages/post_terms" class="box_info_link">Визначення поштових термінів</a></div>
</td></tr></table>
</div>

</div>

          </td>
          <td style="width:15px;"> </td>
          <td style="width:160px;" valign="top">
<div style="margin:15px 0 0 0;" align="center"><script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- 160x600, создано 25.11.13 -->
<ins class="adsbygoogle"
     style="display:inline-block;width:160px;height:600px"
     data-ad-client="ca-pub-3057864862569550"
     data-ad-slot="7740651985"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
</div><div style="margin:8px 0 0 0;"><table border="0" cellpadding="0" cellspacing="0" style="width:120px;">
  <tr>
    <td style="height:10px;"></td>
  </tr>
  <tr>
    <td style="height:1px;  background:#bcd3f0 url(http://postcode.in.ua/images/line1.png) repeat-x;"></td>
  </tr>
  <tr>
    <td style="height:2px;"></td>
  </tr>
  <tr>
    <td align="left" valign="top"><div align="left">
<div class="box_right_text_head">Інформаційний центр Укрпошти:</div>
<div style="font-family:Arial; font-size:14px; color:#f99350; font-weight:bold;">(044) 32 32 099</div>
<div class="text_8">Вартість дзвінків згідно з тарифами Вашого оператора зв'язку</div>
</div>
</td>
  </tr>
  <tr>
    <td style="height:10px;"></td>
  </tr>
</table>
<table border="0" cellpadding="0" cellspacing="0" style="width:120px;">
  <tr>
    <td style="height:10px;"></td>
  </tr>
  <tr>
    <td style="height:1px;  background:#bcd3f0 url(http://postcode.in.ua/images/line1.png) repeat-x;"></td>
  </tr>
  <tr>
    <td style="height:2px;"></td>
  </tr>
  <tr>
    <td align="left" valign="top"><div class="ed_text_2">Помітили помилку на<br>сторінці? Виділіть її<br>та натисніть:</div><img src="http://postcode.in.ua/images/ctrl_enter.png" border="0" alt="Ctrl + Enter"></td>
  </tr>
  <tr>
    <td style="height:10px;"></td>
  </tr>
</table>
<div id="full_fon" style="display:none;"></div>
<div id="ed_box" style="display:none;">
  <table border="0" cellpadding="4" cellspacing="0" style="width:100%; height:100%">
    <tr>
      <td rowspan="2" align="center" valign="top">
        <img src="http://postcode.in.ua/images/attention.png" border="0" alt="">      </td>
      <td colspan="2" align="left" valign="top">
<div class="ed_text">Відправити помилку:</div>
<textarea id="ed_error" maxlength="100" wrap="hard" class="ed_input_1"></textarea>
<div class="ed_text">Ваші коментарі (не обов'язково):</div>
<textarea id="ed_comment" maxlength="100" wrap="hard" class="ed_input_2"></textarea>
      </td>
    </tr>
    <tr>
      <td align="right" valign="middle">
<table border="0" cellpadding="0" cellspacing="0" style="height:20px;">
  <tr>
    <td rowspan="3" style="width:2px; background:#f99350;"><img src="http://postcode.in.ua/images/button_1.png" border="0" width="2" height="20" alt=""></td>
    <td style="height:1px; background:#f99350;"></td>
    <td rowspan="3" style="width:2px; background:#f99350;"><img src="http://postcode.in.ua/images/button_2.png" border="0" width="2" height="20" alt=""></td>
  </tr>
  <tr>
    <td style="height:18px; background:#fff url(http://postcode.in.ua/images/button_3.png) bottom repeat-x;"><a href="javascript:send_error();" class="button_text_1" title="Відправити">Відправити</a></td>
  </tr>
  <tr>
    <td style="height:1px; background:#f99350;"></td>
  </tr>
</table>
      </td>
      <td align="right" valign="middle">
<table border="0" cellpadding="0" cellspacing="0" style="height:20px;">
  <tr>
    <td rowspan="3" style="width:2px; background:#f99350;"><img src="http://postcode.in.ua/images/button_1.png" border="0" width="2" height="20" alt=""></td>
    <td style="height:1px; background:#f99350;"></td>
    <td rowspan="3" style="width:2px; background:#f99350;"><img src="http://postcode.in.ua/images/button_2.png" border="0" width="2" height="20" alt=""></td>
  </tr>
  <tr>
    <td style="height:18px; background:#fff url(http://postcode.in.ua/images/button_3.png) bottom repeat-x;"><a href="javascript:hide_edbox();" class="button_text_1" title="Відміна">Відміна</a></td>
  </tr>
  <tr>
    <td style="height:1px; background:#f99350;"></td>
  </tr>
</table>
      </td>
    </tr>
  </table>
</div>
<div style="display:none;" id="pageurl">ua</div>
</div>          </td>
          <td style="width:10px;"> </td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td style="height:30px; background:#fff" align="center">
<div>
<a href="http://postcode.in.ua/ua" class="bottom_menu_link">
Головна</a>
<span class="bottom_menu_text"><img src="http://postcode.in.ua/images/marker5.png" border="0" alt=""></span>
<a href="http://postcode.in.ua/ua/feedback" class="bottom_menu_link">Зворотній&nbsp;зв'язок</a>
<span class="bottom_menu_text"><img src="http://postcode.in.ua/images/marker5.png" border="0" alt=""></span>
<a href="http://postcode.in.ua/ua/about" class="bottom_menu_link">Про&nbsp;проект</a>
</div>
    </td>
  </tr>
  <tr>
    <td style="height:1px; background:#bcd3f0"> </td>
  </tr>
  <tr>
    <td style="height:50px; background:#fff url(http://postcode.in.ua/images/line4.png) top repeat-x;" align="center">
      <table border="0" cellpadding="0" cellspacing="0" style="height:50px; width:923px;">
        <tr>
          <td style="width:10px;"> </td>
          <td style="width:903px;" valign="top">
            <table border="0" cellpadding="0" cellspacing="0" style="height:50px; width:100%;">
              <tr>
                <td style="width:50%;" align="left" valign="middle">
<div class="bottom_text_1">Copyright © 2010-2017 postcode.in.ua</div>
<div class="bottom_text_1">Поштові індекси України – довідкова система</div>
<div class="bottom_text_1">Використання матеріалів з цього сайту можливе тільки з посиланням на джерело</div>
                </td>
                <td style="width:50%;" align="right" valign="middle">
<span class="bottom_baner_box">
<!-- begin of Top100 code -->
<script id="top100Counter" type="text/javascript" src="http://counter.rambler.ru/top100.jcn?2519796"></script>
<noscript>
<a href="http://top100.rambler.ru/navi/2519796/">
<img src="http://counter.rambler.ru/top100.cnt?2519796" alt="Rambler's Top100" border="0" />
</a>
</noscript>
<!-- end of Top100 code -->
</span>

<span class="bottom_baner_box">
<!-- I.UA counter --><a href="http://www.i.ua/" target="_blank" onclick="this.href='http://i.ua/r.php?119501';" title="Rated by I.UA">
<script type="text/javascript" language="javascript"><!--
iS='<img src="http://r.i.ua/s?u119501&p159&n'+Math.random();
iD=document;if(!iD.cookie)iD.cookie="b=b; path=/";if(iD.cookie)iS+='&c1';
iS+='&d'+(screen.colorDepth?screen.colorDepth:screen.pixelDepth)
+"&w"+screen.width+'&h'+screen.height;
iT=iD.referrer.slice(7);iH=window.location.href.slice(7);
((iI=iT.indexOf('/'))!=-1)?(iT=iT.substring(0,iI)):(iI=iT.length);
if(iT!=iH.substring(0,iI))iS+='&f'+escape(iD.referrer.slice(7));
iS+='&r'+escape(iH);
iD.write(iS+'" border="0" width="88" height="31" />');
//--></script></a><!-- End of I.UA counter -->
</span>

                </td>
              </tr>
            </table>
          </td>
          <td style="width:10px;"> </td>
        </tr>
      </table>
    </td>
  </tr>
</table>
</body>
</html>
  <!-- Генерация за 0.00486 сек. -->