<!DOCTYPE html>
<html lang="ru">
<head>
<title>RGhost — файлообменник</title>
<meta content=". скачать . Скачать с хорошего файлообменника" name="description" />
<meta content="скачать , скачать , rghost" name="keywords" />
<meta charset="utf-8">
<meta content="IE=edge" http-equiv="X-UA-Compatible">
<meta content="width=device-width, initial-scale=1" name="viewport">
<meta content="authenticity_token" name="csrf-param" />
<meta content="2k67qX5aq5oVwMQqd+W8yZmFhrUXn0YYK9MQTkKL3cs=" name="csrf-token" />
<link href="/assets/application-4287de6bdedb3ebedf2c40fd2f2e938d.css" media="screen" rel="stylesheet" type="text/css" />

<link href="/opensearch_ru.xml" rel="search" title="rghost" type="application/opensearchdescription+xml">
<link href="/favicon.ico?v1" rel="shortcut icon" sizes="16x16 32x32 48x48 64x64" type="image/vnd.microsoft.icon" />
<link href="/favicon.ico?v1" rel="icon" sizes="196x196">

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-15644263-1', 'auto', {'allowLinker': true});
  ga('linker:autoLink', ['rgho.st', 'ad-file.com']);
  ga('require', 'displayfeatures');
  
  ga('send', 'pageview');
  new Image().src = "//counter.yadro.ru/hit?r"+
  escape(document.referrer)+((typeof(screen)=="undefined")? "" : ";s"+screen.width+"*"+screen.height+"*"+(screen.colorDepth ? screen.colorDepth:screen.pixelDepth))+";u"+escape(document.URL)+";"+Math.random();
</script>
<!-- Yandex.Metrika counter --> <script type="text/javascript"> (function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter37151970 = new Ya.Metrika({ id:37151970, clickmap:true, trackLinks:true, accurateTrackBounce:true, webvisor:true, trackHash:true }); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = "https://mc.yandex.ru/metrika/watch.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks"); </script> <noscript><div><img src="https://mc.yandex.ru/watch/37151970" style="position:absolute; left:-9999px;" alt="" /></div></noscript> <!-- /Yandex.Metrika counter -->
<script>
  window.rgh = {}
  window.rgh.usersignedin = 'false'
</script>

<!--[if lt IE 9]>
<script src="/assets/html5_ie-012ca019dd744748a285b10b23c1b18e.js" type="text/javascript"></script>
<![endif]-->

</head>
<body class="with-top-navbar" id="welcome___index">
<div id="flash-messages">
</div>
<div class="with-bg wrapper">

<nav class="navbar navbar-inverse navbar-fixed-top app-navbar">
<div class="container">
<div class="navbar-header">
<button class="navbar-toggle collapsed" data-target="#navbar-collapse-main" data-toggle="collapse" type="button">
<span class="sr-only">Toggle navigation</span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<div class="hidden-xs">
<a href="/main" class="brand" title="RGhost — файлообменник"><img alt="Logo" height="50px" onerror="this.onerror=null; this.src=&#x27;/logo.png&#x27;" src="/logo.svg?v2" /></a>
</div>
<div class="visible-xs">
<a href="/main" class="brand m-l-15" title="RGhost — файлообменник"><img alt="Logo" height="50px" onerror="this.onerror=null; this.src=&#x27;/logo.png&#x27;" src="/logo.svg?v2" /></a>
</div>
</div>
<div class="navbar-collapse collapse" id="navbar-collapse-main">
<form accept-charset="UTF-8" action="/search" class="navbar-form navbar-right app-search hidden-sm" id="small-search-form" method="get" role="search"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" /></div>
<div class="form-group">
<input class="search-input form-control" data-action="grow" name="s" placeholder="Поиск" type="text">
</div>
</form>

<ul class="nav navbar-nav hidden-xs">
<li class=""><a href="/main">Обзор</a></li>
</ul>
<ul class="nav navbar-nav navbar-right hidden-xs">
<li><a href="#registerModal" data-target="#registerModal" data-toggle="modal" title="Получить бесплатный аккаунт на файлообменнике">Зарегистрироваться</a></li>
<li><a href="#signInModal" data-target="#signInModal" data-toggle="modal">Войти</a></li>
</ul>
<ul class="nav navbar-nav hidden-sm hidden-md hidden-lg">
<li class=""><a href="/main">Обзор</a></li>
<li class=""><a href="/upload/multiple">Аплоад</a></li>
<li class=""><a href="/faq">FAQ</a></li>
<li><a href="#" class="reformal_feedback">Обратная связь</a></li>
<li><a href="#registerModal" data-target="#registerModal" data-toggle="modal" title="Получить бесплатный аккаунт на файлообменнике">Зарегистрироваться</a></li>
<li><a href="#signInModal" data-target="#signInModal" data-toggle="modal">Войти</a></li>
</ul>
</div>
</div>
</nav>


<div class="hide-element" id="file-upload-form">
<div class="upload-info-form hide-element" data-max-file-size="104857600"></div>
<form accept-charset="UTF-8" action="http://muonium.rgho.st/files" class="form-inline height-0" enctype="multipart/form-data" id="upload-form" method="post"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" /><input name="authenticity_token" type="hidden" value="2k67qX5aq5oVwMQqd+W8yZmFhrUXn0YYK9MQTkKL3cs=" /></div>
<input id="uuid" name="uuid" type="hidden" />
<input id="choose" name="file" size="50" type="file" />
<input class="btn btn-primary upload" id="startupload" name="commit" type="submit" value="Отправить" />
</form>

</div>

<div id="dropbox">
<div class="dropbox-info">
<span class="dropbox-info-text">
Для начала загрузки, перетащите файл в любое место на этой странице.
</span>
<br>
<span class="dropbox-info-hint">
Размер файла не более 
100 МБ
</span>
</div>
</div>
<div class="growl" id="dropbox_multiple"></div>
<div class="modal fade" id="dropbox_modal">
<div class="modal-dialog modal-sm-scale">
<div class="modal-content">
<div class="modal-header">
<button aria-label="Отмена" class="close" data-dismiss="modal" type="button"><span aria-hidden="true">&times;</span>
</button><h4 class="modal-title">Вы выбрали</h4>
</div>
<div class="modal-body">
<p class="m-b-0" id="dropbox_modal_text"></p>
<div class="canvas-text" data-content="Править" onclick="UploadLogic.scaleConfirmModal()">
<canvas class="img-responsive" id="dropbox_modal_canvas" style="border:1px solid grey;"></canvas>
</div>
</div>
<div class="modal-actions">
<button class="btn-link modal-action" data-dismiss="modal" type="button">Отмена
</button><button class="btn-link modal-action" onclick="UploadLogic.startUploadFromModal()" type="button"><strong>Отправить</strong>
</button></div>
</div>
</div>
</div>

<div class="container" id="file-upload-content"></div>

<div class="container" id="content">

<div class="container-fill-height">
<div class="container-content-middle">
<div class="row">
<div class="m-x-auto">
<img alt="Cloud-storage" class="img-responsive center-block cloud-img" onerror="this.onerror=null; this.src=&#x27;cloud-storage.png&#x27;" src="/assets/cloud-storage-27cfb32ad71ea9353f6fc5565b632817.svg" />
</div>
</div>
<div class="upload-form-wrap">
<div id="upload-button-block">
<center>
<button class="btn btn-primary btn-upload" id="upload_button" name="button" type="submit">Поделитесь - выберите файл</button>
<span class="hint hint-upload no-overflow nowrap">
Размер файла не более 
100 МБ
</span>
</center>
</div>

</div>
<div class="row hidden-xs shadow flex">
<div class="m-x-auto">
<div class="text-block-main m-t-md">
<p>
<span class="icon icon-copy">
 Вы можете перетащить файлы на эту страницу
</span>
</p>
<p>
<span class="icon icon-image">
 Вставить картинку из буфера обмена
</span>
</p>
<p>
<span class="icon icon-archive">
 Воспользоваться <a href="/upload/multiple">пакетными загрузчиками</a>
</span>
</p>
<p>
<span class="icon icon-cloud">
 Или выбрать файл в облачном хранилище
</span>
</p>
</div>
</div>
</div>
<div class="cloud-icons shadow">
<div class="row text-center">
<ul class="list-inline">
<li>
<a href="#" class="link-button" data-remote="true"><div class="icon-dropbox"></div>
<div class="hint hint-hover">Dropbox</div>
</a></li>
<li>
<a href="#" class="link-button" data-remote="true"><div class="icon-google"></div>
<div class="hint hint-hover">Google Drive</div>
</a></li>
<li>
<a href="#" class="link-button" data-remote="true"><div class="icon-onedrive"></div>
<div class="hint hint-hover">Onedrive</div>
</a></li>
</ul>
</div>
</div>
<script data-app-key="sx0b6jakttt9di5" id="dropboxjs" src="https://www.dropbox.com/static/api/2/dropins.js" type="text/javascript"></script>

<script src="https://apis.google.com/js/api.js?onload=onApiLoad" type="text/javascript"></script>
<div id="result-google"></div>

<script client-id="0000000044188C39" id="onedrive-js" src="https://js.live.net/v5.0/OneDrive.js" type="text/javascript"></script>

</div>
</div>

</div>
</div>
<div aria-hidden="true" aria-labelledby="msgModal" class="modal fade" id="signInModal" role="dialog" tabindex="-1">
<div class="modal-dialog">
<div class="modal-content">
<form accept-charset="UTF-8" action="/profile/sign_in" class="simple_form form-horizontal" method="post"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" /><input name="authenticity_token" type="hidden" value="2k67qX5aq5oVwMQqd+W8yZmFhrUXn0YYK9MQTkKL3cs=" /></div><div class="modal-header">
<button aria-hidden="true" class="close" data-dismiss="modal" type="button">×</button>
<h4 class="modal-title">Войти</h4>
</div>
<div class="modal-body">

<div class="form-group email required user_email"><div class="col-xs-4 col-sm-3 control-label"><label class="email required" for="user_email"><abbr title="required">*</abbr> E-mail</label></div><div class="col-xs-8 col-sm-9"><input class="string email required form-control form-control" id="user_email" name="user[email]" required="required" size="50" type="email" value="" /></div></div>
<div class="form-group password required user_password"><div class="col-xs-4 col-sm-3 control-label"><label class="password required" for="user_password"><abbr title="required">*</abbr> Пароль</label></div><div class="col-xs-8 col-sm-9"><input class="password required form-control" id="user_password" name="user[password]" required="required" size="50" type="password" /><p class="help-block"><a href="/profile/password/new">Забыли пароль?</a></p></div></div>
<div class="on-top-20">
<div class="form-group boolean optional user_remember_me"><div class="col-sm-offset-3 col-sm-9"><div class="checkbox"><input name="user[remember_me]" type="hidden" value="0" /><label class="checkbox"><input checked="checked" class="boolean optional" id="user_remember_me" name="user[remember_me]" type="checkbox" value="1" />Запомнить меня</label></div></div></div>
</div>
</div>
<div class="modal-footer">
<div class="row">
<div class="col-xs-6">
<div class="text-left">
<a href="/profile/openid_login" class="btn btn-default">OpenID</a>
</div>
</div>
<div class="col-xs-6">
<div class="text-right">
<input class="btn btn-primary" name="commit" type="submit" value="Войти" />
</div>
</div>
</div>
</div>
</form>

</div>
</div>
</div>

<div aria-hidden="true" aria-labelledby="msgModal" class="modal fade" id="registerModal" role="dialog" tabindex="-1">
<div class="modal-dialog">
<div class="modal-content">
<form accept-charset="UTF-8" action="/profile" class="simple_form form-horizontal" id="new_user" method="post"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" /><input name="authenticity_token" type="hidden" value="2k67qX5aq5oVwMQqd+W8yZmFhrUXn0YYK9MQTkKL3cs=" /></div><div class="modal-header">
<button aria-hidden="true" class="close" data-dismiss="modal" type="button">×</button>
<h4 class="modal-title">Регистрация</h4>
</div>
<div class="modal-body">

<div class="form-group string required user_name"><div class="col-xs-4 col-sm-3 control-label"><label class="string required" for="user_name"><abbr title="required">*</abbr> Имя</label></div><div class="col-xs-8 col-sm-9"><input class="string required form-control" id="user_name" name="user[name]" required="required" size="50" type="text" /></div></div>
<div class="form-group email required user_email"><div class="col-xs-4 col-sm-3 control-label"><label class="email required" for="user_email"><abbr title="required">*</abbr> E-mail</label></div><div class="col-xs-8 col-sm-9"><input class="string email required form-control form-control" id="user_email" name="user[email]" required="required" size="50" type="email" /></div></div>
<div class="form-group password required user_password"><div class="col-xs-4 col-sm-3 control-label"><label class="password required" for="user_password"><abbr title="required">*</abbr> Пароль</label></div><div class="col-xs-8 col-sm-9"><input class="password required form-control" id="user_password" name="user[password]" required="required" size="50" type="password" /></div></div>
<div class="form-group password required user_password_confirmation"><div class="col-xs-4 col-sm-3 control-label"><label class="password required" for="user_password_confirmation"><abbr title="required">*</abbr> Повторите</label></div><div class="col-xs-8 col-sm-9"><input class="password required form-control" id="user_password_confirmation" name="user[password_confirmation]" required="required" size="50" type="password" /></div></div>
</div>
<div class="modal-footer">
<div class="row">
<div class="col-xs-2">
<div class="text-left">
<a href="/profile/openid_login" class="btn btn-default">OpenID</a>
</div>
</div>
<div class="col-xs-10">
<div class="text-right">
<input class="btn btn-primary" data-disable-with="Создаю…" name="commit" type="submit" value="Зарегистрироваться" />
</div>
</div>
</div>
</div>
</form>

</div>
</div>
</div>

<div class="overlay hide-element" id="overlay">
<div class="overlay-dialog" id="overlay-dialog">
<div class="overlay-waiting" id="overlay-waiting">
<div class="overlay-spinner-content">
<div class="loader">Загрузка…</div>
</div>
</div>
<div class="overlay-content hide-element" id="overlay-content">
<div class="container" id="animate-container"></div>
</div>
</div>
</div>

<div id="file-list-modals"></div>
<svg height="0px" version="1.1" xmlns="http://www.w3.org/2000/svg">
<filter id="blur">
<feGaussianBlur stdDeviation="5"></feGaussianBlur>
</filter>
</svg>
<script src="/assets/application-958d9ea64b90a2fe2aec36ff7feacf2f.js" type="text/javascript"></script>




<script type="text/javascript">
//<![CDATA[
I18n.defaultLocale = "en"
I18n.locale = "ru"
I18n.fallbacks = true

//]]>
</script><script>
  var blocks = JSON.parse(atob("e30="));
</script>
</body>
</html>