<!DOCTYPE HTML SYSTEM>
<html>
<HEAD>
   <meta HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">
   <meta NAME="GENERATOR" CONTENT="vim">
<meta name="google-site-verification" content="slZJtTlmOThyLOSMfZslv6wdS-rmYDQClukGtM6AOu0" >
   <link rel="stylesheet" href="style.css">
  <title>Sivann's page</title>
</head>

<BODY >

<div class=headouter>

<div class='headtit'> Home </div>
<div class=headlnk>
  <div style='float:left;padding-left:10px;padding-right:10px;'>
    <a href="index.php">Home</a>&nbsp;
    <a href="software.php">Software</a>&nbsp;
    <a href="about.php">About</a>&nbsp;
    <a href="links.php">Links</a>
  </div>
  <div class='headline' ></div>
</div>
</div>

<div class=maindiv>
	<div class=bcard itemscope itemtype="http://data-vocabulary.org/Person">  <!-- w3c validator bug 14020 -->
	  <div style='font-weight:bold;font-size:110%' itemprop="name">Spiros Ioannou</div>
	  <!--
	  <span itemprop="nickname">sivann</span> 
	    Currently employed as <span itemprop="title">IT Manager</span>
	    by the <span itemprop="affiliation"><a href="http://www.avarchive.gr">Hellenic National Audiovisual Archive</a></span>.
	  -->

	  E:
	  <script  type="text/javascript"  language=javascript>
	  <!--
	  var username = "sivann";
	  var hostname = "gmail.com";
	  var linktext = username + "@" + hostname;
	  document.write("<a href=" + "mail" + "to:" + username +
	  "@" + hostname + ">" + linktext + "</a>");
	  //-->
	  </script> 
	  <noscript>
	  sivann at cs dot gm ail dot com
	  </noscript>

	  <br>
	  <span itemprop="address">
	  A (en): Zalokosta 16A 15233 Halandri, Greece<br>
	  A (el): Ζαλοκώστα 16Α 15233 Χαλάνδρι<br>
	  M: 6973903808<br>
	  </span>

	</div>
</div>



</BODY>
</HTML>