<!DOCTYPE html>
<html>
<head>

            
    <meta http-equiv="Content-Language" content="ru">
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=yes">
<title>Новости Одессы сегодня онлайн: власть, транспорт, деньги, кино, музыка, туризм, светская хроника, интересные факты - Одесский Курьер</title>
<meta name="description" content="Новости Одессы онлайн. События, происшествия, комментарии, власть, политика, туризм. Ежедневное обновление">
<meta name="keywords" content="новости, одессы, одесса, политика, происшествия, власть, туризм, курьер, транспорт">
    <link rel="canonical" href="http://uc.od.ua">




    <link rel="icon" href="http://uc.od.ua/images/favicon.ico" type="image/x-icon">
    <link rel="shortcut icon" href="http://uc.od.ua/images/favicon.ico" type="image/x-icon">

    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=PT+Sans:400,400i,700,700i|Merriweather:900i&subset=latin,cyrillic">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="http://uc.od.ua/js/bxslider/jquery.bxslider.min.css">
    <link rel="stylesheet" href="http://uc.od.ua/css/jquery.colorbox.css">
    <link rel="stylesheet" type="text/css" href="http://uc.od.ua/css/all_transport.css"/>


    <!--[if lt IE 9]>
    <script src="http://uc.od.ua/js/html5.js"></script>
    <script src="http://uc.od.ua/js/css3-mediaqueries.js"></script>
    <![endif]-->

    <meta name="google-site-verification" content="0x1VIWmn_1k2ssyBOLcIe5B2oSzhvRO4uYwD_neUECM" />
<meta name='yandex-verification' content='5ffab18f63809e23' />

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-68383260-1', 'auto');
  ga('send', 'pageview');

</script>

<!-- Yandex.Metrika counter -->
<script type="text/javascript">
(function (d, w, c) {
    (w[c] = w[c] || []).push(function() {
        try {
            w.yaCounter32821250 = new Ya.Metrika({id:32821250,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true});
        } catch(e) { }
    });

    var n = d.getElementsByTagName("script")[0],
        s = d.createElement("script"),
        f = function () { n.parentNode.insertBefore(s, n); };
    s.type = "text/javascript";
    s.async = true;
    s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

    if (w.opera == "[object Opera]") {
        d.addEventListener("DOMContentLoaded", f, false);
    } else { f(); }
})(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="//mc.yandex.ru/watch/32821250" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-6812131684807721",
    enable_page_level_ads: true
  });
</script>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-6812131684807721",
    enable_page_level_ads: true
  });
</script>

    <!--[if IE 8 ]>
    <body class="ie8"><![endif]-->
    <!--[if IE 9 ]>
    <body class="ie9"><![endif]-->
    <meta name="cmsmagazine" content="0225b83d65f5abd3f311ba82859ed3eb">
</head>

<body>


<div id="wrap">
    <div class="header">
    <div class="header_inner">
        <div class="header_layout">
            <div class="header-top">
                <div class="main">
                    <div class="dozorLinks">
                        <span>Дозоры:</span>
                        <a target="_blank" rel="nofollow" href="http://dozor.com.ua/" class="afisha">Афиша</a>
                        <a target="_blank" rel="nofollow" href="http://kiev.dozor.ua/" class="kiev">Столичный</a>
                        <a target="_blank" rel="nofollow" class="varta" href="http://varta.com.ua/">Львов</a>
                        <a target="_blank" rel="nofollow" class="crimea" href="http://courier.crimea.ua/">Крым</a>
                        <a target="_blank" rel="nofollow" class="vostok" href="http://vostok.dozor.com.ua/">Донбасс</a>
                        <a target="_blank" rel="nofollow" class="sport" href="http://sport.dozor.com.ua/">Спорт</a>
                        <a target="_blank" rel="nofollow" class="life" href="http://lifestyle.dozor.com.ua/">Lifestyle</a>
                        <a target="_blank" rel="nofollow" class="food" href="http://eda.dozor.com.ua/">Еда</a>
                        <a target="_blank" rel="nofollow" class="woman" href="http://kabluchki.ua/">Каблучки</a>
                        <a target="_blank" rel="nofollow" class="shopping" href="http://shopping.kabluchki.ua/">Шоппинг-Гид</a>
                    </div>
                </div>
            </div>

            <span class="logo">http://uc.od.ua</span>
                                            <div class="hot_theme">
                    <a href="http://uc.od.ua/tema"><span class="highlight bold">ГОРЯЧАЯ ТЕМА:</span></a><br><a href="http://uc.od.ua/tema/1005">Реконструкция Пересыпи</a>
                    </a>
                </div>
            
            <div class="header_right">
                <div class="our_sites">
                    <div class="shid_zahid highlight"><span class="region">Ваш регион:</span> Одесса<i
                                class="fa fa-chevron-down"></i>
                        <ul class="submenu_sites">
                            <li><a href="http://kiev.dozor.ua">Киев</a></li>
                            <li><a href="http://kharkov.dozor.ua">Харьков</a></li>
                            <li><a href="http://vostok.dozor.com.ua/news/dnepropetrovsk/">Днепр</a></li>
                            <li><a href="http://courier.crimea.ua/">Крым</a></li>
                            <li><a href="http://courier.crimea.ua/news/azov/">Азов</a></li>
                            <li><a href="http://vostok.dozor.com.ua/news/donetsk/">Донецк</a></li>
                            <li><a href="http://vostok.dozor.com.ua/news/lugansk/">Луганск</a></li>
                            <li><a href="http://vostok.dozor.com.ua/news/zaporoje//">Запорожье</a></li>
                        </ul>
                    </div>

                </div>
                <div class="header_social">
                    <div class="search">
                        <form action="http://uc.od.ua/search" method="GET"
                              onsubmit="if(!this.query.value){this.query.focus();return false}">
                            <input type="text" name="query" placeholder="Поиск">
                            <button type="submit" class="fa fa-search"></button>
                        </form>
                    </div>
                                            <a class="face" href="https://www.youtube.com/channel/UCdg5P2bOBS1FymwMxudDTHQ" target="_blank" rel="nofollow" title="Youtube"><i
                                    class="fa fa-youtube"></i></a>
                                                                <a class="face" href="https://twitter.com/KaiserOdessa" target="_blank" rel="nofollow" title="Twitter"><i
                                    class="fa fa-twitter"></i></a>
                                                                                    <a class="face" href="https://www.facebook.com/YuzhnyjCourier" target="_blank" rel="nofollow"
                           title="Facebook"><i class="fa fa-facebook"></i></a>
                                    </div>
            </div>
        </div>
    </div>
</div>
<div class="nav">
    <div class="nav_inner">
        <div class="nav_layout">
            <div id="btn-menu-show" class="menu_show">Меню<i class="fa fa-chevron-down"></i></div>
            <div id="menu" class="main_menu">
                <ul><li class="nav_news"><a href="http://uc.od.ua/news">Новости<i class="fa fa-chevron-down"></i></a><ul class="subnews"><li><a href="http://uc.od.ua/news/city">Одесса</a></li><li><a href="http://uc.od.ua/news/region">Регион</a></li><li><a href="http://uc.od.ua/news/politic">Политика</a></li><li><a href="http://uc.od.ua/news/crime">Происшествия</a></li><li><a href="http://uc.od.ua/news/culture">Культура</a></li><li><a href="http://uc.od.ua/news/urbanism">Урбанистика</a></li></ul></li><li><a href="http://uc.od.ua/975">Досье</a></li><li><a href="http://uc.od.ua/tema">Темы</a></li><li><a href="http://uc.od.ua/photo">Фоторепортажи</a></li><li><a href="http://uc.od.ua/columns">Блоги</a></li></ul>
            </div>
            <a href="#" id="btn-search-show" class="btn-search fa fa-search"></a>
            <div id="mob-search" class="zoom">
                <form action="http://uc.od.ua/search" method="GET"
                      onsubmit="if(!this.query.value){this.query.focus();return false}">
                    <input type="text" name="query" placeholder="Пошук" class="zoom__field">
                    <button type="submit" class="zoom__btn fa fa-search"></button>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="after_nav">
    <div class="after_nav_inner">
        <div class="after_nav_layout">
            <div>Вторник
                , 20 марта 2018</div>
                            <div>|</div>
                <div>В Одессе: <sup>о</sup>С</div>
                                        <div>|</div>
                <div>НБУ : USD  EUR </div>
                        
        </div>
    </div>
</div>
    <div class="main-content">
    <div class="main-content_inner">
        <div class="layout-main">
            
            <div class="cols clearfix">
                                    <div class="col_fluid">
                        <div class="col_fluid_inner">
                                <div class="wrap_slider">
        <div class="inner_slider block-slider">
            <ul id="slider">
                                                            <li class="wrap_slide">
                            <a href="http://uc.od.ua/news/culture/1201014">
                                <img class="grayscale" src="http://uc.od.ua/content/documents/12011/1201014/thumb-slider-626x405-c9b6.jpg"
                                     alt="В обход облсовета: директором Одесского художественного музея назначили Ройтбурда"
                                     height="405"
                                     width="626">
                                <div class="text_slider">
                                    <h2>В обход облсовета: директором Одесского художественного музея назначили Ройтбурда</h2>
                                    <div class="text_anons">19 марта глава Одесской ОГА Максим Степанов назначил художника Александра Ройтбурда директором художественного музея.</div>
                                    <div class="info">
                                                                                    <i class="fa fa-circle bordo"></i>
                                            <span class="nadiyne">надежный источник</span>
                                            &nbsp;&nbsp;
                                            <span class="vertical_razd">|</span>
                                            &nbsp;
                                                                                                                        20 часов назад
                                                                            </div>
                                </div>
                                <div class="icon">
                                                                    </div>
                            </a>
                        </li>
                                                                                <li class="wrap_slide">
                            <a href="http://uc.od.ua/news/urbanism/1200930">
                                <img class="grayscale" src="http://uc.od.ua/content/documents/12010/1200930/thumb-slider-626x405-d7c6.jpg"
                                     alt="Парк Шевченко, стадион Черноморец и Одесский порт: полет над городом (ФОТО, ВИДЕО)"
                                     height="405"
                                     width="626">
                                <div class="text_slider">
                                    <h2>Парк Шевченко, стадион Черноморец и Одесский порт: полет над городом (ФОТО, ВИДЕО)</h2>
                                    <div class="text_anons">Мы полетали над парком Шевченко, стадионом Черноморец и любуемся величественными панорамами порта, моря и города.</div>
                                    <div class="info">
                                                                                    <i class="fa fa-circle bordo"></i>
                                            <span class="nadiyne">надежный источник</span>
                                            &nbsp;&nbsp;
                                            <span class="vertical_razd">|</span>
                                            &nbsp;
                                                                                                                                                                                                                4 дня назад
                                                                                                                        </div>
                                </div>
                                <div class="icon">
                                                                            <span class="icon_photo"><i class="fa fa-camera"></i></span>
                                                                    </div>
                            </a>
                        </li>
                                                                                <li class="wrap_slide">
                            <a href="http://uc.od.ua/news/city/1200893">
                                <img class="grayscale" src="http://uc.od.ua/content/documents/12009/1200893/thumb-slider-626x405-0e31.jpg"
                                     alt="Максим и его команда: глава Одесского облздрава Вячеслав Полясный"
                                     height="405"
                                     width="626">
                                <div class="text_slider">
                                    <h2>Максим и его команда: глава Одесского облздрава Вячеслав Полясный</h2>
                                    <div class="text_anons">Через неделю будет ровно год, как председатель ОГА представил одесситам Стратегический план действий на 2017-2019 годы, получивший название «Умный регион».</div>
                                    <div class="info">
                                                                                    <i class="fa fa-circle bordo"></i>
                                            <span class="nadiyne">надежный источник</span>
                                            &nbsp;&nbsp;
                                            <span class="vertical_razd">|</span>
                                            &nbsp;
                                                                                                                                                                                                                5 дней назад
                                                                                                                        </div>
                                </div>
                                <div class="icon">
                                                                    </div>
                            </a>
                        </li>
                                                                                <li class="wrap_slide">
                            <a href="http://uc.od.ua/news/urbanism/1200456">
                                <img class="grayscale" src="http://uc.od.ua/content/documents/12005/1200456/thumb-slider-540x405-f711.jpg"
                                     alt="Зимняя Одесса со стометровой высоты: снег, море, высотки и санатории (ФОТО, ВИДЕО)"
                                     height="405"
                                     width="540">
                                <div class="text_slider">
                                    <h2>Зимняя Одесса со стометровой высоты: снег, море, высотки и санатории (ФОТО, ВИДЕО)</h2>
                                    <div class="text_anons">Южный Курьер показывает, как выглядит заснеженная Одесса с высоты сто метров.</div>
                                    <div class="info">
                                                                                                                                                                                                                24 дня назад
                                                                                                                        </div>
                                </div>
                                <div class="icon">
                                                                            <span class="icon_photo"><i class="fa fa-camera"></i></span>
                                                                    </div>
                            </a>
                        </li>
                                                                                <li class="wrap_slide">
                            <a href="http://uc.od.ua/news/crime/1200425">
                                <img class="grayscale" src="http://uc.od.ua/content/documents/12005/1200425/thumb-slider-607x405-e633.jpg"
                                     alt="Захват одесского санатория: вооруженные люди не пускали начальника полиции (ФОТО, ВИДЕО)"
                                     height="405"
                                     width="607">
                                <div class="text_slider">
                                    <h2>Захват одесского санатория: вооруженные люди не пускали начальника полиции (ФОТО, ВИДЕО)</h2>
                                    <div class="text_anons">Утром 23 февраля несколько десятков вооруженных людей захватили санаторий &quot;Лермонтовский&quot;.</div>
                                    <div class="info">
                                                                                                                                                                                                                25 дней назад
                                                                                                                        </div>
                                </div>
                                <div class="icon">
                                                                            <span class="icon_photo"><i class="fa fa-camera"></i></span>
                                                                    </div>
                            </a>
                        </li>
                                                                                <li class="wrap_slide">
                            <a href="http://uc.od.ua/news/politic/1200408">
                                <img class="grayscale" src="http://uc.od.ua/content/documents/12005/1200408/thumb-slider-626x405-bdf6.jpg"
                                     alt="В Киеве судят мэра Одессы (обновляется)"
                                     height="405"
                                     width="626">
                                <div class="text_slider">
                                    <h2>В Киеве судят мэра Одессы (обновляется)</h2>
                                    <div class="text_anons">В Cоломенском районном суде Киева началось рассмотрение ходатайства САП и НАБУ об отстранении от обязанностей мэра Одессы, Геннадия Труханова и его заместителя, Павла Вугельмана.</div>
                                    <div class="info">
                                                                                                                                                                                                                26 дней назад
                                                                                                                        </div>
                                </div>
                                <div class="icon">
                                                                            <span class="icon_photo"><i class="fa fa-camera"></i></span>
                                                                    </div>
                            </a>
                        </li>
                                                </ul>
        </div>
    </div>

<div class="col_left_wrap">
    <div class="col_left">
        <div class="head_str_news">
            <h3>Новости</h3>
            <div class="tab_news j-tab-news">
                <a class="tab_news__item active" href="#">Последние</a>
                <a class="tab_news__item" href="#">Популярные</a>
            </div>
        </div>
        <div class="str_news_ostanni j-tab-news-panel active">
                                                <div class="one_str_news">
                                                <div class="data_str_news">11:02
                                                            <img class="our_mat" src="http://uc.od.ua/images/self-material.png" alt="Собственный материал">
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/columns/1533/1201032"><span class="text-normal">Долги &quot;Роснефти&quot; поставили исторический рекорд</span>
                                                            </a>
                        </div>
                    </div>
                                    <div class="one_str_news">
                                                <div class="data_str_news">10:31
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/city/1201031"><span class="text-normal">Депутат: в Одесской мэрии не знали о долгах тепловиков</span>
                                                            </a>
                        </div>
                    </div>
                                    <div class="one_str_news">
                                                    <div class="photo_str_news">
                                <a href="http://uc.od.ua/news/urbanism/1201030">
                                    <img class="grayscale enlarge" src="http://uc.od.ua/content/documents/12011/1201030/thumb-wide-310x113-9308.jpg"
                                         alt="В Одессе начинают реставрацию дома Маразли (ФОТО)"
                                         height="113"
                                         width="310">
                                </a>
                            </div>
                                                <div class="data_str_news">09:55
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/urbanism/1201030"><span class="text-normal">В Одессе начинают реставрацию дома Маразли (ФОТО)</span>
                                                                    <span class="icon_photo"><i class="fa fa-camera"></i></span>
                                                            </a>
                        </div>
                    </div>
                                    <div class="one_str_news">
                                                    <div class="photo_str_news">
                                <a href="http://uc.od.ua/news/city/1201028">
                                    <img class="grayscale enlarge" src="http://uc.od.ua/content/documents/12011/1201028/thumb-wide-310x113-93ff.jpg"
                                         alt="Одесские фигуристы и хоккеисты получили свой специализированный спортивный центр индивидуальной подготовки"
                                         height="113"
                                         width="310">
                                </a>
                            </div>
                                                <div class="data_str_news">09:19
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/city/1201028"><span class="text-normal">Одесские фигуристы и хоккеисты получили свой специализированный спортивный центр индивидуальной подготовки</span>
                                                                    <span class="icon_photo"><i class="fa fa-camera"></i></span>
                                                            </a>
                        </div>
                    </div>
                                    <div class="one_str_news">
                                                <div class="data_str_news">08:53
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/region/1201027"><span class="text-normal">21 марта синоптики обещают в Одессе и области сильные снегопады</span>
                                                            </a>
                        </div>
                    </div>
                                    <div class="one_str_news">
                                                <div class="data_str_news">19:19
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/city/1201023"><span class="text-normal">Власти Одессы хотят, но не могут выкупить коммунальное имущество у банка</span>
                                                            </a>
                        </div>
                    </div>
                                    <div class="one_str_news">
                                                <div class="data_str_news">18:47
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/city/1201021"><span class="text-normal">Почти 50 миллионов выделят на новую котельную для Шкодовой горы</span>
                                                            </a>
                        </div>
                    </div>
                                    <div class="one_str_news">
                                                <div class="data_str_news">18:20
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/city/1201022"><span class="text-normal">Одесская ТЭЦ перейдет в собственность города?</span>
                                                            </a>
                        </div>
                    </div>
                                    <div class="one_str_news">
                                                <div class="data_str_news">17:50
                                                            <img class="our_mat" src="http://uc.od.ua/images/self-material.png" alt="Собственный материал">
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/columns/1533/1201006"><span style="color: #000000">Турецкий поток идёт под нож</span>
                                                            </a>
                        </div>
                    </div>
                                    <div class="one_str_news">
                                                <div class="data_str_news">17:17
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/culture/1201019"><span class="text-normal">Одесситов ожидает встреча с немецким композитором Берндом Шультайсом</span>
                                                            </a>
                        </div>
                    </div>
                                    <div class="one_str_news">
                                                <div class="data_str_news">16:40
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/region/1201018"><span class="text-normal">Иван Русев обвинил Минэкологии в дезинформации Европы о состоянии заповедной степи в Одесской области</span>
                                                            </a>
                        </div>
                    </div>
                                    <div class="one_str_news">
                                                <div class="data_str_news">16:06
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/crime/1201017"><span class="text-normal">Одну из одесских телекоммуникационных компаний уличили в работе на террористов Донбасса и Россию</span>
                                                            </a>
                        </div>
                    </div>
                                    <div class="one_str_news">
                                                <div class="data_str_news">15:41
                                                            <img class="our_mat" src="http://uc.od.ua/images/self-material.png" alt="Собственный материал">
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/culture/1201014"><span class="text-normal">В обход облсовета: директором Одесского художественного музея назначили Ройтбурда</span>
                                                            </a>
                        </div>
                    </div>
                                    <div class="one_str_news">
                                                <div class="data_str_news">15:05
                                                            <img class="our_mat" src="http://uc.od.ua/images/self-material.png" alt="Собственный материал">
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/columns/1533/1201003"><span style="color: #000000">Африн – наш! Что дальше?</span>
                                                            </a>
                        </div>
                    </div>
                                    <div class="one_str_news">
                                                <div class="data_str_news">14:33
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/railua/1201012"><span class="text-normal">Некоторые поезда из Одессы в апреле будут слегка менять расписание</span>
                                                            </a>
                        </div>
                    </div>
                                    <div class="one_str_news">
                                                    <div class="photo_str_news">
                                <a href="http://uc.od.ua/news/city/1201008">
                                    <img class="grayscale enlarge" src="http://uc.od.ua/content/documents/12011/1201008/thumb-wide-310x113-e680.jpg"
                                         alt="Заснеженная в конце марта Одесса: Аркадия, парки и море"
                                         height="113"
                                         width="310">
                                </a>
                            </div>
                                                <div class="data_str_news">14:03
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/city/1201008"><span class="text-normal">Заснеженная в конце марта Одесса: Аркадия, парки и море</span>
                                                                    <span class="icon_photo"><i class="fa fa-camera"></i></span>
                                                            </a>
                        </div>
                    </div>
                                    <div class="one_str_news">
                                                <div class="data_str_news">13:31
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/city/1201002"><span class="text-normal">Спуски к одесским пляжам обещают осветить в темное время суток</span>
                                                            </a>
                        </div>
                    </div>
                                    <div class="one_str_news">
                                                <div class="data_str_news">13:01
                                                            <img class="our_mat" src="http://uc.od.ua/images/self-material.png" alt="Собственный материал">
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/columns/1533/1200996"><span style="color: #000000">Газовая экспансия США в самом разгаре</span>
                                                            </a>
                        </div>
                    </div>
                                    <div class="one_str_news">
                                                <div class="data_str_news">12:30
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/urbanism/1200989"><span class="text-normal">Одесская ОГА одобрила проект микрорайона без социальной инфраструктуры</span>
                                                            </a>
                        </div>
                    </div>
                                    <div class="one_str_news">
                                                <div class="data_str_news">11:47
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/region/1200999"><span class="text-normal">Мэр Одессы отчитал своего подчиненного за мусор</span>
                                                            </a>
                        </div>
                    </div>
                                    <div class="one_str_news">
                                                <div class="data_str_news">11:11
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/region/1200998"><span class="text-normal">Ненастье оставило без электричества 10 сел в Одесской области</span>
                                                            </a>
                        </div>
                    </div>
                                    <div class="one_str_news">
                                                <div class="data_str_news">10:37
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/busua/1200992"><span class="text-normal">В Белгороде-Днестровском презентовали новые автобусы (ФОТО)</span>
                                                                    <span class="icon_photo"><i class="fa fa-camera"></i></span>
                                                            </a>
                        </div>
                    </div>
                                    <div class="one_str_news">
                                                <div class="data_str_news">10:01
                                                            <img class="our_mat" src="http://uc.od.ua/images/self-material.png" alt="Собственный материал">
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/columns/1533/1200994"><span style="color: #000000">Коротко по выборам в России</span>
                                                            </a>
                        </div>
                    </div>
                                    <div class="one_str_news">
                                                    <div class="photo_str_news">
                                <a href="http://uc.od.ua/news/eltransua/1200990">
                                    <img class="grayscale enlarge" src="http://uc.od.ua/content/documents/12010/1200990/thumb-wide-310x113-9864.jpg"
                                         alt="Фото дня: одесские трамваи в буйстве летней зелени"
                                         height="113"
                                         width="310">
                                </a>
                            </div>
                                                <div class="data_str_news">09:27
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/eltransua/1200990"><span class="text-normal">Фото дня: одесские трамваи в буйстве летней зелени</span>
                                                                    <span class="icon_photo"><i class="fa fa-camera"></i></span>
                                                            </a>
                        </div>
                    </div>
                                    <div class="one_str_news">
                                                <div class="data_str_news">08:56
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/city/1200986"><span class="text-normal">Одесские чиноники говорят о непогоде, бюджете и подготовке к весне (трансляция)</span>
                                                            </a>
                        </div>
                    </div>
                                    <div class="one_str_news">
                                                <div class="data_str_news">07:33
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/dorogi/1200987"><span class="text-normal">Дороги Одесской области доступны для проезда (ВИДЕО)</span>
                                                            </a>
                        </div>
                    </div>
                                    <div class="one_str_news">
                                                    <div class="photo_str_news">
                                <a href="http://uc.od.ua/news/city/1200985">
                                    <img class="grayscale enlarge" src="http://uc.od.ua/content/documents/12010/1200985/thumb-wide-310x113-b1d4.jpg"
                                         alt="У берегов Одессы бушует море (ФОТО, ВИДЕО)"
                                         height="113"
                                         width="310">
                                </a>
                            </div>
                                                <div class="data_str_news">19:56
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/city/1200985"><span class="text-normal">У берегов Одессы бушует море (ФОТО, ВИДЕО)</span>
                                                                    <span class="icon_photo"><i class="fa fa-camera"></i></span>
                                                            </a>
                        </div>
                    </div>
                                    <div class="one_str_news">
                                                <div class="data_str_news">18:08
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/dorogi/1200983"><span class="text-normal">На севере Одесской области затруднено движение по трассе на Киев (ФОТО)</span>
                                                            </a>
                        </div>
                    </div>
                                    <div class="one_str_news">
                                                <div class="data_str_news">17:13
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/crime/1200982"><span class="text-normal">Консульство РФ в Одессе минировали по телефону второй раз</span>
                                                            </a>
                        </div>
                    </div>
                                    <div class="one_str_news">
                                                <div class="data_str_news">15:15
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/urbanism/1200981"><span class="text-normal">На крышах домов на Дерибасовской &quot;поселились&quot; мансарды</span>
                                                            </a>
                        </div>
                    </div>
                                    </div>
        <div class="str_news_naytsikavi j-tab-news-panel">
                                                <div class="one_str_news">
                                                    <div class="photo_str_news">
                                <a href="http://uc.od.ua/news/city/1200618">
                                    <img class="grayscale enlarge"
                                         src="http://uc.od.ua/content/documents/12007/1200618/thumb-wide-310x113-e9d0.jpg"
                                         alt="Одесса выдержала снежную стихию и готовится к следующей (ФОТО)"
                                         height="113"
                                         width="310">
                                </a>
                            </div>
                                                <div class="data_str_news">18:08
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/city/1200618"><span class="text-normal">Одесса выдержала снежную стихию и готовится к следующей (ФОТО)</span>
                                                                                            </a>
                        </div>
                                                    <div class="info">
                                <span class="prosmotry"><i class="fa fa-eye"></i>13449</span>
                            </div>
                                            </div>
                                    <div class="one_str_news">
                                                <div class="data_str_news">09:05
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/city/1200590"><span class="text-normal">Порошенко &quot;имеет виды&quot; на Одессу</span>
                                                                                            </a>
                        </div>
                                                    <div class="info">
                                <span class="prosmotry"><i class="fa fa-eye"></i>6947</span>
                            </div>
                                            </div>
                                    <div class="one_str_news">
                                                <div class="data_str_news">09:05
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/city/1200895"><span class="text-normal">На Одессу идут метели и снегопады</span>
                                                                                            </a>
                        </div>
                                                    <div class="info">
                                <span class="prosmotry"><i class="fa fa-eye"></i>6756</span>
                            </div>
                                            </div>
                                    <div class="one_str_news">
                                                <div class="data_str_news">12:12
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/city/1200487"><span class="text-normal">Завтра на Одессу надвигается снежный циклон</span>
                                                                                            </a>
                        </div>
                                                    <div class="info">
                                <span class="prosmotry"><i class="fa fa-eye"></i>6492</span>
                            </div>
                                            </div>
                                    <div class="one_str_news">
                                                <div class="data_str_news">11:27
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/city/1200465"><span class="text-normal">На Одессу надвигаются сильные морозы</span>
                                                                                            </a>
                        </div>
                                                    <div class="info">
                                <span class="prosmotry"><i class="fa fa-eye"></i>5324</span>
                            </div>
                                            </div>
                                    <div class="one_str_news">
                                                <div class="data_str_news">10:28
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/city/1200477"><span class="text-normal">На время сильных морозов в Одессе отменяют занятия в школах и детских садах</span>
                                                                                            </a>
                        </div>
                                                    <div class="info">
                                <span class="prosmotry"><i class="fa fa-eye"></i>4563</span>
                            </div>
                                            </div>
                                    <div class="one_str_news">
                                                    <div class="photo_str_news">
                                <a href="http://uc.od.ua/news/urbanism/1200466">
                                    <img class="grayscale enlarge"
                                         src="http://uc.od.ua/content/documents/12005/1200466/thumb-wide-310x113-2197.jpg"
                                         alt="Одесская Аркадия пополнится еще одним гигантским небоскребом (ФОТО)"
                                         height="113"
                                         width="310">
                                </a>
                            </div>
                                                <div class="data_str_news">14:16
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/urbanism/1200466"><span class="text-normal">Одесская Аркадия пополнится еще одним гигантским небоскребом (ФОТО)</span>
                                                                                            </a>
                        </div>
                                                    <div class="info">
                                <span class="prosmotry"><i class="fa fa-eye"></i>4075</span>
                            </div>
                                            </div>
                                    <div class="one_str_news">
                                                    <div class="photo_str_news">
                                <a href="http://uc.od.ua/news/urbanism/1200456">
                                    <img class="grayscale enlarge"
                                         src="http://uc.od.ua/content/documents/12005/1200456/thumb-wide-310x113-9867.jpg"
                                         alt="Зимняя Одесса со стометровой высоты: снег, море, высотки и санатории (ФОТО, ВИДЕО)"
                                         height="113"
                                         width="310">
                                </a>
                            </div>
                                                <div class="data_str_news">00:03
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/urbanism/1200456"><span class="text-normal">Зимняя Одесса со стометровой высоты: снег, море, высотки и санатории (ФОТО, ВИДЕО)</span>
                                                                                            </a>
                        </div>
                                                    <div class="info">
                                <span class="prosmotry"><i class="fa fa-eye"></i>2871</span>
                            </div>
                                            </div>
                                    <div class="one_str_news">
                                                    <div class="photo_str_news">
                                <a href="http://uc.od.ua/news/city/1200380">
                                    <img class="grayscale enlarge"
                                         src="http://uc.od.ua/content/documents/12004/1200380/thumb-wide-310x113-e06f.jpg"
                                         alt="На одесском пляже возводят гигантскую летнюю площадку (ФОТО)"
                                         height="113"
                                         width="310">
                                </a>
                            </div>
                                                <div class="data_str_news">15:19
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/city/1200380"><span class="text-normal">На одесском пляже возводят гигантскую летнюю площадку (ФОТО)</span>
                                                                                            </a>
                        </div>
                                                    <div class="info">
                                <span class="prosmotry"><i class="fa fa-eye"></i>2595</span>
                            </div>
                                            </div>
                                    <div class="one_str_news">
                                                <div class="data_str_news">08:56
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/urbanism/1200385"><span class="text-normal">Сколько стоит квартира в Одессе (инфографика)</span>
                                                                                            </a>
                        </div>
                                                    <div class="info">
                                <span class="prosmotry"><i class="fa fa-eye"></i>2429</span>
                            </div>
                                            </div>
                                    <div class="one_str_news">
                                                <div class="data_str_news">18:05
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/region/1200666"><span style="color: #000000">Одесские школьники начнут учиться уже в понедельник 5 марта (ОБНОВЛЕНО)</span>
                                                                                            </a>
                        </div>
                                                    <div class="info">
                                <span class="prosmotry"><i class="fa fa-eye"></i>2398</span>
                            </div>
                                            </div>
                                    <div class="one_str_news">
                                                    <div class="photo_str_news">
                                <a href="http://uc.od.ua/news/city/1200985">
                                    <img class="grayscale enlarge"
                                         src="http://uc.od.ua/content/documents/12010/1200985/thumb-wide-310x113-b1d4.jpg"
                                         alt="У берегов Одессы бушует море (ФОТО, ВИДЕО)"
                                         height="113"
                                         width="310">
                                </a>
                            </div>
                                                <div class="data_str_news">19:56
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/city/1200985"><span class="text-normal">У берегов Одессы бушует море (ФОТО, ВИДЕО)</span>
                                                                                            </a>
                        </div>
                                                    <div class="info">
                                <span class="prosmotry"><i class="fa fa-eye"></i>2367</span>
                            </div>
                                            </div>
                                    <div class="one_str_news">
                                                <div class="data_str_news">12:30
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/region/1200643"><span class="text-normal">Школы Одесской области могут продлить выходные до 6 марта включительно</span>
                                                                                            </a>
                        </div>
                                                    <div class="info">
                                <span class="prosmotry"><i class="fa fa-eye"></i>2304</span>
                            </div>
                                            </div>
                                    <div class="one_str_news">
                                                    <div class="photo_str_news">
                                <a href="http://uc.od.ua/news/city/1200575">
                                    <img class="grayscale enlarge"
                                         src="http://uc.od.ua/content/documents/12006/1200575/thumb-wide-310x113-7f49.jpg"
                                         alt="На одесском морском вокзале бушует метель"
                                         height="113"
                                         width="310">
                                </a>
                            </div>
                                                <div class="data_str_news">18:48
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/city/1200575"><span class="text-normal">На одесском морском вокзале бушует метель</span>
                                                                                            </a>
                        </div>
                                                    <div class="info">
                                <span class="prosmotry"><i class="fa fa-eye"></i>2287</span>
                            </div>
                                            </div>
                                    <div class="one_str_news">
                                                    <div class="photo_str_news">
                                <a href="http://uc.od.ua/news/city/1200583">
                                    <img class="grayscale enlarge"
                                         src="http://uc.od.ua/content/documents/12006/1200583/thumb-wide-310x113-2402.jpg"
                                         alt="Одессу накрыла метель: пустые улицы, котики и огромные сугробы"
                                         height="113"
                                         width="310">
                                </a>
                            </div>
                                                <div class="data_str_news">20:13
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/city/1200583"><span class="text-normal">Одессу накрыла метель: пустые улицы, котики и огромные сугробы</span>
                                                                                            </a>
                        </div>
                                                    <div class="info">
                                <span class="prosmotry"><i class="fa fa-eye"></i>2216</span>
                            </div>
                                            </div>
                                    <div class="one_str_news">
                                                <div class="data_str_news">12:22
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/region/1200605"><span class="text-normal">Американский инвестор уничтожает населенный пункт в Лиманском районе</span>
                                                                                            </a>
                        </div>
                                                    <div class="info">
                                <span class="prosmotry"><i class="fa fa-eye"></i>2089</span>
                            </div>
                                            </div>
                                    <div class="one_str_news">
                                                <div class="data_str_news">12:43
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/city/1200610"><span class="text-normal">Маленькие одесситы пойдут в школу аж в понедельник 5 марта</span>
                                                                                            </a>
                        </div>
                                                    <div class="info">
                                <span class="prosmotry"><i class="fa fa-eye"></i>2087</span>
                            </div>
                                            </div>
                                    <div class="one_str_news">
                                                    <div class="photo_str_news">
                                <a href="http://uc.od.ua/news/city/1200656">
                                    <img class="grayscale enlarge"
                                         src="http://uc.od.ua/content/documents/12007/1200656/thumb-wide-310x113-f42a.jpg"
                                         alt="Красота зимних пляжей Одессы: Ланжерон и Отрада во льдах (ФОТО)"
                                         height="113"
                                         width="310">
                                </a>
                            </div>
                                                <div class="data_str_news">18:35
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/city/1200656"><span class="text-normal">Красота зимних пляжей Одессы: Ланжерон и Отрада во льдах (ФОТО)</span>
                                                                                            </a>
                        </div>
                                                    <div class="info">
                                <span class="prosmotry"><i class="fa fa-eye"></i>1955</span>
                            </div>
                                            </div>
                                    <div class="one_str_news">
                                                    <div class="photo_str_news">
                                <a href="http://uc.od.ua/news/region/1200299">
                                    <img class="grayscale enlarge"
                                         src="http://uc.od.ua/content/documents/12003/1200299/thumb-wide-310x113-27f9.jpg"
                                         alt="Зимняя сказка украинских Карпат глазами одессита (ФОТО)"
                                         height="113"
                                         width="310">
                                </a>
                            </div>
                                                <div class="data_str_news">21:33
                                                            <img class="our_mat" src="http://uc.od.ua/images/self-material.png" alt="Собственный материал">
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/region/1200299"><span class="text-normal">Зимняя сказка украинских Карпат глазами одессита (ФОТО)</span>
                                                                                            </a>
                        </div>
                                                    <div class="info">
                                <span class="prosmotry"><i class="fa fa-eye"></i>1948</span>
                            </div>
                                            </div>
                                    <div class="one_str_news">
                                                    <div class="photo_str_news">
                                <a href="http://uc.od.ua/news/urbanism/1200349">
                                    <img class="grayscale enlarge"
                                         src="http://uc.od.ua/content/documents/12004/1200349/thumb-wide-310x113-fcb2.jpg"
                                         alt="Как в Одессе ремонтируют забор, построенный из старинных пушек (ФОТО)"
                                         height="113"
                                         width="310">
                                </a>
                            </div>
                                                <div class="data_str_news">09:11
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/urbanism/1200349"><span class="text-normal">Как в Одессе ремонтируют забор, построенный из старинных пушек (ФОТО)</span>
                                                                                            </a>
                        </div>
                                                    <div class="info">
                                <span class="prosmotry"><i class="fa fa-eye"></i>1944</span>
                            </div>
                                            </div>
                                    <div class="one_str_news">
                                                <div class="data_str_news">17:23
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/city/1200530"><span class="text-normal">Суд решил оставить Труханова мэром Одессы</span>
                                                                                            </a>
                        </div>
                                                    <div class="info">
                                <span class="prosmotry"><i class="fa fa-eye"></i>1917</span>
                            </div>
                                            </div>
                                    <div class="one_str_news">
                                                <div class="data_str_news">09:26
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/crime/1200425"><span class="text-normal">Захват одесского санатория: вооруженные люди не пускали начальника полиции (ФОТО, ВИДЕО)</span>
                                                                                            </a>
                        </div>
                                                    <div class="info">
                                <span class="prosmotry"><i class="fa fa-eye"></i>1890</span>
                            </div>
                                            </div>
                                    <div class="one_str_news">
                                                    <div class="photo_str_news">
                                <a href="http://uc.od.ua/news/city/1200525">
                                    <img class="grayscale enlarge"
                                         src="http://uc.od.ua/content/documents/12006/1200525/thumb-wide-310x113-daee.jpg"
                                         alt="В Одессе море штормит, а пляжи заледенели (ФОТО)"
                                         height="113"
                                         width="310">
                                </a>
                            </div>
                                                <div class="data_str_news">14:30
                                                            <img class="our_mat" src="http://uc.od.ua/images/self-material.png" alt="Собственный материал">
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/city/1200525"><span class="text-normal">В Одессе море штормит, а пляжи заледенели (ФОТО)</span>
                                                                                            </a>
                        </div>
                                                    <div class="info">
                                <span class="prosmotry"><i class="fa fa-eye"></i>1852</span>
                            </div>
                                            </div>
                                    <div class="one_str_news">
                                                    <div class="photo_str_news">
                                <a href="http://uc.od.ua/news/city/1200464">
                                    <img class="grayscale enlarge"
                                         src="http://uc.od.ua/content/documents/12005/1200464/thumb-wide-310x113-ba23.jpg"
                                         alt="Одесса под снегом (ФОТО)"
                                         height="113"
                                         width="310">
                                </a>
                            </div>
                                                <div class="data_str_news">22:05
                                                            <img class="our_mat" src="http://uc.od.ua/images/self-material.png" alt="Собственный материал">
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/city/1200464"><span class="text-normal">Одесса под снегом (ФОТО)</span>
                                                                                            </a>
                        </div>
                                                    <div class="info">
                                <span class="prosmotry"><i class="fa fa-eye"></i>1788</span>
                            </div>
                                            </div>
                                    <div class="one_str_news">
                                                <div class="data_str_news">13:40
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/city/1200843"><span class="text-normal">Активисты попытаются сорвать выборы Путина в Одессе</span>
                                                                                            </a>
                        </div>
                                                    <div class="info">
                                <span class="prosmotry"><i class="fa fa-eye"></i>1767</span>
                            </div>
                                            </div>
                                    <div class="one_str_news">
                                                <div class="data_str_news">10:30
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/city/1200663"><span class="text-normal">Над ректором Одесского медицинского университета сгустились тучи</span>
                                                                                            </a>
                        </div>
                                                    <div class="info">
                                <span class="prosmotry"><i class="fa fa-eye"></i>1534</span>
                            </div>
                                            </div>
                                    <div class="one_str_news">
                                                    <div class="photo_str_news">
                                <a href="http://uc.od.ua/news/city/1200570">
                                    <img class="grayscale enlarge"
                                         src="http://uc.od.ua/content/documents/12006/1200570/thumb-wide-310x113-5546.jpg"
                                         alt="Как одесситы развлекаются в парке Победы"
                                         height="113"
                                         width="310">
                                </a>
                            </div>
                                                <div class="data_str_news">17:02
                                                            <img class="our_mat" src="http://uc.od.ua/images/self-material.png" alt="Собственный материал">
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/city/1200570"><span class="text-normal">Как одесситы развлекаются в парке Победы</span>
                                                                                            </a>
                        </div>
                                                    <div class="info">
                                <span class="prosmotry"><i class="fa fa-eye"></i>1460</span>
                            </div>
                                            </div>
                                    <div class="one_str_news">
                                                <div class="data_str_news">17:12
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/city/1200398"><span class="text-normal">В Одессе открылась школа отельно-ресторанного сервиса (ФОТО)</span>
                                                                                            </a>
                        </div>
                                                    <div class="info">
                                <span class="prosmotry"><i class="fa fa-eye"></i>1443</span>
                            </div>
                                            </div>
                                    <div class="one_str_news">
                                                <div class="data_str_news">15:15
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/city/1200881"><span class="text-normal">В Одессе продают высотное здание обанкротившегося банка</span>
                                                                                            </a>
                        </div>
                                                    <div class="info">
                                <span class="prosmotry"><i class="fa fa-eye"></i>1428</span>
                            </div>
                                            </div>
                                    <div class="one_str_news">
                                                <div class="data_str_news">12:21
                                                    </div>
                        <div class="text_str_news">
                            <a href="http://uc.od.ua/news/politic/1200780"><span class="text-normal">Саакашвили нацелился на кабинет Труханова: когда-нибудь потом</span>
                                                                                            </a>
                        </div>
                                                    <div class="info">
                                <span class="prosmotry"><i class="fa fa-eye"></i>1419</span>
                            </div>
                                            </div>
                                    </div>

        <div class="button_bilshe clearfix">
            <a class="to_arhive" href="http://uc.od.ua/news">
                <span class="data">Больше новостей</span>
                <span class="next"><i class="fa fa-long-arrow-right"></i></span>
            </a>
        </div>

    </div>
</div>


    <div class="col_center_wrap">
        <div class="col_center">
            <div class="raw_anons">
                                <div class="wrap_column_anons column2">
                    <div class="column_anons_background">
                        <div class="inner_background"></div>
                    </div>
                    <div class="column_anons">
                        <div class="wrap_img">
                                                            <a href="http://uc.od.ua/columns/1533/1200994">
                                    <img class="grayscale" src="http://uc.od.ua/content/documents/12010/1200994/thumb-list-298x193-c4aa.jpg"
                                         alt="Коротко по выборам в России"
                                         height="193"
                                         width="298">
                                </a>
                                                        <div class="icon">
                                                            </div>
                        </div>
                        <div class="wr_anons">
                            <div class="data_anons"></div>
                            <div class="head_anons">
                                <a href="http://uc.od.ua/columns/1533/1200994">Коротко по выборам в России</a>
                            </div>
                            <div class="text_anons">В России состоялся фарс, именуемый “президентские выборы”.</div>
                            <div class="info">
                                                                    <i class="fa fa-circle bordo"></i>
                                    <span class="nadiyne">надежный источник</span>
                                    &nbsp;&nbsp;
                                    <span class="vertical_razd">|</span>
                                    &nbsp;
                                                                <span class="Rubrika"><a
                                            href="http://uc.od.ua/columns/1533">Zloy Odessit</a></span>
                                <span class="Koly">
                                                Вчера
                                                                    </span>
                                                                    <span class="prosmotry"><i class="fa fa-eye"></i>1278</span>
                                                            </div>
                        </div>
                    </div>
                </div>
                                                <div class="wrap_column_anons column2">
                    <div class="column_anons_background">
                        <div class="inner_background"></div>
                    </div>
                    <div class="column_anons">
                        <div class="wrap_img">
                                                            <a href="http://uc.od.ua/news/crime/1200978">
                                    <img class="grayscale" src="http://uc.od.ua/content/documents/12010/1200978/thumb-list-298x193-7f53.jpg"
                                         alt="Утро воскресенья в Одессе началось с минирования российского консульства"
                                         height="193"
                                         width="298">
                                </a>
                                                        <div class="icon">
                                                                    <span class="icon_photo"><i class="fa fa-camera"></i></span>
                                                            </div>
                        </div>
                        <div class="wr_anons">
                            <div class="data_anons"></div>
                            <div class="head_anons">
                                <a href="http://uc.od.ua/news/crime/1200978">Утро воскресенья в Одессе началось с минирования российского консульства</a>
                            </div>
                            <div class="text_anons">Сегодня, 18 марта, в день проведения выборов президента России в одесское управление полиции поступил анонимный звонок о &quot;минировании&quot; генконсульства РФ. Об этом сообщила пресс-служба полиции Одесской области.</div>
                            <div class="info">
                                                                <span class="Rubrika"><a
                                            href="http://uc.od.ua/news/crime">Происшествия</a></span>
                                <span class="Koly">
                                                2 дня назад
                                                                    </span>
                                                                    <span class="prosmotry"><i class="fa fa-eye"></i>632</span>
                                                            </div>
                        </div>
                    </div>
                </div>
                            </div>
            <div class="raw_anons">
                                                <div class="wrap_column_anons column3">
                    <div class="column_anons_background">
                        <div class="inner_background"></div>
                    </div>
                    <div class="column_anons">
                        <div class="wrap_img">
                                                            <a href="http://uc.od.ua/news/urbanism/1200969">
                                    <img class="grayscale" src="http://uc.od.ua/content/documents/12010/1200969/thumb-list-298x193-a6b4.jpg"
                                         alt="Новые скульптуры: коты для Одессы больше чем коты (ФОТО)"
                                         height="193"
                                         width="298">
                                </a>
                                                        <div class="icon">
                                                            </div>
                        </div>
                        <div class="wr_anons">
                            <div class="data_anons"></div>
                            <div class="head_anons">
                                <a href="http://uc.od.ua/news/urbanism/1200969">Новые скульптуры: коты для Одессы больше чем коты (ФОТО)</a>
                            </div>
                            <div class="text_anons">Коты для одесситов больше, чем коты. И это отражается в &quot;кошачьих&quot; скульптурах по всему городу.</div>
                            <div class="info">
                                                                <span class="Rubrika"><a
                                            href="http://uc.od.ua/news/urbanism">Урбанистика </a></span>
                                <span class="Koly">
                                                3 дня назад
                                                                    </span>
                                                                    <span class="prosmotry"><i class="fa fa-eye"></i>630</span>
                                                            </div>
                        </div>
                    </div>
                </div>
                                                <div class="wrap_column_anons column3">
                    <div class="column_anons_background">
                        <div class="inner_background"></div>
                    </div>
                    <div class="column_anons">
                        <div class="wrap_img">
                                                            <a href="http://uc.od.ua/news/city/1200963">
                                    <img class="grayscale" src="http://uc.od.ua/content/documents/12010/1200963/thumb-list-298x193-2315.jpg"
                                         alt="Мэр отчитался перед одесситами: как это было (ФОТО)"
                                         height="193"
                                         width="298">
                                </a>
                                                        <div class="icon">
                                                                    <span class="icon_photo"><i class="fa fa-camera"></i></span>
                                                            </div>
                        </div>
                        <div class="wr_anons">
                            <div class="data_anons"></div>
                            <div class="head_anons">
                                <a href="http://uc.od.ua/news/city/1200963">Мэр отчитался перед одесситами: как это было (ФОТО)</a>
                            </div>
                            <div class="text_anons">Как проходил отчёт городского головы Геннадия Труханова перед одесситами за проделанную в 2017 году работу. Публикуем подробный фоторепортаж</div>
                            <div class="info">
                                                                <span class="Rubrika"><a
                                            href="http://uc.od.ua/news/city">Город</a></span>
                                <span class="Koly">
                                                3 дня назад
                                                                    </span>
                                                                    <span class="prosmotry"><i class="fa fa-eye"></i>357</span>
                                                            </div>
                        </div>
                    </div>
                </div>
                                                <div class="wrap_column_anons column3">
                    <div class="column_anons_background">
                        <div class="inner_background"></div>
                    </div>
                    <div class="column_anons">
                        <div class="wrap_img">
                                                            <a href="http://uc.od.ua/news/urbanism/1200918">
                                    <img class="grayscale" src="http://uc.od.ua/content/documents/12010/1200918/thumb-list-298x193-df07.jpg"
                                         alt="Восстановлением дома Руссова победитель тендера заниматься не хочет"
                                         height="193"
                                         width="298">
                                </a>
                                                        <div class="icon">
                                                            </div>
                        </div>
                        <div class="wr_anons">
                            <div class="data_anons"></div>
                            <div class="head_anons">
                                <a href="http://uc.od.ua/news/urbanism/1200918">Восстановлением дома Руссова победитель тендера заниматься не хочет</a>
                            </div>
                            <div class="text_anons">Партнёр Руслана Тарпана. победивший в тендере, отказался реставрировать дом Руссова. В связи с этим, ремонт подорожал на 26 миллионов</div>
                            <div class="info">
                                                                <span class="Rubrika"><a
                                            href="http://uc.od.ua/news/urbanism">Урбанистика </a></span>
                                <span class="Koly">
                                                4 дня назад
                                                                    </span>
                                                                    <span class="prosmotry"><i class="fa fa-eye"></i>617</span>
                                                            </div>
                        </div>
                    </div>
                </div>
                            </div>
            <div class="raw_anons">
                                                <div class="wrap_column_anons column2">
                    <div class="column_anons_background">
                        <div class="inner_background"></div>
                    </div>
                    <div class="column_anons">
                        <div class="wrap_img">
                                                            <a href="http://uc.od.ua/columns/1533/1200900">
                                    <img class="grayscale" src="http://uc.od.ua/content/documents/12009/1200900/thumb-list-298x193-32d7.jpg"
                                         alt="Мэй против Путина или начало Крестового похода туманного Альбиона"
                                         height="193"
                                         width="298">
                                </a>
                                                        <div class="icon">
                                                            </div>
                        </div>
                        <div class="wr_anons">
                            <div class="data_anons"></div>
                            <div class="head_anons">
                                <a href="http://uc.od.ua/columns/1533/1200900">Мэй против Путина или начало Крестового похода туманного Альбиона</a>
                            </div>
                            <div class="text_anons">Вчера начался новый этап прессинга мировым сообществом России, что не сулит в этом году ей избавления от позорного титула страны-изгоя. </div>
                            <div class="info">
                                                                    <i class="fa fa-circle bordo"></i>
                                    <span class="nadiyne">надежный источник</span>
                                    &nbsp;&nbsp;
                                    <span class="vertical_razd">|</span>
                                    &nbsp;
                                                                <span class="Rubrika"><a
                                            href="http://uc.od.ua/columns/1533">Zloy Odessit</a></span>
                                <span class="Koly">
                                                5 дней назад
                                                                    </span>
                                                                    <span class="prosmotry"><i class="fa fa-eye"></i>924</span>
                                                            </div>
                        </div>
                    </div>
                </div>
                                                <div class="wrap_column_anons column2">
                    <div class="column_anons_background">
                        <div class="inner_background"></div>
                    </div>
                    <div class="column_anons">
                        <div class="wrap_img">
                                                            <a href="http://uc.od.ua/news/urbanism/1200892">
                                    <img class="grayscale" src="http://uc.od.ua/content/documents/12009/1200892/thumb-list-298x193-ada6.jpg"
                                         alt="В центре Одессы сносят здания Чайной фабрики (ФОТО, ВИДЕО)"
                                         height="193"
                                         width="298">
                                </a>
                                                        <div class="icon">
                                                                    <span class="icon_photo"><i class="fa fa-camera"></i></span>
                                                            </div>
                        </div>
                        <div class="wr_anons">
                            <div class="data_anons"></div>
                            <div class="head_anons">
                                <a href="http://uc.od.ua/news/urbanism/1200892">В центре Одессы сносят здания Чайной фабрики (ФОТО, ВИДЕО)</a>
                            </div>
                            <div class="text_anons">На улице Карантинной начали сносить здание бывшей чайной фабрики. На их месте вырастет новый квартал жилых домов.</div>
                            <div class="info">
                                                                <span class="Rubrika"><a
                                            href="http://uc.od.ua/news/urbanism">Урбанистика </a></span>
                                <span class="Koly">
                                                5 дней назад
                                                                    </span>
                                                                    <span class="prosmotry"><i class="fa fa-eye"></i>784</span>
                                                            </div>
                        </div>
                    </div>
                </div>
                            </div>
            <div class="raw_anons">
                                                <div class="wrap_column_anons column2">
                    <div class="column_anons_background">
                        <div class="inner_background"></div>
                    </div>
                    <div class="column_anons">
                        <div class="wrap_img">
                                                            <a href="http://uc.od.ua/news/culture/1200878">
                                    <img class="grayscale" src="http://uc.od.ua/content/documents/12009/1200878/thumb-list-298x193-3fad.jpg"
                                         alt="Одесский облсовет не смог утвердить скандального художника директором музея"
                                         height="193"
                                         width="298">
                                </a>
                                                        <div class="icon">
                                                            </div>
                        </div>
                        <div class="wr_anons">
                            <div class="data_anons"></div>
                            <div class="head_anons">
                                <a href="http://uc.od.ua/news/culture/1200878">Одесский облсовет не смог утвердить скандального художника директором музея</a>
                            </div>
                            <div class="text_anons">На сегодняшней сессии областного совета депутаты не смогли утвердить выигравшего конкурс на должность директора Художественного музея Александра Ройтбурда - художника с неоднозначной репутацией и огромным количеством противников.</div>
                            <div class="info">
                                                                <span class="Rubrika"><a
                                            href="http://uc.od.ua/news/culture">Культура</a></span>
                                <span class="Koly">
                                                5 дней назад
                                                                    </span>
                                                                    <span class="prosmotry"><i class="fa fa-eye"></i>484</span>
                                                            </div>
                        </div>
                    </div>
                </div>
                                                <div class="wrap_column_anons column2">
                    <div class="column_anons_background">
                        <div class="inner_background"></div>
                    </div>
                    <div class="column_anons">
                        <div class="wrap_img">
                                                            <a href="http://uc.od.ua/news/region/1200859">
                                    <img class="grayscale" src="http://uc.od.ua/content/documents/12009/1200859/thumb-list-298x193-cc28.jpg"
                                         alt="Одесский облсовет собрался на первую сессию 2018 года (трансляция)"
                                         height="193"
                                         width="298">
                                </a>
                                                        <div class="icon">
                                                            </div>
                        </div>
                        <div class="wr_anons">
                            <div class="data_anons"></div>
                            <div class="head_anons">
                                <a href="http://uc.od.ua/news/region/1200859">Одесский облсовет собрался на первую сессию 2018 года (трансляция)</a>
                            </div>
                            <div class="text_anons">14 марта в Одессе проходит сессия областного совета, первая в нынешнем году. Южный Курьер ведет прямую трансляцию.</div>
                            <div class="info">
                                                                <span class="Rubrika"><a
                                            href="http://uc.od.ua/news/region">Регион</a></span>
                                <span class="Koly">
                                                6 дней назад
                                                                    </span>
                                                                    <span class="prosmotry"><i class="fa fa-eye"></i>426</span>
                                                            </div>
                        </div>
                    </div>
                </div>
                                            </div>
        </div>
    </div>

                        </div>
                    </div>
                    <div class="col_sidebar_wrap">
                        <div class="col_sidebar grayscale">
                                <div class="widget_wrap"><a href="http://uc.od.ua/bmg/3khk3p5a"><img src="http://uc.od.ua/content/bmg/b6-h9ecd3h5em-240x350.gif" border="0" width="240" height="350" alt=""></a></div>

            <div class="widget_wrap">
        <div class="blogs-left">
            <div class="blogs-left__head"><a href="http://uc.od.ua/columns">Блоги</a></div>
            <a href="http://uc.od.ua/columns/1533" class="blogs-left__link">
                                    <img src="http://uc.od.ua/content/folders/1533/69267020-bloger-80x80.png" alt="Zloy Odessit"
                         width="80">
                                <div class="blogs-left__name">Zloy Odessit</div>
            </a>
            <div class="blogs-left__descr"><a href="http://uc.od.ua/columns/1533/1201032"
                                              class="blogs-left__link">Долги "Роснефти" поставили исторический рекорд</a></div>
        </div>
    </div>








    <div class="widget_wrap budmo_wrap">
        <div class="budmo_rubrika"><a href="http://uc.od.ua/photo">Фоторепортажи</a></div>
        <div class="fotopoglyad">
            <div class="inner_slider block-photo-slider">
                <ul id="photo-slider">
                                                                                                <li>
                                <a href="http://uc.od.ua/news/city/1201008">
                                    <img class="grayscale" src="http://uc.od.ua/content/documents/12011/1201008/thumb-list-298x193-8779.jpg"
                                         alt="Заснеженная в конце марта Одесса: Аркадия и море (ФОТО)"
                                         height="193"
                                         width="298">
                                    <div class="text_slider"><h2 class="fixed-heigth">Заснеженная в конце марта Одесса: Аркадия и море (ФОТО)</h2>
                                    </div>
                                </a>
                            </li>
                                                                                                                        <li>
                                <a href="http://uc.od.ua/news/city/1200985">
                                    <img class="grayscale" src="http://uc.od.ua/content/documents/12010/1200985/thumb-list-298x193-c7ff.jpg"
                                         alt="У берегов Одессы бушует море (ФОТО, ВИДЕО)"
                                         height="193"
                                         width="298">
                                    <div class="text_slider"><h2 class="fixed-heigth">У берегов Одессы бушует море (ФОТО, ВИДЕО)</h2>
                                    </div>
                                </a>
                            </li>
                                                                                                                        <li>
                                <a href="http://uc.od.ua/news/city/1200970">
                                    <img class="grayscale" src="http://uc.od.ua/content/documents/12010/1200970/thumb-list-298x193-96c9.jpg"
                                         alt="В Одессе отметили самый ирландский празник - день святого Патрика (ФОТО, ВИДЕО)"
                                         height="193"
                                         width="298">
                                    <div class="text_slider"><h2 class="fixed-heigth">В Одессе отметили самый ирландский празник - день святого Патрика (ФОТО, ВИДЕО)</h2>
                                    </div>
                                </a>
                            </li>
                                                                                                                        <li>
                                <a href="http://uc.od.ua/news/culture/1200857">
                                    <img class="grayscale" src="http://uc.od.ua/content/documents/12009/1200857/thumb-list-298x193-e255.jpg"
                                         alt="&quot;Любовь&quot; советского периода по &quot;Квадратуре круга&quot;: как это делали в Одессе (ФОТО)"
                                         height="193"
                                         width="298">
                                    <div class="text_slider"><h2 class="fixed-heigth">&quot;Любовь&quot; советского периода по &quot;Квадратуре круга&quot;: как это делали в Одессе (ФОТО)</h2>
                                    </div>
                                </a>
                            </li>
                                                                                                                        <li>
                                <a href="http://uc.od.ua/news/city/1200786">
                                    <img class="grayscale" src="http://uc.od.ua/content/documents/12008/1200786/thumb-list-298x193-a510.jpg"
                                         alt="Одесское побережье целый день укрывает туман (ФОТО)"
                                         height="193"
                                         width="298">
                                    <div class="text_slider"><h2 class="fixed-heigth">Одесское побережье целый день укрывает туман (ФОТО)</h2>
                                    </div>
                                </a>
                            </li>
                                                                                                                        <li>
                                <a href="http://uc.od.ua/news/city/1200664">
                                    <img class="grayscale" src="http://uc.od.ua/content/documents/12007/1200664/thumb-list-298x193-dcf5.jpg"
                                         alt="Юбилей Одесской области отметили многонациональной ярмаркой (ФОТО)"
                                         height="193"
                                         width="298">
                                    <div class="text_slider"><h2 class="fixed-heigth">Юбилей Одесской области отметили многонациональной ярмаркой (ФОТО)</h2>
                                    </div>
                                </a>
                            </li>
                                                            </ul>
            </div>
        </div>
    </div>







    <div class="widget_wrap social">
        
        <div class="budmo_rubrika j-tab-soc">
                            <a href="#" class="active">Facebook</a>
                                        <a href="#">ВКонтакте</a>
                                </div>
                    <div class="tab-soc-panel j-tab-soc-panel active">
                <iframe src="//www.facebook.com/plugins/likebox.php?href=https%3A%2F%2Fwww.facebook.com%2FYuzhnyjCourier&amp;width&amp;height=350&amp;colorscheme=light&amp;show_faces=true&amp;header=false&amp;stream=false&amp;show_border=true" scrolling="no" frameborder="0" style="border:none; overflow:hidden; height:270px;" allowTransparency="true"></iframe>
            </div>
                            <div class="tab-soc-panel j-tab-soc-panel">
                <script type="text/javascript" src="http://userapi.com/js/api/openapi.js?48"></script>
<div id="vk_groups"></div>
<script type="text/javascript">
    VK.Widgets.Group("vk_groups", {mode: 0, width: "300", height: "350"}, 35987993);
</script>
            </div>
                    </div>



    <!-- links will appear here -->

<script async="async" src="https://w.uptolike.com/widgets/v1/zp.js?pid=1326777" type="text/javascript"></script>
<script type="text/javascript">
<!--
var _acic={dataProvider:10};(function(){var e=document.createElement("script");e.type="text/javascript";e.async=true;e.src="//www.acint.net/aci.js";var t=document.getElementsByTagName("script")[0];t.parentNode.insertBefore(e,t)})()
//-->
</script>



                        </div>
                    </div>
                            </div>
        </div>
    </div>
</div>
</div>
<div id="footer" class="footer">
    <div class="footer_inner">
        <div class="nav_layout">
            <ul class="footer_main_menu">
                
                                    <li><a href="http://uc.od.ua/news">Новости</a></li>
                                    <li><a href="http://uc.od.ua/975">Досье</a></li>
                                    <li><a href="http://uc.od.ua/tema">Темы</a></li>
                                    <li><a href="http://uc.od.ua/photo">Фоторепортажи</a></li>
                                    <li><a href="http://uc.od.ua/columns">Блоги</a></li>
                            </ul>
            <ul class="footer_dop_menu">
                <li><a href="http://uc.od.ua/reklama/reklama.html">Реклама</a></li>
                <li><a href="http://uc.od.ua/reklama/editorialoffice.html">Редакция</a></li>
            </ul>
        </div>
        <div class="footer_layout">
                            <div class="footer_info">
                                        Новости Одессы. Copyright © 2011—2018 Южный Курьер<br />
Все права защищены.<br />
При полном или частичном использовании материалов<br />
сайта, ссылка на uc.od.ua обязательна.
                </div>
                        <div class="footer_social">
                <div class="social_info">Мы в социальных сетях:</div>
                <div class="header_social">
                    <a class="face" href="https://www.facebook.com/YuzhnyjCourier" target="_blank"
                                                   rel="nofollow" title="Facebook"><i class="fa fa-facebook"></i>
                        </a>                                        <a class="face" href="https://twitter.com/KaiserOdessa" target="_blank"
                                                   rel="nofollow" title="Twitter"><i class="fa fa-twitter"></i>
                        </a>                    <a class="face" href="https://www.youtube.com/channel/UCdg5P2bOBS1FymwMxudDTHQ" target="_blank"
                                                   rel="nofollow" title="Youtube"><i class="fa fa-youtube"></i>
                        </a>                </div>
            </div>
            <div id="back-top" class="back-top fa fa-arrow-up"></div>
        </div>
    </div>
</div>

<script type="text/javascript" src="http://uc.od.ua/extras/jquery/jquery.min.js"></script>
<script type="text/javascript" src="http://uc.od.ua/js/bxslider/jquery.bxslider.min.js"></script>
<script type="text/javascript" src="http://uc.od.ua/js/wucmf.min.js?3"></script>
<script type='text/javascript'>
    var wucmf = new WUCMF({
        selfPath: 'http://uc.od.ua',
        pathImg: 'http://uc.od.ua/images/',
        pathJs: 'http://uc.od.ua/js/',
        page: '',
        isMain: true,
        isGallery: false,
        monthesB: {"01":"\u042f\u043d\u0432\u0430\u0440\u044c","02":"\u0424\u0435\u0432\u0440\u0430\u043b\u044c","03":"\u041c\u0430\u0440\u0442","04":"\u0410\u043f\u0440\u0435\u043b\u044c","05":"\u041c\u0430\u0439","06":"\u0418\u044e\u043d\u044c","07":"\u0418\u044e\u043b\u044c","08":"\u0410\u0432\u0433\u0443\u0441\u0442","09":"\u0421\u0435\u043d\u0442\u044f\u0431\u0440\u044c","10":"\u041e\u043a\u0442\u044f\u0431\u0440\u044c","11":"\u041d\u043e\u044f\u0431\u0440\u044c","12":"\u0414\u0435\u043a\u0430\u0431\u0440\u044c"}
    });
</script>



</body>
</html>