 <!DOCTYPE HTML>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://ogp.me/ns/fb#" xmlns:og="http://ogp.me/ns#" xmlns:fb="http://www.facebook.com/2008/fbml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta http-equiv="content-language" content="el_GR">
<title>Whocallsme.gr, αντίστροφη αναζήτηση αριθμού τηλεφώνου</title>
<base href="http://www.whocallsme.gr/" target="_self" />
<META HTTP-EQUIV="CACHE-CONTROL" CONTENT="Public">
<META NAME="ROBOTS" CONTENT="ALL">
<meta name="description" content="Εύκολος, γρήγορος και πρακτικός τρόπος αναζήτησης και καταγραφής τηλεφωνικών αριθμών από χρήστες. Λάβατε μια  παράξενη  ή ενοχλητική κλήση, ένα  ανεπιθύμητο μήνυμα (SMS)  ή απλά σας κάλεσε ένας αριθμός που δεν αναγνωρίζετε και θέλετε περισσότερες πληροφορίες σχετικά; Πιθανότητα δεν είστε ο μόνος. Ψάξτε στην αναζήτηση του www.whocallsme.gr  γι’αυτόν τον αριθμό τηλεφώνου και δείτε αναφορές από άλλους χρήστες." />
<meta name="keywords" content="αντίστροφη, τηλέφωνο, τηλέφωνο, κινητό" />
<link rel="search" type="application/opensearchdescription+xml" title="whocallsme.gr Search" href="http://www.whocallsme.gr/opensearchdescription.xml" />
<meta property="og:locale" content="el_GR" />
<meta property="og:type" content="website" />
<meta property="og:url" content="http://www.whocallsme.gr/" />
<meta property="og:site_name" content="whocallsme.gr" />
<meta property="og:title" content="Whocallsme.gr, αντίστροφη αναζήτηση αριθμού τηλεφώνου" />
<meta property="og:description" content="Εύκολος, γρήγορος και πρακτικός τρόπος αναζήτησης και καταγραφής τηλεφωνικών αριθμών από χρήστες. Λάβατε μια  παράξενη  ή ενοχλητική κλήση, ένα  ανεπιθύμητο μήνυμα (SMS)  ή απλά σας κάλεσε ένας αριθμός που δεν αναγνωρίζετε και θέλετε περισσότερες πληροφορίες σχετικά; Πιθανότητα δεν είστε ο μόνος. Ψάξτε στην αναζήτηση του www.whocallsme.gr  γι’αυτόν τον αριθμό τηλεφώνου και δείτε αναφορές από άλλους χρήστες." />
<meta property="og:image" content="http://www.whocallsme.gr/img/social.jpg?v=0.981" /> <link rel="alternate" type="application/rss+xml" title="BLOG RSS 2.0" href="http://www.whocallsme.gr/rss.php" />
<META name="IDENTIFIER-URL" content="http://www.whocallsme.gr" />
<meta name="designer" content="www.cdl.gr" />
<meta name="generator" content="MVC" />
<meta name="revisit-after" content="1 days" />
<meta name="rating" content="general" />
<meta name="distribution" content="global" />
<meta name='email' content='info@whocallsme.gr' />
<meta name='author' content='whocallsme.gr' />
<meta name='copyright' content='whocallsme.gr' />
<meta name='Publisher' content='MVC' />
<link rel="icon" type="image/x-icon" href="http://www.whocallsme.gr/img/favicon.ico" />
<link rel="shortcut icon" href="http://www.whocallsme.gr/img/favicon.ico" type="image/vnd.microsoft.icon" />
<link rel="image_src" href="http://www.whocallsme.gr/img/social.jpg?v=0.981" />
<link rel="apple-touch-icon" href="http://www.whocallsme.gr/img/whocallsme/apple-touch-icon-57x57.png" />
 <link rel="apple-touch-icon" sizes="72x72" href="http://www.whocallsme.gr/img/whocallsme/apple-touch-icon-72x72.png" />
<link rel="apple-touch-icon" sizes="114x114" href="http://www.whocallsme.gr/img/whocallsme/apple-touch-icon-114x114.png" />
<link rel="apple-touch-startup-image" href="http://www.whocallsme.gr/img/whocallsme/apple-touch-startup-image-320x460.png" />
<link rel="apple-touch-startup-image" sizes="768x1004" href="http://www.whocallsme.gr/img/whocallsme/apple-touch-startup-image-768x1004.png" />
<script type="text/javascript">
            var Durl = 'http://www.whocallsme.gr/el';
            var url = 'http://www.whocallsme.gr';
            var lang = 'el';
            var counter = '100';
        </script>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<link rel="stylesheet" href="http://www.whocallsme.gr/js/foundation/stylesheets/foundation.css">
<link rel="stylesheet" href="http://www.whocallsme.gr/js/foundation/stylesheets/app.css">
<!--[if lt IE 9]>
        <link rel="stylesheet" href="http://www.whocallsme.gr/js/foundation/stylesheets/ie.css">
        <![endif]-->

<!--[if lt IE 9]>
        <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
<link href="http://www.whocallsme.gr/css/reset.css?v=0.981" rel="stylesheet" type="text/css" media="all" />
<link href="http://www.whocallsme.gr/css/whocallsme.css?v=0.981" rel="stylesheet" type="text/css" media="all" />
<link href="http://www.whocallsme.gr/css/cpaging/css/03_round.css?v=0.981" rel="stylesheet" type="text/css" media="all" />
<script src="http://www.whocallsme.gr/js/validation/lib/jquery.metadata.js?v=0.981" type="text/javascript"></script>
<script type='text/javascript' src='//cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.10.0/additional-methods.min.js'></script>
<script type='text/javascript' src='//cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.10.0/jquery.validate.min.js'></script>
<script src="http://www.whocallsme.gr/js/jquery.prettydate.js?v=0.981" type="text/javascript"></script>
<script src="http://www.whocallsme.gr/js/foundation/javascripts/foundation.js?v=0.981" type="text/javascript"></script>
<script src="http://www.whocallsme.gr/js/foundation/javascripts/app.js?v=0.981" type="text/javascript"></script>
<script src="http://www.whocallsme.gr/js/foundation/javascripts/modernizr.foundation.js?v=0.981" type="text/javascript"></script>
<script src="http://www.whocallsme.gr/js/jquery.expander.min.js?v=0.981" type="text/javascript"></script>
<script src="http://www.whocallsme.gr/js/plugins.js?v=0.981" type="text/javascript"></script>
<script src="http://www.whocallsme.gr/js/assets.js?v=0.981" type="text/javascript"></script>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
            (adsbygoogle = window.adsbygoogle || []).push({
                google_ad_client: "ca-pub-4509339520757331",
                enable_page_level_ads: true
            });
        </script>
</head>
<body class="index">
<div id="wrap_all">
<div id="wrap_header">
<div class="header_user">
<div class="header_user_data">
</div>
</div>
<header>
<div class="header">
<a href="http://www.whocallsme.gr/el/master/index" class="logo" title="whocallsme.gr"></a>
<div id="searchArea" class="searchArea">
<div class="error"></div>
<form action="http://www.whocallsme.gr/el/master/search" id="reverseLookUp" class="reverseLookUp" method="GET">
<label for="q">
 <span class="line1 blackShadow">Πληκτρολογήστε έναν αριθμό τηλεφώνου</span>
<span class="line2 blackShadow">για παράδειγμα: +88 888-88-88888</span>
</label>
<input class="searchAreaTelInput {required:true,minlength:3}" type="tel" name="q" id="q" placeholder="Πληκτρολογήστε τον αριθμό" title="Πληκτρολογήστε τον αριθμό" autofocus="autofocus" required="required" />
<button class="searchAreaTelButton" type="submit">Αναζήτηση</button>
</form>
</div>
</div>
</header>
<div class="clear"></div>
<div class="banner_top" style="padding-top:10px; margin:0px auto; width:728px; display:block">
<script type="text/javascript">
                google_ad_client = "ca-pub-4509339520757331";
                google_ad_slot = "6863007152";
                google_ad_width = 728;
                google_ad_height = 90;
            </script>

<script type="text/javascript" src="//pagead2.googlesyndication.com/pagead/show_ads.js">
            </script>
</div>
</div>
<div class="clear"></div>
<div id="banner_b">
<div class="banner_bottom">
</div>
</div>
<div id="wrap_footer">
<div class="footer">
<div class="f_left">
<ul class="footerList">
<li>Languages:
<a href="http://www.whocallsme.gr/en/master/index" title="English Language">Αγγλικά</a> |
<a href="http://www.whocallsme.gr/el/master/index" title="Greek Language">Ελληνικά</a> | <a title="change to mobile version" href="http://www.whocallsme.gr/changer.php?action=mobile&url=http://www.whocallsme.gr/">Mobile Version</a></li>
<li>
<a href="http://www.whocallsme.gr/el/master/page/blog" title="WCM Blog">WCM Blog</a>
</li>
<li>
<a href="http://www.whocallsme.gr/el/master/page/about" title="Σχετικά">Σχετικά</a>
</li>
<li>
<a href="http://www.whocallsme.gr/el/master/page/help" title="Βοήθεια">Βοήθεια</a>
</li>
<li>
<a href="http://www.whocallsme.gr/el/master/page/widgets" title="WCM Widgets">WCM Widgets</a>
</li>
<li>
<a href="http://www.whocallsme.gr/el/master/page/contact" title="Επικοινωνία">Επικοινωνία</a>
</li>
<li>
<a href="http://www.whocallsme.gr/el/master/page/api-developers" title="API / Web Service">API / Web Service</a>
</li>
<li>
<a href="http://www.whocallsme.gr/el/master/page/terms" title="Όροι χρήσης">Όροι χρήσης</a>
</li>
<li><a href="http://www.whocallsme.gr/el/master/page/versioning" title="whocallsme.gr versioning">έκδοση v. 0.981</a>
| &copy; 2018 Whocallsme.gr
</li>
</ul>
</div>
<div class="f_right"></div>
<div class="clearfix clearboth"></div>
<div id="preloader" style="display:none">Whocallsme.gr, αντίστροφη αναζήτηση αριθμού τηλεφώνου</div>
</div>
</div>
</div>

</body>
</html>